feat: visitor info page with details and journey tabs
JesusFilm/core pull request #1029
Opened 2022-11-04 00:01 UTC by tataihono

# Description

Please include a summary of the change and which todo is completed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Depends on https://github.com/JesusFilm/core/pull/1028
- Link to Basecamp Todo

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-11-04 01:47 UTC, csiyang requested changes

2022-11-04 01:47 UTC, csiyang commented on apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyList/VisitorJourneyListItem/VisitorJourneyListItem.tsx
> +export function VisitorJourneyListItem({
No story for this?

2022-11-04 01:47 UTC, csiyang commented on apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/VisitorJourneyDrawer.tsx
> +  const smUp = useMediaQuery((theme: Theme) => theme.breakpoints.up('sm'))
I think we decided to move away from useMediaQuery. Can we change this to be SSR friendly? https://mui.com/material-ui/react-use-media-query/#server-side-rendering

2022-11-04 01:47 UTC, csiyang commented on apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/VisitorJourneyDrawer.spec.tsx
> +
Can we add a test to make sure the time line is rendered?

2022-11-04 01:51 UTC, tataihono commented on apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetail.tsx
> +interface Props {
I can change it. But I started using @storyworks new method of getting props from the component using React's ComponentProps<T> type. So there is no longer case where we are going to export Props like in the other situations. This is a start to stop us trying to export Props.

2022-11-04 01:53 UTC, tataihono commented on apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/VisitorJourneyDrawer.tsx
> +  const smUp = useMediaQuery((theme: Theme) => theme.breakpoints.up('sm'))
only in cases where javascript is not necessary (i.e when the content is visible at page render). See other examples of the drawer. Since javascript is necessary to render a drawer SSR support is not needed.

2022-11-04 01:53 UTC, tataihono commented on apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/VisitorJourneyDrawer.spec.tsx
> +
This is done in story.

2022-11-04 06:41 UTC, csiyang commented
Are the newest events nearest to the top on the timeline? 

Why is this random event at a weird as time lol

<img width="280" alt="image" src="https://user-images.githubusercontent.com/67619008/199908453-ff209418-27c7-4271-8cae-45db7cfcb46c.png">

2022-11-04 06:55 UTC, csiyang requested changes

2022-11-04 06:55 UTC, csiyang commented on apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetail.stories.tsx
> +  ...simpleComponentConfig,
```suggestion
  ...journeysAdminConfig,
```

2022-11-04 06:55 UTC, csiyang commented on apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetail.stories.tsx
> +import { simpleComponentConfig } from '../../../libs/storybook'
```suggestion
import { journeysAdminConfig } from '../../../libs/storybook'
```

2022-11-04 06:55 UTC, csiyang commented on apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetail.stories.tsx
> +  ...simpleComponentConfig,
I think all the stories need to use the admin config to get the proper snap shots

2022-11-04 21:00 UTC, tataihono commented on apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetail.stories.tsx
> +  ...simpleComponentConfig,
I am going to change VisitorJourneyDrawer & VisitorInfo to journeyAdmin. Everything else is just the same on mobile as it is on desktop.

2022-11-06 19:41 UTC, csiyang approved these changes

2022-11-06 20:00 UTC, merged