22 08 je feat report navigation buttons
JesusFilm/core pull request #1034
Opened 2022-11-04 20:21 UTC by jernst7

# Description

Please include a summary of the change and which todo is completed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Created a component with the buttons for viewing visitor and journey reports with links to appropriate URLs

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29689022/todos/5426656935)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-11-04 20:50 UTC, csiyang requested changes
Don't forget to actually add this onto the /reports/journeys and /reports/visitors pages!

2022-11-04 20:50 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +  pageName: string
```suggestion
  pageName: "journeys" | "visitor"
```

2022-11-04 20:50 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +  pageName: string
it would be nice to limit this type, so its more clear

2022-11-04 20:50 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +          pageName === "journeys" ?
Quite a lot of repeating code here, I think we can just make the color of the button be dynamic instead of this, have a look below...

2022-11-04 20:50 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +                <Typography color="red">
```suggestion
                <Typography color={{pageName === 'journeys' ? 'primary' : 'divider}}>
```
Do this for the visitor button too

You can find a full list of the theme colours we're using in /journeys-admin/src/components/ThemeProvider/adim/tokens/colors

2022-11-04 20:50 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +                async () => await router.push(`/journeys-admin/journeys`, undefined, {
```suggestion
                async () => await router.push('/reports/journeys', undefined, {
```

normal string is fine here

2022-11-04 20:50 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +                async () => await router.push(`/journeys-admin/visitors`, undefined, {
```suggestion
                async () => await router.push('/reports/visitors', undefined, {
```

normal string is fine here

2022-11-04 20:50 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.stories.tsx
> +  ...journeysAdminConfig,
```suggestion
  ...simpleComponentConfig,
```

This just cuts down on the snapshots we take since this component won't change depending on screen size

2022-11-04 20:50 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.spec.tsx
> +        '/journeys-admin/journeys',
```suggestion
        '/reports/journeys',
```

2022-11-04 20:50 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.spec.tsx
> +    const push = jest.fn()
```suggestion
    const push = jest.fn()
    mockUseRouter.mockReturnValue({ push } as unknown as NextRouter)
```

need to use mock return the value from the router here

2022-11-04 20:50 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.spec.tsx
> +
```suggestion

jest.mock('next/router', () => ({
  __esModule: true,
  useRouter: jest.fn()
}))

const mockUseRouter = useRouter as jest.MockedFunction<typeof useRouter>
```

need to mock router

2022-11-04 20:50 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.spec.tsx
> +import { ReportButtons } from './ReportButtons'
```suggestion
import { ReportButtons } from './ReportButtons'
import { NextRouter, useRouter } from 'next/router'
```

import router and type

2022-11-05 00:21 UTC, csiyang requested changes

2022-11-05 00:21 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +              <strong>Journeys</strong>
Can you use typogs variants instead of styling the text. It should be located close where the color variants are

2022-11-05 00:21 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.spec.tsx
> +
Can we add a test for selection, check that when selected the typogs color is correct

2022-11-06 20:14 UTC, csiyang requested changes

2022-11-06 20:14 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +  pageName: 'journeys' | 'visitor'
```suggestion
  selected: 'journeys' | 'visitor'
```

2022-11-06 20:14 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +        borderTop: 1,
```suggestion
```

2022-11-06 20:14 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +        borderBottom: 1
```suggestion
        borderBottom: 1,
        borderColor: 'divider'
```

2022-11-06 20:14 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +              color={pageName === 'journeys' ? 'primary' : 'divider'}
```suggestion
              color={selected === 'journeys' ? 'primary' : 'divider'}
```

2022-11-06 20:14 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +              color={pageName === 'visitor' ? 'primary' : 'divider'}
```suggestion
              color={selected === 'visitor' ? 'primary' : 'divider'}
```

2022-11-06 20:14 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +          <Button
```suggestion
          <Button
              aria-selected = {selected === 'journeys'}
```

2022-11-06 20:14 UTC, csiyang commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.tsx
> +          <Button
```suggestion
          <Button
               aria-selected = {selected === 'journeys'}
```

2022-11-07 22:51 UTC, tataihono requested changes

2022-11-07 22:51 UTC, tataihono commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.spec.tsx
> +            <JourneyProvider value={{ admin: true }}>
not sure this is required?

2022-11-07 22:51 UTC, tataihono commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.spec.tsx
> +            <JourneyProvider value={{ admin: true }}>
same for this

2022-11-07 22:51 UTC, tataihono commented on apps/journeys-admin/src/components/ReportButtons/ReportButtons.stories.tsx
> +  <MockedProvider>
this is not needed.

2022-11-16 22:56 UTC, csiyang submitted a review, later dismissed

2022-12-21 03:13 UTC, tataihono commented
closing for now. can reopen in future if we need this functionality.

2022-12-21 03:13 UTC, closed without merging