docs: migrate handbook to docs site
JesusFilm/core pull request #1042
Opened 2022-11-09 01:26 UTC by tataihono

# Description

Please include a summary of the change and which todo is completed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- depends on https://github.com/JesusFilm/core/pull/1041
- [Migrate handbook to docs site](https://3.basecamp.com/3105655/buckets/29689605/todos/5521093770)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-11-09 02:11 UTC, GeronimoJohn commented on apps/docs/docs/05-team/05-how-we-work.md
> +In between each cycle, we spend one week cooling down. That’s the time to deal with bugs or smaller issues that come up, write up what we worked on, and figure out what we should tackle next. It’s so
Though it's also 1 week cooling down on the actual docs
https://core-docs-git-22-08-tn-docs-migrate-handbook-jesusfilm.vercel.app/docs/team/how-we-work

2022-11-09 02:21 UTC, GeronimoJohn approved these changes

2022-11-09 02:22 UTC, csiyang requested changes

2022-11-09 02:22 UTC, csiyang commented on apps/docs/docs/05-team/05-how-we-work.md
> +Fourth, and finally, there are the kickoffs. These are the team version of What are you going to work on next cycle? This is where the plan for the coming four weeks is presented. Every team lead is
```suggestion
Fourth, and finally, there are the kickoffs. These are where the plan for the coming four weeks is presented. Every team lead is obliged to write, or designate someone on the team to write, this account before the start of the new cycle.
```

2022-11-09 02:22 UTC, csiyang commented on apps/docs/docs/05-team/06-making-a-career/index.md
> +- Graduate Product Engineer
```suggestion
- Junior Product Engineer
```

2022-11-09 02:22 UTC, csiyang commented on apps/docs/docs/05-team/07-our-habits.md
> +Twice a year, our team gathers at a ministry hub for a week. Your first meet-up will be overwhelming; there are a lot of people to meet, most or all of whom you’ve only chatted with virtually. People
This is referring to when all JF SOL team gathers?

```suggestion
Once a year, our team gathers at a ministry hub for a week. Your first meet-up will be overwhelming; there are a lot of people to meet, most or all of whom you’ve only chatted with virtually. People tend to arrive on the Sunday before the meet-up, but ’campers who travel longer distances arrive earlier to beat the jet lag. Jesus Film books accomodation nearby, so you don’t need to worry about finding a place to stay.
```

2022-11-09 02:22 UTC, csiyang commented on apps/docs/docs/05-team/08-our-responsibilities.md
> +  - writing heartbeats and kick-offs (with input from team); providing status updates in between as needed
```suggestion
  - writing standup updates and kick-offs (with input from team); providing status updates in between as needed
```

2022-11-09 02:22 UTC, csiyang commented on apps/docs/docs/05-team/08-our-responsibilities.md
> +  - writing heartbeats and kick-offs (with input from team) or contributing to Executive write-ups; providing status updates in between as needed
```suggestion
  - writing standup updates and kick-offs (with input from team) or contributing to Executive write-ups; providing status updates in between as needed
```

2022-11-09 02:22 UTC, csiyang commented on apps/docs/docs/05-team/08-our-responsibilities.md
> +  - contributing to heartbeats and kick-offs; providing status updates in between as needed
```suggestion
  - contributing to standup updates and kick-offs; providing status updates in between as needed
```

2022-11-09 02:22 UTC, csiyang commented on apps/docs/docs/05-team/09-international-travel-guide.md
> +
Add instructions for WARP?

2022-11-10 02:09 UTC, tataihono commented on apps/docs/docs/05-team/08-our-responsibilities.md
> +  - writing heartbeats and kick-offs (with input from team); providing status updates in between as needed
No. heartbeats are a thing they need to write.

2022-11-10 02:09 UTC, tataihono commented on apps/docs/docs/05-team/08-our-responsibilities.md
> +  - writing heartbeats and kick-offs (with input from team) or contributing to Executive write-ups; providing status updates in between as needed
No. heartbeats are a thing they need to write.

2022-11-10 02:09 UTC, tataihono commented on apps/docs/docs/05-team/08-our-responsibilities.md
> +  - contributing to heartbeats and kick-offs; providing status updates in between as needed
No. heartbeats are a thing they need to write.

2022-11-10 02:10 UTC, tataihono commented on apps/docs/docs/05-team/09-international-travel-guide.md
> +
Still deciding if thats what we want to use in the long term. We may end up using AWS for this.

2022-11-10 02:10 UTC, tataihono commented on apps/docs/docs/05-team/07-our-habits.md
> +Twice a year, our team gathers at a ministry hub for a week. Your first meet-up will be overwhelming; there are a lot of people to meet, most or all of whom you’ve only chatted with virtually. People
Done.

2022-11-10 02:26 UTC, csiyang approved these changes

2022-11-10 02:37 UTC, storyworks commented on apps/docs/docs/05-team/06-making-a-career/02-titles-for-designers.md
> +- WEB: Fully capable of writing modern HTML/CSS/JS + the ability to make moderate progress in Rails.
Rails!?

2022-11-10 02:59 UTC, tataihono commented on apps/docs/docs/05-team/06-making-a-career/02-titles-for-designers.md
> +- WEB: Fully capable of writing modern HTML/CSS/JS + the ability to make moderate progress in Rails.
fixed.

2022-11-10 03:25 UTC, storyworks approved these changes

2022-11-10 03:41 UTC, merged