feat: ecs complete deployment
JesusFilm/core pull request #1078
Opened 2022-11-18 07:36 UTC by mikeallisonJS

# Description

This adds the missing stage services, along with permissions required to get everything running.
This PR is already deployed to terraform

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-11-24 03:51 UTC, tataihono requested changes

2022-11-29 22:24 UTC, mikeallisonJS commented on infrastructure/modules/aws/locals.tf
> +        to_port     = 5000
graphql is on port 4000-4004

2022-11-29 22:26 UTC, mikeallisonJS commented on infrastructure/modules/aws/ecs-task/variables.tf
> +    alb_listener = any
It could, but it's polymorphic. The actual listener types used are defined in each app variable file

2022-11-29 22:27 UTC, mikeallisonJS commented on infrastructure/environments/stage/main.tf
> +  internal_ecs_config = {
stage is no longer a root object, since it's a module, it's no longer a naming collision

2022-11-29 22:27 UTC, mikeallisonJS commented on infrastructure/environments/stage/main.tf
> +  public_ecs_config = {
same, no longer a collision

2022-12-02 23:19 UTC, tataihono approved these changes

2022-12-13 22:55 UTC, merged