feat: get video by path api
JesusFilm/core pull request #1087
Opened 2022-11-25 01:49 UTC by csiyang

# Description

- Add API to get a video by path
- Added a test for getVideoBySlug
- Refactored video return types in video.service

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/30300650/todos/5566326330)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Can query a video based off path

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-11-25 01:51 UTC, csiyang commented
This PR requires path to be added to videoVariant first

2022-11-25 03:20 UTC, csiyang commented on apps/api-videos/src/app/modules/video/video.service.ts
> +        break
@tataihono was a bit unsure if I should add something like this for the episodes, or just remove this...

2022-11-27 21:59 UTC, tataihono requested changes

2022-11-27 21:59 UTC, tataihono commented on apps/api-videos/src/app/modules/video/video.service.ts
> +        break
path here needs to be replaced with slug.

2022-11-28 01:47 UTC, tataihono requested changes

2022-11-28 01:47 UTC, tataihono commented on apps/api-videos/src/app/modules/video/video.service.ts
> +    let idFilter
```suggestion
    let idFilter: GeneratedAqlQuery
```

2022-11-28 02:21 UTC, csiyang commented on apps/api-videos/src/app/modules/video/video.service.ts
> +    let idFilter
```suggestion
    let idFilter: GeneratedAqlQuery | undefined
```

2022-11-28 02:21 UTC, csiyang commented on apps/api-videos/src/app/modules/video/video.service.ts
> +    if (idFilter == null || variantFilter == null) {
```suggestion
    if (idType == null || idFilter == null || variantFilter == null) {
```

2022-12-01 19:50 UTC, csiyang commented on apps/api-videos/src/app/modules/videoVariant/videoVariant.graphql
> +  slug: String!
@tataihono Are we still calling this slug, or should I rename to value?

2022-12-02 23:24 UTC, mikeallisonJS approved these changes

2022-12-02 23:27 UTC, merged