feat: collection description component
JesusFilm/core pull request #1090
Opened 2022-11-29 01:36 UTC by DanChae03

# Description

Create the Description component for the collections page. This will be used for all video collections on the next steps page.

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/30316909/todos/5575184458)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] It should render the description for the video collection
- [ ] The share button should correctly render

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-11-29 01:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JesusFilm/core?pullRequest=1090) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JesusFilm/core?pullRequest=1090) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JesusFilm/core?pullRequest=1090) it.</sub>

2022-11-29 02:20 UTC, DanChae03 commented on apps/watch/src/components/Description/Description.tsx
> +          borderColor: 'secondary.main', // TODO: #BBBCBC
Button colour #BBBCBC does not exist on current light palette

2022-12-05 21:09 UTC, csiyang approved these changes

2022-12-05 21:10 UTC, csiyang commented on apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.stories.tsx
> +  'Following Jesus is a mini series designed to ground followers of Jesus in their faith and equip them to be fruitful members of Christ\'s body. Using storytelling techniques and incorporating image
Remove
```suggestion
```

2022-12-06 22:33 UTC, csiyang requested changes

2022-12-06 22:33 UTC, csiyang commented on apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
> +  const newArray: string[] = []
Can you change this name to be more descriptive to what the array is?

2022-12-06 22:33 UTC, csiyang commented on apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
> +    expect(getByLabelText('collection-share-button')).toBeInTheDocument()
This test is not needed since the click event will check for its existence
```suggestion
```

2022-12-06 22:33 UTC, csiyang commented on apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.spec.tsx
> +  })
Not needed since the value of the button never changes, and the visuals can be captured through VR testing
```suggestion
```

2022-12-07 21:55 UTC, csiyang commented on apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx
> +      </Button>
Use defaults for the icon and text
```suggestion
      <Button
        startIcon={<ShareOutlinedIcon />}
        size="medium"
        variant="outlined"
        color="secondary"
        aria-label="collection-share-button"
        onClick={() => setOpenShare(true)}
        sx={{
          display: { xs: 'none', sm: 'flex' },
          minWidth: 220
        }}
      >
          Share
      </Button>
```

2022-12-07 22:53 UTC, csiyang approved these changes

2022-12-07 22:58 UTC, merged