feat: video hero overlay
JesusFilm/core pull request #1096
Opened 2022-11-29 22:54 UTC by GeronimoJohn

# Description

Created the VideoHeroOverlay Component for our Video hero. 

[- Link to Basecamp Todo
](https://3.basecamp.com/3105655/buckets/30300130/todos/5566230905)

# How should this PR be QA Tested?
Currently, Single Video Page is not rendering properly due to the URL. 

**Requirements**
To visually test this
- Visit its story in Storybook

To test this locally
- Find the `[...slug]` file
- On line 154, change the logic to be `siblingsData == null`
- Run Watch project locally
- Visit a video

- [ ] it should render the Video Image as a background
- [ ] it should render the Hero Texture on top of the video
The following should be rendered on top of the Video Image and Hero Texture
- [ ] it should render the Video Title
- [ ] it should render the duration of the video
- [ ] it should render the Play Video Button
- [ ] it should render the Mute Icon Button

- [ ] it should play the video on Play Video Button click
- [ ] it should close the overlay on Play Video Button click
- [ ] it should mute/unmute video on Mute Icon click

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-11-30 01:00 UTC, jernst7 reviewed
Looks good to me

2022-12-02 00:56 UTC, storyworks commented on apps/watch/src/components/Hero/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
> +            onClick={handleMute}
Check with Lyuba if should `handlePlay`

2022-12-15 03:57 UTC, tataihono requested changes
looks good just remove a story.

2022-12-15 03:57 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.stories.tsx
> +import { Meta, Story } from '@storybook/react'
remove this file. capture in VideoHero.

2022-12-15 21:26 UTC, tataihono approved these changes

2022-12-15 22:26 UTC, tataihono approved these changes

2022-12-15 22:38 UTC, merged