feat: collections video grid
JesusFilm/core pull request #1118
Opened 2022-12-05 00:32 UTC by DanChae03

# Description

Complete refactor of the videosgrid component. Create gridItem component that acts as the tiled element in the videosgrid. These components will be used in the collections page.

- Link to Basecamp Todo

# How should this PR be QA Tested?

- [ ] Grid title should correctly render
- [ ] Video duration should properly render (minutes and seconds)
- [ ] Each video should have correct URL associated with it
- [ ] Grid should render all videos passed in as prop array

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-12-09 02:01 UTC, csiyang requested changes

2022-12-09 02:01 UTC, csiyang commented on apps/watch/src/components/VideosGrid/VideosGrid.stories.tsx
> +  videos
@DanChae03 This is rendering too many videos, most of it is not getting loaded in the story. We should decrease this to max 9 videos

2022-12-09 03:02 UTC, mikeallisonJS commented
![image](https://user-images.githubusercontent.com/838371/206614661-2ea2c2a0-856a-4217-ac59-7271d44e74d3.png)
There is a strange hover state on the lower text

2022-12-09 03:06 UTC, mikeallisonJS submitted a review, later dismissed

2022-12-09 03:35 UTC, DanChae03 commented on apps/watch/src/components/VideosGrid/VideoGridCard/VideoGridCard.tsx
> +                  <Typography variant="body1" sx={{ lineHeight: '1rem' }}>
Yeah it's not necessary, think it was just left over from the past

2022-12-12 22:12 UTC, csiyang requested changes

2022-12-12 22:13 UTC, csiyang commented on apps/watch/src/components/VideosGrid/VideoGridCard/VideoGridCard.tsx
> +          <CardMedia
After checking with @stevendiller the current darken behaviour is fine

2022-12-14 00:42 UTC, tataihono requested changes

2022-12-15 02:23 UTC, csiyang commented on apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
> +export function ContainerHero({
Merging main should resolve all the Hero changes

2022-12-15 02:32 UTC, tataihono commented on apps/watch/src/components/VideoCard/VideoCard.stories.tsx
> +    <Grid container spacing={2} rowSpacing={8}>
nope look closer there are prop changes in each item.

2022-12-15 03:15 UTC, csiyang approved these changes

2022-12-15 03:18 UTC, merged