feat: get all video language variants api
JesusFilm/core pull request #1124
Opened 2022-12-05 23:53 UTC by csiyang

# Description

Please include a summary of the change and which todo is completed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Link to Basecamp Todo

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-12-06 00:01 UTC, tataihono requested changes
Please change language id to a language. See the resolver variant language field resolver for how to do this.

2022-12-06 00:01 UTC, tataihono commented on apps/api-videos/src/app/modules/video/video.graphql
> +  languageId: String
This must be a language. You should use a resolver function for this.

2022-12-06 22:50 UTC, storyworks commented
Can you put this `onStage` and make sure it works there so we can test?

2022-12-07 00:33 UTC, storyworks approved these changes

2022-12-07 00:36 UTC, merged