feat: videos page
JesusFilm/core pull request #1126
Opened 2022-12-06 20:54 UTC by mikeallisonJS

# Description

This page provides a common workspace for the current cycle work. Since it is not available in navigation, or in production we will be adding work here.

# How should this PR be QA Tested?

- [ ] watch /videos page available

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-12-06 23:19 UTC, csiyang requested changes

2022-12-06 23:19 UTC, csiyang commented on apps/watch/pages/videos.tsx
> +      <VideosHero />
```suggestion
    <PageWrapper hero={<VideosHero />} />
```

2022-12-06 23:19 UTC, csiyang commented on apps/watch/src/components/Hero/VideosHero/VideosHero.tsx
> +export function VideosHero(): ReactElement {
We recently moved a lot these Hero's from this folder as a sub folder in where they are being used. I think we should move this too...

2022-12-06 23:19 UTC, csiyang commented on apps/watch/pages/videos.tsx
> +        <Videos layout="grid" limit={limit} />
Recent page changes have that we only render one component on the page, and then that component will render the stuff for the page. Thoughts on making that change here too?

2022-12-07 22:32 UTC, csiyang requested changes
Also can the `Gird` component be moved out as well since it's also used by VideoContainerPage

2022-12-07 22:32 UTC, csiyang commented on apps/watch/src/components/Videos/Hero/VideosHero.tsx
> +          <Typography variant="h2" color="text.primary">
The title here should be aligned with the content on the page
<img width="1049" alt="Screen Shot 2022-12-08 at 11 21 29 AM" src="https://user-images.githubusercontent.com/67619008/206309383-cecd615f-cad9-4bef-88b7-f10806adfabd.png">

2022-12-07 22:32 UTC, csiyang commented on apps/watch/src/components/Videos/Videos.tsx
> +export function Videos(): ReactElement {
To match the other pages
```suggestion
export function AllVideosPage(): ReactElement {
```

2022-12-07 22:32 UTC, csiyang commented on apps/watch/src/components/VideoContentPage/VideosCarousel/VideosCarousel.spec.tsx
> +describe('carousel', () => {
@storyworks has requested that we don't make any changes to carousel since she is intending on making some of these herself

2022-12-07 22:34 UTC, mikeallisonJS commented on apps/watch/src/components/VideoContentPage/VideosCarousel/VideosCarousel.spec.tsx
> +describe('carousel', () => {
I didn't make changes, just moved the story since it's not used in Videos any more.

2022-12-07 22:59 UTC, mikeallisonJS commented on apps/watch/src/components/Videos/Videos.tsx
> +export function Videos(): ReactElement {
Went with VideosPage since that is the url route

2022-12-08 03:20 UTC, csiyang requested changes

2022-12-08 03:20 UTC, csiyang commented on apps/watch/src/components/VideosPage/SubHero/Stats/VideosSubHeroStats.tsx
> +      <div>
Can these just be fragments?

2022-12-08 03:20 UTC, csiyang commented on apps/watch/src/components/VideoContentPage/VideosCarousel/VideosCarousel.spec.tsx
> +describe('carousel', () => {
Yeah she would like us to not move it since she 's making that change

2022-12-08 21:13 UTC, csiyang approved these changes

2022-12-08 21:15 UTC, merged