feat: video hero player
JesusFilm/core pull request #1143
Opened 2022-12-12 03:34 UTC by GeronimoJohn

# Description

Please include a summary of the change and which todo is completed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Link to Basecamp Todo

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-12-13 22:35 UTC, gdub01 reviewed
Looks great!

2022-12-13 22:35 UTC, gdub01 commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
> +  }, [player, currentTime, setFullscreen, timeFormatToHHMMSS])
@GeronimoJohn I think currentTime can be removed

2022-12-13 22:35 UTC, gdub01 commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
> +      setProgress(value)
I wonder if we can avoid this as the player listener above also sets progress? Or maybe set progress immediately but debounce the player.currentTime function below?

2022-12-13 22:35 UTC, gdub01 commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
> +            'playToggle',
Are these just getting set here because we need them for fullscreen? 
I wonder if we add `fullscreen` beside` , [playerRef, videoRef]) ` below and then if it's in fullscreen we have those children and if it's not fullscreen there's no children?

2022-12-14 03:00 UTC, GeronimoJohn commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
> +      setProgress(value)
I've tried your suggestion, though I found that this function is needed for the onChange event on the scrub bar (Material UI Slider).

This function handles users' interaction with the scrub bar while the player listener above sets the current time and progress of the video

I think a better name for this function would be` handleSeek`. Though let me know if I didn't understand what you mean

2022-12-14 15:10 UTC, gdub01 commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
> +            'playToggle',
lol =) okay.

2022-12-14 15:14 UTC, gdub01 submitted a review, later dismissed

2022-12-14 15:14 UTC, gdub01 commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
> +      setProgress(value)
Right on. I was thinking setting `player.currentTime(value)` in this handleProgress/handleSeek function triggers the `player.on('timeupdate'` function which then does this: `setProgress(Math.round(player.currentTime()))`. So was just thinking setProgress gets called twice. 
The advantage of your way though is feedback is immediate in the scrub bar.. whereas there could be jankiness waiting for the video player to update the scrub bar. So anyways, ya I think the way you have it is great.

2022-12-16 00:47 UTC, tataihono submitted a review, later dismissed

2022-12-16 00:47 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
> +  videojs.registerComponent('subtitleControl', SubtitleControl)
remove

2022-12-16 00:47 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
> +        ],
not needed.

2022-12-16 00:47 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
> +    if (videoRef.current != null && variant?.hls != null) {
revert

2022-12-16 00:47 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
> +          ]
revert

2022-12-16 00:47 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
> +      data-testid={`video-${id}`}
not needed?

2022-12-16 02:21 UTC, tataihono requested changes

2022-12-16 02:21 UTC, tataihono commented on libs/shared/ui/src/libs/timeFormat/timeFormat.spec.ts
> +      expect(secondsToTimeFormat(NaN, { trimZeroes: true })).toEqual('0:00')
nit: move to bottom to match test above.

2022-12-16 02:21 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.stories.tsx
> +const video: VideoContentFields = {
can you draw this from the video test data we've all been referencing?

2022-12-16 02:21 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.spec.tsx
> +  const video: VideoContentFields = {
use test data here?

2022-12-16 02:21 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
> +          setFullscreen={(value: boolean) => setFullscreen(value)}
does this need `: boolean`?

2022-12-16 02:21 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
> +      player.requestFullscreen()
can this be moved to the setFullscreen function provided in the prop? This will make it easier for us to manage fullscreen in VideoHero later.

2022-12-16 02:21 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
> +  }
drop

2022-12-16 02:21 UTC, tataihono commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
> +    })
drop and handle in videoHero

2022-12-16 03:46 UTC, tataihono approved these changes

2022-12-16 03:49 UTC, merged