Render by step
JesusFilm/core pull request #118
Opened 2021-11-10 02:12 UTC by csiyang

- Renders card content for only the active card
- Place holder card used for cards that are not active (for the swiper slide)
- added e2e tests for journeys

2021-11-10 22:14 UTC, lumberman commented
Hey, @csiyang I appreciate very much you working on this fix!
I have an issue with how it feels now. Initially, I thought that the slider somehow skips one step (grey coloured card) and goes from 1st to 3rd card directly. Then I realized it's due to simultaneous colour changes. I'm not sure what solution will be to that problem, but can you try adding a bit of colour transition or delay to remove this confusion?

2021-11-12 09:55 UTC, csiyang commented
Hi @lumberman, we updated how the step is rendered, please let me know if it's what you had in mind?

2021-11-17 00:00 UTC, tataihono approved these changes
approving everything but the video blocks.

2021-11-17 00:20 UTC, storyworks requested changes

2021-11-17 00:20 UTC, storyworks commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +                    backgroundColor={theme.palette.background.paper}
```suggestion
                    backgroundColor={theme.palette.primary.light}
```
Reverting back to this - I've just remembered we did this so the next Card was more visible

2021-11-17 00:46 UTC, storyworks approved these changes

2021-11-17 00:46 UTC, merged