feat: use subtitle count field on VideoControls
JesusFilm/core pull request #1228
Opened 2023-01-11 04:35 UTC by jianwei1

# Description

Use subtitleCount field on videoControls to enable/disable the subtitle button

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/30278084/todos/5711232308)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2023-01-12 21:57 UTC, GeronimoJohn commented on apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
> +                    disabled={variant?.subtitleCount === 0}
Sorry bro, after thinking about it can we do something like what's happening before

```suggestion
                    disabled={variant?.subtitleCount === undefined ||
                    variant?.subtitleCount < 1}
```
This just allows us to cover null values and negative and zero values

2023-01-13 00:07 UTC, GeronimoJohn commented on apps/watch/src/libs/videoContentFields.ts
> +      subtitleCount
In the file `SubtitleDialog`, can you please change line 125 to be using the subtitle count instead. it's the helper text props

2023-01-13 03:49 UTC, tataihono requested changes
need some test data regeneration!

2023-01-13 03:51 UTC, tataihono approved these changes

2023-01-13 03:56 UTC, merged