C4/basic authentication schema
JesusFilm/core pull request #123
Opened 2021-11-17 22:41 UTC by gdub01

user & userJourney schema and types in api-journeys

2021-11-23 03:55 UTC, tataihono requested changes
user should be a stand-alone microservice as many services will depend on the user object. should be able to just reference the userId which is already passed to every microservice instead of creating your own internal userId.

2021-11-23 04:11 UTC, storyworks commented on apps/api-journeys/schema.graphql
> +  firstName: String
Would firstName be required? So we have a at least a name to display with all the change access modals / avatars.

2021-11-23 04:11 UTC, storyworks commented on apps/api-journeys/src/modules/user/user.spec.ts
> +        const user: User = {
You could extract this, define it outside of the `describe` and reuse it in all the tests?

Also 'lo' at the examples xD

2021-11-23 14:04 UTC, gdub01 commented on apps/api-journeys/schema.graphql
> +  firstName: String
That's fair. The issue is email signup doesn't have a first name field. There's a way to maybe split the email at the @ sign and get a first name from there, though. Think we should do that?

2021-11-23 14:08 UTC, gdub01 commented
> user should be a stand-alone microservice as many services will depend on the user object. should be able to just reference the userId which is already passed to every microservice instead of creating your own internal userId.

I'm not sure what this means. 

The user model has an id that's used for the user_journey join table that needs to be unique. 

A service can pass any value they'd like for the id, but it defaults to a UUID if that helps?

You mentioned a userId is already passed to every micro service... but I don't know anything about that. Can you elaborate?  ie. where does that id come from?

2021-11-23 23:08 UTC, storyworks commented on apps/api-journeys/schema.graphql
> +  firstName: String
Hmm if we can't add first name to the email signup, possibly we can just display the email as the fallback.

Although.. if we can't get first name from email sign up and there's no userUpdate mutation - how will we ever get firstName and lastName?

2021-11-23 23:37 UTC, tataihono commented
So if you call the api with an authorization header containing a user's firebase id token. This is decoded by the api gateway here: https://github.com/JesusFilm/core/blob/main/apps/api-gateway/src/main.ts#L45

The uid is then passed to each graphql api as userId in the context object. You can see an example of this here: https://github.com/JesusFilm/core/blob/main/apps/api-journeys/src/modules/image/image.ts#L70

This uid is set by firebase and is guaranteed unique by firebase. It is a string not a uuid.

A user service could be created to take in any additional information about a user in a user service (e.g. api-users).  You can define a new User table where the id is just the uid from firebase.

2021-11-24 01:55 UTC, gdub01 commented
Okay ty for reply. I'm afraid I'm only kind of understanding. 

The task we have is for 'basic authentication' which in the strictest sense is Authorization: Basic <credentials> where credentials is the Base64 encoding of ID and password joined by a single colon :.

However we're using oauth with multiple external providers using a 3P of firebase which is not basic auth, and it seems to have already been at least partially implemented which is... a bit surprising. 

It also seems we're assuming auth is always going to be done by firebase. ie. if you don't have a session from firebase, you can't access our graphql setup? Last I heard there was not a small chance we were using aws' cognito in the long term and I hadn't heard differently?

By "user's firebase id token" do you mean the "access token" firebase issues, or the user's "id" firebase issues? I'm storing firebase's id on the user's table which I believe makes sense... unless you're wanting a firebase_user's table? I'm not really understanding the need for that, though. I'm not storing the access token as they are meant to be temporary. 

The general plan is to have access to the user's firebase id so that we can find journeys relating to the logged in user. Looking at the code you've written in the past, it seems you're getting the firebase id already, but calling firebase's user id a generic userId instead of an explicit firebaseUserId. Using any alternative auth provider could make that confusing?

If we make the firebaseUserId co-opt our user table's 'id' that's fine, but risk of collision increases as we add more external providers, each with their own id. We could make the index unique from both the id column and provider column, though. ie. we set the id as firebase's user id and provider as 'firebase' for example. But the user_journey join table will be a little harder.  @tataihono

2021-11-24 16:33 UTC, gdub01 commented on apps/api-journeys/schema.graphql
> +  firstName: String
Yes that's true - we can't ever get that information. There was an idea to provide a screen to the user to allow them to add/update info, but that got vetoed at this time.

2021-11-26 01:04 UTC, tataihono commented
Okay ty for reply. I'm afraid I'm only kind of understanding.

**The task we have is for 'basic authentication' which in the strictest sense is Authorization: Basic where credentials is the Base64 encoding of ID and password joined by a single colon :.**

Sorry. The pitch name Basic Authentication here just means the first version of Auth. There was a much more complex Authentication pitch so this was called Basic Authentication to note that it was a stripped-down version of the original pitch.

**However we're using oauth with multiple external providers using a 3P of firebase which is not basic auth, and it seems to have already been at least partially implemented which is... a bit surprising.**

Right, it was implemented to support anonymous authentication on the visitor client.

**It also seems we're assuming auth is always going to be done by firebase. ie. if you don't have a session from firebase, you can't access our graphql setup? Last I heard there was not a small chance we were using aws' cognito in the long term and I hadn't heard differently?**

We are using firebase moving forward. AWS Cognito does not support anonymous authentication nor transitioning those anonymous accounts to a properly authenticated account.

**By "user's firebase id token" do you mean the "access token" firebase issues, or the user's "id" firebase issues? I'm storing firebase's id on the user's table which I believe makes sense... unless you're wanting a firebase_user's table? I'm not really understanding the need for that, though. I'm not storing the access token as they are meant to be temporary.**

The thing you are referring to as an access token is more formally called an ID Token by [firebase](https://firebase.google.com/docs/auth/admin/verify-id-tokens). This token contains encoded data that allows us to verify it without needing to connect to a third-party service or connect to a local database which makes it a perfect fit for the api-gateway as it needs to do its verification without a datastore.

**The general plan is to have access to the user's firebase id so that we can find journeys relating to the logged in user. Looking at the code you've written in the past, it seems you're getting the firebase id already, but calling firebase's user id a generic userId instead of an explicit firebaseUserId. Using any alternative auth provider could make that confusing?**

We are not going to use an alternative auth provider. Firebase is our auth provider going forward for this repo.

**If we make the firebaseUserId co-opt our user table's 'id' that's fine, but risk of collision increases as we add more external providers, each with their own id. We could make the index unique from both the id column and provider column, though. ie. we set the id as firebase's user id and provider as 'firebase' for example. But the user_journey join table will be a little harder.**

As above Firebase is our auth provider. There is no need to manage collisions here. Just replace the ID primary key with the one from Firebase.

Hope that helps.

2021-11-27 00:43 UTC, gdub01 commented
Okay thanks @tataihono I understand.

I removed the firebase id and it allows for sending the firebase id when we create the user.

2021-11-29 20:30 UTC, tataihono requested changes
user needs to be in a separate service not api-journeys using federation.

2021-11-29 20:30 UTC, tataihono commented on CONTRIBUTING.md
> +1. Docker set up:nx generate-graphql api-gateway
```suggestion
1. Docker set up:
```

2021-11-29 20:30 UTC, tataihono commented on apps/journeys-admin/pages/_app.tsx
> +
```suggestion
```

2021-11-30 01:43 UTC, gdub01 commented
@tataihono By separate service, are you meaning you want another app created? Would it have its own db?

2021-11-30 01:54 UTC, gdub01 commented
Also, are you imagining apps would hit api-gateway which would then either send requests to api-users or api-journeys?

2021-12-01 22:10 UTC, tataihono commented
@gdub01 yes. please connect with @mikeallisonJS about what that might look like. You'll need to read into federation to see how data is shared between services.

2021-12-02 18:27 UTC, gdub01 commented
Hello @mikeallisonJS! I'm not sure what timezone you're in but would you be free to discuss this today or tomorrow? I'm in EST.

2021-12-06 18:24 UTC, gdub01 commented
Hello @mikeallisonJS ... just wanted to follow up again. Do you have another contact I could reach out to? Can you describe what it means to create a new service and whether a new db is required?

2021-12-07 03:53 UTC, mikeallisonJS commented
Sorry @gdub01 , you're comments were lost amongst the initial github noise. I have fixed the notifications and they should work going forward. The JFP digital slack is the best place to catch me (I'm in pacific time, but schedule work just before the the NZ team hours)

Please reach out and I'll walk you through the new microservice architecture we've been working on this cycle

2021-12-20 22:59 UTC, tataihono submitted a review, later dismissed

2021-12-20 22:59 UTC, tataihono commented on apps/api-journeys/prisma/factories/nua1.ts
> +
no seed necessary.

2021-12-20 22:59 UTC, tataihono commented on apps/api-journeys/prisma/schema.prisma
> +  userId    String
needed for cache management

```suggestion
  id String @id
  userId    String
```

2021-12-20 22:59 UTC, tataihono commented on apps/api-journeys/src/modules/user/user.ts
> +    user(id: ID!): User
these endpoints are not required

2021-12-20 22:59 UTC, tataihono commented on apps/api-journeys/src/modules/user/user.ts
> +    userCreate(input: UserCreateInput!): User!
it looks like i can call this endpoint and set it to any email i want it to. I think we should rely on firebase to set this up.

2021-12-20 22:59 UTC, tataihono commented on apps/api-journeys/src/modules/user/user.ts
> +      return await db.user.findUnique({ where: { id } })
looks like i can get user data for any user in the system. This seems like a security hole.

2021-12-20 22:59 UTC, tataihono commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +    },
remove. this isn't being used at the moment right? Looks like user calls the userJourneyRequest.

2021-12-20 22:59 UTC, tataihono commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +    async userJourneyUpdate(_parent, { input }, { db, userId }) {
this should be userJourneyApprove or something like that.

2021-12-20 22:59 UTC, tataihono commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +    // update naming
remove.

2021-12-20 22:59 UTC, tataihono commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +          'Owners cannot remove themselves from their journey'
```suggestion
          ' you cannot remove yourself from this journey when you are an owner'
```

2021-12-20 22:59 UTC, tataihono commented on apps/journeys-admin/src/libs/firebaseClient/UseFirebase.tsx
> +export const UseFirebase = (): UseFirebaseProps => {
only components should start with a capital letter. Also Props refers to the input props provided to a component. This should be renamed to something like UseFirebaseResponse.

```suggestion
export const useFirebase = (): UseFirebaseResponse => {
```

2021-12-20 22:59 UTC, tataihono commented on apps/journeys-admin/test/testingLibrary.tsx
> +import { ReactElement } from 'react'
drop. If you are using MockedProvider you don't need to wrap an apollo provider.

2021-12-20 22:59 UTC, tataihono commented on apps/journeys-admin/src/components/InviteUserModal/ApproveUser/ApproveUser.spec.tsx
> +    const { getByText } = renderWithApolloClient(
renderWithApolloClient should be just render

2021-12-20 22:59 UTC, tataihono commented on apps/journeys-admin/src/components/InviteUserModal/PromoteUser/PromoteUser.spec.tsx
> +    const { getByText } = renderWithApolloClient(
should just be render

2021-12-21 01:12 UTC, GeronimoJohn commented on apps/api-journeys/src/modules/user/user.ts
> +      return await db.user.findUnique({ where: { id } })
I've made some changes - is this what you meant

2021-12-21 01:12 UTC, GeronimoJohn commented on apps/api-journeys/src/modules/user/user.ts
> +          imageUrl: imageUrl as string
I've made some changes - is this what you meant

2021-12-21 01:12 UTC, GeronimoJohn commented on apps/api-journeys/src/modules/user/user.ts
> +    userCreate(input: UserCreateInput!): User!
I'm not too sure what to do for this one

2021-12-21 19:04 UTC, gdub01 commented on apps/api-journeys/src/modules/user/user.ts
> +    userCreate(input: UserCreateInput!): User!
it now uses the email belonging to the logged-in user in firebase

2021-12-22 01:40 UTC, tataihono submitted a review, later dismissed

2021-12-22 01:40 UTC, tataihono commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +    async usersJourneys(journey, __, { db }) {
```suggestion
    async userJourneys(journey, __, { db }) {
```

2021-12-22 01:40 UTC, tataihono commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +  }
i don't think this is necessary. This will allow you to navigate through other users to find out what journeys they have access to.

2021-12-22 01:40 UTC, tataihono commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +    usersJourneys: [UserJourney!]
```suggestion
    userJourneys: [UserJourney!]
```

2021-12-22 01:40 UTC, tataihono commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +  }
drop

2021-12-22 01:40 UTC, tataihono commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +    userJourneyRemove(input: UserJourneyRemoveInput!): UserJourney!
```suggestion
    userJourneyApprove(id: ID!): UserJourney!
    userJourneyPromote(id: ID!): UserJourney!
    userJourneyRemove(id: ID!): UserJourney!
```

2021-12-22 01:40 UTC, tataihono commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +    userId: ID!
don't need userId. You should use the id of the authenticated user.

2021-12-22 01:40 UTC, tataihono commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +          userId: input.userId,
```suggestion
          userId,
```

2021-12-22 21:18 UTC, mikeallisonJS requested changes

2021-12-22 21:18 UTC, mikeallisonJS commented on apps/api-journeys/src/modules/userJourney/userJourney.ts
> +    userJourneyRequest(input: UserJourneyRequestInput!): UserJourney!
Since the input is not being used to modify data, can this be a parameter journeyId: ID! ?

2021-12-24 00:24 UTC, tataihono approved these changes

2021-12-24 00:26 UTC, merged