Access Avatars component
JesusFilm/core pull request #127
Opened 2021-11-18 03:56 UTC by csiyang

2021-11-22 23:16 UTC, storyworks commented on apps/journeys-admin/src/components/blocks/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.stories.tsx
> +    <AccessAvatars users={args.users} />
```suggestion
    <AccessAvatars {...args} />
```

2021-11-22 23:16 UTC, storyworks commented on apps/journeys-admin/src/components/blocks/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.stories.tsx
> +Single.args = singleAvatar
```suggestion
Single.args = {
users: [ singleAvatar ]
}
```

2021-11-22 23:43 UTC, csiyang commented on apps/journeys-admin/src/components/blocks/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.stories.tsx
> +    <AccessAvatars users={args.users} />
updated as suggested

2021-11-22 23:43 UTC, csiyang commented on apps/journeys-admin/src/components/blocks/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.stories.tsx
> +Single.args = singleAvatar
updated as suggested

2021-12-13 23:12 UTC, tataihono requested changes
this PR should be returned to draft an be implemented post changes coming from @GeronimoJohn and @gdub01

2021-12-13 23:12 UTC, tataihono commented on apps/journeys-admin/pages/journeys/[journeySlug].tsx
> +
remove.

2022-01-11 01:04 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.tsx
> +  const maxAvatars = breakpoints.sm ? 5 : 3
```suggestion
  const maxAvatars = breakpoints.md ? 5 : 3
```

2022-01-11 03:27 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.spec.tsx
> +      expect(getByText('Janelle Clegg')).toBeInTheDocument()
Changed the lastNames to respective numbers

2022-01-11 04:16 UTC, storyworks requested changes

2022-01-11 04:16 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.spec.tsx
> +    it('should display 5 avatars max for desktop', () => {
```suggestion
    it('should display 5 avatars max', () => {
```

2022-01-11 04:44 UTC, storyworks requested changes

2022-01-11 04:44 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.spec.tsx
> +    it('should display 5 avatars ', () => {
```suggestion
    it('should display 5 avatars max', () => {
```

2022-01-11 04:44 UTC, storyworks commented on apps/journeys-admin/pages/journeys/[journeySlug].tsx
> +  JourneyViewPageProps
These haven't changed at all, how come they've been reformatted?

Happens to a couple of files in this..

2022-01-11 04:44 UTC, storyworks commented on apps/journeys/next-env.d.ts
> -/// <reference types="next/types/global" />
This is still removed for some reason...

2022-01-11 08:59 UTC, csiyang commented on apps/journeys/next-env.d.ts
> -/// <reference types="next/types/global" />
I'll add that line of code back in

2022-01-11 09:00 UTC, csiyang commented on apps/journeys-admin/pages/journeys/[journeySlug].tsx
> +  JourneyViewPageProps
Not sure, I haven't touched them at all. I'll change it back though

2022-01-11 09:14 UTC, csiyang commented on apps/journeys-admin/pages/journeys/[journeySlug].tsx
> +  JourneyViewPageProps
@storyworks Found out these changes are brought in by prettier

2022-01-12 01:02 UTC, storyworks approved these changes

2022-01-12 01:07 UTC, merged