feat: add user invite api
JesusFilm/core pull request #1279
Opened 2023-01-25 22:18 UTC by storyworks

# Description

Creates and updates a userInvite to set journey permissions

[Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245893/todos/5763468706)

# How should this PR be QA Tested?

Stage graphql correctly returns expected data
- [ ] userInviteCreate - returns new userInvite
- [ ] userInvites - returns all user invites for a particular user
- [ ] userUpdate - returns updated userInvite (only allows changing `acceptedBy` value for now)

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2023-01-26 01:26 UTC, csiyang requested changes

2023-01-26 01:26 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.service.ts
> +  async getUserInviteByInviteId(id: string): Promise<UserInvite> {
any reason we couldn't use the get function from base service?

2023-01-26 01:26 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.graphql
> +  sentBy: ID!
This only ties invitations with the person who sends them right? What happens if someone else is also looking at the invitees, they won't be able to see the list of those that have been invited right?

2023-01-26 01:26 UTC, csiyang commented on apps/api-gateway/schema.graphql
> -"""DateTime custom scalar"""
how come this comment disappeared?

2023-01-26 01:26 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    const inviteId = uuidv4()
why is this needed? Can't we just use the id generated by arrango?

2023-01-26 19:54 UTC, storyworks commented on apps/api-gateway/schema.graphql
> -"""DateTime custom scalar"""
It's a generated file, possibly the last person who made the change didn't update the schema

2023-01-26 19:57 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    const inviteId = uuidv4()
UX haven't replied about whether they want the invite code to be more user friendly than uuid. I can use the userInvite for now and add this back in later, but at least now we have a record of the change :)

2023-01-26 19:59 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.service.ts
> +  async getUserInviteByInviteId(id: string): Promise<UserInvite> {
Since we're using the `inviteId` to fetch the userInvite rather than the `id` itself. 

After confirming with Tatai there are no security risks, let's revert to `id` and shift back to `inviteId` only if UX has a strong suggestion to use some other type of code.

2023-01-26 20:51 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.graphql
> +  sentBy: ID!
Umm kinda... so currently the user invited list shows everyone thats been invited. But that won't be the case when this gets added.

- say me and you are editors
- you invite someone to our journey and we're waiting for them to respond
- When I look on my user list for our journey, i'll see that they haven't been invited yet

2023-01-26 21:39 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.graphql
> +  sentBy: ID!
Interesting use case! 

We could make it that only the owner can invite people by email, so there would also only be 1 sender id.

We could also make the front end fetch all the userInvites linked to all the owners (if we make multiple owners in the future)

2023-01-26 22:19 UTC, csiyang requested changes

2023-01-26 22:19 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.graphql
> +  inviteId: ID!
Lets not add this until we're sure we want it. It's way more annoying to remove redundant data than to add a new field
```suggestion
```

2023-01-26 23:21 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.graphql
> +  inviteId: ID!
Oops, thought I removed - will do.

2023-01-31 03:20 UTC, csiyang requested changes

2023-01-31 03:20 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.spec.ts
> +          accepted: false
expire at needs to be tested here too. I think you need to mock the timer to make it work

2023-01-31 03:20 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +      return await this.userInviteService.update(id, { accepted: true })
can we make this conditional on the approve being successful?

2023-01-31 03:20 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    const userJourney = await this.userJourneyResolver.userJourneyRequest(
thoughts on a new resolver for creating a approved userJourney?

2023-01-31 03:25 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    console.log('JOURNEY ID', userInvite)
Oh my lol, thanks

2023-01-31 03:27 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    // TODO: Get email from user in db
No, this is still needed - we can't reference user related data between api's purely server-side. Tatai said it might make sense later down the line to allow user to be referenced by other apis. When it can, we no longer want to pass in email but get it from the user via userId

2023-01-31 03:27 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.spec.ts
> +          accepted: false
Just saw your test, can do.

2023-01-31 03:28 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    const userJourney = await this.userJourneyResolver.userJourneyRequest(
? We're reusing userJourneyApprove and that's already tested, so what would the new resolver do?

2023-01-31 03:29 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +      return await this.userInviteService.update(id, { accepted: true })
That's already the case, see line 91 below is the end of the `if` statement

2023-01-31 03:42 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.graphql
> +  senderId: ID!
By nature of it being the senderId, it cannot be the current user. 

We call userInviteCreate only when the newly invited user is logged in, so the current user is the invitee. Tatai wants senderId to be stored for auditing, we don't need to expose it on the front end.

2023-01-31 03:46 UTC, csiyang commented
Could not QA via stage, something about firebase token being wrong.

Locally the get and the create worked, but the accept did not. It throws the circular structure error, but after trying some different auth headers the call succeeded but the but the "accepted" value did not change

2023-01-31 03:53 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.graphql
> +  senderId: ID!
Doesn't this get created when the inviter creates the invite, how will it get created when the invitee logs in? User id's are exposed so, so if we expose senderId, bad actors can fake journey invites.

2023-01-31 03:56 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    const userJourney = await this.userJourneyResolver.userJourneyRequest(
it would create a userJourney that was already approved, instead of requesting and approving. Just a little cleaner I guess, but just wondering if it was something considered, not a change request

2023-01-31 05:22 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +      await this.userInviteService.getUserInviteByJourneyAndEmail(
We don't don't use the invite code anymore, navigating directly to the page will trigger the userInviteAccept call

2023-01-31 18:48 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    if (userInvite != null && input.email === userInvite.email) {
Forgot to add accepted and expired checks, doing that now + tests.

2023-02-01 03:22 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.graphql
> +    senderId: ID!
Oops, I think we can remove these now that we're getting via CurrentUserId...

2023-02-01 22:14 UTC, csiyang requested changes

2023-02-01 22:14 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    return userInvite
Do you mind if we do this just so it's a bit more clear?
```suggestion
    else { return userInvite }
```

2023-02-01 22:35 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    return userInvite
I would do this, but previous times Tatai has told me just to return.

2023-02-01 22:37 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    @Args('journeyId') journeyId: string
Needed so the RoleGuard can reference it.

2023-02-02 23:17 UTC, csiyang requested changes

2023-02-02 23:17 UTC, csiyang commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +      if (journey == null) throw new UserInputError('journey does not exist')
can we test this error?

2023-02-03 00:31 UTC, csiyang commented
Getting circular structure error when trying to test accept, will try to test the accept on https://github.com/JesusFilm/core/pull/1293#pullrequestreview-1282103498

2023-02-03 00:57 UTC, storyworks commented
> Getting circular structure error when trying to test accept, will try to test the accept on [#1293 (review)](https://github.com/JesusFilm/core/pull/1293#pullrequestreview-1282103498)

2023-02-06 21:04 UTC, csiyang commented
> Getting circular structure error when trying to test accept, will try to test the accept on [#1293 (review)](https://github.com/JesusFilm/core/pull/1293#pullrequestreview-1282103498)

Have tested the acceptAll is working

2023-02-06 21:04 UTC, csiyang approved these changes

2023-02-06 22:19 UTC, csiyang approved these changes

2023-02-06 22:20 UTC, storyworks commented on apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
> +    const userJourney = await this.userJourneyResolver.userJourneyRequest(
Better to reuse than to create a new one I think.

2023-02-06 22:21 UTC, merged