feat: add journeyProfile table
JesusFilm/core pull request #1295
Opened 2023-02-01 20:42 UTC by storyworks

# Description

Add a user profile table for api-journeys. 

[Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245893/todos/5783931883)

# How should this PR be QA Tested?

- [ ] Able to make a user profile for userId without profile with `getJourneyProfile`
- [ ] Able to retrieve a user profile via the userId with `getJourneyProfile`

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2023-02-01 22:53 UTC, csiyang commented on apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.graphql
> +}
add the update mutation? Or were you planning on doing that in another PR?

2023-02-01 23:01 UTC, csiyang commented
Also getting the circular structure error when trying to follow QA steps locally

2023-02-01 23:04 UTC, storyworks commented on apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.graphql
> +}
Oops forgot! Will do.

2023-02-03 00:41 UTC, csiyang requested changes
Also fix merge conflict in stage

2023-02-03 00:41 UTC, csiyang commented on apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.ts
> +        acceptedTermsAt: new Date().toISOString()
when I created a profile, the acceptedTermsAt value was null

2023-02-09 21:41 UTC, storyworks commented on apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.ts
> +        acceptedTermsAt: new Date().toISOString()
Not sure why that'd be unless you already had a profile in the db with acceptedTermsAt set to null... Nicks frontend change can help debug this.

2023-02-09 22:52 UTC, storyworks commented on apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.ts
> +        acceptedTermsAt: new Date().toISOString()
fixed!

2023-02-12 20:07 UTC, csiyang approved these changes

2023-02-12 20:08 UTC, merged