feat: journey builder invite by email
JesusFilm/core pull request #1323
Opened 2023-02-13 05:53 UTC by storyworks

# Description

[Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245893/todos/5763500979)

# How should this PR be QA Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2023-02-13 10:12 UTC, storyworks commented on apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
> +    const existingUserJourney = await this.userJourneyService.forJourneyUser(
Will extract out this change to a seperate PR - adding it here to fix bugs / allow UX to have preliminary testing.

2023-02-16 01:49 UTC, PShuckle commented
Trying to remove an access request as an editor throws an ApolloError

2023-02-16 01:55 UTC, PShuckle commented
1. Invite a user by email
2. In incognito tab, sign in with invited user and check you have access to the journey
3. On original account, without closing the access dialog, delete the newly added user
4. Refresh the incognito tab. User can still access the journey

2023-02-16 01:59 UTC, PShuckle commented
Invite disappears from UserList after invited user signs in

This check might not be applicable anymore since we can't invite users who have already requested access

2023-02-16 02:03 UTC, PShuckle commented
No change invite with same email as an existing request

Fails on access avatars from the JourneyCard.

2023-02-16 02:06 UTC, PShuckle commented
![Screen Shot 2023-02-16 at 3 02 04 PM](https://user-images.githubusercontent.com/72791134/219249052-0c66e3dc-072a-4617-9a30-3f0e7962ac1f.png)

Had a graphical glitch with the text field, can't figure out how to recreate it though

2023-02-16 02:38 UTC, storyworks commented on apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
>        </SnackbarProvider>
Adding all Nicks comments here just so we can resolve conversation once it's done:

- Trying to remove an access request as an editor throws an ApolloError
---
1. Invite a user by email
2. In incognito tab, sign in with invited user and check you have access to the journey
3. On original account, without closing the access dialog, delete the newly added user
4. Refresh the incognito tab. User can still access the journey
---
Invite disappears from UserList after invited user signs in
This check might not be applicable anymore since we can't invite users who have already requested access
---
No change invite with same email as an existing request
Fails on access avatars from the JourneyCard.

2023-02-16 02:52 UTC, storyworks commented on apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
>        </SnackbarProvider>
> Invite disappears from UserList after invited user signs in
>This check might not be applicable anymore since we can't invite users who have already requested access

Have clarified check with Nick, will be retested in next round of testing.

2023-02-16 03:28 UTC, csiyang requested changes

2023-02-16 03:28 UTC, csiyang commented on apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.tsx
> +    event: MouseEvent<HTMLElement>,
It doesn't look like this is being used, remove it?

2023-02-16 03:28 UTC, csiyang commented on apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
> +        update(cache, { data }) {
Test the cache gets updated correctly

2023-02-16 03:28 UTC, csiyang commented on apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
>      <Formik
lets check if we need to clear the form after submission

2023-02-16 03:28 UTC, csiyang commented on apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/RemoveUser.tsx
> +        update(cache, { data }) {
cache update is not being tested

2023-02-16 03:28 UTC, csiyang commented on apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.spec.tsx
> +    // const { getByRole } = render(
comments

2023-02-16 03:28 UTC, csiyang commented on apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.tsx
> +    return ''
use the default option for switch instead
```suggestion
```

2023-02-16 03:28 UTC, csiyang commented on apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.tsx
> +    return ''
oh and make sure the default option is tested

2023-02-16 03:28 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
> +            <JourneyProvider
why does this need journeyProvider now? Isn't already being wrapped at the page level?

2023-02-16 03:30 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
> +            <JourneyProvider
This is for the JourneyList page. I didn't want to prop drill `journey` down to The UserListItems that needed it.

2023-02-16 03:41 UTC, storyworks commented on apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
>        </SnackbarProvider>
> Invite a user by email
> In incognito tab, sign in with invited user and check you have access to the journey
> On original account, without closing the access dialog, delete the newly added user
> Refresh the incognito tab. User can still access the journey

Confirmed with Nick, wasn't a coding issue. Possible UX issue, it was the invite that was removed - not the newly created user. But it could be confusing that you think you're removing the user.

2023-02-16 03:50 UTC, storyworks commented on apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
>        </SnackbarProvider>
> No change invite with same email as an existing request
> Fails on access avatars from the JourneyCard.

Occurs because you've requested an invite and this data has been saved to the server. But on the original browser tab, unless you close and reopen the dialog, we don't refetch that data. So it looks like the request hasn't been made.

I've added back the complex flow to reflect this will just happen.

2023-02-16 03:58 UTC, storyworks commented on apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
> +            : ''
This is better as an E2E test.. 

Essentially to test it, I'd be creating a scenario where I have 1 user, I request and 3 invites (1 with removedAt value, 1 with acceptedAt value, 1 with null for both fields).

Input the email and check validation for each of these 5 cases and check that 3 of them throw the error and 2 of them don't.

It seemed a bit overkill to mock this (and the dependencies of `EmailInviteForm`) all out within AccessDialog, when I do test in EmailInviteForm that validation works provided a list of emails.

2023-02-16 03:59 UTC, storyworks commented on apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.tsx
> +    event: MouseEvent<HTMLElement>,
Line 83 & line 86

2023-02-16 18:15 UTC, storyworks commented on apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
>      <Formik
This is still needed as the user could miss seeing the user on the list after going away /  coming back and type it again.

2023-02-16 19:29 UTC, storyworks commented on apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.spec.tsx
> +    // const { getByRole } = render(
I wanted to uncomment and reuse this for testing once the updated Avatars changes get merged in

2023-02-17 02:18 UTC, merged