C4/journey card
JesusFilm/core pull request #134
Opened 2021-11-23 01:33 UTC by csiyang

Journey card component for JourneyList

2021-12-02 23:47 UTC, storyworks requested changes

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
> +    it('should render the formated  date', () => {
```suggestion
    it('should format the date with day and month', () => {
```

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
> +    it('should not render the draft status', () => {
Not sure this test is needed?

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
> +      const { getAllByText } = render(<JourneyCard journey={draftJourney} />)
```suggestion
      const { getAllByText } = render(<JourneyCard journey={defaultJourney} />)
```

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
> +    const draftJourney: Journey = {
Can just use defaultJourney from journeyListData

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
> +    const oldJourney: Journey = {
Can remove this and import from journeyListData

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
> +  describe('journey created at before the current year', () => {
It's nice to group the tests if there are multiple different functions being tested (eg getTitle, getDate...), but in our case, it's just the data that differs so all these tests could go under describe "JourneyCard"

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
> +    it('should render the formated date with year', () => {
```suggestion
    it('should format dates from previous years with year', () => {
```

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.stories.tsx
> +export const CardWithLongText = Template.bind({})
```suggestion
export const LongText = Template.bind({})
```

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.stories.tsx
> +CardWithLongText.args = {
```suggestion
LongText.args = {
```

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
> +const Template: Story = ({ ...args }) => <JourneyList journeys={[]} {...args} />
```suggestion
const Template: Story<JourneyListProps> = ({ ...args }) => <JourneyList {...args} />
```

And export JourneyListProps like how we did for the others

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +        <b>{date}</b> {' - '}
```suggestion
       `{date}{journey.description !== null ? ` - ${journey.description}`: ""}`
```

So we don't display the dash when there's no description

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +    <Card sx={{ padding: '15px 29px', borderRadius: '0px' }} variant="outlined">
```suggestion
    <Card sx={{ padding: '15px 29px', borderRadius: '0px' }} variant="outlined">
```
Avoid hardcoding pixel values - we have spacing tokens we can use for padding. See https://mui.com/system/the-sx-prop/#spacing

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +              margin: '0px 15px',
Same here for spacing.. just find the closest match.

Also, just add a margin-left so this same chip styling can be used for locale as well

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +        <Chip
This is used quite often - could be extracted out as a component itself.. JourneyCardChip or something.. but we can do that refactoring later.

2021-12-02 23:47 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +        <Box sx={{ marginLeft: 'auto' }}>
Stick to flexBox for element positioning rather than using margin / left/right when you can. But we can leave this here for now since we might need to make some changes to JourneyCardMenu

2021-12-02 23:48 UTC, storyworks commented
Nice to see some thorough tests and stories!

2021-12-03 02:24 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.spec.tsx
> +import { render } from '@testing-library/react'
The PR is up for it now :D

2021-12-03 04:13 UTC, storyworks requested changes

2021-12-03 04:13 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
> +    it('should not render the draft status', () => {
Remove test, we aren't conditionally rendering publish or draft - we are just rendering the chip for a status type. Similar to how we're rendering typography for some heading text.

Even some cases of conditional rendering - testing the negative condition isn't necessary eg when we're using switch statements.

2021-12-03 04:13 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
> +    it('should render the formated date with year', () => {
Change naming so we can understand the requirement (context / action) just from the heading - will be more useful when we do test coverage analytics and need to just rely on the heading to understand test

2021-12-03 04:13 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.stories.tsx
> +export const CardWithLongText = Template.bind({})
Story naming convention is to keep it short:
![image](https://user-images.githubusercontent.com/10802634/144543570-f8bbd66e-5b7d-4a80-a612-4ac047c015a1.png)

Probably no need to add "Journey" to scenarios too. "Published", "NoDescription", "LongText", "PrevYear"

I've been making Default the minimal setup (only have the required props), because everything else is an added feature. So possibly better to do "Published", "Description", "ExcessContent" (contains long title, description, avatars, locale name is long too), "PrevYear"

2021-12-03 04:14 UTC, storyworks commented
Also there are still some Access Avatar files on this PR to be removed :)

2021-12-05 22:43 UTC, storyworks requested changes

2021-12-05 22:43 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
> +  it('should render the formatred  date', () => {
```suggestion
  it('should render the formatted  date', () => {
```

2021-12-05 22:43 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/journeyListData.ts
> +  __typename: 'Journey',
```suggestion
...defaultJourney,
```
And remove rest of duplicated values? id, theme, publishedAt etc

2021-12-05 22:43 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/journeyListData.ts
> +  description: ' a published journey',
Remove space ?
```suggestion
  description: 'a published journey',
```

2021-12-05 22:43 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
> +const Template: Story = ({ ...args }) => <JourneyList journeys={[]} {...args} />
If you set the type of Story as <JourneyListProps> this avoids you having to specify a placeholder `journeys={[]}` for every prop on this component (good practice for when components have multiple props / since we're using typescript)

2021-12-05 22:54 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/journeyListData.ts
> +  locale: 'tzm-Latn-DZ',
Lastest thinking around locale is using locales from:
https://github.com/mozilla/language-mapping-list/blob/master/language-mapping-list.js

so `tzm-Latn-DZ` would not be possible for now, so feel free to remove this as a prop / just use the default for this scenario as well.

2021-12-05 23:09 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/journeyListData.ts
> +  locale: 'tzm-Latn-DZ',
I thought you wanted me to put in a locale with a long name here?

2021-12-05 23:27 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/journeyListData.ts
> +  locale: 'tzm-Latn-DZ',
I updated it with the longest one I could find from the suggested list _zh-Hans_

2021-12-06 00:50 UTC, storyworks approved these changes

2021-12-06 01:36 UTC, merged