fix: edit text and button block on create
JesusFilm/core pull request #1356
Opened 2023-02-22 01:33 UTC by storyworks

# Description

It's annoying to select and edit text on the typography and button blocks on creation. This PR triggers edit mode when on block create for just those components and replaces existing content with a placeholder.

https://3.basecamp.com/3105655/buckets/31245472/todos/5861894458
https://3.basecamp.com/3105655/buckets/31245472/todos/5863849539

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Create a typography block, it should be immediately editable & have placeholder text.
- [ ] If you press done / blur without typing anything, the entire block is deleted
- [ ] If you type and then press done / blur - the content is saved

- [ ] Create a button block, it should be immediately editable & have placeholder text.
- [ ] If you press done / blur without typing anything, the button block is saved with nothing.
- [ ] If you type and then press done / blur - the content is saved

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2023-02-22 03:40 UTC, csiyang requested changes

2023-02-22 03:40 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.spec.tsx
Every component where you've used use-translation needs a i18n mock

```
jest.mock('react-i18next', () => ({
  __esModule: true,
  useTranslation: () => {
    return {
      t: (str: string) => str
    }
  }
}))
```

2023-02-22 03:40 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
> +      onClick={(e) => {
why the change here?

2023-02-22 03:48 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.spec.tsx
Why if the test passes without it?

2023-02-22 03:48 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
> +      onClick={(e) => {
Can tidy up - I was experimenting with fixes.

2023-02-23 02:09 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.spec.tsx
It throws like a million warning messages, really clogging up logs when we're running tests

2023-02-23 18:31 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.spec.tsx
Ah! Good point, can do.

2023-02-23 20:21 UTC, csiyang approved these changes

2023-03-02 23:00 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
> +  // TODO: Refactor out delete block logic
I've just copied over the selection logic which occurs after a normal block delete. Want to refactor this out in a subsequent PR - hence have not added tests for this. This refactor would touch a couple of different components so didn't want to do it in this PR.

2023-03-02 23:03 UTC, storyworks commented on libs/journeys/ui/src/components/Typography/Typography.tsx
> +      sx={{ wordBreak: 'break-all' }}
Fixes this issue 
<img width="390" alt="image" src="https://user-images.githubusercontent.com/10802634/222580130-2d8526c1-4a32-4026-aba3-929279a51e19.png">

2023-03-03 02:54 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Variant/Variant.tsx
> +      nested
Fixes control panel background color incorrect.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/10802634/222619638-53c898c0-d5dd-4083-9901-ad9239a36d84.png">

2023-03-03 03:05 UTC, storyworks commented on libs/journeys/ui/src/components/Typography/Typography.tsx
> +      sx={{ wordBreak: 'break-all' }}
Actually, sorry I'm going to revert this, since normal words look incorrect (see VR)
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/10802634/222621244-b2bf2cfb-747f-41d8-baf6-742058733a17.png">

2023-03-03 04:26 UTC, csiyang commented
- If you have an empty typography block (new or recently deleted), click and drag to select all the text - don't yet release the mouse! Move the mouse to outside the input but within the card - let go of the mouse, the input should stay focused.

Not sure what an empty typog block means, but a tried a typog block that has text and the card was selected, and I tried after deleting the text and it brought back the text I deleted and selected the card
 
- Put the cursor in any position in the input field and change text block properties, it should stay in the same place.

How to change text block properties while leaving cursor in the input field???

2023-03-05 18:18 UTC, storyworks commented
> * If you have an empty typography block (new or recently deleted), click and drag to select all the text - don't yet release the mouse! Move the mouse to outside the input but within the card - let go of the mouse, the input should stay focused.
> 
> Not sure what an empty typog block means, but a tried a typog block that has text and the card was selected, and I tried after deleting the text and it brought back the text I deleted and selected the card
> 

Strange, it should work - huddle sometime today?

> * Put the cursor in any position in the input field and change text block properties, it should stay in the same place.
> 
> How to change text block properties while leaving cursor in the input field???

If you click into the cursor field, and then click to change text block properties - the cursor shouldn't leave the input field / it should still be in edit mode if you tried typing between changing text block properties.

2023-03-05 20:35 UTC, csiyang approved these changes

2023-03-05 20:48 UTC, merged