fix: access denied edit report
JesusFilm/core pull request #1376
Opened 2023-02-27 23:38 UTC by tanflem

# Description
Before FIX: 
journeys/[id]/edit - 501 error if the user did not have access
journeys/[id]report - allowed the user to view even without access

After FIX:

journeys/[id]/edit - Redirects to journeys/[id] when the user does not have access
journeys/[id]report - Redirects to journeys/[id] when the user does not have access

-   [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245472/todos/5855598322)

# How should this PR be QA Tested?

-  Navigate to journeys/[id]/edit on a journey that the current user does not have access to. Should Redirect to journeys/[id] and Request Access.
-   Navigate to journeys/[id]/reports on a journey that the current user does not have access to. Should Redirect to journeys/[id] and Request Access.

# Checklist

-    I have performed a self-review of my own code
-    I have commented my code, particularly in hard-to-understand areas
-    I have made corresponding changes to the documentation
-    Any dependent changes have been merged into main

2023-02-27 23:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JesusFilm/core?pullRequest=1376) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JesusFilm/core?pullRequest=1376) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JesusFilm/core?pullRequest=1376) it.</sub>

2023-02-28 01:13 UTC, csiyang requested changes

2023-02-28 01:13 UTC, csiyang commented on apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
> +})(async ({ AuthUser, locale, query}) => {
Can we also remove the error check on line 42, its not needed anymore since we added a try catch

2023-02-28 01:23 UTC, tanflem commented on apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
> +})(async ({ AuthUser, locale, query}) => {
Pushed

2023-02-28 19:36 UTC, csiyang approved these changes

2023-02-28 20:08 UTC, merged