C4 - Sort Journeys
JesusFilm/core pull request #140
Opened 2021-11-25 22:45 UTC by storyworks

TODO:

Finish tests

2021-12-20 20:53 UTC, tataihono requested changes

2021-12-20 20:53 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +import JourneysAppBar from '../JourneysAppBar'
didn't the import change on this?

2021-12-20 20:53 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +    })
this logic could be moved out into a function and tested?

2021-12-20 20:53 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneySort/JourneySort.tsx
> +            Cancel
this button bottom margin on mine looks off

2021-12-20 20:53 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +          borderTopLeftRadius: border,
I'm not a fan of using breakpoints for styling. We should reserve useBreakpoints where codeflow is affected by responsiveness. You should use the expressive syntax inline that mui provides for this.

```suggestion
          borderTopLeftRadius: { xs: 0, sm: 12 },
```

2021-12-20 20:53 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +import JourneysAppBar from '../JourneysAppBar'
didn't i see somewhere where this changed from a default export?

2021-12-20 21:25 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneySort/JourneySort.tsx
> +            Cancel
It is off because it uses Button medium and that's something that comes from theming which I don't want to touch yet because it'll affect your buttons too..

2021-12-20 21:27 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +    })
This is unit tested in JourneyList at the moment, didn't extract it out yet since it was still small..

2021-12-21 00:37 UTC, tataihono approved these changes

2021-12-21 00:37 UTC, merged