refactor: remove redundant router and title
JesusFilm/core pull request #1406
Opened 2023-03-13 02:44 UTC by storyworks

# Description

Fixing this before I add in my PageWrapper changes. Starting PageWrapper changes so we can easily add in the side panel on the landing page.

2 Changes:
- Use useRouter directly in NavigationDrawer instead of passing `router` down 2 levels
- remove unused `title` prop

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Checks are green
- [ ] Drawer still highlights correct page
- [ ] Drawer still shows correctly on desktop and mobile

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2023-03-13 22:22 UTC, csiyang requested changes

2023-03-13 22:22 UTC, csiyang commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
> -          selected={selectedPage === 'journeys' || selectedPage == null} // null for when page is index. UPDATE when we add the actual index page
can we keep the comment? I still don't think its super clear why `selectedPage == null` is there for otherwise.

2023-03-13 22:22 UTC, csiyang commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
> +            selectedPage === 'journeys' || selectedPage === '' || router == null
why check `router == null` here? If router is null it would be an error right?

2023-03-13 22:27 UTC, storyworks commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
> -          selected={selectedPage === 'journeys' || selectedPage == null} // null for when page is index. UPDATE when we add the actual index page
Actually, I tested and when the page is index, it was correctly returning "/".

2023-03-13 22:34 UTC, storyworks commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
> +            selectedPage === 'journeys' || selectedPage === '' || router == null
Router is null in stories. I did look into using https://github.com/scottrippey/next-router-mock but it didn't work initially. Possibly I'd need more time to debug to get it to work.

If the router was jacked in main, I'm not sure we'd even be able to get to this page :/ So mainly added this here to say, if it's null for whatever reason - make "journeys" the selected icon by default.

But true, maybe this is better to push through more thoroughly after mocking properly works.

2023-03-14 01:06 UTC, csiyang commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
> -          selected={selectedPage === 'journeys' || selectedPage == null} // null for when page is index. UPDATE when we add the actual index page
oh sounds good then

2023-08-01 04:24 UTC, closed without merging