C4/journey card menu
JesusFilm/core pull request #142
Opened 2021-11-29 01:28 UTC by csiyang

2021-12-03 02:21 UTC, storyworks requested changes

2021-12-03 02:21 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/journeyListData.ts
> +  status: JourneyStatus.published
In another PR we made this draft

```suggestion
  status: JourneyStatus.draft
```

2021-12-03 02:21 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
> +    fireEvent.click(getByRole('button'))
Should also check     `expect(getByRole('button')).toHaveAttribute('aria-expanded', 'true')` after button is clicked

2021-12-03 02:21 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
> +    expect(getByRole('menu')).toHaveAttribute(
Check this before clicking the button? It's something that should be set no matter if you click the button or not.

2021-12-03 02:21 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.stories.tsx
> +const JoruneyCardMenuDemo = {
```suggestion
const JourneyCardMenuDemo = {
```
Typo is repeated a couple of times down this page as well

2021-12-03 02:21 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.stories.tsx
> +export const DraftJoruneyCardMenu = Template.bind({})
```suggestion
export const Draft = Template.bind({})
```

2021-12-03 02:21 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.stories.tsx
> +export const PublishedJoruneyCardMenu = Template.bind({})
```suggestion
export const Published = Template.bind({})
```

2021-12-03 03:35 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
> +        <Link href={`/journeys/${slug}/access`} underline="none">
nope, just a placeholder, hence the comment above it

2021-12-03 03:58 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
> +    expect(getByRole('menu')).toHaveAttribute(
menu does not appear in the DOM before the button is clicked on

2021-12-03 04:05 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.stories.tsx
> +const Template: Story = ({ ...args }) => (
How do we force this to open? Would I need to update the component to allow for this?

2021-12-05 22:26 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.stories.tsx
> +const Template: Story = ({ ...args }) => (
Yeah you would.. add the open prop to JourneyCardMenuProps - you can make it an optional `open?: boolean`

2021-12-05 22:26 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
> +    expect(getByRole('menu')).toHaveAttribute(
Good point!

2021-12-07 00:44 UTC, merged