feat: common icon button
JesusFilm/core pull request #1421
Opened 2023-03-19 15:50 UTC by tanflem

# Description

Added a common component for the icon button. Created stories for said component.
<img width="571" alt="image" src="https://user-images.githubusercontent.com/17752008/226187605-2de910d5-11ad-4391-b771-7d01b29a436b.png">

- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31822575/todos/5935534867#__recording_5945605020)

# How should this PR be QA Tested?

The component is currently not used anywhere but the stories can be tested and the tests can be run. Ideally component is tested when added to the template side bar.

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2023-03-19 15:52 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +  icon?: typeof SvgIcon
Here I changed from ReactNode type to SvgIcon in order to use the ImageBlockThumnail component. However, I have a reworked version that does not use that component. I was not sure which would be better.

2023-03-19 15:52 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +import { ImageBlockThumbnail } from '../Editor/ImageBlockThumbnail'
Should I be using this component?

2023-03-19 15:54 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
> +import { render, fireEvent } from '@testing-library/react'
This was my first time making tests. I looked at some other files as examples. If there are things I need to add I would appreciate a bit of explanation of the workflow when creating these tests to cover all bases.

2023-03-19 15:56 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +import { Meta, Story } from '@storybook/react'
The same goes for stories as tests. This was my first time, and I am unsure if I covered all the bases. Would appreciate a short process explanation.

2023-03-19 21:49 UTC, storyworks commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +import { ImageBlockThumbnail } from '../Editor/ImageBlockThumbnail'
Not directly, but you'd probably be using much of the same logic. Take a look at https://docs.core.jesusfilm.org/docs/basics/frontend/component-library/#our-components for some context :) 

Essentially we have an existing component 
<img width="318" alt="image" src="https://user-images.githubusercontent.com/10802634/226210445-a91f367e-7ab9-4b64-a8d7-888b379cf647.png">

And in our designs, we have a new button which looks and functions almost exactly the same. But we can't use the existing component since it has some built in logic specific to it's current use case (eg ImageBlockThumbnail requires a selectedBlock to display the image source.)

So we want to built a common component that can render both our new design and the existing one.

Sorry I forgot to add loading / error icon use cases to the todo like how they have in ImageBlockThumbnail.

2023-03-19 21:49 UTC, storyworks commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +  icon?: typeof SvgIcon
I suggested `ReactNode` so in the future to use it, we can pass <OurCustomIcon/> and it will just render whatever we pass it. <OurCustomIcon/> will actually be a component we build to standardise how we use icons. 

We could reuse image thumbnail, but I'd recommend refactoring it first in another PR. eg:
1) Move ImageBlockThumbnail outside of Editor and as a direct component within journey-admins components. (since it's used outside of the Editor now too)
2) Rename to ImageThumbnail since it displays images not just for blocks
3) split out `selectedBlock` field into `imageSrc` and `imageAlt` props. 

I'd still like to use `ReactNode` in this refactor just to support future icon use.

Tests / stories would then also need to be updated.

2023-03-19 21:49 UTC, storyworks commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +import { Meta, Story } from '@storybook/react'
https://docs.core.jesusfilm.org/docs/basics/frontend/storybook/ 

Let me know if there are any questions after that :) Would be nice to refine the docs.

2023-03-19 21:49 UTC, storyworks commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
> +import { render, fireEvent } from '@testing-library/react'
We don't have docs for this yet but looks like you're on the right track :) 

Generally we test interaction logic like onClick or any additional display logic in the component (eg disabled ? items[0]: items => "it shows only the first item in the list when disabled")

The goal is to have basic interactions, low level logic tested by Unit tests. CSS and other simple display logic (eg that all elements appear on the page when passed) tested by VR and complex inter-component interactions tested via E2E (when it's up).

2023-03-19 21:49 UTC, storyworks commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +    <>
React only allows 1 child node to be returned for the component function. 

So if we had something like 
```
Component(){
return (<div/><div/>)
}
```

It would error saying we're passing 2 nodes and it only accepts one. Fragments (`<> </>`) can be used to wrap these 2 divs to tell the compiler to treat them as 1.

In this case the entire component is encompassed by `<Card/>` so the extra fragments are redundant. There are a couple of places in our code base that I've seen redundant fragments. Feel free to remove them during cooldown, they should not be in there.

2023-03-19 21:57 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +import { ImageBlockThumbnail } from '../Editor/ImageBlockThumbnail'
Also noticed the existing button only has the icon clickable, but the common component, the entire button is clickable. Did UX mention what behaviour they wanted?

2023-03-28 02:45 UTC, csiyang requested changes
Good job, almost there! Just a few changes to be made =)

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +            {description !== undefined && (
The check below will check both null and undefined https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality

```suggestion
            {description != null && (
```

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +Image.args = {
```suggestion
export const Complete = Template.bind({})
Complete.args = {
```

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +  onClick: () => console.log('Clicked')
we can use noop in this case since we don't need to worry about what the on click is doing. You can import it from the lodash library (its in our packages already)

```suggestion
  onClick: noop
```

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +  onClick: () => console.log('Clicked')
```suggestion
  onClick: noop
```

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +  onClick: () => console.log('Clicked')
```suggestion
  onClick: noop
```

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +  imageAlt: undefined,
Not needed
```suggestion
```

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
> +        onClick={onClick}
```suggestion
        onClick={noop}
```

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
> +  //   })
Remove comment
```suggestion
```

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
> +
Add a test for the description since its conditionally rendered

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +  onClick: () => void
Small nit pick, but this should be called handleClick, also update for the rest of the document
```suggestion
  handleClick: () => void
```

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +  actionIcon: ReactNode
Lets make these optional, and fill it with some icons by default
```suggestion
  thumbnailIcon?: ReactNode
  actionIcon?: ReactNode
```

2023-03-28 02:45 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +  actionIcon,
The ImageThumbnail already handles a default icon if one is not given. Once you do this

- on stories, for the default story, you should no longer need to pass in thumbnailIcon and actionIcon
- on tests, add a test to see if a custom `actionIcon` will show.

```suggestion
  thumbnailIcon,
  actionIcon = <AddIcon />,
```

2023-03-28 13:02 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +  icon?: typeof SvgIcon
Current component uses React Node.
ImageBlockThumbnail refactored here.
https://github.com/JesusFilm/core/pull/1442

2023-03-28 13:03 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +import { ImageBlockThumbnail } from '../Editor/ImageBlockThumbnail'
Refactored here.
https://github.com/JesusFilm/core/pull/1442

2023-03-28 13:20 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +  onClick: () => console.log('Clicked')
fixed in d8e8bf0109b1e043cd7b28720c33560c89eab24c

2023-03-28 13:21 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +Image.args = {
fixed in d8e8bf0109b1e043cd7b28720c33560c89eab24c

2023-03-28 17:05 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +            {description !== undefined && (
fixed in cc28faa3eac2c914812f6794c2f77c31032c2471

2023-03-28 17:06 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +  actionIcon,
fixed in 1dca4540ebe0a2853e4ff46a2f5f024b0153a5d0

2023-03-28 17:06 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +  actionIcon: ReactNode
fixed in 1dca4540ebe0a2853e4ff46a2f5f024b0153a5d0

2023-03-28 17:07 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +  onClick: () => void
fixed in 1dca4540ebe0a2853e4ff46a2f5f024b0153a5d0

2023-03-28 17:15 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
> +
added in 5f8047e2ba7d0fc3cd7c2ee05a0ffeb9bfadc894

2023-03-28 17:18 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
> +    expect(onClick).toHaveBeenCalled()
I was getting an error here when trying `expect(noop).toHaveBeenCalled`

Is there a way to do this with noop or is it correct to use the jest function?

2023-03-28 17:21 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +          <Icon color="primary" sx={{ pr: 8 }}>
This is the information I have about the padding. Does this look correct? Is this something that is worth posting in the shared channel and asking the designers?

![Screenshot 2023-03-28 at 1 19 55 PM](https://user-images.githubusercontent.com/17752008/228318858-2bff39ab-aeca-428f-83db-d7cd2002955c.png)

<img width="778" alt="Screenshot 2023-03-28 at 8 41 25 AM" src="https://user-images.githubusercontent.com/17752008/228318358-56ef077c-d783-419b-be60-77856727f063.png">

This is how I currently have it. 
<img width="314" alt="Screenshot 2023-03-28 at 8 46 51 AM" src="https://user-images.githubusercontent.com/17752008/228318399-d75919e1-e5cf-42c6-bf11-a9b46d53455b.png">

2023-03-28 20:14 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
> +    expect(onClick).toHaveBeenCalled()
Yes this one needs to stay as a jest function, noop is for when we don't really care about what the function is doing

2023-03-28 20:30 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +          <Icon color="primary" sx={{ pr: 8 }}>
Just checked the design, yep the padding is good. Its off by like 1px, but thats ok since we should use spacing tokens (1 spacing token = 4px)

2023-03-28 20:35 UTC, csiyang commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +  </Paper>
We usually use paper for stories that need the background/ needs it to provide context for multiple components.
```suggestion
  <Box sx={{maxWidth: '300px'}}>
      <ContainedIconButton {...args} />
    </Box>
```

2023-03-28 20:40 UTC, storyworks commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +  thumbnailIcon: <NoteAddIcon />,
Only pass in the required props in default. Default should show us the state of the component when we pass in the bare minimum / don't customise it in any extra way.

2023-03-28 20:44 UTC, storyworks commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +  description: 'descripition',
typo :)

2023-03-28 21:42 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +  description: 'descripition',
fixed in b391cafd3f6e38079bdd51e9ac4f5d7f20714d4b

2023-03-28 21:44 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
> +  onClick: () => void
back to onClick in 057027edb949c85f092aaa1c431a7a891cc24854

2023-03-28 22:22 UTC, tanflem commented on apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
> +  </Paper>
fixed in f05592296ac42d6ff6667e8ed9e238d75e4b83c1

2023-03-29 00:57 UTC, csiyang approved these changes

2023-03-29 01:13 UTC, merged