FramePortal
JesusFilm/core pull request #143
Opened 2021-11-29 02:12 UTC by tataihono

- add FramePortal component
- add types for journeys-admin

2021-11-29 21:18 UTC, storyworks commented on apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
> +const StyledFrame = styled('iframe')(() => ({
I'm going to add a todo for this for cooldown https://mui.com/system/styled/#how-to-use-components-selector-api

2021-11-29 21:37 UTC, storyworks commented on apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
> +    <StylesProvider>
What's the use of `StylesProvider` if we're not passing any props to it atm? 
It's part of mui legacy styling so unless we really need it should we omit it? Removing it, the story still had correct styling..

2021-11-29 21:40 UTC, storyworks commented on apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
> +  ...other
```suggestion
  ...props
```
Shall we stick to React terminology?

2021-11-29 22:03 UTC, storyworks requested changes

2021-11-29 22:03 UTC, storyworks commented on apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
> +  const [iframeLoaded, onLoad] = useReducer(() => true, false)
```suggestion
  const [iframeLoaded, dispatch] = useReducer(() => true, false)
```
or use `dispatchLoad`? Keeping to React terminology makes it a bit more familiar to read + on___ comes with all sorts of other connotations.

2021-11-29 22:03 UTC, storyworks commented on apps/journeys-admin/apollo.config.js
> +    includes: ['./pages/**', './src/**', '../../libs/journeys/ui/**'],
What's this for?

2021-11-30 01:19 UTC, tataihono commented on apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
> +  ...other
is this the norm in react? I thought props was only used when it contained all the props. In react docs i've seen other and rest as the name of the remaining props.

2021-11-30 01:21 UTC, tataihono commented on apps/journeys-admin/apollo.config.js
> +    includes: ['./pages/**', './src/**', '../../libs/journeys/ui/**'],
needed to generate types with fragments in a different location.

2021-11-30 01:30 UTC, tataihono commented on apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
> +    <StylesProvider>
removed

2021-11-30 01:30 UTC, tataihono commented on apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
> +  ...other
going with rest as I have seen that elsewhere.

2021-11-30 01:30 UTC, tataihono commented on apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
> +      <StyledFrame onLoad={onLoad} ref={frameRef} {...other} />
ok

2021-11-30 01:31 UTC, tataihono commented on apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
> +  const [iframeLoaded, onLoad] = useReducer(() => true, false)
done

2021-11-30 01:31 UTC, tataihono commented on apps/journeys-admin/src/components/FramePortal/FramePortal.spec.tsx
> +    ).toHaveStyle('font-family: "Roboto","Helvetica","Arial",sans-serif')
done

2021-12-02 03:49 UTC, storyworks requested changes
Merge in latest master? (It updates the config so we only use light theme in storybook - will change VR) Otherwise looks good :)

2021-12-02 03:51 UTC, storyworks commented on apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
> +  ...other
I've mainly just seen props

2021-12-05 23:13 UTC, storyworks approved these changes

2021-12-05 23:14 UTC, merged