C4/ share section for single journey
JesusFilm/core pull request #144
Opened 2021-11-29 02:53 UTC by csiyang

2021-12-13 23:05 UTC, tataihono requested changes

2021-12-13 23:05 UTC, tataihono commented on apps/journeys-admin/src/components/SingleJourney/ShareSection/ShareSection.spec.tsx
> +describe('JourneyShare', () => {
```suggestion
describe('ShareSection', () => {
```

2021-12-13 23:05 UTC, tataihono commented on apps/journeys-admin/src/components/SingleJourney/ShareSection/ShareSection.spec.tsx
> +    console.log(getAllByRole('button'))
no console log

2021-12-13 23:05 UTC, tataihono commented on apps/journeys-admin/src/components/SingleJourney/ShareSection/ShareSection.spec.tsx
> +      expect(getByText('Link Copied')).toBeInTheDocument()
only have one expect per waitFor.

2021-12-13 23:05 UTC, tataihono commented on apps/journeys-admin/src/components/SingleJourney/ShareSection/ShareSection.stories.tsx
> +  // forceMenu: true
delete

2021-12-13 23:05 UTC, tataihono commented on apps/journeys-admin/src/components/SingleJourney/ShareSection/ShareSection.tsx
> +const ShareSection = ({ slug, forceMenu }: ShareSectionProps): ReactElement => {
this should be function
```suggestion
export function ShareSection ({ slug, forceMenu }: ShareSectionProps): ReactElement {
```

2021-12-13 23:05 UTC, tataihono commented on apps/journeys-admin/src/components/SingleJourney/ShareSection/ShareSection.tsx
> +export default ShareSection
we will be dropping default exports soon

2021-12-13 23:05 UTC, tataihono commented on apps/journeys-admin/src/components/SingleJourney/ShareSection/index.ts
> +export { default } from './ShareSection'
```suggestion
export { ShareSection } from './ShareSection'
```

2021-12-13 23:34 UTC, csiyang commented on apps/journeys-admin/src/components/SingleJourney/ShareSection/ShareSection.stories.tsx
> +  // forceMenu: true
Need this prop for VR testing, I have uncommented it

2021-12-19 23:54 UTC, storyworks requested changes

2021-12-20 01:10 UTC, csiyang commented on apps/journeys-admin/src/components/ThemeProvider/admin/tokens/components.ts
> +          borderRadius: 40
There's a change on another PR making the default not capitalized

2021-12-20 17:01 UTC, storyworks requested changes

2021-12-20 19:19 UTC, merged

2021-12-20 19:23 UTC, csiyang commented on apps/journeys-admin/src/components/SingleJourney/ShareSection/ShareSection.tsx
> +      {breakpoints.sm ? (
I used sm so that the tablet view could be similar to the desktop view