C4/Single journey actions
JesusFilm/core pull request #154
Opened 2021-12-03 03:31 UTC by storyworks

TODO: 
Update with real url
Find out about journeyUpdate..

2021-12-10 02:19 UTC, tataihono requested changes

2021-12-14 18:12 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourneyPage/CardOverview/CardOverview.stories.tsx
> +  title: 'Journeys-Admin/SingleJourneyPage/CardOverview'
List / View / Edit / Create ?

2021-12-14 19:15 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyView/CardView/CardView.stories.tsx
> +const CardViewDemo = {
```suggestion
const CardViewStory = {
```

2021-12-14 19:16 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyView/CardView/CardView.stories.tsx
> +export default CardViewDemo as Meta
```suggestion
export default CardViewStory as Meta
```

2021-12-14 19:17 UTC, storyworks commented on apps/journeys-admin/src/components/ThemeProvider/admin/tokens/components.ts
> +          maxHeight: 48,
Adding the large button makes the Properties Toolbar 1 pixel off from the main Toolbar

2021-12-20 04:02 UTC, tataihono requested changes
some changes for you 👍🏽

2021-12-20 04:02 UTC, tataihono commented on apps/journeys-admin/src/components/ThemeProvider/admin/tokens/components.ts
> -          borderBottom: '1px solid #DCDDE5'
this removal is going to change depart from the styles vlad had created. I am assuming this is something aerial advocated for?

2021-12-20 04:09 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/JourneyDetails.tsx
> +    : format(date, 'MMM do, yyyy')
For reference this is what I changed it to
`const formattedDate = intlFormat(date, {
    day: 'numeric',
    month: 'long',
    year: isThisYear(date) ? undefined : 'numeric'
  })`

2021-12-20 19:44 UTC, storyworks commented on apps/journeys-admin/src/components/ThemeProvider/admin/tokens/components.ts
> -          borderBottom: '1px solid #DCDDE5'
I'm adding it on the Toolbar instead of the app bar

2021-12-20 19:50 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
> +      id
I know it does pass it back, but do I really need to ask to fetch it if I don't need to use it anywhere?

2021-12-20 19:56 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
> +      <Divider />
Need to keep it here as there is no drawer in mobile mode

2021-12-20 22:56 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyView/Context/Context.tsx
> +export const JourneyContext = createContext<Journey>(defaultJourney)
https://kentcdodds.com/blog/how-to-use-react-context-effectively Using this to update how we use context

2021-12-21 23:37 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyView/Menu/Alert/Alert.tsx
> +import { ReactElement } from 'react'
Will change in cool down

2021-12-21 23:37 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.tsx
> +  const [showSuccessAlert, setShowSuccessAlert] = useState(false)
Will do in cool down

2021-12-21 23:39 UTC, csiyang approved these changes

2021-12-21 23:40 UTC, merged