updated links used in menu
JesusFilm/core pull request #160
Opened 2021-12-07 02:42 UTC by csiyang

Updated place holder links in the menu

2021-12-09 22:24 UTC, jianwei1 approved these changes

2021-12-12 23:12 UTC, storyworks approved these changes

2021-12-13 23:00 UTC, tataihono requested changes

2021-12-19 20:13 UTC, storyworks commented
Next time if you're cherry picking from another feature branch, let's put it in it's own PR so it doesn't get muddled with the work in this one but approved :)

2021-12-19 21:19 UTC, merged