C4/single journey overview
JesusFilm/core pull request #162
Opened 2021-12-08 01:48 UTC by csiyang

- added card(s) preview
- added text describing the number of cards cards
- added option for when there is no cards

2021-12-08 23:30 UTC, storyworks requested changes

2021-12-08 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.tsx
> +        <Button
Use https://mui.com/components/floating-action-button/

2021-12-08 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.tsx
> +        No cards in this journey
```
<>
check Blocks exist {
Render CardPreview
Render Fab (I think FAB will always appear at the bottom)
}
Render Typography (always)
</>
```

2021-12-08 23:30 UTC, storyworks commented on apps/journeys/pages/[journeySlug].tsx
> -        # slug might have to be string
Leave this here / don't touch it for this PR - if we want to remove do it in another diff PR

2021-12-08 23:30 UTC, storyworks commented on apps/journeys-admin/pages/journeys/[journeySlug].tsx
> +          blocks={
```suggestion
          blocks={blocks as Array<TreeBlock<StepBlock>>}
```
and on line 22:

const blocks = journey.blocks !== null ? transformer(journey.blocks) : []

2021-12-08 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.tsx
> +  blocks?: Array<TreeBlock<StepBlock>>
```suggestion
  blocks: Array<TreeBlock<StepBlock>>
```
Maybe better to always pass in blocks, even if it's an empty array - because the main purpose of this component is to display blocks..

2021-12-08 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.stories.tsx
> +NoCards.args = {
pass in `blocks: []`

2021-12-08 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.stories.tsx
> +    <CardOverview {...args} />
```suggestion
    <CardOverview {...args} slug={'my-journey'} />
```
In this case, the slug value is a valid value that we want to reuse for all stories (in previous tests, the value of some props were hard-coded to invalid values to fix linting)

2021-12-08 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.stories.tsx
> +  slug: 'my-journey',
Can remove all instances of slug in these args

2021-12-08 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.spec.tsx
> +  it('should have text on how many cards present in journey', () => {
```suggestion
  it('should render description for multiple cards', () => {
```
Just trying to keep the wording consistent

2021-12-08 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.spec.tsx
> +  it('should have text describe a singular card', () => {
```suggestion
  it('should render description for one card`, () => {
```

2021-12-08 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.spec.tsx
> +  it('should have edit button', () => {
```suggestion
  it('should have edit button when cards present', () => {
```
And also check the link to the edit sends us to the right place

In the future well also have a test `it('should have add button when cards not present',`

2021-12-12 22:04 UTC, storyworks requested changes

2021-12-13 01:43 UTC, storyworks requested changes

2021-12-13 01:43 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.tsx
> +                sx={{
Don't use custom sx - use a variant closest in the design tokens

2021-12-13 01:43 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.tsx
> +              right: '17px'
use theme token here as well

2021-12-13 02:16 UTC, storyworks requested changes

2021-12-13 02:16 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.spec.tsx
> +  it('should redner description for 1 card', () => {
```suggestion
  it('should render description for 1 card', () => {
```

2021-12-13 02:16 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.spec.tsx
> +  it('should have for multiple cards', () => {
```suggestion
  it('should have for multiple cards', () => {
```
have what?

2021-12-13 02:16 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.tsx
> +            color="primary"
```suggestion
            color="primary"
```
Is the default color not primary?

2021-12-13 02:16 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.tsx
> +              <AddToPhotosIcon color="primary" />
Same here - is the default color not primary? Do we need to specify?

2021-12-13 02:26 UTC, csiyang commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.spec.tsx
> +  it('should have for multiple cards', () => {
it was cards lol

2021-12-13 02:27 UTC, csiyang commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.tsx
> +            color="primary"
Nope, its like a grey without this

2021-12-13 02:28 UTC, csiyang commented on apps/journeys-admin/src/components/SingleJourney/CardOverview/CardOverview.tsx
> +              <AddToPhotosIcon color="primary" />
same here also

2021-12-14 03:10 UTC, storyworks approved these changes

2021-12-14 03:21 UTC, merged