C4/journey list
JesusFilm/core pull request #166
Opened 2021-12-09 20:38 UTC by csiyang

2021-12-09 22:09 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +              <Box key={journey.id} sx={{ pb: padding }}>
This will look right once changes from JourneyCard-styling has also been merged in

2021-12-13 23:09 UTC, tataihono requested changes

2021-12-13 23:09 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +
```suggestion
```

2021-12-13 23:09 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +  function handleAdd(): void {
not a fan. future code like this should be dropped.

2021-12-13 23:09 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +            padding = i === journeys.length - 1 ? '0px' : '1px'
this should be done in css.

2021-12-13 23:09 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +              <Box key={journey.id} sx={{ pb: padding }}>
```suggestion
              <Box key={journey.id} sx={{ pb: '1px', '&:last-child': {
              pb: 0
            }  }}>
```

2021-12-13 23:09 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +  let padding = '1px'
drop

2021-12-13 23:09 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +            onClick={handleAdd}
drop

2021-12-20 01:15 UTC, storyworks requested changes

2021-12-20 01:15 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
> +          sx={{
Make this Card outlined as well?

2021-12-20 01:15 UTC, storyworks commented on apps/journeys-admin/src/components/ThemeProvider/admin/tokens/components.ts
> +          width: '186px',
Don't hard code width and height but let the button content determine that? I'm assuming this is for the "Create a card" button

2021-12-20 01:29 UTC, storyworks approved these changes

2021-12-20 01:34 UTC, merged