C4/journey card styling
JesusFilm/core pull request #167
Opened 2021-12-09 23:30 UTC by csiyang

Updated styling to match figma

2021-12-13 02:19 UTC, tataihono requested changes

2021-12-13 02:19 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +            display: '-webkit-box',
no prefixes

2021-12-13 02:19 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +            display: '-webkit-box',
no prefixes

2021-12-13 02:19 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +            {journey.status === 'draft' ? (
this needs a unit test

2021-12-13 02:19 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +                  color: '#F0720C',
is there no design token for this?

2021-12-13 02:19 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +                  color: '#3AA74A',
is there no design token for this?

2021-12-13 02:19 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +              {journey.status.charAt(0).toUpperCase() + journey.status.slice(1)}
is this just uppercasing the first character of the status?

2021-12-13 02:19 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +            <Typography variant="caption">{`${journey.locale
i don't think this is how you should handle the locale.

2021-12-13 02:22 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +              {journey.status.charAt(0).toUpperCase() + journey.status.slice(1)}
Yes

2021-12-13 22:39 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +            display: '-webkit-box',
removed

2021-12-13 22:39 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +            {journey.status === 'draft' ? (
removed

2021-12-13 22:39 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +            display: '-webkit-box',
removed

2021-12-13 23:13 UTC, tataihono requested changes

2021-12-13 23:13 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +  const theme = useTheme()
drop

2021-12-13 23:13 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +          sx={{ color: theme.palette.secondary.main }}
```suggestion
          sx={{ color: (theme) => theme.palette.secondary.main }}
```

2021-12-14 02:42 UTC, storyworks requested changes

2021-12-14 02:42 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +                  color: (theme) => theme.palette.success.main,
```suggestion
                  color: 'success.main',
```
And remove the same in every other place you use it

2021-12-14 02:42 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +                  pr: '6px'
Use spacing token here and every other place you've hard-coded

2021-12-14 04:50 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +            {journey.status === 'draft' ? (
agreed.

2021-12-14 05:40 UTC, tataihono requested changes

2021-12-14 05:40 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
> +    expect(getAllByText('en-US')[0]).toBeInTheDocument()
these tests should all be changed to getByText

2021-12-14 05:40 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +    : format(date, 'MMM do, yyyy')
```suggestion
  const date = intlFormat(date, { day: 'numeric', month: 'long', year: isThisYear(date) ? undefined : 'numeric' })
```

2021-12-14 05:40 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +          sx={{ color: (theme) => theme.palette.secondary.main }}
```suggestion
          sx={{ color: 'secondary.main' }}
```

2021-12-14 05:40 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +        {formattedDate}
```suggestion
        {date}
```

2021-12-14 05:40 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/journeyListData.ts
> +  createdAt: '2021-11-19T12:34:56.647Z',
```suggestion
  createdAt: formatISO(startOfYear(new Date())),
```

2021-12-14 05:40 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/journeyListData.ts
> +  publishedAt: '2021-12-19T12:34:56.647Z',
```suggestion
  publishedAt: formatISO(startOfYear(new Date())),
```

2021-12-14 11:01 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +    : format(date, 'MMM do, yyyy')
@tataihono I don't think we can do this and keep the formatting from the design. intlFormat doesn't allow the order of the display to be changed and also no ordinals. Eg instead of November 20th it's 20 November.

Thoughts on adding a special case for when locale uses english to get the correct formatting?

2021-12-14 18:02 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
> +    : format(date, 'MMM do, yyyy')
I think you should just use this. This will format the date according to the locale.

2021-12-19 20:18 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/journeyListData.ts
> +  createdAt: formatISO(startOfYear(new Date())),
Hard code this else VR will fail each new year?

2021-12-19 21:21 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/journeyListData.ts
> +  createdAt: formatISO(startOfYear(new Date())),
Made this change with @tataihono because hard coded date will fail the unit test at the start of each year

2021-12-19 23:44 UTC, storyworks approved these changes

2021-12-20 00:08 UTC, merged