editor drawer
JesusFilm/core pull request #168
Opened 2021-12-10 00:28 UTC by tataihono

2021-12-10 01:14 UTC, mikeallisonJS reviewed
Just 1 small fix

2021-12-10 01:14 UTC, mikeallisonJS commented on apps/journeys-admin/src/components/ThemeProvider/theme.ts
> +          paddingRight: '24 !important'
this is missing px

2021-12-10 02:30 UTC, tataihono commented on apps/journeys-admin/src/components/ThemeProvider/theme.ts
> +          paddingRight: '24 !important'
good catch.

2021-12-20 20:53 UTC, mikeallisonJS commented on apps/journeys-admin/src/components/Editor/Context/Context.tsx
> +          action.mobileOpen != null ? action.mobileOpen : state.drawerMobileOpen
this can be better represented with nullish operator:
action.mobileOpen ?? state.drawerMobileOpen

2021-12-20 20:58 UTC, mikeallisonJS requested changes
1 suggestion, 1 question

2021-12-20 20:58 UTC, mikeallisonJS commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attribute/Attribute.tsx
> +      data-testid={id}
Is this intentionally left in?

2021-12-20 21:07 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attribute/Attribute.tsx
> +      data-testid={id}
removed

2021-12-20 21:07 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Context/Context.tsx
> +          action.mobileOpen != null ? action.mobileOpen : state.drawerMobileOpen
fixed

2021-12-20 21:07 UTC, mikeallisonJS approved these changes

2021-12-20 21:13 UTC, merged