Arangodb schema first
JesusFilm/core pull request #171
Opened 2021-12-15 22:56 UTC by mikeallisonJS

2021-12-20 03:12 UTC, tataihono requested changes

2021-12-20 03:12 UTC, tataihono commented on apps/api-journeys/src/app/modules/response/signUp/signUp.resolvers.spec.ts
> +
can you drop all specs that look like this?
```suggestion
```

2021-12-20 03:12 UTC, tataihono commented on apps/api-journeys/src/app/modules/response/video/video.resolvers.spec.ts
> +  describe('VideoResponse', () => {
```suggestion
  describe('videoResponseCreate', () => {
```

2021-12-20 03:12 UTC, tataihono commented on apps/api-journeys/tsconfig.app.json
> +  "exclude": ["**/*.spec.ts", "**/*.test.ts"],
want to standardise on spec.ts

```suggestion
  "exclude": ["**/*.spec.ts"],
```

2021-12-20 03:12 UTC, tataihono commented on apps/api-journeys/tsconfig.spec.json
> +  "include": ["**/*.spec.ts", "**/*.test.ts", "**/*.d.ts"]
standardise on spec.ts

```suggestion
  "include": ["**/*.spec.ts", "**/*.d.ts"]
```

2021-12-20 03:12 UTC, tataihono commented on apps/api-users/.eslintrc.json
> +        "@typescript-eslint/semi": "error"
no rule customization at project level.

2021-12-20 03:12 UTC, tataihono commented on apps/api-users/.eslintrc.json
> +        "indent": ["error", 2]
no rule customization at project level

2021-12-20 03:12 UTC, tataihono commented on apps/api-users/db/seed.ts
> +    await db.createCollection('userJourneys', { keyOptions: { type: 'uuid' }})
I'm not convinced that userJourneys belongs in this project.

2021-12-20 03:12 UTC, tataihono commented on apps/api-users/db/seeds/user1.ts
> +import { aql, Database } from 'arangojs'
this should not have a seed.

2021-12-20 03:12 UTC, tataihono commented on apps/api-users/schema.graphql
> +  userJourneyRemove(id: ID!): UserJourney!
i'm not sure that this service should manage everything to do with a user. Happy to be convinced otherwise.

2021-12-20 03:12 UTC, tataihono commented on apps/api-users/schema.graphql
> +  user(id: ID!): User
these are not required at the moment.

2021-12-20 03:12 UTC, tataihono commented on apps/api-users/src/app/modules/user/user.graphql
> +  userCreate(input: UserCreateInput!): User!
users should not be able to be created. This data should automatically be inferred from Firebase. The user should then update their own data in an userUpdate function.

2021-12-20 03:12 UTC, tataihono commented on apps/api-users/src/app/modules/user/user.resolver.spec.ts
> +  const userresponse = {
```suggestion
  const userResponse = {
```

2021-12-20 08:40 UTC, mikeallisonJS commented on apps/api-users/db/seeds/user1.ts
> +import { aql, Database } from 'arangojs'
I pulled the seed from the c4 auth branch, let me know if it should be removed

2021-12-20 08:41 UTC, mikeallisonJS commented on apps/api-users/schema.graphql
> +  userJourneyRemove(id: ID!): UserJourney!
I was following the convention in the c4 branch, happy to discuss

2021-12-20 23:10 UTC, mikeallisonJS commented on apps/api-journeys/project.json
> +            "with": "apps/api-journeys/src/environments/environment.testing.ts"
automated, allows for future testing environment config

2022-01-09 22:12 UTC, tataihono approved these changes
too big to review.

2022-01-09 22:22 UTC, merged