updated some styling for the app bar
JesusFilm/core pull request #172
Opened 2021-12-17 03:41 UTC by jianwei1

2021-12-19 21:23 UTC, csiyang approved these changes

2021-12-19 21:25 UTC, csiyang commented
@storyworks changes look good, but I think we need these in both the single journey and journey list

2021-12-20 17:15 UTC, storyworks requested changes

2021-12-20 17:15 UTC, storyworks commented on apps/journeys-admin/pages/journeys/[journeySlug].tsx
> +        ${BLOCK_FIELDS}
Remove these updates here as well as anything associated with CardOverview  / will cause more conflict errors when we merge feature branches...

2021-12-20 17:15 UTC, storyworks commented on apps/journeys-admin/pages/journeys/[journeySlug].tsx
> +        ${BLOCK_FIELDS}
Same on the JourneyList page

2021-12-20 17:15 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/journeyListData.ts
> +  locale: 'en_US',
This will all be updated when merging feature branches, let's not make that harder for ourselves..

2021-12-20 17:15 UTC, storyworks commented on apps/journeys-admin/src/components/SingleJourney/SingleJourneyData.ts
> +import { GetJourney_journey as Journey } from '../../../__generated__/GetJourney'
Same here, don't need this file just yet..

2021-12-20 20:08 UTC, storyworks approved these changes

2021-12-20 20:09 UTC, merged