Attributes for typography block
JesusFilm/core pull request #193
Opened 2022-01-13 01:06 UTC by csiyang

2022-01-13 03:27 UTC, storyworks requested changes

2022-01-13 03:27 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
> +        <MuiTypography align="center">Editing Card Properties</MuiTypography>
Add ability to switch this label based on block selected

2022-01-13 03:27 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.spec.tsx
> +describe('Typography', () => {
I know this label is just copying what's there but maybe in the future we can rename it "Typography Properties" or something like that so test analysis is clearer..

2022-01-13 03:27 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +          _.upperFirst(
Named imports for lodash

2022-01-13 20:21 UTC, storyworks requested changes

2022-01-13 20:21 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +          'None'
```suggestion
          'None'
```
Replace this with the actual default variant - find it in the add blocks pitch

2022-01-13 20:21 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +        value={captialize(align?.toString()) ?? 'None'}
```suggestion
        value={captialize(align?.toString()) ?? 'None'}
```
Same here and for color - replace None with actual default values.

2022-01-13 20:22 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +          'None'
https://3.basecamp.com/3105655/buckets/23266566/messages/4514250301

2022-01-13 20:26 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +          'None'
Doesn't that mean it can technically display a value but its actually null? If attributes are set correctly onCreate, the 'None' should never appear.

2022-01-13 20:30 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +          'None'
<img width="491" alt="Screen Shot 2022-01-14 at 9 28 29 AM" src="https://user-images.githubusercontent.com/67619008/149404385-2527b9e0-a66c-4f23-950b-074374254e89.png">

The text alignment is what it looks like when I remove the `?? 'None'` part of it. Thoughts on just removing the null check?

2022-01-13 20:36 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +          'None'
Not too sure what you mean but if the property is returning null, it means that the journey builder hasn't set it themselves and we're using the default property that's based on the theme / hard coded on the component. 

I thought onCreate would just set the required props leaving the optional ones to default. So if we get that null, we have to match it to what it displays by default..

2022-01-13 21:45 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +          'None'
As discussed will change these to display default values

2022-01-14 02:04 UTC, storyworks submitted a review, later dismissed

2022-01-14 03:22 UTC, storyworks submitted a review, later dismissed

2022-01-14 03:22 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +                width: 20,
If you decrease the icon size here you'd need to do it for Card as well? Are you able to find out from the designs how they want to handle what to do when the text overflows? 
And stick to one consistent size for the attribute icons (I think Vlad mentioned it in a design comment for Ariel)

2022-01-14 03:22 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Button/Button.tsx
> +        maxWidth: 150
Nice that this was reverted back to match the rest

2022-01-14 03:47 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +                width: 20,
Wasn’t sure if I should do it in this PR?

2022-01-16 20:30 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +                width: 20,
I thought your fix for overflowing text on the attributes was to revert the width of the box back to before (which you've done), keeping the icon consistent size with the others, but updating the css that affects text display so it uses ellipsis ?

2022-01-16 20:32 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +                width: 20,
I thought you said you'd fix the overflowing text here and that the was to revert the width of the box back to before (which you've done), keeping the icon consistent size with the others, but updating the css that affects text display so it uses ellipsis (assuming that's what they want) ?

2022-01-16 21:53 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +                width: 20,
I add back the overflow hidden in the button component. This fixes both the color icon clipping as well as preserving the right margin.

2022-01-17 00:53 UTC, storyworks approved these changes

2022-01-17 01:28 UTC, merged