Add image block default content
JesusFilm/core pull request #208
Opened 2022-01-17 21:06 UTC by GeronimoJohn

- Add image block default content 
   - Content placeholder: grey block with image icon

2022-01-23 22:42 UTC, tataihono requested changes

2022-01-23 22:42 UTC, tataihono commented on libs/journeys/ui/src/components/Image/Image.tsx
> +          src={`${window.location.origin}/DefaultImageIcon.png`}
```suggestion
          src="/DefaultImageIcon.png"
```

2022-01-23 22:42 UTC, tataihono commented on libs/journeys/ui/src/components/Image/Image.spec.tsx
> +    const { getByRole } = render(<Image {...block} src={null} alt={'defaultImageIcon'} />)
Please use the notation below.
```suggestion
    const { getByRole } = render(<Image {...block} src={null} alt="defaultImageIcon" />)
```

2022-01-23 22:42 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/Image/Image.spec.tsx
> +describe('Image', () => {
need to add in a spec to test the mutation is being called correctly.

2022-01-24 02:32 UTC, tataihono requested changes

2022-01-24 02:32 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/Image/Image.tsx
> +import { useJourney } from 'apps/journeys-admin/src/libs/context'
can't import like this

2022-01-26 04:07 UTC, tataihono submitted a review, later dismissed

2022-01-26 04:07 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.tsx
> +        <Image />
I think the component needs to be called NewImageButton

2022-01-26 20:53 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.tsx
> +        <Image />
Should this naming pattern also be applied to the other add button components? e.g. NewTypographyButton, NewPollButton

2022-01-31 21:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JesusFilm/core?pullRequest=208) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/JesusFilm/core?pullRequest=208) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Mike Allison<br/>:x: GeronimoJohn<br/><hr/>**Mike Allison** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JesusFilm/core?pullRequest=208) it.</sub>

2022-02-03 03:03 UTC, tataihono approved these changes

2022-02-03 03:06 UTC, merged