Editor typog drawer
JesusFilm/core pull request #210
Opened 2022-01-18 03:47 UTC by csiyang

Added drawers for attributes in typography block

2022-01-25 02:13 UTC, storyworks requested changes

2022-01-25 02:13 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/TextColor/TextColor.tsx
> +        display: 'flex',
Minor but you could put all these styles on 1 line? Makes the file shorter so less to scroll through when quickly reading

2022-01-25 02:13 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/ColorDisplayIcon/ColorDisplayIcon.spec.tsx
> +  it('should show the color', () => {
```suggestion
  it('should show the selected color', () => {
```

2022-01-25 02:13 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/ColorDisplayIcon/ColorDisplayIcon.tsx
> +        themeName={card?.themeName ?? ThemeName.base}
Use the journey theme?
```suggestion
        themeName={card?.themeName ?? journey.themeName}
```

2022-01-25 02:13 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/ColorDisplayIcon/ColorDisplayIcon.tsx
> +          data-testid="color-display-icon"
```suggestion
          data-testid=`${color}-color-icon`
```
Make sure id's are unique

2022-01-25 02:13 UTC, storyworks commented on apps/journeys-admin/src/components/ThemeProvider/admin/tokens/components.ts
> +    MuiToggleButtonGroup: {
This might need to be moved in the future..

2022-01-25 03:42 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/FontVariant/FontVariant.spec.tsx
> +      <FontVariant id={'font-variant-id'} variant={null} />
Renaming to Variant as discussed

2022-01-25 03:44 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/TextAlign/TextAlign.tsx
> +export function TextAlign({ id, align }: TextAlignProps): ReactElement {
renamed to Align as discussed

2022-01-25 22:48 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
> +            title: 'Font Variant',
```suggestion
            title: 'Text Variant',
```

And I've asked Vlad and Ariel to change design

2022-01-25 22:49 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Variant/Variant.spec.tsx
> +      <Variant id={'font-variant-id'} variant={null} />
```suggestion
      <Variant id={'text-variant-id'} variant={null} />
```

2022-01-25 22:49 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Variant/Variant.tsx
> +    varint: TypographyVariant
```suggestion
    variant: TypographyVariant
```

2022-01-26 04:31 UTC, storyworks commented
Found a bug when running the app locally

> Go to the card with the typography block and RadioQuestion,
> Click on typography and change header variant
> Click onto RadioQuestion - header selectors still exist in drawer
> Click through header selectors - they change even though RadioQuestion is selected

Similar for switching between different types of typography blocks. We should update the selectors for each block selected..

Seeing it all working together is so satisfying though - well done! :D

2022-01-26 21:36 UTC, storyworks approved these changes

2022-01-26 21:37 UTC, merged