fix: close menu after duplication
JesusFilm/core pull request #2231
Opened 2024-01-22 02:23 UTC by JayChen2004

# Description

Fixed an issue where menu would not close after duplicating in journey editor

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/35391220/todos/6948516862)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] dropdown tab should close after duplicating

2024-01-25 22:49 UTC, csiyang requested changes

2024-01-25 22:49 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/EditToolbar/DuplicateBlock/DuplicateBlock.tsx
> +  closeMenu,
Add a test in this component that the `closeMenu` function gets called

2024-01-25 22:54 UTC, csiyang requested changes

2024-01-25 22:54 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
> +    await waitFor(() => expect(queryByRole('menu')).not.toBeInTheDocument())
You're only asserting that the menu is no longer there, check that the result of you're mock is called.

2024-01-26 03:01 UTC, csiyang requested changes

2024-01-26 03:01 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
> +    const selectedBlock: TreeBlock<TypographyBlock> = {
This test is looking good! Can you do a refactor of the mocking so it matches a similar style to how its done here? https://github.com/JesusFilm/core/blob/f89a4172f4961d7e6b5e9e8faec28cad3a329c65/apps/journeys-admin/src/components/AccessDenied/AccessDenied.spec.tsx

2024-01-30 20:31 UTC, JayChen2004 commented on apps/journeys-admin/src/components/Editor/EditToolbar/DuplicateBlock/DuplicateBlock.spec.tsx
> +      >
my handleClick function is inside a function handleDuplicateBlock that needs this mock

2024-01-30 20:31 UTC, JayChen2004 commented on apps/journeys-admin/src/components/Editor/EditToolbar/DuplicateBlock/DuplicateBlock.spec.tsx
> +    }))
this is needed for handleClick to be called too

2024-02-02 00:52 UTC, csiyang requested changes

2024-02-02 00:52 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
> +    const mockBlockDuplicate: MockedResponse = {
```suggestion
    const mockBlockDuplicate: MockedResponse<BlockDuplicate> = {
```

2024-02-02 01:46 UTC, csiyang approved these changes

2024-02-02 01:56 UTC, merged