feat: card swiping
JesusFilm/core pull request #2293
Opened 2024-02-09 02:46 UTC by csiyang

# Description

Removes the use of `swiper.js` in journeys and replaced with new custom swiper (+ refactors)

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/35958767/todolists/7065619847)

2024-02-12 01:57 UTC, tataihono requested changes
the journeys/ui changes need to be tested on journeys-admin fyi.

2024-02-12 01:57 UTC, tataihono commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +          height: viewportHeight ?? '100vh',
started to move away from this. They started to define these values using new lvh & svh variables which is really nice. It does away with the need to use div100vh library. Can we start using it here? https://dev.to/frehner/css-vh-dvh-lvh-svh-and-vw-units-27k4

2024-02-12 01:57 UTC, tataihono commented on apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx
> +    blockHistory[blockHistory.length - 2] as TreeBlock<StepFields>
```suggestion
  const getCurrentActiveBlock = (): TreeBlock<StepFields> =>
    blockHistory[blockHistory.length - 1] as TreeBlock<StepFields> | undefined
  const getPreviousBlock = (): TreeBlock<StepFields> =>
    blockHistory[blockHistory.length - 2] as TreeBlock<StepFields> | undefined
```

2024-02-12 01:57 UTC, tataihono commented on apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
thoughts about using a library for this?
https://www.npmjs.com/package/react-swipeable

These guys since they have a larger audience probably cover more use cases than we can hope to test.

2024-02-12 01:57 UTC, tataihono commented on libs/journeys/ui/src/components/Card/Card.tsx
> +  const handleNav = (e: MouseEvent): void => {
no shorthand

2024-02-29 21:47 UTC, csiyang reviewed
@tataihono

2024-02-29 21:47 UTC, csiyang commented on apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx
> +              {isCurrent || isPreRender ? (
Updates how conductor renders cards, and handles prerenders

2024-02-29 21:47 UTC, csiyang commented on apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
> +  const swipeHandlers = useSwipeable({
handles swipe

2024-02-29 21:47 UTC, csiyang commented on libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx
> +  useEffect(() => {
use effects moved from `Video.tsx`

2024-02-29 21:47 UTC, csiyang commented on libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx
> +  useEffect(() => {
handles video autoplay

2024-02-29 21:47 UTC, csiyang commented on libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
> +  const [state, dispatch] = useReducer(playbackReducer, {
Refactors how the state of the video is handled

2024-02-29 21:47 UTC, csiyang commented on libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.tsx
> +        {treeBlocks.map((block) => {
New pagination bullets

2024-03-01 01:22 UTC, tataihono requested changes

2024-03-01 01:22 UTC, tataihono commented on apps/journeys/src/components/Conductor/DynamicCardList/DynamicCardList.tsx
> +              className={isCurrent ? 'active-card' : ''}
```suggestion
              className={isCurrent ? 'active-card' : undefined}
```

2024-03-01 01:22 UTC, tataihono commented on libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
> +      const currentPosition = (player.currentTime() ?? 0) + 2
comment for why plus 2

2024-03-01 01:32 UTC, tataihono approved these changes

2024-03-01 01:33 UTC, tataihono approved these changes

2024-03-01 02:14 UTC, merged