test: step updates
JesusFilm/core pull request #2319
Opened 2024-02-15 00:52 UTC by levi-zustiak

# Description
- adds test to validate `stepViewEventCreate` only emits when `activeStep` is true
- adds tests to validate Seo changes based on `activeStep` and if first step

[Link](https://3.basecamp.com/3105655/buckets/35958767/todos/7065661942) to Basecamp Todo

2024-02-15 00:58 UTC, levi-zustiak commented
Are there any other tests you'd like to see for the activeStep?

2024-02-15 01:28 UTC, csiyang requested changes

2024-02-15 01:28 UTC, csiyang commented on libs/journeys/ui/src/components/Step/Step.spec.tsx
> +  it('should not send stepViewEvent if not activeStep', async () => {
This test is failing for me locally, can you double checK?

2024-02-15 01:28 UTC, csiyang commented on libs/journeys/ui/src/components/Step/Step.spec.tsx
> +          {
We're in the middle of converting to a new standard of writting out these mocks. You can find a recent example of one I wrote in `SwipeNavigation.tsx` (line 84)

2024-02-15 21:35 UTC, levi-zustiak commented on libs/journeys/ui/src/components/Step/Step.spec.tsx
> +  it('should not send stepViewEvent if not activeStep - broken', async () => {
This test fails since the result mock has been called in the other tests. Should I create a new result mock like I did in the working version of this test?

I also tried to reset the mock using jest, but it caused Apollo to throw errors

2024-02-15 21:40 UTC, csiyang commented on libs/journeys/ui/src/components/Step/Step.spec.tsx
>        <MockedProvider>
Does this work? If not, lets make one just for this test
```suggestion
      <MockedProvider mocks={[mockStepViewEventCreate]}>
```

2024-02-19 16:59 UTC, levi-zustiak commented on libs/journeys/ui/src/components/Step/Step.tsx
> +      wrappers === undefined
This check was added for the wrapper test. I don't really have the context for the wrapper functionality or if it's still valid, but this now will prevent the event from firing if there are wrappers

2024-02-19 22:07 UTC, csiyang approved these changes

2024-02-20 00:43 UTC, merged