feat: more prominent unmute button
JesusFilm/core pull request #2387
Opened 2024-02-26 19:00 UTC by levi-zustiak

# Description
Modifies the `VideoControls` component to combine the play/pause button with the unmute button on mobile devices.

- [Link](https://3.basecamp.com/3105655/buckets/35958767/todos/6986070521) to Basecamp Todo

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Mobile devices will show the Play button first if not playing or autoplay, then transition to the unmute button if the video is muted, and then to the pause button after unmuting.
- [ ] Desktop controls should not be affected by the changes to mobile controls
- [ ] Playback controls should be kept in sync between desktop and mobile in case a user switches between the two.

# Walkthrough
Testing can be done using a muted video or muting the video on a desktop viewport and then viewing the page on a mobile viewport using developer tools.

2024-02-26 20:29 UTC, csiyang requested changes
The file is getting a little big, do you think we could also refactor, and pull out the the `desktop controls`, `mobile controls` and `centre button` into their own components?

Just the rendered components themselves (if there is logic only that component uses it can be moved as well, otherwise just pass the required props in). I don't think we would need to write any new tests either, the main ones from `VideoControls.spec.tsx` should be sufficient.

2024-02-26 20:29 UTC, csiyang commented on libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
> +                  <IconButton
The position of this has moved from where it originally was. Can we shift it back?

2024-02-26 20:29 UTC, csiyang commented on libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
>                    <Slider
The slider behaviour has changed now, can make it so that it can stay open again?

2024-02-26 20:29 UTC, csiyang commented on libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
> -          <Stack
The removal of this has also shifted the play button up, can we bring back what's necessary to keep it at its original position?

2024-02-26 20:29 UTC, csiyang commented on libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
> +import useMediaQuery from '@mui/material/useMediaQuery'
Just a FYI, we're pretty tight on the use `useMediaQuery.tsx`, it causes layout shift when applied to UI elements. But it's fine in this case since it only affect the click handlers

2024-02-26 20:32 UTC, levi-zustiak commented on libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
> +import useMediaQuery from '@mui/material/useMediaQuery'
I didn't see another example for determining the viewport width other than useMediaQuery, do you guys have an example of that somewhere?

2024-02-27 23:18 UTC, levi-zustiak commented
@csiyang couldn't really figure out a better folder structure for the mobile/desktop/general components, so if you have any recommendations I'd love to hear them.

2024-02-28 22:20 UTC, csiyang approved these changes

2024-02-29 03:12 UTC, merged