test: add tests for base node
JesusFilm/core pull request #2421
Opened 2024-03-06 00:02 UTC by levi-zustiak

# Description
- Adds required mocks for React Flow
- Adds test suite for `BaseNode`

- [Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145947690) to Basecamp Todo

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Walkthrough

2024-03-06 23:07 UTC, csiyang requested changes

2024-03-06 23:07 UTC, csiyang commented on apps/journeys-admin/test/mockReactFlow.ts
> +const noop = (): undefined => undefined
use lodash noop
```suggestion
import noop from 'lodash/noop'
```

2024-03-06 23:14 UTC, levi-zustiak commented on apps/journeys-admin/test/mockReactFlow.ts
> +const noop = (): undefined => undefined
Is there a reason to use the lodash noop function vs defining it ourselves? I'll change it to keep it consistent, but just curious if there's any advantage to using the lodash version?

2024-03-06 23:16 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
> +      data-testid="base-node"
I used the PascalCase originally and then swapped to kebab... haha

2024-03-06 23:41 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.spec.tsx
> +  const stepAndCardBlockCreateBlockMock = {
Could you maybe elaborate more on what is expected for the new format? Is the main concern for these to be type annotated with the `MockedResponse` type and move them out of the test definitions?

2024-03-07 00:01 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.spec.tsx
> +  const stepAndCardBlockCreateBlockMock = {
Yes it should by typed through `MockedResponse<StepAndCardBlockCreate>`. And the result object should be combined into that too instead of  its own const

2024-03-07 01:44 UTC, csiyang commented on apps/journeys-admin/test/mockReactFlow.ts
> +const noop = (): undefined => undefined
Not as far as I know

2024-03-07 01:55 UTC, csiyang approved these changes

2024-03-07 16:20 UTC, merged