test: action node
JesusFilm/core pull request #2425
Opened 2024-03-06 21:59 UTC by levi-zustiak

# Description
- Adds tests for `ActionNode`

- [Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145947300) to Basecamp Todo

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Walkthrough

2024-03-07 20:55 UTC, csiyang requested changes
Can you also test the functions `handleSourceConnect` and `handleClick`

2024-03-08 01:39 UTC, csiyang requested changes
Minor change, but looks good otherwise

2024-03-08 01:39 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.tsx
> +import { useTranslation } from 'next-i18next'
can you revert this change since its getting handled in another PR?

2024-03-13 20:13 UTC, csiyang requested changes

2024-03-13 20:13 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ActionNode/ActionNode.spec.tsx
> +    )
Sorry, missed this one earlier
```suggestion
    const { getByText } = render(
      <ReactFlowProvider>
        <MockedProvider>
          <ActionNode {...defaultProps} />
        </MockedProvider>
      </ReactFlowProvider>
    )
```

2024-03-13 20:13 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.tsx
> +import { useTranslation } from 'react-i18next'
rip, this needs to be changed back
```suggestion
import { useTranslation } from 'next-i18next'
import { ReactElement } from 'react'
```

2024-03-13 20:28 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.tsx
> +import { useTranslation } from 'react-i18next'
The react version is restricted in eslint. Are we still supposed to use the react version? If so, do we need to revert the rule?

2024-03-14 01:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.tsx
> +import { useTranslation } from 'react-i18next'
No, the correct import is from next. This was only a recent change so thats why some files are still using the react one. 

I think when I asked you to revert, it was before your actual signupblock tests when in. 
We basically want no changes in this file.

2024-03-14 01:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ActionNode/ActionNode.spec.tsx
> +    )
nvm

2024-03-14 02:19 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.tsx
> +import { useTranslation } from 'react-i18next'
Ohhhh I understand now haha I forgot we reverted already. My bad

2024-03-14 02:31 UTC, csiyang approved these changes

2024-03-14 02:35 UTC, merged