test: text response block node
JesusFilm/core pull request #2444
Opened 2024-03-11 15:20 UTC by levi-zustiak

# Description
- Adds tests for `TextResponseBlockNode`

- [Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145949638) to Basecamp Todo

2024-03-12 23:04 UTC, csiyang requested changes

2024-03-12 23:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlock.spec.tsx
> +  } satisfies TreeBlock<TextResponseBlock>
Wow, didn't know `satisfies` was a thing! I'm still looking into exactly how it works, but I dont think its necessary here.

```suggestion
  const mockTextResponseBlock: TreeBlock<TextResponseBlock> = {
    __typename: 'TextResponseBlock',
    id: 'TextResponseBlock.id',
    parentBlockId: 'CardBlock.id',
    parentOrder: 0,
    label: 'TextResponseBlock',
    hint: null,
    minRows: null,
    submitLabel: null,
    submitIconId: null,
    action: null,
    children: []
  }
```

2024-03-12 23:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlock.spec.tsx
> +    expect(screen.getByText('Feedback')).toBeInTheDocument()
```suggestion
    const { getByText } = render(
      <ReactFlowProvider>
        <MockedProvider>
          <TextResponseBlockNode {...defaultProps} />
        </MockedProvider>
      </ReactFlowProvider>
    )

    expect(getByText('Feedback')).toBeInTheDocument()
```

2024-03-13 01:38 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlock.spec.tsx
> +  } satisfies TreeBlock<TextResponseBlock>
Yeah, it's a pretty neat type! I'm fine switching to the annotation since it's really the same in this instance. The main idea is to provide 'narrow' types vs 'wider' types which is pretty nice. https://www.learningtypescript.com/articles/the-satisfies-operator this article does a great job of explaining it.

2024-03-13 01:42 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlock.spec.tsx
> +    expect(screen.getByText('Feedback')).toBeInTheDocument()
Is it possible that we move to using `screen` queries instead of render queries? It's recommended to use `screen` for dx and usability. And once again, if this is preferred for an outstanding reason or just preference that works too.

2024-03-13 20:15 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlock.spec.tsx
> +    expect(screen.getByText('Feedback')).toBeInTheDocument()
I would defer to @tataihono for this decision

2024-03-13 21:14 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlock.spec.tsx
> +    expect(screen.getByText('Feedback')).toBeInTheDocument()
yes. I agree. Was something we should have done a long time ago. If we were going to do it we should consider linting and making the update in cooldown.

2024-03-14 01:05 UTC, csiyang approved these changes

2024-03-14 01:05 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlock.spec.tsx
> +describe('TextResponseBlockNode', () => {
The title of the file also needs to be changed to this
```suggestion
describe('TextResponseBlockNode', () => {
```

2024-03-14 01:07 UTC, csiyang requested changes

2024-03-14 01:07 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlock.spec.tsx
> +describe('TextResponseBlockNode', () => {
The title of the file also needs to be changed to this `TextResponseBlockNode.spec.tsx`
```suggestion
describe('TextResponseBlockNode', () => {
```

2024-03-14 02:31 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlock.spec.tsx
> +describe('TextResponseBlockNode', () => {
Oops, good catch!

2024-03-14 02:32 UTC, csiyang approved these changes

2024-03-14 02:50 UTC, merged