test: social preview node
JesusFilm/core pull request #2447
Opened 2024-03-11 21:49 UTC by levi-zustiak

# Description
- Adds tests for `SocialPreviewNode`

[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145948840) to Basecamp Todo

2024-03-11 21:51 UTC, levi-zustiak commented
I pretty much just pulled over all the tests from the other PR. I didn't really see much else to test. Just lmk if there's anything else

2024-03-13 00:12 UTC, csiyang requested changes

2024-03-13 00:12 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.spec.tsx
> +  const stepAndCardBlockCreateMock: MockedResponse<
Is this mock actually being used? I don't think the node has any mutations on it

2024-03-14 02:55 UTC, csiyang approved these changes

2024-03-14 03:11 UTC, merged