test: social preview
JesusFilm/core pull request #2468
Opened 2024-03-14 20:53 UTC by levi-zustiak

# Description
- Refactors tests for `SocialPreview`

[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145955438) to Basecamp Todo

2024-03-15 01:52 UTC, csiyang requested changes
Can you also please test the `handleSelect` in the component

2024-03-15 01:52 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
> +jest.mock('@core/journeys/ui/EditorProvider', () => {
Any special reason we need to mock this out? Can we use the `EditorProvider` instead? (example below)

2024-03-15 01:52 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
>      )
```suggestion
  it('should render Message Post and Fab for viewports larger than mobile', () => {
    render(
      <EditorProvider initialState={state}>
        <ThemeProvider>
          <SocialPreview />
        </ThemeProvider>
      </EditorProvider>
    )
```

2024-03-15 02:27 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
> +jest.mock('@core/journeys/ui/EditorProvider', () => {
Definitely would have been the better option for the two original tests haha I am going to use the mock for the click test

2024-03-17 19:47 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
> +jest.mock('@core/journeys/ui/EditorProvider', () => {
Do you think we can change it in this PR? For code maintainability as well as don't want someone to accidentally copy this somewhere else.

2024-03-18 02:37 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
> +jest.mock('@core/journeys/ui/EditorProvider', () => {
Do you have an example to mock the dispatch function for me to use then? I'm not sure how to do that without this

2024-03-18 20:11 UTC, csiyang approved these changes

2024-03-18 20:16 UTC, merged