Add Move buttons
JesusFilm/core pull request #247
Opened 2022-02-01 20:06 UTC by storyworks

2022-02-02 00:13 UTC, tataihono requested changes
I wonder if we should allow for parentOrder to be null in the case where it is a cover block. That way we would know that it shouldn't be displayed without needing to know anything about the parent.

2022-02-02 00:13 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
> +        data-testid="move-block-buttons"
id not used anywhere

```suggestion
```

2022-02-02 00:13 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
> +  const handleMove = async (move: 'up' | 'down'): Promise<void> => {
could you just provide a function that returns a function?
```suggestion
  const handleMove = async (move: 'up' | 'down'): () => Promise<void> => {
```

would simplify button logic below
```
          onClick={handleMove('up')}
```

2022-02-02 00:13 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
> +  const firstBlockIndex = coverBlock != null ? 1 : 0
i think one of the options in this ternary is not tested.

2022-02-02 00:13 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
> +      ? searchBlocks(parentBlock.children, parentBlock.coverBlockId)
this line is not tested.

2022-02-02 00:13 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
> +        await blockOrderUpdate({
this line is also not tested.

2022-02-02 00:13 UTC, tataihono commented on libs/journeys/ui/src/libs/context/EditorContext.tsx
> +export function searchBlocks(
this function should be extracted out as a lib function and tested separately since it's no longer tightly coupled with EditorContext.

2022-02-02 00:28 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
> +        data-testid="move-block-buttons"
This is used in Attributes.spec.ts

2022-02-02 01:12 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
> +  const handleMove = async (move: 'up' | 'down'): Promise<void> => {
Every async function must return a Promise typescript error - it suggests `Promise<() => Promise<void>>` which isn't right either..

2022-02-02 01:13 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
> +  const handleMove = async (move: 'up' | 'down'): Promise<void> => {
Every async function must return a Promise typescript error - it suggests `Promise<() => Promise<void>>` which isn't right either..

2022-02-02 01:16 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
> +  const handleMove = async (move: 'up' | 'down'): Promise<void> => {
Every async function must return a Promise typescript error - it suggests `Promise<() => Promise<void>>` which isn't right either..

2022-02-02 01:27 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
> +  const handleMove = async (move: 'up' | 'down'): Promise<void> => {
Every async function must return a Promise typescript error - it suggests `Promise<() => Promise<void>>` which isn't right either.. but noted to simplify onClick

2022-02-02 02:42 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
> +  const firstBlockIndex = coverBlock != null ? 1 : 0
Possibly lastBlockIndex  - I don't have a test showing that when parent == null we use parentOrder 0 since parent should always exist (Move Buttons don't get applied to StepBlock). 

However, I've added a test showing both move buttons are disabled when there's a single child now.

2022-02-03 03:54 UTC, tataihono approved these changes

2022-02-03 03:54 UTC, merged