add block-response module
JesusFilm/core pull request #25
Opened 2021-09-09 19:28 UTC by soberstadt

2021-09-13 00:35 UTC, tataihono requested changes
Great start! Mostly just changes to match styles and best practices now.

Wondering why the JourneySession didn't get split out into its own module?

2021-09-13 00:35 UTC, tataihono commented on apps/api-journeys/src/modules/block-response/index.ts
> +  }
```suggestion
  input SignupBlockResponseInput {
  	journeySessionId: ID!
  	blockId: ID!
  	name: String!
  	email: String!
  }
  
  input VideoBlockResponseInput {
  	journeySessionId: ID!
  	blockId: ID!
  	position: Float!
  	state: VideoBlockResponseStateEnum!
  }
  
  input RadioQuestionBlockResponseInput {
  	journeySessionId: ID!
  	blockId: ID!
  	selectedResponseBlockId: ID!
  }

  extend type Mutation {
    journeySessionCreate(journeyId: ID!): ID!

    signupBlockResponseCreate(input: SignupBlockResponseInput!): ID!
    videoBlockResponseCreate(input: VideoBlockResponseInput!): ID!
    radioQuestionBlockResponseCreate(input: RadioQuestionBlockResponseInput!): ID!
  }
```

This pattern is used by Relay and arguably has become a [best practice](https://atheros.ai/blog/input-object-type-as-an-argument-for-graphql-mutations-and-queries) for defining mutation inputs.

It also provides better type safety for frontend clients validating mutation inputs in files separate from where the mutation query is being executed i.e types are generated for SignupBlockResponseInput etc.

If you accept this suggestion you'll need to update your resolvers to destructure the input object too.

2021-09-13 00:35 UTC, tataihono commented on apps/api-journeys/src/modules/block-response/index.ts
> +    journeySessionCreate(journeyId: ID!): ID!
I think this should be moved into journey-session module?

2021-09-13 00:35 UTC, tataihono commented on apps/api-journeys/src/modules/block-response/index.ts
> +      return response.id
I like to leverage destructuring to be explicit about what is being used in the response. Not needed though if you don't like it.

```suggestion
      const { id } = await db.blockResponse.create({
        data: {
          journeySessionId,
          blockId,
          responseData: { name, email }
        }
      })
      return id
```

2021-09-13 00:35 UTC, tataihono commented on apps/api-journeys/src/modules/block-response/index.ts
> +  id: 'block-response',
```suggestion
  id: 'blockResponse',
```

can we change all instances where we are using dashes here and with file names to camelCase? This file directory should be renamed blockResponse. This is to match the other project's (FE) extensive use of this kind labeling.

2021-09-14 18:46 UTC, soberstadt commented on apps/api-journeys/src/modules/block-response/index.ts
> +      return response.id
Awesome, thanks for the reminder on this, I forget about destructuring in TS

2021-09-14 18:47 UTC, soberstadt commented on apps/api-journeys/src/modules/block-response/index.ts
> +  id: 'block-response',
I didn't know how we were doing module naming, I'm good with renaming to `blockResponse`

2021-09-14 18:51 UTC, soberstadt commented on apps/api-journeys/src/modules/block-response/index.ts
> +    journeySessionCreate(journeyId: ID!): ID!
Done.

2021-09-14 18:53 UTC, soberstadt commented on apps/api-journeys/src/modules/block-response/index.ts
> +  }
I updated this on the blockResponse module, I didn't think it should be done for `userSessionCreate` since that is a single input value at this point.

2021-09-14 18:53 UTC, soberstadt commented
@tataihono I believe this is ready for re-review.

2021-09-15 20:43 UTC, tataihono submitted a review, later dismissed

2021-09-16 13:44 UTC, soberstadt commented
@tataihono which of the many generate functions did you use to update the graphql schema?

2021-09-16 23:42 UTC, tataihono requested changes

2021-09-16 23:42 UTC, tataihono commented on apps/api-journeys/src/lib/mockDb.ts
> +import prisma from './db'
this should match the exported name which is db

```suggestion
import db from './db'
```

2021-09-16 23:42 UTC, tataihono commented on apps/api-journeys/src/lib/mockDb.ts
> +export const prismaMock = prisma as unknown as DeepMockProxy<PrismaClient>
```suggestion
export const dbMock = db as unknown as DeepMockProxy<PrismaClient>
```

2021-09-16 23:42 UTC, tataihono commented on apps/api-journeys/src/lib/mockDb.ts
> +import { PrismaClient } from '@prisma/client'
```suggestion
import { PrismaClient } from '.prisma/api-journeys-client'
```

this will give you strong types.

2021-09-16 23:42 UTC, tataihono commented on apps/api-journeys/src/lib/mockDb.ts
> +  mockReset(prismaMock)
```suggestion
  mockReset(dbMock)
```

2021-09-16 23:42 UTC, tataihono commented on apps/api-journeys/src/modules/userSession/index.spec.ts
> +    variableValues: { journeyId: journeyId },
```suggestion
    variableValues: { journeyId },
```

2021-09-16 23:42 UTC, tataihono commented on apps/api-journeys/src/modules/userSession/index.spec.ts
> +      }
I am surprised that this query doesn't fail. This mutation returns id not { id }. When I try this command against the served graph (`nx serve`) it fails.

```suggestion
      userSessionCreate(journeyId: $journeyId)
```

2021-09-16 23:42 UTC, tataihono commented on apps/api-journeys/src/modules/userSession/index.spec.ts
> +it('creates a journey session', async () => {
I think a spec needs to be added here to capture what happens when the journeyId does not exist.

2021-09-16 23:43 UTC, tataihono commented
Looks like your changes to the package-lock.json file are run against an old version of npm. Try `npm i -g npm@7.24.0`

2021-09-21 04:23 UTC, closed without merging