feat: step block node stories
JesusFilm/core pull request #2563
Opened 2024-04-02 18:17 UTC by levi-zustiak

# Description
- Adds stories for `StepBlockNode`

[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7150977911) to Basecamp Todo

2024-04-02 22:54 UTC, csiyang requested changes
This story needs a few more variants
- default: should have no `image`, `title` or `description`
- One variant for each of the different types `<StepBlockNodeIcon />` (Video, TextResponse, Button, Typography, RadioQuestion)
- Hover: to show the menu fab appearing

2024-04-05 01:11 UTC, csiyang requested changes

2024-04-05 01:11 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx
> +
Can we also add the hover variant

2024-04-05 01:50 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx
> +const Template: StoryObj<ComponentPropsWithoutRef<typeof StepBlockNode>> = {
It was recommended in the ts doc. It was recommended to use the `ComponentWithRef` for components with a forwarded ref or `ComponentWithoutRef` for components without

2024-04-05 01:59 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx
> +
The Menu Fab shows on hover for the other variants. Are you saying that you want a variant to display the Menu Fab without having to hover on the component?

2024-04-08 02:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx
> +
@levi-zustiak you can use story book play to mouse over the component on render, this means we can get a snapshot of the hover

2024-04-10 21:16 UTC, csiyang approved these changes

2024-04-10 21:31 UTC, csiyang requested changes
Lint is failing

2024-04-10 21:31 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx
> +export const Hover = {
This story is failing

2024-04-10 22:34 UTC, csiyang approved these changes

2024-04-10 22:35 UTC, merged