feat: toggle option stories
JesusFilm/core pull request #2566
Opened 2024-04-02 20:43 UTC by levi-zustiak

# Description
- Changes story path for `ToggleOption`
- Replaces `Drawer` placeholder with `ToggleOption`

[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7155986571) to Basecamp Todo

2024-04-02 23:04 UTC, csiyang requested changes

2024-04-02 23:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ToggleOption/ToggleOption.stories.tsx
>  import { ToggleOptionProps } from './ToggleOption'
We've changed how we do this now, and don't actually export the prop types of components now. Can you also change, the code in the component itself, to not export the prop type
```suggestion
```

2024-04-02 23:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ToggleOption/ToggleOption.stories.tsx
>  const Template: StoryObj<typeof ToggleOption> = {
`import { ComponentProps } from 'react'`
```suggestion
const Template: StoryObj<ComponentProps<typeof ToggleOption>> = {
```

2024-04-02 23:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ToggleOption/ToggleOption.stories.tsx
> +  render: (args: ToggleOptionProps) => {
```suggestion
  render: ({ ...args }) => {
```

2024-04-05 01:10 UTC, csiyang requested changes

2024-04-05 01:10 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ToggleOption/ToggleOption.stories.tsx
>    ...journeysAdminConfig,
Still need this change

2024-04-05 01:10 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ToggleOption/ToggleOption.stories.tsx
> +const Template: StoryObj<ComponentPropsWithoutRef<typeof ToggleOption>> = {
Any reason for using `WithoutRef`?
```suggestion
const Template: StoryObj<ComponentProps<typeof ToggleOption>> = {
```

2024-04-05 02:05 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ToggleOption/ToggleOption.stories.tsx
> +const Template: StoryObj<ComponentPropsWithoutRef<typeof ToggleOption>> = {
Recommended in the ts doc to use the type with or without ref

2024-04-05 02:07 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ToggleOption/ToggleOption.stories.tsx
> +const Template: StoryObj<ComponentPropsWithoutRef<typeof ToggleOption>> = {
<img width="491" alt="image" src="https://github.com/JesusFilm/core/assets/91484241/37954235-0014-4c65-afea-9ba094e0eb82">

2024-04-08 02:05 UTC, csiyang approved these changes

2024-04-08 14:18 UTC, merged