24 03 nc feat create bull queue for bq
JesusFilm/core pull request #2665
Opened 2024-04-23 04:01 UTC by Kneesal

# Description

### Issue

establising extract iterator pattern

[[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)](https://3.basecamp.com/3105655/buckets/37071156/todos/7322458871)

### Solution

establising extract iterator pattern

# External Changes

new env vars added to doppler

# Additional information

2024-04-24 01:08 UTC, tataihono requested changes

2024-04-25 10:31 UTC, Kneesal commented on apps/api-videos/src/app/modules/bigQuery/bigQuery.service.ts
> +      pageToken = res[1]?.pageToken
had to leave this up here as iterator is off by one result otherwise - please see revised code

2024-04-26 03:26 UTC, tataihono approved these changes

2024-04-26 04:01 UTC, edmonday approved these changes

2024-04-26 04:10 UTC, merged