feat: big query video title importer
JesusFilm/core pull request #2682
Opened 2024-04-29 03:52 UTC by Kneesal

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-05-01 23:24 UTC, tataihono requested changes

2024-05-01 23:24 UTC, tataihono commented on apps/api-videos/src/app/modules/importer/importerVideos/importerVideos.service.ts
> +        data: videoObj
```suggestion
        data: {
          ...video,
          slug: this.slugify(video.id, video.slug)
        }
```

2024-05-01 23:24 UTC, tataihono commented on apps/api-videos/src/app/modules/importer/importerVideos/importerVideos.service.ts
> +  private async transform(video: Video): Promise<Prisma.VideoCreateInput> {
change name to slugify and return a string that = slug. Args should be id, title.

2024-05-02 00:03 UTC, tataihono commented on apps/api-videos/src/app/modules/importer/importerVideos/importerVideos.service.ts
>      })
```suggestion
    const input = { ...video, slug: await this.slugify(video.id, video.slug) }
    await this.prismaService.video.upsert({
      where: { id: video.id },
      update: input,
      create: input
    })
```

2024-05-07 13:54 UTC, tataihono requested changes
please drop your tests from this. Do the compare on a separate branch. @mikeallisonJS can you help @Kneesal compare the seed import to the bq import here?

2024-07-23 03:49 UTC, Kneesal commented
this has been re-assigned to @mikeallisonJS  who will complete this in a separate PR

2024-07-23 03:49 UTC, closed without merging