feat: ingest crowdin translations
JesusFilm/core pull request #2686
Opened 2024-04-30 23:58 UTC by edmonday

# Description

### Issue

As we look to migrate video data from Arclight to core, translation data from Crowdin will also need to be ingested.

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071156/todolists/7278000510)

### Solution

Crowdin translations are retrieved via CDN, transformed and pushed to api-videos.

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-05-07 13:53 UTC, tataihono requested changes
now that you have a working implementation can you take a run and simplifying your code? Particularly try to remove the number of maps that you are needing to do.

2024-05-07 13:53 UTC, tataihono commented on apps/api-videos/src/app/modules/crowdin/crowdin.consumer.ts
> +    console.log(job.name)
drop

2024-05-07 13:53 UTC, tataihono commented on apps/api-videos/src/app/modules/crowdin/crowdin.service.ts
> +  async getCrowdinTranslations(): Promise<void> {
```suggestion
  async pullTranslations(): Promise<void> {
```

2024-05-07 13:53 UTC, tataihono commented on apps/api-videos/src/app/modules/crowdin/crowdin.service.ts
> +    if (hash === '') throw new Error('crowdin distribution hash not set')
```suggestion
    if (process.env.CROWDIN_DISTRIBUTION_HASH == null) throw new Error('crowdin distribution hash not set')
```

2024-05-07 13:53 UTC, tataihono commented on apps/api-videos/src/app/modules/crowdin/crowdin.service.ts
> +    })
what is this doing? I think its unclear.

2024-05-07 13:53 UTC, tataihono commented on apps/api-videos/src/app/modules/crowdin/crowdin.service.ts
> +            const data: CrowdinData = await xliff12ToJs(content)
the data json response should be validated through something like yup. So that we can be sure that it has the correct format otherwise fail. I did something like this with row validation on the bq import pr. can you check that ou t with @Kneesal then apply that here.

2024-05-07 13:53 UTC, tataihono commented on apps/api-videos/src/app/modules/crowdin/crowdin.service.ts
> +            const data: CrowdinData = await xliff12ToJs(content)
this seems overly complex. Why can't we just map over one set of files?

2024-05-07 22:47 UTC, edmonday commented on apps/api-videos/src/app/modules/crowdin/crowdin.service.ts
> +    })
The WESS language code for the custom mapping from Crowdin language codes can only be retrieved from the exported file name.  So what this is doing is creating an object with key value pairs `CrowdinLanguageCode : WESS Code` e.g `ko: 3804`

I then use this later on when storing the translations so we have the correct WESS code. This is needed since the converted xliff to json object has an attribute `targetLanguage` which is still the Crowdin language code.

What would you recommend in terms of making this more clear?

2024-05-08 00:09 UTC, edmonday commented on apps/api-videos/src/app/modules/crowdin/crowdin.service.ts
> +    })
Did more thinking around this. What do you think about this?

```
 await Promise.all(
      map(languages, async (language) => {
        const data: CrowdinData = await xliff12ToJs(language[0].content)
        const languageCode = language[0].file.match(/\/content\/(.*?)\.xliff/)
        if (languageCode != null)
          await this.storeTranslations(languageCode[1], data)
      })
    )
  }
```

this will get rid of the `wessLanguageMap` and remove one map.

2024-05-17 19:30 UTC, mikeallisonJS commented on apps/api-videos/src/app/modules/crowdin/crowdin.service.ts
> +      case '/Arclight/media_metadata_description.csv':
Is this by chance a snippet and not a description?

2024-05-21 19:11 UTC, mikeallisonJS submitted a review, later dismissed

2024-09-11 02:19 UTC, closed without merging