feat: add videos tab
JesusFilm/core pull request #2689
Opened 2024-05-01 23:05 UTC by edmonday

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071156/todos/7336692389)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-05-07 02:40 UTC, Kneesal reviewed
On second thought. Would be good to split this PR into two. 
One PR is all your storybook configs/setups 
Second PR for moving common components to libs and reusing them 
thoughts?

2024-05-07 02:40 UTC, Kneesal commented on apps/nexus-admin/src/components/PageWrapper/Header/Header.tsx
> +export const Header: FC<HeaderProps> = ({ title, hasBack, user }) => {
```suggestion
export function Header ({ title, hasBack, user }): ReactElement  {
```

2024-05-07 02:40 UTC, Kneesal commented on apps/nexus-admin/src/components/PageWrapper/Header/Header.tsx
> +      data-testid="main-header"
change all data-testids in the files you have touched to pascal case

2024-05-07 02:40 UTC, Kneesal commented on apps/nexus-admin/src/components/PageWrapper/NavigationDrawer/ListGroup/ListGroup.spec.tsx
> +})
write proper test

2024-05-07 02:40 UTC, Kneesal commented on apps/nexus-admin/src/components/PageWrapper/NavigationDrawer/ListGroup/ListGroup.tsx
> +import Collapse from '@mui/material/Collapse'
Story for this file?

2024-05-07 02:40 UTC, Kneesal commented on apps/nexus-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
> +import CampaignIcon from '@mui/icons-material/Campaign'
Thoughts on using existing nav drawer to libs folder and extending its functionality so we can pass our own drawer buttons and then reusing it here?

2024-05-07 02:40 UTC, Kneesal commented on apps/nexus-admin/src/components/PageWrapper/PageWrapper.tsx
> +import Stack from '@mui/material/Stack'
I wonder if we will be able to move PageWrapper in journeys-admin to shared/libs and reuse that here as well? Can you please look into this?

2024-05-07 13:45 UTC, tataihono requested changes

2024-05-07 13:45 UTC, tataihono commented on apps/nexus-admin/.eslintrc.json
> +        "i18next/no-literal-string": "off"
no sir. please fix the issues.

2024-05-07 13:45 UTC, tataihono commented on apps/nexus-admin/src/components/PageWrapper/Header/Header.tsx
> +      data-testid="main-header"
this is not right. the value is data-testid.

2024-05-09 22:02 UTC, Kneesal commented on apps/nexus-admin/src/components/PageWrapper/Header/Header.tsx
> +      data-testid="main-header"
^ @tataihono examples of where we have moved to Pascal Case 
https://github.com/JesusFilm/core/pull/2014

2024-10-06 23:07 UTC, closed without merging