test: horiztonal flow
JesusFilm/core pull request #2690
Opened 2024-05-02 01:01 UTC by csiyang

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-05-09 22:18 UTC, scottkelso reviewed
Looks really good @csiyang! Love the new look. Had a quick look after our chat on call. Made some suggestions mostly around clean code standards while they were fresh. 

In general, some of the things you had to describe in more detail to us for us to better understand, tends to suggest a comment or more refactoring is needed.

👏

2024-05-09 22:18 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +  })
9 indents would be considered a code smell. At the least is it possible to create something like this?

```
  const [stepAndCardBlockCreate] = useStepAndCardBlockCreateMutation({
    update(cache, { data }) {
      if (hasStepAndCardCreate) {
        createNewCacheBlock(data.stepBlockCreate)
      }
    }
  })
```

2024-05-09 22:18 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
> +            {card != null && <Divider />} */}
Is there a reason this is left in?

2024-05-09 22:18 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
> +        )
This took a bit of describing on call to understand. Wondering if it warrants a comment? (Or even better yet - refactored into well named function calls)

2024-05-09 23:48 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
> +          <ControlButton onClick={async () => await blockPositionsUpdate({})}>
not without making another arrow function, since the empty object needs to be passed in

2024-05-09 23:48 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
> +        onEdgeUpdateEnd={onEdgeUpdateEnd}
sure

2024-05-09 23:48 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
> +            {card != null && <Divider />} */}
Yeah, still need to double check if want bring this functionality back or not

2024-05-09 23:48 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
> +        )
This is the suggested way from the docs, I feel like, is `targetIsPane` is descriptive already, the main complexity was in explaining why mobile won't work.

What do you suggest the naming should be?

2024-05-09 23:48 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +  })
sure can have a look into it

2024-05-09 23:48 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
> +    id: `SocialPreview->${steps[0].id}`,
lint

2024-05-09 23:54 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
> +          <ControlButton onClick={async () => await blockPositionsUpdate({})}>
Np, just wanted to check! Good stuff.

2024-05-10 00:06 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
> +        )
Yea naming is good. Was thinking more about mobile. Although maybe there is a better place/process for documenting device specific caveats like this.

2024-05-10 00:33 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +  })
@scottkelso not much I can really simply here due to the amount of probs I have to pass down

2024-05-10 18:56 UTC, tataihono requested changes

2024-05-10 18:56 UTC, tataihono requested changes
thanks. few things.

2024-05-10 19:32 UTC, tataihono requested changes
to be fixed

2024-05-10 19:32 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/CustomEdge/CustomEdge.tsx
> +  const [selectedEdge, setSelectedEdge] = useState<Edge | undefined>(undefined)
drop and use source & sourceHandleId props.

2024-05-10 19:32 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/CustomEdge/CustomEdge.tsx
> +  const [edgeSelected, setEdgeSelected] = useState(false)
```suggestion
  const [selected, setSelected] = useState(false)
```

2024-05-10 19:32 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/arrangeSteps/arrangeSteps.ts
>    blocks.forEach((row, index) => {
can you change row here to column.
```suggestion
  blocks.forEach((column, index) => {
```

2024-05-10 19:32 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
> +export const MARKER_END_SELECTED_COLOR = '#C52D3A' // theme.palette.primary.main
```suggestion
export const MARKER_END_SELECTED_COLOR = adminLight.palette.primary.main
```

2024-05-10 19:32 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
> +export const MARKER_END_DEFAULT_COLOR = '#D3D3D3'
```suggestion
export const MARKER_END_DEFAULT_COLOR = darken(adminLight.palette.divider, 0.5)
```

2024-05-10 19:32 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
> +  }
add in to edge and node array above when arrays are initialised above. add comment to ensure it is not deleted.

2024-05-10 19:32 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +      if (data?.stepBlockCreate != null && data?.cardBlockCreate != null) {
```suggestion
      if (data?.stepBlockCreate == null || data?.cardBlockCreate == null) return
```

2024-05-10 19:32 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +  ): Promise<StepAndCardBlockCreate | null | undefined> {
```suggestion
  async function createStep({ x, y, sourceStepId, sourceBlockId }: {
    x: number,
    y: number,
    sourceStepId?: string,
    sourceBlockId?: string,
    sourceSocialPreview?: boolean
  }): Promise<StepAndCardBlockCreate | null | undefined> {
```

2024-05-10 19:32 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +    const block = searchBlocks(step != null ? [step] : [], handleId ?? '')
```suggestion
    const block = step == null || sourceBlockId == null ? undefined : searchBlocks([step], sourceBlockId)
```

2024-05-10 19:32 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +    const step = steps?.find((step) => step.id === nodeId ?? '')
```suggestion
    const step = sourceStepId == null || sourceStepId == 'SocialPreview' ? undefined : steps?.find((step) => step.id === sourceStepId)
```

2024-05-12 21:24 UTC, GeronimoJohn commented
Will pick up the requested changes above

2024-05-13 03:05 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +  })
I would mark this as resolve but will move the suggested changes above to this ticket if we really want this to be cleaned up further

https://3.basecamp.com/3105655/buckets/37071143/todos/7390523100

2024-05-14 02:15 UTC, tataihono requested changes

2024-05-14 02:15 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.tsx
@GeronimoJohn to assign splitting this into DuplicateBlock (variant button) and DuplicateStep (variant list-item)

2024-05-14 02:18 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.tsx
@levi-zustiak are you able to look into splitting the current DuplicateBlock into a more specific components as Tatai mentioned above please?

2024-05-14 03:56 UTC, tataihono requested changes

2024-05-14 03:56 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.tsx
> +      onClick={handleAddStepAndCardBlock}
```suggestion
      onClick={handleClick}
```

2024-05-14 03:56 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.tsx
> +  async function handleAddStepAndCardBlock(event): Promise<void> {
```suggestion
  async function handleClick(event): Promise<void> {
```

2024-05-14 03:56 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +) => Promise<StepAndCardBlockCreate | null | undefined> {
```suggestion

interface CoordinateVariables {
  x: number
  y: number
}

interface StepVariables extends CoordinateVariables {
  sourceStepId: string
  sourceBlockId?: string
  sourceSocialPreview?: false
}

interface SocialPreviewVariables extends CoordinateVariables {
  sourceSocialPreview: true
}

type Variables = StepVariables | SocialPreviewVariables

export function useCreateStep(): (variables: Variables) => Promise<StepAndCardBlockCreate | null | undefined> {
```

2024-05-14 03:56 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +  ): Promise<StepAndCardBlockCreate | null | undefined> {
```suggestion
  async function createStep(
    variables: Variables
  ): Promise<StepAndCardBlockCreate | null | undefined> {
```

2024-05-14 04:52 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +) => Promise<StepAndCardBlockCreate | null | undefined> {
It looks like you want `sourceStepId` to be required, but we currently call createNodeAndEdge in `NewStepButton` with just the x and y param to create a node. Will we need a separate function to create just the node, or continue to let this function handle both?

2024-05-14 04:55 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +  ): Promise<StepAndCardBlockCreate | null | undefined> {
@tataihono is there context for the new `sourceSocialPreview` param and what it's function will be?

2024-05-14 05:03 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateNodeAndEdge/useCreateNodeAndEdge.ts
> +) => Promise<StepAndCardBlockCreate | null | undefined> {
Tatai is currently having a go at refactoring this bit @levi-zustiak

2024-05-14 23:58 UTC, tataihono requested changes

2024-05-15 01:08 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
> +          x: parseInt(x.toString()),
sounds good! thanks for this. what a great method!

2024-05-15 01:16 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
> +        onEdgeUpdateEnd={onEdgeUpdateEnd}
all good on my side!

2024-05-15 01:18 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.tsx
@levi-zustiak fixed this!

2024-05-15 02:04 UTC, tataihono approved these changes

2024-05-15 02:05 UTC, merged