feat: data base model modifications
JesusFilm/core pull request #2694
Opened 2024-05-02 14:00 UTC by bengeos

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-05-02 14:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JesusFilm/core?pullRequest=2694) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JesusFilm/core?pullRequest=2694) before we can accept your contribution.<br/><hr/>**Biniam Kassahun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JesusFilm/core?pullRequest=2694) it.</sub>

2024-05-07 13:43 UTC, tataihono requested changes

2024-05-07 13:43 UTC, tataihono commented on apps/api-nexus/db/schema.prisma
> -    @@index(userId)
this removal needs to be reverted

2024-05-07 13:43 UTC, tataihono commented on apps/api-nexus/db/schema.prisma
> -    publisher
this removal needs to be reverted

2024-05-07 13:43 UTC, tataihono commented on apps/api-nexus/db/schema.prisma
> +    nexusId        String
are we removing the nexus object?

2024-05-07 13:43 UTC, tataihono commented on apps/api-nexus/db/schema.prisma
> +    captionCloudFlareId               String?
can we drop cloudflare?

2024-05-07 13:43 UTC, tataihono commented on apps/api-nexus/db/schema.prisma
> +    nexus                 Nexus                  @relation(fields: [nexusId], references: [id])
is it likely that resources are going to be connected to multiple channels?

2024-05-07 13:43 UTC, tataihono commented on apps/api-nexus/src/app/lib/bullMQ/consumers/batch.job.worker.ts
> +    // UPLOAD VIDEO
drop all commented code. it can be recovered via git.

2024-05-13 20:48 UTC, tataihono requested changes
can we drop the Status fields in favor of timestamps e.g publishedAt and deletedAt?

2024-05-13 20:51 UTC, tataihono requested changes
@bengeos can we also merge the channelYoutube and Channel models?

2024-06-13 19:50 UTC, tataihono requested changes

2024-06-13 19:50 UTC, tataihono commented on apps/api-nexus/db/schema.prisma
> +    status           ChannelStatus     @default(created)
swap for publishedAt?

2024-06-13 19:50 UTC, tataihono commented on apps/api-nexus/db/schema.prisma
>  }
is this needed anymore?

2024-06-13 19:50 UTC, tataihono commented on apps/api-nexus/db/seed.ts
>  async function main(): Promise<void> {
is this file needed anymore?

2024-06-13 19:50 UTC, tataihono commented on apps/api-nexus/src/app/lib/bullMQ/bullMQ.module.ts
> +    GoogleDriveService,
did we decide to drop google drive?

2024-06-13 19:50 UTC, tataihono commented on apps/api-nexus/src/app/lib/bullMQ/bullMQ.service.ts
>      return batch as unknown as Batch
please don't type as unknown. batch needs to have the appropriate type you need to return.

2024-06-13 19:50 UTC, tataihono commented on apps/api-nexus/src/app/lib/bullMQ/bullMQ.service.ts
> +    return batch as unknown as Batch
same for here.

2024-06-13 19:50 UTC, tataihono commented on apps/api-nexus/src/app/lib/bullMQ/consumers/batch.job.worker.ts
> +
uploading to cloudflare is not necessary.

2024-06-13 19:50 UTC, tataihono commented on apps/api-nexus/src/app/lib/bullMQ/consumers/batch.job.worker.ts
> +    console.log('UPLOAD TO YOUTUBE NOW', videoFilePath)
drop this log.

2024-06-13 19:50 UTC, tataihono commented on apps/api-nexus/src/app/lib/bullMQ/listener/jobListener.ts
> +// import { PrismaService } from '../../prisma.service'
drop commented code.

2024-06-13 19:50 UTC, tataihono commented on apps/api-nexus/src/app/lib/google/drive.service.ts
>  export class GoogleDriveService {
this service needs to be dropped right?

2024-06-13 19:50 UTC, tataihono commented on apps/api-nexus/src/app/lib/google/sheets.service.ts
> +import { drive_v3 } from '@googleapis/drive'
we were swapping this out for csv right?

2024-06-17 02:54 UTC, bengeos commented on apps/api-nexus/db/schema.prisma
> +    status           ChannelStatus     @default(created)
this change is introduced @ https://github.com/JesusFilm/core/pull/2771

2024-06-17 02:55 UTC, bengeos commented on apps/api-nexus/db/schema.prisma
>  }
this change is introduced @ https://github.com/JesusFilm/core/pull/2771

2024-06-17 06:11 UTC, bengeos commented on apps/api-nexus/src/app/lib/bullMQ/bullMQ.module.ts
> +    GoogleDriveService,
For time being we are still using the google drive library to download the public drive links. We will completely remove this on the next iteration

2024-06-17 08:34 UTC, bengeos commented on apps/api-nexus/db/seed.ts
>  async function main(): Promise<void> {
this is already done @ https://github.com/JesusFilm/core/pull/2875

2024-06-17 12:11 UTC, merged