Typography component
JesusFilm/core pull request #27
Opened 2021-09-10 00:58 UTC by storyworks

2021-09-26 23:19 UTC, tataihono requested changes

2021-09-28 03:28 UTC, tataihono requested changes
please move typography block component back into the journeys project

2021-09-28 03:28 UTC, tataihono commented on libs/shared/ui/src/components/Typography/Typography.spec.tsx
> +        content={'Hello World!'}
```suggestion
        content="Hello World!"
```

2021-09-28 03:28 UTC, tataihono commented on libs/shared/ui/src/components/Typography/Typography.spec.tsx
> +    ).toBeTruthy()
```suggestion
    ).toBeInTheDocument()
```

2021-09-28 03:28 UTC, tataihono commented on libs/shared/ui/src/components/Typography/Typography.tsx
> +export interface TypographyProps
These props should just be from the API not from Mui Typography.

2021-09-28 06:44 UTC, tataihono requested changes
I would have expected to see pages/[journeyId].tsx to be updated to include the new fragment. Can you add that in then this should be done :)

2021-09-29 01:30 UTC, tataihono commented
can you generate types for your query adjustment `nx codegen journeys`

2021-09-29 01:45 UTC, storyworks commented
> can you generate types for your query adjustment `nx codegen journeys`

I have run that? This was the change
![image](https://user-images.githubusercontent.com/10802634/135189046-cf709d6b-8a6e-414f-a28d-9f9f0c909ed1.png)

2021-09-29 03:58 UTC, tataihono approved these changes

2021-09-29 04:04 UTC, merged