fix: deprecate navigate action
JesusFilm/core pull request #2730
Opened 2024-05-09 23:44 UTC by GeronimoJohn

# Description

### Issue

_We're dropping the use of navigate actions_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7364834584)

### Solution

_The first step to removing an existing type or field within our backend is to add the @deprecated directive to it. Add the @deprecated directive to navigate action_

2024-05-10 02:07 UTC, tataihono submitted a review, later dismissed

2024-05-14 03:16 UTC, GeronimoJohn commented
After chatting with Tatai, converting PR to no longer add deprecation warning. As we're dropping the use of the fields, inputs, and mutations on the client side. Though means that this will now depend on the PR: https://github.com/JesusFilm/core/pull/2727

2024-05-17 00:00 UTC, tataihono requested changes
update nua seeds

2024-05-17 02:27 UTC, tataihono requested changes

2024-05-17 02:27 UTC, tataihono commented on apps/api-journeys/src/app/modules/action/emailAction/emailAction.resolver.ts
> +import { checkBlockSupport } from '../checkBlockSupport'
change name to canBlockHaveAction

2024-05-17 03:17 UTC, tataihono approved these changes

2024-05-17 04:19 UTC, merged