refactor: deprecate NavigateToJourneyAction backend
JesusFilm/core pull request #2733
Opened 2024-05-10 02:10 UTC by scottkelso

# Description

### Issue

`NavigateToJourneyAction` is no longer needed. It needs removed. This is the **_second_** in 3x PRs that will realise this.
1. Safely remove it from the frontend
**2. Mark it for deprecation in the backend**
3. Remove it from the backend

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7364835830)

### Solution

Mark the NavigateToJourneyAction field as deprecated and change from required to optional
Rerun codegen for api-journeys and journeys-admin

# External Changes

n/a

# Additional information

Behaviour of the backend should be unaffected.
You should however see a deprecation warning when trying to use original mutations.
<img width="448" alt="image" src="https://github.com/JesusFilm/core/assets/26043376/8fdb2a7c-6cf8-4660-9c98-007326946de6">

2024-05-10 18:07 UTC, csiyang requested changes
This also needs to go into prod, not the feature branch

2024-05-10 18:07 UTC, csiyang commented on apps/api-journeys/src/app/modules/action/action.graphql
> +  DEPRECATED: use NavigateAction and blockUpdateNavigateAction instead.
Might be better to say `NavaigateToJourneyAction` is being removed, and suggest to use the relevant action update instead

2024-05-12 22:13 UTC, scottkelso commented on apps/api-journeys/db/schema.prisma
> +  NavigateToJourneyAction /// @deprecated Use `NavigateAction` instead.
Ah, that is new info! I'll make changes to the deprecated messages today :)

2024-05-12 23:08 UTC, scottkelso commented
As per @csiyang 's [comment](https://github.com/JesusFilm/core/pull/2733#pullrequestreview-2050589713) I have moved PR to main.

https://github.com/JesusFilm/core/pull/2740

2024-05-12 23:08 UTC, closed without merging