feat: languages bq import support part 1
JesusFilm/core pull request #2739
Opened 2024-05-10 22:32 UTC by mikeallisonJS

# Description

### Issue

Name field is in a Json Blob array

### Solution

Incrementally move name to a table relation

# External Changes

Adds new model & relations, as well as seed for new model

# Additional information

Once complete, this should allow us to import languages from BQ.
Additionally it should make for better caching down the line and reduce cpu usage of filtering json. Especially once we if/when we add WESS data

2024-05-11 13:35 UTC, tataihono requested changes

2024-05-11 13:35 UTC, tataihono commented on apps/api-languages/db/schema.prisma
> +  nameLanguage LanguageName[] @relation(name: "nameLanguage")
Not sure what this relation is for?

2024-05-13 19:49 UTC, mikeallisonJS commented on apps/api-languages/db/schema.prisma
> +  nameLanguage LanguageName[] @relation(name: "nameLanguage")
This is the language relationship for languageId of name. It enforces a foreign key relationship on the data.

2024-05-13 21:12 UTC, tataihono approved these changes

2024-05-13 21:27 UTC, merged