refactor: pagination bullets branching
JesusFilm/core pull request #2786
Opened 2024-05-20 21:52 UTC by Kneesal

# Description

### Issue

pagination bullets are do not reflect the state of the journey since the introduction of branching

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7409977847)

### Solution

pagination bullets are now agnostic of the card/parent order of a journey. 
Start card will always show pagination start, 
middle cards will animate pagination as per normal. 
If you are on a card that has no next-step - it will show end state of pagination bullets

2024-05-22 23:12 UTC, csiyang requested changes

2024-05-22 23:12 UTC, csiyang commented on libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.tsx
> +    blockHistory.splice(1, blockHistory.length - 1)
Can we use [lodash drop right](https://lodash.com/docs/4.17.15#dropRight) instead of the splices. I think it would make it a bit easier to understand

2024-05-22 23:12 UTC, csiyang commented on libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.tsx
> +  }
I think creating this array is redundant. You will always need to loop through all of blockHistory, except you need to do it twice if `prevCards.length > 0`

```suggestion
    blockHistory.forEach((block, i) => {
      if (block.id === currentActiveBlock.id) {
        blockHistory.splice(i + 1, blockHistory.length - i)
      }
    })
```

2024-05-22 23:44 UTC, Kneesal commented on libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.tsx
> +    blockHistory.splice(1, blockHistory.length - 1)
lodash doesn't mutate the original array hence why I opted for using splice instead

2024-05-24 01:30 UTC, csiyang approved these changes

2024-05-24 01:47 UTC, merged