test: useCreateStep
JesusFilm/core pull request #2803
Opened 2024-05-23 21:51 UTC by levi-zustiak

# Description

### Issue
Needed tests for `useCreateStep`

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7390523100)

### Solution
Added tests for `useCreateStep`
_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes
N/A

# Additional information
N/A

2024-05-23 21:54 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.spec.tsx
> +}))
Do you think there is a better way to do this? I feel like this is cumbersome

2024-05-24 02:02 UTC, csiyang requested changes

2024-05-24 02:02 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.spec.tsx
> +
Can you add the cache check for blocks
```suggestion
expect(cache.extract()['Journey:journey-id']).toEqual({
    // step1 ref
    // newStep ref
    //newCard ref
})
```

2024-05-24 04:28 UTC, csiyang approved these changes

2024-05-24 05:21 UTC, merged