fix: add loading state to card templates
JesusFilm/core pull request #2805
Opened 2024-05-24 02:56 UTC by scottkelso

# Description

### Issue

No loading state for adding card templates

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7409941009)

### Solution

Add skeleton on loading state

# External Changes

n/a

# Additional information

n/a

# How to test
Create a new card or start with a blank card
Click on one of the templates in the card template drawer (suggest turning on browser throttling to see worst case scenario)
See that the skeleton is rendered and is not claickable

# Acceptance Criteria
As a user I should not be able to add multiple card templates to the same card at once

2024-05-27 21:04 UTC, csiyang requested changes

2024-05-27 21:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardPoll/CardPoll.data.ts
> +}))
```suggestion
```

2024-05-27 21:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardQuote/CardQuote.data.ts
> +}))
```suggestion
```

2024-05-27 21:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardVideo/CardVideo.data.ts
> +}))
```suggestion
```

2024-05-27 21:04 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.tsx
> +      {loading ? (
Can you add a story for the loading state. You can try this via triggering a click in the story and passing in a mock that keeps loading.

If that doesn't work, we can add a optional prop to set loading just for testing purposes. (This is not best practice and we try to avoid this if we can)

2024-06-24 02:59 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.data.ts
> +export const cachedJourney = {
I understand why you might have reservations about this type of refactoring considering most of our react components inline their functions. However in general clean coding oop practises it is better to refactor out implementational detail so that you are left with high level code description of what the code does. This has many advantages, one being it saves lots of time because future engineers at a glance of 3x lines of code know what the function does, instead of having to scan 20+ lines to gain the same information. After refactoring, if a future engineer needs to know any detail, they can drill down. 

A great resource on this topic for OOP clean code is https://github.com/jnguyen095/clean-code/blob/master/Clean.Code.A.Handbook.of.Agile.Software.Craftsmanship.pdf

The codebase has already established the good clean code practice of refactoring test objects into *.data.ts files.

2024-06-24 03:41 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardCta/CardCta.data.ts
> +}))
Are these a blocker? I assume you want all jest.fn calls in the spec file? I can't move this into `CardCta.spec.tsx` because cardCtaCreateMock in `CardCta.data.ts` needs it.

2024-06-24 04:25 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.spec.tsx
> +const cardTemplate = (
Have kept this as is due to the conflict with the actual imported CardTemplate component.

2024-06-24 04:26 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.spec.tsx
> +    expect(getByText('selectedBlock: stepId')).toBeInTheDocument()
I have renamed this function `expectBlockToBeSelected`.

2024-06-24 04:28 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.spec.tsx
> +  it('changes content of card when video template clicked', async () => {
You're right. Click events are being testing in the specific card template specs. I am now only testing the template option and the loading state each renders.

2024-06-24 04:43 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardCta/CardCta.data.ts
> +  result: cardCtaResult
Ah yes! Brill suggestion!

2024-06-26 00:00 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.tsx
> +      {loading ? (
As you say, I thought this could have been achieved by using the `<ApolloLoadingProvider/>` and a click event. For now I got the loading state to work by adding an optional prop.

2024-06-27 07:10 UTC, csiyang approved these changes

2024-08-12 19:57 UTC, closed without merging