feat: analytics email service
JesusFilm/core pull request #2809
Opened 2024-05-27 03:18 UTC by GeronimoJohn

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-06-04 06:15 UTC, GeronimoJohn commented on apps/api-journeys/src/app/modules/event/email/email.service.ts
> +        removeOnComplete: true,
Note to self: remove on complete, need to have a check where jobId has already been sent, don't send an updated version of the job to the user

2024-06-16 22:34 UTC, Kneesal requested changes

2024-06-16 22:34 UTC, Kneesal commented on apps/api-journeys/src/app/modules/event/email/email.consumer.ts
> +}
Use Prisma.UserJourneyGetPayload, Prisma.UserTeamGetPayload and Prisma.JourneyGetPayload for property types

e.g.
```
export type JourneyWithTeamAndUserJourney = Prisma.JourneyGetPayload<{
  include: {
    userJourneys: true
    team: true
    primaryImageBlock: true
  }
}>
```

2024-06-16 22:34 UTC, Kneesal commented on apps/api-journeys/src/app/modules/event/email/email.consumer.ts
> +  async sendEventsNotification(job: Job<EventsNotificationJob>): Promise<void> {
```suggestion
  async visitorEventEmails(job: Job<EventsNotificationJob>): Promise<void> {
```

2024-06-16 22:34 UTC, Kneesal commented on apps/api-journeys/src/app/modules/event/email/email.consumer.ts
> +  async sendUserNotification(
```suggestion
  async visitorEventEmail(
```

2024-06-16 22:34 UTC, Kneesal commented on apps/api-journeys/src/app/modules/event/email/email.consumer.ts
> +  }
lets move these to a libs folder nested in the directory as these don't pertain to sending email but are just helper functions , lets do DI to pass in services if needed

2024-06-16 22:34 UTC, Kneesal commented on apps/api-journeys/src/app/modules/event/email/email.service.ts
> +  async addVisitorEvent(
```suggestion
  async addVisitorEventEmailJob(
```

2024-06-16 23:44 UTC, GeronimoJohn commented on apps/api-journeys/src/app/modules/event/email/email.consumer.ts
> +}
This is cool

2024-06-17 20:25 UTC, Kneesal submitted a review, later dismissed
lgtm

2024-06-18 02:41 UTC, Kneesal submitted a review, later dismissed

2024-06-18 22:00 UTC, Kneesal submitted a review, later dismissed

2024-06-18 22:28 UTC, Kneesal submitted a review, later dismissed

2024-06-19 03:35 UTC, Kneesal approved these changes

2024-06-19 04:41 UTC, merged