feat: plausible backend
JesusFilm/core pull request #2813
Opened 2024-05-29 03:20 UTC by csiyang

# Description

### Issue

Backend portion of work required for plausible integration

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-06-07 03:06 UTC, tataihono requested changes

2024-06-07 03:06 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.graphql
drop

2024-06-07 03:06 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.resolver.ts
> +
drop

2024-06-07 03:06 UTC, tataihono commented on apps/api-journeys/src/app/modules/plausible/plausible.graphql
drop

2024-06-07 03:06 UTC, tataihono commented on apps/api-journeys/src/app/modules/plausible/plausible.resolver.ts
drop

2024-06-07 03:06 UTC, tataihono commented on apps/api-journeys/src/app/modules/plausible/plausible.service.ts
> +  async getStatsRealtimeVisitors(
drop the public methods from here and below and any private methods that are no longer used.

2024-06-07 03:07 UTC, tataihono requested changes

2024-06-07 03:07 UTC, tataihono commented on package.json
> +    "@mui/x-charts": "^7.3.2",
drop

2024-06-07 03:07 UTC, tataihono commented on package.json
> +    "next-plausible": "^3.12.0",
drop

2024-06-07 03:07 UTC, tataihono commented on package.json
> +    "react-day-picker": "^8.10.1",
drop

2024-06-20 04:08 UTC, tataihono requested changes

2024-06-20 04:08 UTC, tataihono commented on apps/api-journeys/src/app/modules/plausible/plausible.service.spec.ts
each test should define the handlers it needs rather than doing it all at the beginning. Don't want to accidentally call methods you don't intend on from one function to another.

2024-06-20 04:08 UTC, tataihono commented on package.json
> +    "uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.43.0",
dropdd

2024-06-20 05:31 UTC, jianwei1 approved these changes

2024-06-20 05:50 UTC, merged