feat: resource page header
JesusFilm/core pull request #2815
Opened 2024-05-29 04:14 UTC by jianwei1

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-06-13 21:02 UTC, jianwei1 commented on apps/watch/src/components/Header/assets/favicon.png
change to minimal-logo

2024-06-13 21:02 UTC, jianwei1 commented on apps/watch/src/components/HomePage/HomePage.tsx
rename to WatchHomePage

2024-06-17 22:02 UTC, jianwei1 commented on apps/watch/src/components/Header/assets/favicon.png
https://github.com/JesusFilm/core/pull/2815/commits/060d2b38797b9a64bd764fdab74303464dcc02a6

2024-06-19 04:51 UTC, tataihono requested changes

2024-06-19 04:51 UTC, tataihono commented on apps/watch/src/components/Header/Header.spec.tsx
> +  // should hide spacer
drop

2024-06-19 05:04 UTC, tataihono approved these changes

2024-06-19 05:19 UTC, merged