feat: get plausible stats breakdown
JesusFilm/core pull request #2821
Opened 2024-05-30 23:11 UTC by levi-zustiak

# Description

### Issue
Need to fetch the plausible analytic stats for a journey's steps and pass the data to the editor context
_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663055/todos/7446780139)

### Solution
- Created `usePlausibleStatsBreakdownQuery` hook
- Fetch stats break down and pass into editor context

# External Changes
n/a

# Additional information
n/a

2024-05-30 23:12 UTC, levi-zustiak commented on libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
> +import { GetPlausibleStatsBreakdown_journeysPlausibleStatsBreakdown as StatsBreakdown } from '../../../../../../apps/journeys-admin/__generated__/GetPlausibleStatsBreakdown'
I couldn't get the types to generate for journeys-ui. Is there a proper way to access this type?

2024-05-30 23:24 UTC, csiyang commented on libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
> +import { GetPlausibleStatsBreakdown_journeysPlausibleStatsBreakdown as StatsBreakdown } from '../../../../../../apps/journeys-admin/__generated__/GetPlausibleStatsBreakdown'
Yeah, you can check how we generate journeys field. (Search for `${JOURNEY_FIELDS}`.

But basically

1. Create a `PlausibleStatsBreakDownFields.ts` file in journeys-ui
2. Run codegen for journeys-ui, which will generate the type for you to use in EditorProvider
3. In your hook you can import `${PLAUSIBLE_STATS_BREAKDOWN_FIELDS}` from journeys-ui to use when you create your query

2024-06-03 20:55 UTC, csiyang requested changes

2024-06-03 20:55 UTC, csiyang commented on libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
> +  journeyStatsBreakdown: StatsBreakdownFields[]
Lets make this nullable so we don't have to update other components/tests 
```suggestion
  journeyStatsBreakdown?: StatsBreakdownFields[]
```

2024-06-06 04:44 UTC, csiyang commented
closing in favour of https://github.com/JesusFilm/core/pull/2841

2024-06-06 04:44 UTC, closed without merging