fix: refactor eventEmailNotifications
JesusFilm/core pull request #2873
Opened 2024-06-12 03:29 UTC by Kneesal

# Description

### Issue

Ability to get the journeyNotification directly from the userTeam/userJourney

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

added resolve reference fields to user Journey and user Team resolvers

2024-06-12 22:25 UTC, tataihono requested changes

2024-06-12 22:25 UTC, tataihono commented on apps/api-journeys/db/schema.prisma
>    @@unique([userId, journeyId])
```suggestion
  @@unique([userId, journeyId])
  @@unique([userId, journeyId, userTeamId])
```

2024-06-12 22:25 UTC, tataihono commented on apps/api-journeys/db/schema.prisma
> +  journey                 Journey      @relation(fields: [journeyId], references: [id], onDelete: Cascade)
these should all appear at the bottom

2024-06-12 22:25 UTC, tataihono commented on apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.graphql
> +  journeyNotification: [JourneyNotification!]!
```suggestion
  journeyNotification: JourneyNotification
```

2024-06-12 22:25 UTC, tataihono commented on apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.graphql
> +  journeyNotification(journeyId: ID!): [JourneyNotification!]!
```suggestion
  journeyNotification(journeyId: ID!): JourneyNotification
```

2024-06-12 22:25 UTC, tataihono commented on apps/api-journeys/src/app/modules/userTeam/userTeam.resolver.ts
> +  ): Promise<JourneyNotification[] | null> {
```suggestion
  ): Promise<JourneyNotification | null> {
```

2024-06-12 22:25 UTC, tataihono commented on apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
> +  ): Promise<JourneyNotification[] | null> {
```suggestion
  ): Promise<JourneyNotification | null> {
```

2024-06-12 22:25 UTC, tataihono commented on apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.resolver.ts
> +    })
you need to find and associate the correct userTeam or userJourney to this journeyNotifcation object.

2024-06-12 22:25 UTC, tataihono commented on apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.resolver.ts
> +  }
this bleeds information. the general public could get all the journeyNotifcation data.

2024-06-12 23:26 UTC, Kneesal commented on apps/api-journeys/db/schema.prisma
> +  journeyNotification JourneyNotification[]
changed to journeyNotification JourneyNotification?

2024-06-13 05:02 UTC, tataihono requested changes

2024-06-13 05:02 UTC, tataihono commented on apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.resolver.ts
> +    })
this should have a casl guard which ensures that the user has the correct permissions to edit this object.

2024-06-14 00:46 UTC, tataihono requested changes

2024-06-14 00:46 UTC, tataihono commented on apps/api-journeys/src/app/modules/customDomain/customDomain.acl.spec.ts
reset

2024-06-14 00:46 UTC, tataihono commented on apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.resolver.ts
> +    const userJourneyId = journey?.userJourneys?.find(
check user has ability to manage journey.

2024-06-14 03:07 UTC, tataihono approved these changes

2024-06-14 03:21 UTC, merged