feat: link node analytics
JesusFilm/core pull request #2885
Opened 2024-06-14 03:26 UTC by levi-zustiak

# Description

### Issue
Need to display analytics for link node components

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663055/todos/7446895500)

### Solution
- Added `LinkNodeAnalytics`
- added tests and stories for `LinkNodeAnalytics`

# External Changes
N/A

# Additional information
N/A

2024-06-24 04:34 UTC, csiyang requested changes

2024-06-24 04:34 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNodeAnalytics/LinkNodeAnalytics.tsx
> +export function LinkNodeAnalytics({
Can you link it up so that it can show on the flow now

2024-06-24 22:47 UTC, tataihono requested changes

2024-06-24 22:47 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/AnalyticsDataPoint.tsx
> +  tooltipLabel = ''
this is not nullable anyway. so default assignment is not required.

2024-06-24 22:47 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/AnalyticsDataPoint.tsx
> +  tooltipLabel: string
tooltipTitle (match the consuming prop).

2024-06-24 22:47 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.tsx
> +            <LinkNodeAnalytics clicksCount={linkAnalytics} />
can the linkNodeAnalytics get its data from the action? its just that line 44-45 execute regardless of if showAnalytics is true.

2024-06-25 00:04 UTC, tataihono approved these changes

2024-06-25 03:11 UTC, csiyang approved these changes

2024-06-25 03:25 UTC, merged