feat: resources hub journeys
JesusFilm/core pull request #2905
Opened 2024-06-18 22:15 UTC by scottkelso

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-06-27 03:02 UTC, mikeallisonJS requested changes

2024-06-27 03:02 UTC, mikeallisonJS commented on package.json
> +    "uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.44.0",
I don't think this should be here (was removed by Tatai in an another PR)

2024-06-27 03:02 UTC, mikeallisonJS commented on tsconfig.base.json
> +      "@core/journeys/ui/test/*": ["libs/journeys/ui/test/*"],
Is this correct?

2024-06-27 03:05 UTC, scottkelso commented on package.json
> +    "uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.44.0",
Cool I'll remove this now.

2024-06-27 03:07 UTC, scottkelso commented on apps/journeys-admin/test/i18n.ts
> +// eslint-disable-next-line no-restricted-imports
No it's not auto generated. Was added 4 months ago. Although I wonder if it is needed. Removed in last commit and no linting warnings.

2024-06-27 03:13 UTC, scottkelso commented on tsconfig.base.json
> +      "@core/journeys/ui/test/*": ["libs/journeys/ui/test/*"],
I added this so that the i18n file (added in journeys/ui/test/i18n) could be imported which wasn't being included in the existing @core/journeys/ui/*

2024-06-27 03:20 UTC, scottkelso commented on tsconfig.base.json
> +      "@core/journeys/ui/test/*": ["libs/journeys/ui/test/*"],
But looks like it's not used so as long as remove doesn't cause any issues on github actions - we'll drop this.

2024-06-27 03:47 UTC, mikeallisonJS submitted a review, later dismissed

2024-06-27 04:53 UTC, GeronimoJohn approved these changes

2024-07-01 22:33 UTC, mikeallisonJS approved these changes

2024-07-01 23:47 UTC, mikeallisonJS approved these changes

2024-07-03 03:13 UTC, merged