feat: step block analytics
JesusFilm/core pull request #2936
Opened 2024-06-21 21:33 UTC by levi-zustiak

# Description

### Issue
Need the analytics for a step block

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution
Added overlay for step block analytics and analytics for the action buttons on a step

# External Changes

# Additional information

2024-06-24 04:52 UTC, csiyang requested changes
Are the action bars meant to be here too, or will they be on a different PR?

2024-06-24 04:52 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
> +  // const { blockAnalyticsMap } = useMemo(() => {
Remove comments

2024-06-24 22:53 UTC, tataihono requested changes

2024-06-24 22:53 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/AnalyticsDataPoint.tsx
> +  tooltipLabel: string
```suggestion
  tooltipTitle: string
```

2024-06-24 22:53 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/AnalyticsDataPoint.tsx
> +  tooltipLabel = ''
```suggestion
  tooltipTitle
```
not nullable.

2024-06-24 22:53 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
> +          <StepBlockNodeAnalytics {...stepStats} />
can this component handle its analytics fetching?

2024-06-24 22:53 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
> +              analytics={getBlockAnalytics(block)}
action button should handle the conversion to analytics.

2024-06-25 02:16 UTC, tataihono requested changes

2024-06-25 02:16 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
> +  const { percentage, total } = getBlockAnalytics(block)
```suggestion
  const total = analytics?.blockMap.get(block.id) ?? 0]
  let percentage = blockEventTotal / (analytics?.stepMap.get(stepId)?.total ?? 0)

  if (Number.isNaN(percentage) || !Number.isFinite(percentage))
    percentage = 0
```

2024-06-25 23:08 UTC, tataihono approved these changes

2024-06-26 02:13 UTC, csiyang approved these changes

2024-06-26 02:44 UTC, merged