feat: referrer nodes
JesusFilm/core pull request #2944
Opened 2024-06-23 17:16 UTC by levi-zustiak

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-06-23 17:19 UTC, levi-zustiak commented
- Still need tests and stories
- Couldn't get the edge to connect to the social preview node
- Position algorithm, and the node origin is the left side of the node, but it doesn't look like there is a way to provide an origin for a specific node type.
- Icons

2024-06-24 05:16 UTC, csiyang requested changes
I also wasn't able to get this node to show up when the referrer was just `direct `, could be something coming in from the recent refactor

2024-06-24 05:16 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformReferrers/tranformReferrers.ts
> +        markerEnd: {
These edges dont need the arrows at the end

2024-06-24 05:16 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.tsx
> +        <Typography variant="body2">{data.property}</Typography>
I think Lyuba wanted an icon based on the type of refferer

2024-06-25 05:01 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
> +  }, [JSON.stringify(analytics?.referrers)])
Had a question on the best way to add the analytics nodes and edges. This way causes the nodes to be overwritten when the step algorithm reruns on a change.

2024-06-25 05:03 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.tsx
> +  }
This isn't complete since not sure which referrers we are tracking. @csiyang said @tataihono mentioned something about favicons for this

2024-06-26 04:06 UTC, tataihono approved these changes

2024-06-26 04:18 UTC, csiyang submitted a review, later dismissed

2024-06-26 05:17 UTC, csiyang approved these changes

2024-06-26 05:42 UTC, merged