feat: flow stats filters
JesusFilm/core pull request #2969
Opened 2024-06-27 02:43 UTC by csiyang

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-07-01 15:44 UTC, levi-zustiak requested changes
I didn't see the filter added in JourneyFlow. Will it be added in a separate PR?

2024-07-01 15:44 UTC, levi-zustiak commented on apps/journeys-admin/src/components/PlausibleFilter/RangePicker/RangePicker.tsx
> +        color: 'pink',
```suggestion
```

2024-07-01 15:44 UTC, levi-zustiak commented on apps/journeys-admin/src/components/PlausibleFilter/RangePicker/RangePicker.tsx
> +            ':hover': {
Prevents the number from "disappearing" on hover for disabled dates

```suggestion
            ':hover:enabled': {
```

2024-09-03 02:54 UTC, csiyang commented
Closing until the feature is needed

2024-09-03 02:54 UTC, closed without merging