fix: Add parentBlockId to action in api-journeys
JesusFilm/core pull request #300
Opened 2022-02-17 04:23 UTC by storyworks

# Description

Add parentOrderId to action so we can used optimised response in editing actions. This unblocks Siyang

[Basecamp]()

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Updated Unit tests
- [ ] Viewed data returned by apollo server

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-02-17 21:11 UTC, storyworks commented on apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
> +  let resolver: ButtonBlockResolver,
Just cleaning up, most tests use resolver to be the relevant class resolver and `blockResolver: BlockResolver`

2022-02-17 21:12 UTC, storyworks commented on apps/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.resolver.spec.ts
> +    triggerStart: 5,
Not sure why we had the `extraAttrs` prop, updated to be in step with `.graphl` file.

2022-02-17 21:17 UTC, storyworks commented on apps/api-journeys/src/app/modules/block/button/button.resolver.ts
> +  action(@Parent() block: ButtonBlock): Action | null {
We decided to update `parentBlockId` for actions on each parent of action since we couldn't reference the parent block in `action.resolver.ts` itself. 
This would need to be remembered for each future component. Doing this meant we didn't need to touch current nua seed data (less room for error while updating seed data)

It also prompted Tatai to reconsider making Icon a block and revert it back to a type.. Possibly that task will be raised early next week. Please let us know if you have any thoughts @mikeallisonJS

2022-02-20 22:56 UTC, tataihono requested changes
I've only comment on a few places but they should broadly apply to other cases that are similar.

2022-02-20 22:56 UTC, tataihono commented on apps/api-journeys/src/app/modules/block/button/button.resolver.ts
> +      : null
multi-line ternaries are really ugly. Can we do something a bit simpler like:
```suggestion
    if (block.action == null) return null
    
    return {
      ...block.action,
      parentBlockId: block.id
    }
```

2022-02-20 22:56 UTC, tataihono commented on apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.spec.ts
> +      parentBlockId: '1',
this doesn't need to be added here. The underlying resolver should handle adding this.

2022-02-20 22:56 UTC, tataihono commented on apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts
> +      parentBlockId: '1',
not needed. The underlying resolver should do this.

2022-02-20 22:56 UTC, tataihono commented on apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.spec.ts
> +      parentBlockId: '1',
not needed. The underlying resolver should do this.

2022-02-20 22:56 UTC, tataihono commented on apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts
> +      parentBlockId: '1',
not needed. The underlying resolver should do this.

2022-02-20 22:56 UTC, tataihono commented on apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.spec.ts
> +      parentBlockId: '1',
not needed. The underlying resolver should do this.

2022-02-20 22:56 UTC, tataihono commented on apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
> +      parentBlockId: '1',
not needed. The underlying resolver should do this.

2022-02-21 20:02 UTC, storyworks commented on apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
> +      get: jest.fn(() => blockResponse),
Since `blockResponse` now contains `parentBlockId` but `block` doesn't - we need to mock the factory to return blockResponse instead of block to get `returns ButtonBlock - line 136 test to work.

Please correct my understanding if wrong, but `block` is the data stored in the db (uses key). Whilst blockResponse is what we get from the api when we try to retrieve that data (key becomes Id for some cases). Hence get / getAll should return blockResponse.

2022-02-21 21:44 UTC, mikeallisonJS commented on apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
> +      get: jest.fn(() => blockResponse),
block would be what we get from the service, blockResponse would be from the resolver after keyasid is called. Currently all calls to the service should include _key, and calls to the resolvers should use or test id

2022-02-21 21:48 UTC, mikeallisonJS commented on apps/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.resolver.spec.ts
> +    triggerStart: 5,
looks like an oversight during copy/pasta from prisma

2022-02-21 22:41 UTC, mikeallisonJS approved these changes

2022-02-21 22:55 UTC, merged