refactor: other referrers
JesusFilm/core pull request #3002
Opened 2024-07-04 20:33 UTC by levi-zustiak

# Description

### Issue
Needed to update the other referrer component to use an accordion drop down to display the list of other sources rather than a tooltip.

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663055/todos/7575963029)

### Solution
Replaced the use of tooltip for displaying other sources with the accordion component

# External Changes

# Additional information

2024-07-10 21:13 UTC, csiyang requested changes

2024-07-10 21:13 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.tsx
>    switch (property) {
Only just noticed this was only handling the icon for facebook. We'll need to update this at some point to show icons from other sources.

2024-07-10 21:13 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/OtherReferrer/OtherReferrer.tsx
> +import { Accordion, AccordionDetails, AccordionSummary } from '@mui/material'
I think we had a issue with imports importing everything from a module instead of just the functions that was being used, so we've been splitting up the imports
```suggestion
import { Accordion } from '@mui/material/Accordion'
```

2024-07-10 21:13 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/OtherReferrer/OtherReferrer.tsx
> -  const [anchorEl, setAnchorEl] = useState<HTMLElement | null>(null)
Need to update the test and stories for this

2024-07-10 21:13 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerValue/ReferrerValue.tsx
> +export function ReferrerValue({
add unit tests and stories

2024-07-10 23:36 UTC, csiyang commented
atlantis unlock

2024-07-11 02:00 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.tsx
>    switch (property) {
Yeah, I'll see if we can get ticket made for that

2024-07-11 22:06 UTC, csiyang approved these changes

2024-07-11 22:20 UTC, merged