feat: social preview analytic styles
JesusFilm/core pull request #3021
Opened 2024-07-09 14:22 UTC by levi-zustiak

# Description

### Issue
Needed to update the styles for the social preview node when in analytics mode

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7584807182)

### Solution
Updated styles for the social preview node

# External Changes

# Additional information

2024-07-10 02:59 UTC, csiyang requested changes
Some minor changes to use theme tokens. If nothing exactly matches, use the closes matching color.

2024-07-10 02:59 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
> +              outline: '2px solid rgba(0, 0, 0, 0.1)',
Use theme colors tokens

2024-07-10 02:59 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
> +            <Box width={9} height={9} bgcolor={bgcolor} borderRadius="4.5px" />
Use theme token for this
```suggestion
            <Box width={9} height={9} bgcolor={bgcolor} borderRadius={1} />
```

2024-07-10 02:59 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
> +              <ThumbsUp sx={{ fontSize: 9, color: bgcolor, bgColor: 'red' }} />
Use theme color

2024-07-10 02:59 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
> +  const bgcolor = showAnalytics ? 'rgba(0,0,0,0.1)' : 'background.default'
use theme color

2024-07-10 21:15 UTC, csiyang requested changes

2024-07-10 21:15 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
> +              outline: '2px solid rgba(0, 0, 0, 0.1)',
Still need to refactor to use the theme color for the outline

2024-07-10 21:15 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
>                  borderRadius="4.5px"
can you update the rest of these border radiuses?

2024-07-23 21:09 UTC, csiyang requested changes

2024-07-23 21:09 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
> +  targetHandle?: 'none' | 'show' | 'hide' | 'disabled'
Any reason why we cant use `hide` here?

2024-07-24 04:04 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
> +  targetHandle?: 'none' | 'show' | 'hide' | 'disabled'
The original `hide` did not render the handle, which caused the referrer node edges to not display since the handle didn't exist. So I added the additional `none` to take the place of the original `hide` implementation, and used `hide` to set the target handle opacity to 0 so it still exists, but does not show.

2024-07-24 23:53 UTC, csiyang requested changes

2024-07-24 23:53 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
> +    | 'disabled' // Handle is rendered and visible, but not connectable
Do you also think we should also do this for the source handle? Could worth making this into a ENUM at this point
```suggestion
    | 'none' // not rendered - Default value
    | 'show' // rendered, visible and connectable
    | 'hide' // rendered, not visible or connectable
    | 'disabled' // rendered, visible, not connectable
```

2024-07-29 21:10 UTC, csiyang requested changes

2024-07-29 21:10 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
> +  DISABLED = 'disabled' // rendered, visible, not connectable
Just to follow the pattern already set by other enums
```suggestion
  None = 'none', // not rendered - Default value
  Shown = 'shown', // rendered, visible and connectable
  Hidden = 'hidden', // rendered, not visible or connectable.
  Disabled = 'disabled' // rendered, visible, not connectable
```

2024-07-29 23:28 UTC, csiyang approved these changes

2024-07-29 23:41 UTC, merged