feat: undo action changes
JesusFilm/core pull request #3065
Opened 2024-07-17 01:07 UTC by tataihono

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-07-17 21:09 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useUpdateEdge/useUpdateEdge.ts
> +import { get } from 'lodash'
```suggestion
import get from 'lodash/get'
```

2024-07-17 21:30 UTC, Kneesal requested changes

2024-07-17 21:30 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useUpdateEdge/useUpdateEdge.ts
> +import { get } from 'lodash'
```suggestion
import  get  from 'lodash/get'
```

2024-07-17 21:32 UTC, edmonday requested changes

2024-07-17 21:32 UTC, edmonday commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/LinkAction/LinkAction.tsx
> +        sx={{ mt: 1, mb: 3 }}
why was this changed from gutterBottom?

2024-07-17 21:32 UTC, edmonday commented on apps/journeys-admin/src/libs/useBlockActionLinkUpdateMutation/useBlockActionLinkUpdateMutation.spec.tsx
> +        <JourneyProvider value={{ journey }}>
no longer needed since it was dropped

2024-07-17 21:32 UTC, edmonday commented on apps/journeys-admin/src/libs/useBlockActionNavigateToBlockUpdateMutation/useBlockActionNavigateToBlockUpdateMutation.spec.tsx
>            <JourneyProvider value={{ journey }}>
can drop this
```suggestion
     
```

2024-07-17 21:32 UTC, edmonday commented on apps/journeys-admin/src/libs/useBlockActionEmailUpdateMutation/useBlockActionEmailUpdateMutation.spec.tsx
> +        <JourneyProvider value={{ journey }}>
drop
```suggestion

```

2024-07-17 21:32 UTC, edmonday commented on apps/journeys-admin/src/libs/useBlockActionEmailUpdateMutation/useBlockActionEmailUpdateMutation.spec.tsx
> +        <JourneyProvider value={{ journey }}>
drop
```suggestion

```

2024-07-17 21:40 UTC, edmonday approved these changes

2024-07-17 22:28 UTC, Kneesal approved these changes

2024-07-18 01:31 UTC, edmonday approved these changes

2024-07-19 01:17 UTC, edmonday submitted a review, later dismissed

2024-07-19 04:04 UTC, edmonday approved these changes

2024-07-19 05:36 UTC, edmonday approved these changes

2024-07-22 00:02 UTC, merged