Eng 42 style
JesusFilm/core pull request #3071
Opened 2024-07-17 22:29 UTC by Kneesal

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-07-18 22:00 UTC, tataihono requested changes

2024-07-18 22:00 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardStyling/CardStyling.tsx
> +          })
this can be merged into a single function.

2024-07-18 22:00 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardStyling/CardStyling.tsx
> +import { useCommand } from '@core/journeys/ui/CommandProvider'
move up

2024-07-23 03:46 UTC, Kneesal commented
I have completed this ticket in this PR: https://github.com/JesusFilm/core/pull/3083

2024-07-23 03:46 UTC, closed without merging