feat: card properties undo part1
JesusFilm/core pull request #3083
Opened 2024-07-18 20:27 UTC by Kneesal

# Description

### Issue

card properties undo - part 1 

background media does not work and will be covered in part 2

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

2024-07-18 22:52 UTC, tataihono requested changes

2024-07-18 22:52 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardLayout/CardLayout.tsx
> +            journeyId: journey.id,
drop journey id

2024-07-18 22:52 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardStyling/CardStyling.tsx
> +            journeyId: journey.id,
drop journey id

2024-07-18 22:52 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardStyling/CardStyling.tsx
> +        async execute({ journeyId, cardBlockId: id, themeMode }) {
use one execute function

2024-07-19 01:15 UTC, tataihono requested changes

2024-07-19 01:15 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.tsx
> -        <BackgroundColor key={selectedStep?.id} />
revert

2024-07-19 01:15 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardLayout/CardLayout.tsx
>    const handleLayoutChange = async (selected: boolean): Promise<void> => {
can we change selected here to fullscreen? match the others in there name usage.

2024-07-19 01:17 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.tsx
> -        <BackgroundColor key={selectedStep?.id} />
this needs to be here, otherwise if you undo on a different card it doesn't show color state properly in drawer

2024-07-19 01:40 UTC, tataihono requested changes

2024-07-19 01:40 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardLayout/CardLayout.tsx
> +    if (cardBlock != null) {
can we change to using guard statement

if (cardBlock == null) return

2024-07-19 01:40 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardLayout/CardLayout.tsx
> +  const handleLayoutChange = async (fullscreen: boolean): Promise<void> => {
also where you see these can you change them to functions instead of arrow.

2024-07-19 01:40 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardLayout/CardLayout.tsx
> +            selectedStep
can we just pass in the things that are different. so pretty much should only need to pass in fullscreen as a value here.

2024-07-19 03:39 UTC, tataihono requested changes

2024-07-19 03:39 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardStyling/CardStyling.tsx
> +              themeMode === ThemeMode.dark ? ThemeMode.light : ThemeMode.dark
get this from the underlying block.

2024-07-22 20:37 UTC, tataihono approved these changes

2024-07-23 03:36 UTC, merged