feat: plausible embed dashboard
JesusFilm/core pull request #3088
Opened 2024-07-18 23:05 UTC by csiyang

# Description

### Issue

Replace power bi dashboard embed with plausible dashboard embed

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7609096414)

### Solution

Embed plausible dashboard

# External Changes

n/a

# Additional information

n/a

2024-07-23 21:01 UTC, levi-zustiak requested changes

2024-07-24 05:02 UTC, csiyang commented on apps/journeys-admin/src/components/PlausibleEmbedDashboard/PlausibleEmbedDashboard.tsx
> +      // Make sure to cleanup any events/references added to the last instance
Honestly, not super sure. But I added some clean up in there just to be safe.

2024-07-24 23:02 UTC, levi-zustiak requested changes

2024-07-24 23:02 UTC, levi-zustiak commented on apps/journeys-admin/src/components/PlausibleEmbedDashboard/PlausibleEmbedDashboard.tsx
> +            }}
Should this be setting show to true and the default value for show be false?

2024-07-24 23:28 UTC, levi-zustiak approved these changes

2024-07-25 00:31 UTC, merged