feat: search bar in watch home page
JesusFilm/core pull request #3094
Opened 2024-07-19 04:14 UTC by GeronimoJohn

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-07-24 05:12 UTC, GeronimoJohn commented on apps/watch/src/components/VideosPage/FilterList/FilterList.tsx
I function dumped into this file for now until we get direction with keeping this or not

2024-07-24 20:33 UTC, jianwei1 commented on apps/watch/pages/watch/videos.tsx
> +import {} from '../../__generated__/GetHomeVideos'
```suggestion
import {} from '../../__generated__/GetHomeVideos'
```

Drop?

2024-07-24 20:43 UTC, jianwei1 commented on apps/watch/src/components/VideoGrid/VideoGrid.spec.tsx
> +    it('should render correct number of videos', async () => {
```suggestion
    it('should render correct number of videos', async () => 
```

This test doesn't look like it tests for what is described in the it statement? says 'it should render correct number of videos, but just tests that title1 is on the screen

2024-07-24 20:45 UTC, jianwei1 commented on apps/watch/src/components/VideoGrid/VideoGrid.spec.tsx
> +    it('should show load more button', async () => {
```suggestion
    it('should show no more videos button', async () => {
```

Since it's actually testing for the 'No More Videos' button, is it better to change the test name?

2024-07-24 20:46 UTC, jianwei1 commented on apps/watch/src/components/VideoGrid/VideoGrid.spec.tsx
> +    it('should if its loading', () => {
```suggestion
    it('should show loading button if loading', () => {
```

NIT: change test name?

2024-07-24 21:03 UTC, jianwei1 submitted a review, later dismissed
Please make those suggested changes

2024-07-24 21:14 UTC, scottkelso commented on apps/watch/src/components/VideoContainerPage/VideoContainerPage.stories.tsx
> +        <InstantSearchTestWrapper query="" indexName="video-variants-stg">
Not a blocker but just fyi, InstantSearchTestWrapper defaults to query='' so don't need to pass this in

2024-07-24 23:04 UTC, scottkelso commented on apps/watch/src/components/VideoContainerPage/VideoContainerPage.stories.tsx
> +import { InstantSearchTestWrapper } from '@core/journeys/ui/algolia/InstantSearchWrapper'
I have updated this inconsistent file naming. Pull in latest from feature branch to fix.

2024-07-26 02:29 UTC, scottkelso requested changes
Awesome! Loads of super work here. Going to steal a few things for my PR. Just a few of comments left. Also some failing CI steps.

2024-07-26 02:29 UTC, scottkelso commented on apps/watch/src/components/VideosPage/FilterList/FilterList.tsx
> +  // biome-ignore lint/correctness/useExhaustiveDependencies: <explanation>
Is it worth adding an explanation into the biome-ignore?

2024-07-26 02:29 UTC, scottkelso commented on apps/watch/src/components/VideosPage/FilterList/FilterList.spec.tsx
> +    it('should handle audio language filter', async () => {
In this file, I'm wondering if there are better descriptions instead of `should handle audio language filter` maybe something like `should refine and update url on audio language filter`.

Also this file could do with a few blank lines between tests & consts.

2024-07-26 02:29 UTC, scottkelso commented on apps/watch/src/components/VideosPage/VideosPage.spec.tsx
> +                ]
Not a blocker but might be good to have this refactored out?

2024-07-26 02:29 UTC, scottkelso commented on apps/watch/src/components/VideosPage/VideosPage.spec.tsx
> +    ).toBeInTheDocument()
Not a blocker but ideally I would also break this component test up into multiple tests. 4x expects in one test isn't ideal.

2024-07-26 02:29 UTC, scottkelso commented on apps/watch/src/components/VideosPage/VideosPage.tsx
> +            </Stack>
To make it clear that L47-L61 should always be identical to L64-L78, should this fragment be refactored into a function within this file?

2024-07-26 02:29 UTC, scottkelso commented on apps/watch/src/libs/algolia/useAlgoliaVideos/useAlgoliaVideos.spec.ts
> +    await expect(result.current.hits).toEqual([...algoliaVideos])
This seemed weird to me - thought result should have been equal to the transformed videos, not the original ones before being transformed?

2024-07-26 02:29 UTC, scottkelso commented on apps/watch/src/libs/algolia/useAlgoliaVideos/useAlgoliaVideos.ts
> +    })) as unknown as AlgoliaVideo[]
Should our defined algolia interfaces define the shape of how we wish the transformed objects to be? I.e. should AlgoliaVideo not have id for example?

2024-07-26 04:43 UTC, scottkelso approved these changes
Looks good! :)

2024-07-29 23:45 UTC, GeronimoJohn commented
closing as theres a lot of dependency on the feature branch

2024-07-29 23:45 UTC, closed without merging