feat: create block command undo
JesusFilm/core pull request #3097
Opened 2024-07-21 23:38 UTC by Kneesal

# Description

### Issue

ability to undo a create block and step

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

2024-08-01 00:05 UTC, tataihono requested changes
i've provided feedback on the video block. but everything should be adjusted to match.

2024-08-01 00:05 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/utils/useBlockCreateCommand/useBlockCreateCommand.tsx
> +    optimisticBlock,
```suggestion
    block: optimisticBlock,
```

2024-08-01 00:05 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/utils/useBlockCreateCommand/useBlockCreateCommand.tsx
> +  optimisticBlock: TreeBlock<BlockFields>
```suggestion
  block: TreeBlock<BlockFields>
```

2024-08-01 00:05 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/utils/useBlockCreateCommand/useBlockCreateCommand.tsx
> +        void execute()
await

2024-08-01 00:05 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/utils/useBlockCreateCommand/useBlockCreateCommand.tsx
> +  execute: () => Promise<void>
don't care if promise or not.

```suggestion
  execute: () => void
```

2024-08-01 00:05 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/utils/useBlockCreateCommand/useBlockCreateCommand.tsx
> +            blockRestore: [{ ...block } as unknown as RestoredBlock]
not sure why this is needed.

2024-08-01 00:05 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewVideoButton/NewVideoButton.tsx
> +                  }
this appears everywhere. can we move this into a lib?

2024-08-01 00:05 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewVideoButton/NewVideoButton.tsx
> +      const video: TreeBlock<VideoBlock> = {
these don't need to be a treeblock.

2024-08-01 00:05 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewVideoButton/NewVideoButton.tsx
> +                fullsize: true
draw all these params from the video block defined above.

2024-08-01 00:16 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/utils/useBlockCreateCommand/useBlockCreateCommand.tsx
> +            blockRestore: [{ ...block } as unknown as RestoredBlock]
because blocks in canvas don't have x and y values as needed in restored block

2024-08-02 02:35 UTC, tataihono requested changes

2024-08-02 02:35 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewFormButton/NewFormButton.tsx
> +        __typename: 'FormBlock' as const
```suggestion
        __typename: 'FormBlock'
```

2024-08-02 02:35 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewFormButton/NewFormButton.tsx
>    async function handleClick(): Promise<void> {
can you change these functions to 
```suggestion
  function handleClick(): void {
```

2024-08-02 02:35 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewFormButton/NewFormButton.tsx
> +      void addBlock({
```suggestion
      addBlock({
```

2024-08-02 02:35 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewFormButton/NewFormButton.tsx
> +        async execute() {
```suggestion
       execute() {
```

2024-08-05 03:01 UTC, tataihono requested changes

2024-08-05 03:02 UTC, tataihono submitted a review, later dismissed

2024-08-05 03:27 UTC, tataihono approved these changes

2024-08-05 22:29 UTC, merged