feat: add undo redo for subscribe
JesusFilm/core pull request #3098
Opened 2024-07-22 01:23 UTC by edmonday

# Description

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

Allows the user to undo and redo the the following for the Subscribe block.

- Label text
- Icon
- Icon colour

2024-07-29 21:31 UTC, tataihono requested changes

2024-08-01 04:35 UTC, tataihono requested changes

2024-08-01 04:35 UTC, tataihono commented on libs/journeys/ui/src/components/SignUp/SignUp.tsx
> +                  : submitLabel !== ''
```suggestion
                  : submitLabel != null && submitLabel !== ''
```

2024-08-01 04:35 UTC, tataihono commented on libs/shared/ui/src/components/SubmitListener/SubmitListener.tsx
revert

2024-08-01 05:07 UTC, tataihono approved these changes

2024-08-03 11:06 UTC, closed without merging

2024-08-03 11:07 UTC, edmonday commented
merged into https://github.com/JesusFilm/core/pull/3089