Button component
JesusFilm/core pull request #31
Opened 2021-09-14 03:30 UTC by GeronimoJohn

https://3.basecamp.com/3105655/buckets/23904268/todolists/4127216811

2021-09-30 01:42 UTC, tataihono submitted a review, later dismissed

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Button/Button.spec.tsx
> +}
can you define this inside the describe block below

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Button/Button.spec.tsx
> +    expect(getByTestId('CheckCircleIcon')).toBeTruthy()
```suggestion
    expect(getByTestId('CheckCircleIcon')).toBeInTheDocument()
```

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Button/Button.spec.tsx
> +    expect(getByText('This is a button')).toBeTruthy()
```suggestion
    expect(getByText('This is a button')).toBeInTheDocument()
```

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Button/Button.tsx
> +          ) : null
```suggestion
          startIcon != null && (
            <Icon
              __typename="Icon"
              name={startIcon.name}
              color={startIcon.color}
              size={startIcon.size}
            />
          )
```

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Button/Button.tsx
> +          ) : null
Your code is doing three 4 null checks when you could do it in 1.

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Button/Button.tsx
> +          ) : null
```suggestion
          endIcon != null && (
            <Icon
              __typename="Icon"
              name={endIcon?.name}
              color={endIcon?.color}
              size={endIcon?.size}
            />
          )
```

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Button/Button.tsx
> +          ) : null
same here

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Button/Button.tsx
> +  loading,
this prop is not present on the API.

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Button/Button.tsx
> +  disabled
this prop is not present on the API.

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Button/buttonFields.ts
> +      __typename
I don't think you need to manually add typename here.

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Icon/Icon.tsx
> +        <CheckCircle color={color ?? undefined} sx={{ fontSize: fontSize }} />
You can shorthand the property below
```suggestion
        <CheckCircle color={color ?? undefined} sx={{ fontSize }} />
```

2021-09-30 01:42 UTC, tataihono commented on libs/shared/ui/src/libs/storybook/decorators.tsx
> +import { themes } from '../themes/'
Revert

2021-09-30 01:42 UTC, tataihono commented on libs/shared/ui/src/libs/themes/base/theme.ts
> +import { baseComponents } from './tokens/components'
Revert

2021-09-30 01:42 UTC, tataihono commented on libs/shared/ui/__generated__/globalTypes.ts
> +  dark = "dark",
Revert

2021-09-30 01:42 UTC, tataihono commented on libs/shared/ui/src/libs/themes/base/tokens/components.ts
> -          marginBottom: spacingTheme.spacing(4)
This was incorrectly removed for MuiTypography. I think you mean to add in MuiButtonGroup separately.

2021-09-30 01:42 UTC, tataihono commented on libs/shared/ui/src/libs/themes/base/themeFields/themeFields.ts
> +import { gql } from '@apollo/client'
this should be moved to libs/shared/ui/src/libs/themes/themeFields.ts

This query is not specific to base.

2021-09-30 01:42 UTC, tataihono commented on apps/journeys/src/components/blocks/Icon/Icon.spec.tsx
> +import { render } from '@testing-library/react'
This is not a block. It should be moved up into src/components.

2021-09-30 01:42 UTC, tataihono commented on libs/shared/ui/src/libs/themes/base/tokens/components.ts
> +        containedPrimary: {
can you remove all the color settings

2021-09-30 02:59 UTC, tataihono commented on apps/journeys/pages/[journeyId].tsx
> -            id
tab here removed

2021-09-30 07:39 UTC, tataihono requested changes

2021-09-30 07:39 UTC, tataihono commented on apps/journeys/src/components/blocks/Button/Button.tsx
> +  endIcon
The button needs to deal with the action property otherwise this button doesn't actually do anthing.

2021-09-30 07:39 UTC, tataihono commented on libs/shared/ui/src/libs/themes/__generated__/GetJourneys.ts
> +/* tslint:disable */
why does this query exist?

2021-09-30 07:39 UTC, tataihono commented on libs/shared/ui/src/libs/themes/themeFields.ts
> +import { gql } from '@apollo/client'
why does this file exist? There should not be a query here.

2021-10-01 01:30 UTC, storyworks commented on apps/journeys/src/components/Icon/Icon.stories.tsx
> +        p: theme.spacing(3),
You can also write `p: (theme) => theme.spacing(3)` when you don't want to `useTheme()` fyi - I don't mind using the hook here, but we should come up with a convention for when / when not to use it..

2021-10-01 01:30 UTC, storyworks commented on apps/journeys/src/components/Icon/Icon.tsx
> +  ariaHidden?: boolean
Seems like we haven't added many other accessibility props :/ so we could remove for consistency and focus on adding it in another cycle to simplify this component for now..

2021-10-01 01:30 UTC, storyworks commented on apps/journeys/src/components/blocks/Button/Button.spec.tsx
> +    )
I would expect a test `should call actionHandler on click`.

2021-10-01 01:30 UTC, storyworks commented on apps/journeys/src/components/blocks/Button/Button.spec.tsx
> +  it('should not render with the contained value', () => {
Rather than what it should not render as, maybe call it `should render ____ as the default button variant`, and same for size

2021-10-01 01:30 UTC, storyworks commented on apps/journeys/src/libs/action/actionFields.ts
> +    ... on NavigateToBlockAction {
Should also include the 
`... on NavigateAction { ... }` action type, or no need since it doesn't have any additional attributes on it like the others?

2021-10-01 01:30 UTC, storyworks commented on apps/journeys/src/libs/action/handleAction.ts
> +  switch (action?.__typename) {
This should include all 4 action types - add "LinkAction" case and "NavigateToJourneyAction" case

2021-10-01 01:30 UTC, storyworks commented on libs/shared/ui/src/libs/themes/base/tokens/components.ts
> +// Add other component override tokens here
Can probably remove this, hopefully it's more clear now that we have 2 (soon 3) examples :)

2021-10-01 01:30 UTC, storyworks commented on package.json
> +    "@mui/lab": "^5.0.0-alpha.48",
What uses mui/lab?

2021-10-01 01:39 UTC, GeronimoJohn commented on apps/journeys/src/components/Icon/Icon.stories.tsx
> +        p: theme.spacing(3),
Sounds good. I'll stick to this one for now. When we have the time let's set a convention for it

2021-10-01 01:39 UTC, GeronimoJohn commented on apps/journeys/src/libs/action/actionFields.ts
> +    ... on NavigateToBlockAction {
Yup no need for it, doesn't have any additional attributes

2021-10-01 01:40 UTC, GeronimoJohn commented on package.json
> +    "@mui/lab": "^5.0.0-alpha.48",
removed as no longer using

2021-10-01 01:42 UTC, GeronimoJohn commented on apps/journeys/src/libs/action/handleAction.ts
> +  switch (action?.__typename) {
@tataihono

2021-10-01 01:55 UTC, storyworks commented on apps/journeys/src/libs/action/handleAction.ts
> +  switch (action?.__typename) {
Since I need it for SignUp

2021-10-01 01:57 UTC, storyworks commented on libs/shared/ui/src/libs/themes/base/tokens/components.ts
> +        root: {
![image](https://user-images.githubusercontent.com/10802634/135553719-643fc238-22d3-494e-b4ac-44951ba91c2f.png)
The background color of the button onDark should be white (`primary.light`) 
![image](https://user-images.githubusercontent.com/10802634/135553789-ed3cca52-5d9f-4648-a94e-10a60efb5dfa.png)

2021-10-01 02:10 UTC, GeronimoJohn commented on apps/journeys/src/libs/action/handleAction.ts
> +  switch (action?.__typename) {
After chatting with Tatai, basically, the remaining two actions (LinkAction, NavigateToJourneyAction) are currently just a placeholder and don't do anything at this point.

2021-10-01 04:46 UTC, tataihono submitted a review, later dismissed

2021-10-01 05:08 UTC, storyworks approved these changes

2021-10-01 05:12 UTC, merged