Eng 59 dragging from node
JesusFilm/core pull request #3113
Opened 2024-07-23 03:50 UTC by Kneesal

# Description

### Issue

creating steps from dragging nodes and New Step button should have undo/redo functionality 

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

2024-07-29 22:07 UTC, tataihono requested changes

2024-07-29 22:07 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.ts
> +export const BLOCK_DELETE_WITH_STEP_UPDATE = gql`
STEP_BLOCK_DELETE

2024-07-29 22:07 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.ts
> +export const BLOCK_RESTORE_WITH_STEP_UPDATE = gql`
STEP_BLOCK_RESTORE

2024-07-29 22:07 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.ts
> +export const STEP_AND_CARD_BLOCK_CREATE_WITH_STEP_UPDATE = gql`
```suggestion
export const STEP_BLOCK_CREATE = gql`
```

2024-07-29 22:07 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
> +export const BLOCK_DELETE_WITH_BLOCK_ACTION_UPDATE = gql`
```suggestion
export const STEP_BLOCK_DELETE_FROM_ACTION = gql`
```

2024-07-29 22:07 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromSocialPreview/useCreateStepFromSocialPreview.ts
> +export const STEP_AND_CARD_BLOCK_CREATE_WITH_BLOCK_ORDER_UPDATE = gql`
STEP_BLOCK_CREATE_FROM_SOCIAL_PREVIEW

2024-07-29 22:07 UTC, tataihono commented on apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.ts
revert

2024-07-30 22:37 UTC, tataihono requested changes

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.ts
> +  sourceStepAndCoordinates: SourceBlocksAndCoordinates
```suggestion
  input: createStepInput
```

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.ts
> +      stepAndCardBlockCreateCacheUpdate(cache, data, journey?.id)
can this go down where the stepBlockCreate is used?

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
> +  }): Promise<void> {
type?

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
> +  sourceBlocksAndCoordinates: SourceBlocksAndCoordinates
```suggestion
  input: CreateStepInput
```

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
> +              if (data?.blockUpdateAction == null) return
think this should be moved down a line.

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
> +            if (data?.blockUpdateAction == null) return
this should be moved to 316.

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
> +        if (sourceBlock == null) return
this check should be done above.

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
> +        if (sourceBlock == null) return
this check should be done above

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
> +        ) {
can this check be done above?

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
> +            if (data?.blockUpdateAction == null) return
move down a line

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.ts
> +        if (sourceStep != null && stepBeforeDelete != null) {
this check can be done above.

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.ts
> +        if (sourceStep != null) {
same for this

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.ts
> +        if (sourceStep != null) {
move up

2024-07-30 22:37 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.ts
> +      stepAndCardBlockCreateCacheUpdate(cache, data, journey?.id)
can we change the name of this update to stepBlockCreateUpdate

2024-07-31 23:49 UTC, tataihono requested changes

2024-08-01 00:42 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
> +        if (sourceBlock.action == null) return
can't move out

2024-08-01 05:11 UTC, tataihono approved these changes

2024-08-02 02:55 UTC, merged