fix: closing addblock drawer action
JesusFilm/core pull request #3133
Opened 2024-07-24 23:44 UTC by DanChae03

# Description

### Issue

Closing the Addblock drawer used to switch the screen to the journeyflow view. This has now been fixed, and the screen will not switch, and the properties drawer will be brought up. Also, closing the properties drawer has been fixed to redirect to the journeyflow view ONLY on desktop - closing it on mobile now redirects to the content view.

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7586174105)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-07-25 15:26 UTC, levi-zustiak requested changes
Just a couple small comments, but looks good man! Good stuff

2024-07-25 15:26 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.spec.tsx
> -    expect(screen.getByText('activeSlide: 1')).toBeInTheDocument()
Could I have you add an assertion that `activeCanvasDetailsDrawer` is set to `AddBlock` similarly to the previous version?

2024-07-25 15:26 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.spec.tsx
>      await waitFor(() =>
There's aren't necessarily your changes, but if we can also clean some of the extra stuff that's not needed while we're here.

```suggestion
    const closeButton = screen.getByTestId('X2Icon')
    
    expect(closeButton).toBeInTheDocument()
    
    await waitFor(() => userEvent.click(closeButton))
```

2024-08-01 02:21 UTC, levi-zustiak approved these changes
Looks good 👍

2024-08-01 02:43 UTC, csiyang approved these changes

2024-08-01 03:35 UTC, merged