feat: watch strategies page
JesusFilm/core pull request #3153
Opened 2024-07-30 00:15 UTC by jianwei1

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213804/todolists/7585485978)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-08-02 03:42 UTC, scottkelso requested changes
Really good work! Just a few naming things to sort.

2024-08-02 03:42 UTC, scottkelso commented on apps/watch/pages/strategies/index.tsx
> +    <InstantSearchSSRProvider {...serverState}>
Could you try adding some text into the input, the `query=love` or whatever your search is should appear. Then Change that `love` to `loved` in the url and submit. Does it persist? If not, might want to sort that. Could probably do in separate PR. Solution might be similar to mine where we ignore the server state here.

2024-08-02 03:42 UTC, scottkelso commented on apps/watch/src/components/StrategiesView/StrategiesView.spec.tsx
> +import { render, screen } from '@testing-library/react'
Great job on this spec file!

2024-08-02 03:42 UTC, scottkelso commented on apps/watch/src/components/StrategySections/StrategySections.tsx
> +  // TODO: update this indexes variable to use the real indexes
Could you remove this comment?

2024-08-02 03:42 UTC, scottkelso commented on apps/watch/src/components/StrategySections/StrategySections.tsx
> +  const indexes = ['wp_dev_posts_passionpurpose']
Is it possible to add the `wp_dev_posts_mission-trip` into this array? And reference the first one by `indexes[0]` instead? Makes it clearer that there is 2x indexes being used here instead of 1? Then loop through the rest of the indexes using `.shift()` or `.splice(1)`?

2024-08-02 03:42 UTC, scottkelso commented on apps/watch/src/components/StrategySections/StrategySections.tsx
> +    const hasTrueValue = Array.from(resultsMap.values()).some(
`isAnyResults` any better?

2024-08-02 03:42 UTC, scottkelso commented on libs/journeys/ui/src/components/SearchBar/SearchBar.stories.tsx
> +  }
Now that we have got MSW working, we should probably mock all algolia calls in stories, right?

2024-08-02 03:54 UTC, jianwei1 commented on apps/watch/src/components/StrategySections/StrategySections.tsx
> +  // TODO: update this indexes variable to use the real indexes
Leaving this for now as @GeronimoJohn asked me to keep it in

2024-08-05 00:47 UTC, jianwei1 commented on apps/watch/pages/strategies/index.tsx
> +    <InstantSearchSSRProvider {...serverState}>
Will address in separate PR: https://3.basecamp.com/3105655/buckets/38213804/todos/7672021287

2024-08-05 02:08 UTC, scottkelso approved these changes
LGTM!

2024-08-06 04:19 UTC, merged