feat: add optimistic responses to block deletes
JesusFilm/core pull request #3173
Opened 2024-07-31 23:05 UTC by Kneesal

# Description

### Issue

block delete is now blazingly fast with the implementation of block deletes

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

2024-07-31 23:47 UTC, tataihono requested changes
got some failing tests that need to be addressed.

2024-08-01 05:12 UTC, tataihono approved these changes

2024-08-02 03:53 UTC, edmonday commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/ImageOptions.tsx
> +        onChange={async (input) => updateImageBlock(input)}
```suggestion
        onChange={(input) => updateImageBlock(input)}
```

2024-08-02 03:53 UTC, edmonday commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.tsx
> +      onChange={async (input) => handleChange(input)}
```suggestion
      onChange={(input) => handleChange(input)}
```

2024-08-02 03:53 UTC, edmonday commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.tsx
> +          onDelete={async () => deleteImageBlock()}
```suggestion
          onChange={(input) => handleChange(input)}
          onDelete={() => deleteImageBlock()}
```

2024-08-02 04:18 UTC, edmonday approved these changes

2024-08-04 22:56 UTC, tataihono submitted a review, later dismissed

2024-08-04 23:49 UTC, tataihono approved these changes

2024-08-05 00:11 UTC, tataihono submitted a review, later dismissed

2024-08-05 01:03 UTC, tataihono approved these changes

2024-08-05 01:17 UTC, merged