feat: duplicate block command undo and redo
JesusFilm/core pull request #3200
Opened 2024-08-06 22:51 UTC by Kneesal

# Description

### Issue

a custom hook the allows the undo/redo of a duplicate step and block

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

2024-08-06 23:16 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.tsx
> +    if (parentOrder == null) return
moving this above does not infer the type properly

2024-08-07 01:30 UTC, tataihono requested changes

2024-08-07 01:30 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/utils/useBlockDuplicateCommand/useBlockDuplicateCommand.tsx
> +      },
```suggestion
      execute,
```

2024-08-07 01:30 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/DuplicateStep/DuplicateStep.tsx
> +    const stepChildren = flatten(step.children)?.map((block) => {
```suggestion
    const stepDescendants = flatten(step.children)?.map((block) => {
```

2024-08-07 01:30 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/utils/useBlockDuplicateCommand/useBlockDuplicateCommand.tsx
> +          optimisticResponse: { blockDelete: [] }
not the right response.

2024-08-07 01:30 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/utils/useBlockDuplicateCommand/useBlockDuplicateCommand.tsx
> +            blockRestore: [block as BlockRestore]
not the right response.

2024-08-07 03:39 UTC, tataihono requested changes

2024-08-07 03:39 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/utils/useBlockDuplicateCommand/useBlockDuplicateCommand.tsx
> +    if (selectedStep == null || journey == null || steps == null) return
do you even need journey in this?

2024-08-07 03:43 UTC, tataihono approved these changes

2024-08-07 04:55 UTC, merged