fix: editor mobile swipe
JesusFilm/core pull request #3247
Opened 2024-08-12 16:12 UTC by levi-zustiak

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-08-12 19:33 UTC, tataihono requested changes

2024-08-12 19:33 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
> +        showAnalytics === false || showAnalytics == null
```suggestion
      swiperRef.current.swiper.allowTouchMove =
        showAnalytics != true
```

2024-08-12 20:48 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
> +        showAnalytics === false || showAnalytics == null
@tataihono The `eqeqeq` lint rule prevents this comparison, and then we have the lint rule for explicitly handling nullish cases

2024-08-12 20:54 UTC, levi-zustiak commented
@tataihono could we add `showAnalytics` to the default editor state so we don't have to handle the nullish case going forward, or is there justification for keeping it as is?

2024-08-13 07:48 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
> +        showAnalytics === false || showAnalytics == null
sorry it should be showAnalytics !== true.

2024-08-13 20:29 UTC, tataihono approved these changes

2024-08-13 20:41 UTC, merged