fix: add language field
JesusFilm/core pull request #3250
Opened 2024-08-12 23:37 UTC by zwsaqx

# Description
ignore this pull request I messed up the commits and merge. just work on the new one:
https://github.com/JesusFilm/core/pull/3442
the toolbar should display and allow editing of the language directly
### Issue

it currently doesnt

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7668412584)

### Solution

add language field

2024-08-13 03:49 UTC, Kneesal requested changes

2024-08-13 03:49 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
> +                      {' '}
```suggestion
                      
```

2024-08-13 03:49 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
> +                      }{' '}
```suggestion
                      }
```

2024-08-13 03:49 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
> +                          ?.value
```suggestion
                       ` ${journey.language.name?.find(({ primary }) => primary)
                          ?.value}`
```

2024-08-13 03:49 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
> +                          ?.value
can you also extract this value out into a variable above
name it  `journeyLanguage`

2024-08-13 03:49 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
> +                    fontWeight: 'normal'
is this needed?

2024-08-13 03:49 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
> +                  <Box sx={{ display: 'flex', alignItems: 'center' }}>
```suggestion
                  <Stack sx={{  alignItems: 'center' }}>
```

2024-08-13 03:49 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
> +                          ?.value
You can also move the dot inside the template literals

2024-08-13 03:49 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
>              </Box>
on line 276, can you only render the title description dialog when dialogOpen is true, otherwise - it will run the getLanguages query on page load every single time
```  
          {dialogOpen && (
              <TitleDescriptionDialog
                open={dialogOpen}
                onClose={handleDialogClose}
              />
            )}
```

2024-08-19 22:53 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Toolbar/TitleDescriptionDialog/TitleDescriptionDialog.tsx
> +import { LanguageAutocomplete } from '@core/shared/ui/LanguageAutocomplete/LanguageAutocomplete'
```suggestion
import { LanguageAutocomplete } from '@core/shared/ui/LanguageAutocomplete'
```

2024-08-19 22:53 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Toolbar/TitleDescriptionDialog/TitleDescriptionDialog.tsx
> +          }
optimistic response in line 50 should return the correct language as opposed to the old language

2024-08-19 22:53 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
> +                  <Box sx={{ alignItems: 'center' }}>
```suggestion
                  <Stack sx={{ alignItems: 'center' }}>
```

2024-09-25 03:39 UTC, closed without merging

2024-09-25 03:40 UTC, edmonday commented
addressed in https://github.com/JesusFilm/core/pull/3559