feat: add a new variant to custom accordion
JesusFilm/core pull request #3285
Opened 2024-08-21 02:46 UTC by levi-zustiak

# Description

### Issue
Needed an additional variant in the `Accordion` component

[Link to Linear Issue](https://linear.app/jesus-film-project/issue/ENG-622/add-a-new-variant-to-custom-drawer-accordion)

### Solution
Add a new variant to `Accordion` component

# External Changes

# Additional information

2024-08-21 05:10 UTC, csiyang requested changes

2024-08-21 05:10 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioOption/RadioOption.tsx
> -        testId="RadioOption"
Do we need this removed?

2024-08-21 05:10 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.tsx
> +} & (StaticLabelProps | DynamicLabelProps)
Having this kind of variants is a little over engineered for this change I think lol. Do you think we can just make `value` an optional prop, and show the visual differences based off its shown or not?

Can we also add a unit test for this too?

2024-08-21 05:17 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioOption/RadioOption.tsx
> -        testId="RadioOption"
The `testId` prop wasn't used in the component. A `testId` is generated using the `id` prop

2024-08-21 05:28 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.tsx
> +} & (StaticLabelProps | DynamicLabelProps)
Yeah we could use the value prop, but I like this version for the explicit definition so it's harder to misuse and a little more concise on what's expected. If you still think it's overboard I can go ahead and switch implementations 👍

2024-08-21 20:42 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.tsx
> +} & (StaticLabelProps | DynamicLabelProps)
@levi-zustiak Yeah lets switch to using the value prop

2024-08-21 22:07 UTC, csiyang requested changes

2024-08-21 22:07 UTC, csiyang commented on apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.spec.ts
> +          videoId: 'videoId',
what are these changes??

2024-08-21 22:07 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.tsx
> +            {value === undefined ? (
```suggestion
            {value != undefined ? (
```

2024-08-21 22:19 UTC, levi-zustiak commented on apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.spec.ts
> +          videoId: 'videoId',
Broken test from a PR that was merge just a little while ago. Just fixed it so the ci/cd passes

2024-08-22 20:31 UTC, csiyang approved these changes

2024-08-23 19:05 UTC, merged