fix: card delete resetting flow
JesusFilm/core pull request #3298
Opened 2024-08-22 03:37 UTC by csiyang

# Description

### Issue

When deleting a card, journey flow gets reset

### Solution

Flow is calculated using the a `step blocks` query a well as `steps` from use editor. A [recent change](https://github.com/JesusFilm/core/pull/3241) caused `steps` to be updated in later render cycle to `step blocks`, this slight mismatch of step data was causing the flow to get reset.

The fix adds a check for `steps` and `step blocks` to be in sync (have the same length) before calculating if a flow reset is needed.

2024-08-22 03:40 UTC, tataihono submitted a review, later dismissed

2024-08-22 03:44 UTC, tataihono requested changes

2024-08-22 03:44 UTC, tataihono commented on apps/api-journeys/src/app/__generated__/graphql.ts
revert

2024-08-22 03:46 UTC, tataihono submitted a review, later dismissed

2024-08-22 22:17 UTC, tataihono approved these changes

2024-08-26 02:48 UTC, tataihono submitted a review, later dismissed

2024-08-26 03:30 UTC, Kneesal approved these changes

2024-08-26 22:32 UTC, merged