feat: api videos authentication
JesusFilm/core pull request #3316
Opened 2024-08-27 00:36 UTC by mikeallisonJS

# Description

### Issue

videos admin frontend needs specific authentication.

### Solution

Add authentication & query to api-videos

2024-08-27 20:08 UTC, tataihono requested changes

2024-08-27 20:08 UTC, tataihono commented on apps/api-videos/db/schema.prisma
> +}
```suggestion
model VideoUserRole {
  id     String               @id @default(uuid())
  userId String               @unique
  roles  VideoRole[]
}
```

2024-08-27 20:08 UTC, tataihono commented on apps/api-videos/db/schema.prisma
> +}
lets start simple. Everyone can manage everything for now.

```suggestion
enum VideoRole {
  publisher
}
```

2024-08-27 20:08 UTC, tataihono commented on apps/api-videos/db/schema.prisma
> +}
more in line with the journeys labelling of this table.

2024-08-27 20:08 UTC, tataihono commented on apps/api-videos/src/schema/video/video.ts
>    })
can we break this out into a user file and just extend the user object out? that way the me call could be:
```
me {
  id
  videoUserRoles {
    id
    roles
  }
}

2024-08-27 20:08 UTC, tataihono commented on apps/api-videos/src/yoga.ts
> +          : null,
```suggestion
      currentRoles:
        currentUser != null
          ? await prisma.videoAdminUser.findUnique({
              where: { userId: currentUser.id }
            })?.roles
          : null,
```

2024-08-27 20:08 UTC, tataihono commented on libs/yoga/jest.config.ts
> +  displayName: 'nest-decorators',
```suggestion
  displayName: 'yoga',
```

2024-08-27 20:08 UTC, tataihono commented on libs/yoga/README.md
> +Run `nx test nest-decorators` to execute the unit tests via [Jest](https://jestjs.io).
```suggestion
Run `nx test yoga` to execute the unit tests via [Jest](https://jestjs.io).
```

2024-08-27 20:08 UTC, tataihono commented on libs/yoga/README.md
> +# nest-decorators
```suggestion
# yoga
```

2024-08-27 20:08 UTC, tataihono commented on libs/yoga/project.json
> +        "jestConfig": "libs/nest/decorators/jest.config.ts"
```suggestion
        "jestConfig": "libs/yoga/jest.config.ts"
```

2024-08-27 20:08 UTC, tataihono commented on libs/yoga/project.json
> +        "command": "codecov -f coverage/libs/yoga/cobertura-coverage.xml -F libs.nest.decorators"
```suggestion
        "command": "codecov -f coverage/libs/yoga/cobertura-coverage.xml -F libs.yoga"
```

2024-09-04 00:51 UTC, tataihono requested changes

2024-09-04 00:53 UTC, mikeallisonJS commented on apps/api-media/src/workers/algolia/service/service.ts
> +    const { data } = await apollo.query<{
fixed with multi-schema

2024-09-04 00:54 UTC, mikeallisonJS commented on apps/api-media/src/workers/bigQuery/importers/languageSlugs/languageSlugs.ts
> +  }>({
fixed by multi-schema

2024-09-04 01:33 UTC, tataihono requested changes

2024-09-04 01:33 UTC, tataihono commented on apps/api-media/src/schema/user/index.ts
> +import './user'
```suggestion
import './enums'
import './user'
```

2024-09-04 01:33 UTC, tataihono commented on apps/api-media/src/schema/user/user.ts
> +          )?.roles ?? []
can we do a find or create here?

2024-09-04 01:40 UTC, mikeallisonJS commented on apps/api-media/src/schema/user/user.ts
> +          )?.roles ?? []
will implement later if needed

2024-09-04 01:41 UTC, tataihono approved these changes

2024-09-04 01:53 UTC, merged