feat: reactions settings
JesusFilm/core pull request #3320
Opened 2024-08-27 16:18 UTC by levi-zustiak

# Description

### Issue
Add `Reactions` to the `Journey Appearance` drawer

### Changes
- Added `ReactionOption` component, tests, and stories
- Added `Reactions` component, tests, and stories
- Added `Reactions` to `Footer`
- Conditionally render footer buttons based on journey properties

2024-08-27 22:01 UTC, csiyang requested changes

2024-08-27 22:01 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Toolbar/TitleDescriptionDialog/TitleDescriptionDialog.tsx
> +            showDislikeButton: true
Hmm I think we should have a better way of writing out this optimisticResponse. We don't want to get stuck having to remember making these retroactive changes... I'll try a few things on my PR on my PR too to see if I can come up with something

2024-08-27 23:30 UTC, csiyang requested changes

2024-08-27 23:30 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Reactions/Reactions.tsx
> +              tags: [],
For https://github.com/JesusFilm/core/pull/3320/files#r1733573451
```suggestion
              ...journey,
```

2024-08-28 18:54 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Reactions/ReactionOption/ReactionOption.tsx
> +    toggle({ [field]: !active } as unknown as UpdateReactionInput)
I couldn't get this to work properly yesterday. Not sure what I changed but it's being typed correctly now lol

2024-08-28 22:27 UTC, csiyang approved these changes

2024-08-30 00:52 UTC, merged