feat: website mode api
JesusFilm/core pull request #3339
Opened 2024-08-29 03:33 UTC by csiyang

# Description

### Issue

New / updated backend to support stepheader and stepfooter for website mode

2024-08-29 07:39 UTC, tataihono requested changes

2024-08-29 07:39 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.graphql
> +  showReactions: Boolean
```suggestion
  showReactionButtons: Boolean
```

2024-08-29 21:52 UTC, levi-zustiak requested changes

2024-08-29 21:59 UTC, csiyang commented on apps/api-gateway/schema.graphql
> +  globe01 @join__enumValue(graph: JOURNEYS)
ahh yes you're right, i'll change this

2024-08-29 22:00 UTC, csiyang commented on apps/api-gateway/schema.graphql
> +  scale: Int
Do we need the accuracy of a float? We've generally defaulted to using ints.

2024-08-29 22:09 UTC, levi-zustiak commented on apps/api-gateway/schema.graphql
> +  scale: Int
In my mind it's easier to store the scale value as a float if we're using the slider without any step values. Seems like there could be more calculations we have to perform to scale the value using an int. but it sounds like you already may have a general process

2024-08-29 22:32 UTC, csiyang commented on apps/api-gateway/schema.graphql
> +  scale: Int
We'll keep it as int, the mui slider uses ints from 0-100 by default too.

2024-09-02 00:21 UTC, csiyang commented on apps/api-journeys/db/schema.prisma
> +  slug                    String?              @unique
@tataihono I think this makes the field unique across the whole table right? Any ideas on how we could apply this per journey?

2024-09-02 00:41 UTC, tataihono commented on apps/api-journeys/db/schema.prisma
> +  slug                    String?              @unique
drop this @unique req and put this further down
```
  @@unique([slug, journeyId])
```

2024-09-02 03:23 UTC, tataihono approved these changes

2024-09-02 04:35 UTC, merged