feat: add slug edit
JesusFilm/core pull request #3378
Opened 2024-09-04 23:20 UTC by csiyang

# Description

Edit slug for a step

Dependant on https://github.com/JesusFilm/core/pull/3368

2024-09-05 01:57 UTC, levi-zustiak submitted a review, later dismissed

2024-09-05 21:44 UTC, levi-zustiak approved these changes

2024-09-16 23:05 UTC, csiyang commented
Design is unhappy with the UX of the slug edit, closing until there is a solid design

2024-09-16 23:05 UTC, closed without merging

2025-11-18 02:52 UTC, edmonday requested changes

2025-11-18 02:52 UTC, edmonday commented on apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CardSlugEdit/CardSlugEdit.tsx
> +    }
could combine these

2025-11-18 02:52 UTC, edmonday commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.spec.tsx
> +  BlockFields_StepBlock as StepBlock,
this is kinda random to import out of nowhere?

2025-11-18 02:52 UTC, edmonday commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.spec.tsx
> +import { GetJourney_journey as Journey } from '../../../../../../../../../__generated__/GetJourney'
same with this