feat: algolia search in video library
JesusFilm/core pull request #3444
Opened 2024-09-10 04:37 UTC by GeronimoJohn

Convert the Video Library to be using `Algolia` data instead of `Core` data

2024-09-10 21:23 UTC, scottkelso requested changes
I haven't manually tested this as I'm not sure exactly where this is in the NSA app. Will do this on re-review. Have added some comments re code.

2024-09-10 21:23 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/Source.spec.tsx
> +      status: 'idle'
Same as before

2024-09-10 21:23 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
> +  }
Is there a reason we can't reuse our `useAlgoliaVideos` hook instead of repeating logic?

2024-09-10 21:23 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
> +  function transformItems(items): VideoListProps['videos'] {
As per the pattern we have established for useAlgoliaVideos, we should refactor this out and unit test it.

2024-09-10 21:23 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.handlers.ts
> +      '21753',
This feels like repeated code from `useAlgoliaVideos/data.ts`. Maybe we should consider refactoring some of this data into `journeys-ui/algolia` folder.

2024-09-10 21:23 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.spec.tsx
> +      hits: [
Same as above

2024-09-10 21:23 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoSearch/VideoSearch.tsx
> +  const { refine } = useSearchBox()
Thinking about the open-closed principle here. Would it be better/possible to pass the `refine` from `useSearchBox()` in using the `onChange` prop?

2024-09-17 22:04 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.handlers.ts
> +      '21753',
Will wait for Language Filter PR to go in before applying this

2024-09-17 22:05 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
> +  }
Can! Applying the above

2024-09-20 10:37 UTC, GeronimoJohn commented on apps/journeys-admin/pages/journeys/[journeyId].tsx
> +  process.env.NEXT_PUBLIC_ALGOLIA_API_KEY ?? ''
We shouldn't need to as we're not server side rendering

2024-09-20 10:38 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
> +  }
This PR was made before we had useAlgoliaVideos in prod I think. But will see if I can just reuse it and apply it here

2024-09-20 10:47 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.handlers.ts
> +      '21753',
Agreed with the comment above but we should create a separate ticket for it? Thoughts?

2024-09-20 10:49 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
> +  function transformItems(items): VideoListProps['videos'] {
Agreed with the comment above but we should create a separate ticket for it? Thoughts?

2024-09-20 10:49 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
> +  }
Same comment on useAlgoliaVideos

2024-09-23 03:42 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
> +  function transformItems(items): VideoListProps['videos'] {
Will do this instead

2024-09-23 03:54 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
> +  }
We're not able to move out `useAlgoliaVideos` from watch to the shared libs folder. The hook requires types that is not defined in any of our shared library and would require a lot of refactor in order to generate required types

2024-09-23 22:01 UTC, scottkelso submitted a review, later dismissed
This is a great feature! Good job. I've left a few comments mostly suggesting refactors for code readability and cleanliness. 

Some comments are related to the question of refactoring useAlgoliaVideos into shared space. We are straying towards two different implementations of useAlgoliaVideos. It feels in theory like it would be better to have just one but might need more thought. Will have a think myself today.

2024-09-23 23:00 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.handlers.ts
> +      '184497',
This goes back to the conversation of refactoring out useAlgoliaVideos to the shared library.

2024-09-23 23:04 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/utils/useAlgoliaLocalVideos/useAlgoliaLocalVideos.spec.tsx
> +      title: 'Video 2',
I don't think this will be reused in other places? The function `transformItems` will only be called in the hook and pattern we set in `useAlgoliaStrategies` and `useAlgoliaVideos` seems to contain this data in the spec file

2024-09-23 23:07 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/utils/useAlgoliaLocalVideos/useAlgoliaLocalVideos.ts
> +    showMore
Will handle metrics when asked and in a different ticket. No results is handled differently in NSA, it's based if videos has values or not. The component that is rendering the list is used by different providers - Algolia and YouTube

2024-09-23 23:08 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/utils/useAlgoliaLocalVideos/useAlgoliaLocalVideos.ts
> +export function useAlgoliaLocalVideos({
Local refers to the name of the component where this is being used. In NSA we refer to Core Videos as LocalVideos. Other video options that we have are YouTube and Cloudflare

2024-09-23 23:08 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
> +  const [searchQuery, setSearchQuery] = useState<string>('')
Good point! Will implement using query from searchbox instead

2024-09-23 23:21 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.spec.tsx
>            primaryLanguageId: '529',
Just getting an understanding for the comment above. Is it for readability or reusability or both or some other thing? 

If readability that makes sense to me. Though one can argue that we are to do this for all our test cases as this pattern is repeated a lot. Which would prompt a further discussion on testing practices with the overall dev team

If reusability - makes sense, though can be a bit complicated as the mock here is tied to the component. Meaning the graphql call was defined in the component, doesn't come from a reusable graphql query hook. If I were to move this out to a data file, it will not really be reusable as tied to the component?

Though either way, will tackle this in a different ticket!

2024-09-24 00:17 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.spec.tsx
>            primaryLanguageId: '529',
Both. Clean code practises/engineering principles and standard NextJS patterns suggest this is a good pattern for a number of reasons, main ones being 'Separation of Concerns', 'Reusability' and 'Maintainability'.

I understand this is a codebase wide issue but we are doing it in alot of places and already use this pattern of `data.ts` in stories tests https://docs.core.jesusfilm.org/docs/basics/frontend/storybook/#basic-story-structure

Yeap, something to keep in mind for the future!

2024-09-24 00:26 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/utils/useAlgoliaLocalVideos/useAlgoliaLocalVideos.spec.tsx
> +      title: 'Video 2',
I feel like I've reused objects like this from data.ts files before. The way this is written now is closed and does not allow reusability, even if you don't currently forsee any useful reusability. Always try an write all code as modular and open as possible. So there is always a case for reuseability, but also don't forget maintainability and separation of concerns. Again, not a blocker but my recommendation here for wider consideration is that is not a clean coding pattern that should be followed. Ask me about this in person and I can explain where I think this style has emerged from.

2024-09-25 21:36 UTC, scottkelso commented on apps/journeys-admin/pages/journeys/[journeyId].tsx
> +
Can you use the new <InstantSearchProvider/> from @journeys/ui? See `apps/watch/pages/watch/index.tsx` for an example.

2024-09-25 21:48 UTC, scottkelso commented on apps/watch/src/components/VideoCard/VideoCard.spec.tsx
> +jest.mock('@core/journeys/ui/algolia/useAlgoliaVideos')
You should be able to drop this if I am remembering correctly

2024-09-25 21:48 UTC, scottkelso commented on apps/watch/src/components/VideoCarousel/VideoCarousel.spec.tsx
> +jest.mock('@core/journeys/ui/algolia/useAlgoliaVideos')
Same here

2024-09-25 23:06 UTC, GeronimoJohn commented on apps/watch/src/components/VideoCard/VideoCard.spec.tsx
> +jest.mock('@core/journeys/ui/algolia/useAlgoliaVideos')
Since the component is calling `useAlgoliaVideos` - it still requires us to mock the state of it

2024-09-25 23:18 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/utils/useAlgoliaLocalVideos/useAlgoliaLocalVideos.spec.tsx
> +      title: 'Video 2',
Have moved to it's own file

2024-09-26 00:51 UTC, scottkelso submitted a review, later dismissed
Awesome refactor!

2024-09-26 21:06 UTC, scottkelso approved these changes
Nice! Much cleaner!

2024-10-01 21:07 UTC, merged