feat: menu edit
JesusFilm/core pull request #3455
Opened 2024-09-11 01:29 UTC by levi-zustiak

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-09-11 21:08 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Menu/MenuActionButton/useMenuBlockCreateMutation/useMenuBlockCreateMutation.ts
> +      // },
@csiyang I was having issues with the `menuStepBlock` being cached on the journey, am I supposed to manually update the field as well?

2024-09-11 22:37 UTC, csiyang requested changes

2024-09-11 22:37 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Menu/MenuIconSelect/MenuIconSelect.tsx
> +      iconUpdate(null)
Add a test for removing the icon (+ undo action)

2024-09-11 22:37 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Menu/MenuActionButton/MenuActionButton.tsx
> +          // MENU-TODO: set selected block here
Remove comment
```suggestion
```

2024-09-11 22:37 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Menu/MenuActionButton/useMenuBlockCreateMutation/useMenuBlockCreateMutation.ts
> +      }
This should fix your cache problem. Returning the id is how the cache identifies which record to update. Can you also add this to your other hooks?
```suggestion
    journeyUpdate(id: $journeyId, input: $journeyUpdateInput) {
      id
      menuStepBlock {
        ...StepFields
      }
```

2024-09-11 22:37 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Menu/MenuActionButton/useMenuBlockCreateMutation/useMenuBlockCreateMutation.ts
> +export function useMenuBlockCreateMutation(
The hooks also all need tests

2024-09-11 22:37 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Menu/MenuActionButton/MenuActionButton.tsx
> +  const { add } = useCommand()
Not sure if you've already tried this, but is it possible to use the existing command `add` and `delete`? It should save on some complexity you have to do for the undo/redo
```suggestion
const { addBlock } = useBlockCreateCommand()
const { addBlockDelete } = useBlockDeleteCommand()
```

2024-09-11 22:37 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Menu/MenuActionButton/useMenuBlockDeleteMutation/useMenuBlockDeleteMutation.ts
> +    }
This is not necessary, when a block is deleted, all its children are deleted too. 
```suggestion
```

2024-09-11 22:44 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Menu/MenuActionButton/useMenuBlockCreateMutation/useMenuBlockCreateMutation.ts
> +export function useMenuBlockCreateMutation(
Is that because that's where the muation hooks go or to be reused later? I'm not sure if they would be used elsewhere

2024-09-12 01:55 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Menu/MenuActionButton/MenuActionButton.tsx
> +  const { add } = useCommand()
You might be able to do this if you need to do custom redo/undo mutations though

2024-09-12 06:24 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Menu/MenuActionButton/useMenuBlockCreateMutation/useMenuBlockCreateMutation.ts
> +export function useMenuBlockCreateMutation(
I think its just generally where we store our hooks. Since its already a hook it can be reused, so it would be easier to keep track of as well in the future.

2024-09-13 02:10 UTC, merged