feat: logo edit
JesusFilm/core pull request #3469
Opened 2024-09-12 06:04 UTC by csiyang

# Description

Edit logo for website mode

2024-09-12 06:17 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Logo/Logo.tsx
> +export function Logo(): ReactElement {
Logo Edit

2024-09-12 06:17 UTC, csiyang commented on libs/shared/ui/src/components/icons/Diamond.tsx
> +export default createSvgIcon(
new icon

2024-09-12 06:17 UTC, csiyang commented on libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
> +    logoImageBlock {
new `logoImageBlock` field for journey

2024-09-12 06:17 UTC, csiyang commented on libs/journeys/ui/src/components/Image/imageFields.ts
> +    scale
new `scale` field for imageBlocks

2024-09-12 06:17 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/CustomImage/CustomImage.tsx
> +  selectedBlock?: ImageBlock | null
Had to add a few of these to satisfy some types, should have no real impact on the app since all our checks are nullish checks

2024-09-12 20:01 UTC, levi-zustiak requested changes

2024-09-12 20:01 UTC, levi-zustiak commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Logo/Logo.tsx
> +export function Logo(): ReactElement {
Looks like the foreign key for the logo doesn't get updated when removing the logo. It still technically works since the block itself is soft deleted, but it's probably better to update it regardless.

2024-09-12 21:12 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Logo/Logo.tsx
> +export function Logo(): ReactElement {
No thats not quite whats happening. The only thing here that actually deletes it is the `undo` action that happens after the initial create. Everything else is just updating the src field of the imageBlock, so the existing reference is accurate.

Although its not the cleanest way, its a lot more simple to do it this way.

2024-09-12 22:05 UTC, levi-zustiak submitted a review, later dismissed

2024-09-13 03:26 UTC, levi-zustiak approved these changes

2024-09-13 04:43 UTC, merged