feat: step header button
JesusFilm/core pull request #3470
Opened 2024-09-12 19:23 UTC by levi-zustiak

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-09-13 00:24 UTC, csiyang requested changes

2024-09-13 00:24 UTC, csiyang commented on libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
> +            px: { xs: 4, lg: 0 },
I ended up using 3 here to make sure the logo alignment was correct, will this work for you too?
```suggestion
            px: { xs: 3, lg: 0 },
```

2024-09-13 00:24 UTC, csiyang commented on libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
> +            <StepHeaderMenu />
Remove comment and space
```suggestion
            <StepHeaderMenu />
```

2024-09-13 00:24 UTC, csiyang commented on libs/journeys/ui/src/components/StepHeader/StepHeaderMenu/StepHeaderMenu.tsx
> +  const blocks = transformer(journey?.blocks ?? [])
any reason we need to look through all the blocks. We can just use `journey.menuStepBlock`?

2024-09-13 00:32 UTC, levi-zustiak commented on libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
> +            px: { xs: 4, lg: 0 },
Yeah, I don't see any issues with that

2024-09-13 01:15 UTC, csiyang requested changes

2024-09-13 01:15 UTC, csiyang commented on libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
> +            px: { xs: 4, lg: 0 },
Great, can you make this change then?

2024-09-13 01:15 UTC, csiyang commented on libs/journeys/ui/src/components/StepHeader/StepHeaderMenu/StepHeaderMenu.tsx
> +        opacity: menuButtonIcon == null ? 0.6 : 1
To match the other placeholder buttons
```suggestion
        opacity: menuButtonIcon == null ? 0.5 : 1
```

2024-09-13 01:18 UTC, levi-zustiak commented on libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
> +            px: { xs: 4, lg: 0 },
Yeah I forgot to add it.. my bad haha

2024-09-13 01:25 UTC, csiyang approved these changes

2024-09-13 02:13 UTC, csiyang submitted a review, later dismissed

2024-09-17 21:52 UTC, csiyang approved these changes

2024-09-17 22:11 UTC, merged