chore: self-closing eslint rule
JesusFilm/core pull request #351
Opened 2022-03-14 21:00 UTC by mikeallisonJS

# Description

Adds a rule for self-closing html & jsx tags. Additionally adds react rules to libraries and cleans up a few resulting errors.

# How should this PR be QA Tested?

These changes are a test

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-03-14 21:25 UTC, storyworks submitted a review, later dismissed

2022-03-20 22:14 UTC, tataihono commented on libs/journeys/ui/.eslintrc.json
> +    "next/core-web-vitals"
this shouldn't have next dependencies as it is just a react project.

2022-03-20 22:17 UTC, tataihono requested changes
not entirely sure if next and next-vitals should be included in react projects. Thoughts?

2022-03-21 19:49 UTC, mikeallisonJS commented on libs/journeys/ui/.eslintrc.json
> +    "next/core-web-vitals"
It has at least one next dependency in Image (maybe more, not sure). I'm happy to swap it (your call). Going to swap shared-ui though, since it is only react

2022-03-22 00:34 UTC, tataihono approved these changes

2022-03-22 00:51 UTC, merged