Signup component UI
JesusFilm/core pull request #36
Opened 2021-09-16 05:29 UTC by storyworks

2021-10-01 00:24 UTC, storyworks commented on apps/journeys/src/components/Conductor/Conductor.stories.tsx
>            nextBlockId: 'step2.id',
This file should be overwritten when John puts his changes in..

2021-10-01 00:31 UTC, storyworks commented on apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.tsx
> +    <div data-testid="RadioQuestionCard">
This will also be overwritten by Johns changes - needed to update in my branch so Conductor story wouldn't break. I'm also using Conductor in SignUp story.

2021-10-01 00:31 UTC, storyworks commented on apps/journeys/src/components/blocks/SignUp/SignUp.tsx
> +        switch (action?.__typename) {
onSubmit doesn't fire if there are validation errors, since we're assuming all valid input will return a correct response - we can fire actions right after submitting form values. Will move this to triggering after signup response is returned once we handle server errors / return successful responses.

If I add it there right now, we're not able to see it working in Storybook (see comments in that file)

2021-10-01 00:31 UTC, storyworks commented on apps/journeys/src/components/blocks/SignUp/SignUp.stories.tsx
> +  <MockedProvider>
Adding a custom mock here like in the test file doesn't work because we can't mock `uuid` :(

2021-10-01 00:53 UTC, storyworks commented on apps/journeys/src/components/Conductor/Conductor.stories.tsx
>            nextBlockId: 'step2.id',
Conductor container also needs to be fixed so we can fully see the shadows on cards
![image](https://user-images.githubusercontent.com/10802634/135549540-76d20f00-7f4e-4990-aa64-a74ef0ca7eaf.png)

2021-10-04 02:54 UTC, tataihono requested changes
just one removal here

2021-10-04 02:54 UTC, tataihono commented on apps/journeys/src/libs/action/handleAction.ts
> +      break
remove this.

2021-10-04 19:52 UTC, tataihono requested changes

2021-10-04 19:52 UTC, tataihono commented on libs/shared/ui/src/libs/themes/base/tokens/components.ts
> +import { spacingThemeToken } from '../tokens/spacing'
revert

2021-10-04 21:29 UTC, tataihono approved these changes

2021-10-04 21:51 UTC, tataihono commented
I approved the design for this as they match pixel-perfect to the designs. We can revisit modifications to this in future cycles if I was wrong to approve the design.

2021-10-04 21:51 UTC, merged