fix: mobile card selection experience
JesusFilm/core pull request #3600
Opened 2024-10-03 23:50 UTC by Kneesal

# Description

### Issue

mobile card selection experience on journey flow

2024-10-04 01:44 UTC, tataihono requested changes
not sure if this is needed.

2024-10-04 01:44 UTC, tataihono commented on libs/shared/ui/src/libs/useMediaQuery/index.ts
drop custom hook

2024-10-16 19:16 UTC, tataihono approved these changes

2024-10-20 21:58 UTC, tataihono approved these changes

2024-10-20 23:57 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
> +            if (isIphone) handleClick()
good pickup, thanks

2024-10-21 00:05 UTC, tataihono approved these changes

2024-10-21 19:41 UTC, merged