feat: mobile scroll down arrow
JesusFilm/core pull request #3647
Opened 2024-10-13 21:07 UTC by jianwei1

### Issue

Show a bouncing scroll down arrow at bottom of card if there is more content below (on mobile)

2024-10-14 22:25 UTC, scottkelso requested changes
Looking good! Added a few things to think about and would also need some sort of test for this. At the very least just test that it appears when we would expect it to.

2024-10-14 22:25 UTC, scottkelso commented on libs/journeys/ui/src/components/Card/OverlayContent/DownScrollArrow/DownScrollArrow.tsx
> +export function DownScrollArrow({
Would it be a better name to swap scroll and down and also not tie the naming to what icon is used?

```suggestion
interface ScrollDownIndicatorProps {
  trigger: boolean
}
export function ScrollDownIndicator({
```

You could also take the icon in as a prop so that in the future you could use this with another icon instead of that particular down arrow.

2024-10-14 22:25 UTC, scottkelso commented on libs/journeys/ui/src/components/Card/OverlayContent/DownScrollArrow/DownScrollArrow.tsx
> +    }, 5000)
This is a MAGIC_NUMBER so should be pulled out as a const. Even make it a prop too that defaults to `BOUNCE_DELAY = 5000`

2024-10-14 22:25 UTC, scottkelso commented on libs/journeys/ui/src/components/Card/OverlayContent/OverlayContent.tsx
>      overflowY: 'scroll',
```suggestion
  const cardOverlayRef = useRef<any>()
  
  const trigger = useScrollTrigger({
    disableHysteresis: true,
    target: cardOverlayRef.current,
    threshold: 20
  })
  
  const isScrollable = (): boolean => {
    const box = cardOverlayRef.current
    return box != null ? box.scrollHeight > box.clientHeight : false
  }
  
  const enableVerticalScroll: SxProps = {
    overflowY: 'scroll',
```

Add spacing to break up the code blocks for better reading

2024-10-15 23:00 UTC, scottkelso requested changes
Looks well! Left a couple of suggestions. Also need some test coverage.

2024-10-15 23:00 UTC, scottkelso commented on libs/journeys/ui/src/components/Card/OverlayContent/ScrollDownIndicator/ScrollDownIndicator.tsx
> +}
It would be a really pro move to have `bounceDelay` and `icon` be optional props that default to `BOUNCE_DELAY` and `<ChevronDownIcon />` respectfully. This better adheres to the open/closed principle.

2025-03-17 19:39 UTC, tataihono commented
closing due to age.

2025-03-17 19:39 UTC, closed without merging