fix: eng 1091 upload video error
JesusFilm/core pull request #3649
Opened 2024-10-14 03:51 UTC by scottkelso

# Description

### Issue

If an upload video error occurs but the user tries again, there error text still remains as well as the uploading/processing text

[Link to Linear Todo](https://linear.app/jesus-film-project/issue/ENG-1091/upload-video-error)

### Solution

Set error state to false onDrop

# External Changes

Refactored test class

# How to test
When a video upload error occurs (maybe forced by network change eta), the user should be able to retry again.
On another attempt you should never have both the old error text and the new uploading/processing text together.

2024-10-14 04:12 UTC, csiyang requested changes

2024-10-14 04:12 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.tsx
> +    setError(undefined)
anyway to unit test this?

2024-10-14 20:49 UTC, jianwei1 reviewed
Great job on extracting the mocks! The spec file looks much cleaner now

2024-10-14 21:27 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.tsx
> +    setError(undefined)
Thought of a way thismorning. Have a look!

2024-10-14 22:41 UTC, csiyang approved these changes

2024-10-20 23:14 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.spec.tsx
> +      expect(screen.queryByText('Processing...')).not.toBeInTheDocument()
is it possible to check this text is in the document before its completed?

2024-10-21 00:05 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.spec.tsx
> +      expect(screen.queryByText('Processing...')).not.toBeInTheDocument()
That's what `should complete a file upload and call onChange` test is doing.

2024-10-21 01:27 UTC, csiyang approved these changes

2024-10-22 02:02 UTC, merged