feat: display video block properties by default instead of card properties
JesusFilm/core pull request #3663
Opened 2024-10-15 23:00 UTC by jianwei1

### Issue

When a new card is created and video is selected from the list of card templates, display the video properties instead of card properties

2024-10-17 20:51 UTC, tataihono approved these changes

2024-10-20 22:17 UTC, tataihono requested changes

2024-10-20 22:17 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
> +      if (card?.children[0].__typename === 'VideoBlock') {
need to check that this is not the background video.

2024-10-21 01:48 UTC, tataihono submitted a review, later dismissed

2024-10-22 02:41 UTC, csiyang approved these changes

2024-10-22 03:26 UTC, merged