Johngeronimo/eng 1060 background images should have a focal point
JesusFilm/core pull request #3667
Opened 2024-10-16 03:28 UTC by GeronimoJohn

# Description

### Issue

_Provide a brief summary of why this task is needed_

[Link to Basecamp Todo](https://3.basecamp.com/3105655/projects)

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2024-10-21 05:46 UTC, tataihono requested changes
I found that splitting this out into a bunch of components is making this more difficult to understand. I don't think you'll reuse any of the subcomponents anywhere else.

2024-10-21 05:46 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/FocalPointInputs/FocalPointInputs.tsx
> +      ))}
just make two inputs. this is not really saving much code but its more confusing.

2024-10-21 05:46 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/FocalPointImage/GridLines/GridLines.tsx
> +      ))}
can we write this out by hand? just introducing a loop which makes it a bit more complex.

2024-10-21 05:46 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/FocalPointImage/FocalPointImage.tsx
> +      {imageBlock?.src != null ? (
i don't think this component should render at all if there is no image.

2024-10-21 06:48 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/FocalPointImage/FocalPointImage.tsx
> +      {imageBlock?.src != null ? (
That makes sense

2024-11-13 23:10 UTC, tataihono approved these changes

2024-11-14 21:04 UTC, merged