fix: disable add video button if card has background image or video
JesusFilm/core pull request #3755
Opened 2024-10-20 23:23 UTC by jianwei1

### Issue

Users were able to press the "Add Video" button if the card had a background video/image. An apollo error was then thrown

### Solution

Change the hasChildBlock check on AddBlock.tsx to disable the NewVideoButton if the cardblock has any children( previously, it would only check if it had children that weren't coverblocks, which allowed the button to be enabled if the card had a background image/video)

2024-10-20 23:58 UTC, tataihono requested changes

2024-10-20 23:58 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.tsx
> +  const hasChildBlock = cardBlock?.children?.length > 0
```suggestion
  const hasChildBlock = cardBlock?.children != null && cardBlock.children.length > 0
```

2024-10-21 01:06 UTC, tataihono submitted a review, later dismissed

2024-10-22 03:33 UTC, scottkelso approved these changes

2024-10-22 04:15 UTC, merged