feat: color hex validation
JesusFilm/core pull request #3934
Opened 2024-10-31 03:03 UTC by DanChae03

# Description

### Issue

Currently the HEX field in the background colour picker accepts any string as a hex. Fixed to ensure only valid HEX values result in network calls that change the colour.

### Solution

Isolate field value as a useState variable. 
Regex validation for colour string
Reset upon blur if value is invalid.

2024-10-31 04:15 UTC, scottkelso requested changes
Looks good! Nice refactoring into named functions. For future reference there would be nothing stopping you refactoring out the `isValidHex` function and unit testing it. We definitely need some tests here so make sure that we have somewhere check for the invalid states.

2024-10-31 04:15 UTC, scottkelso commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  function validateHexString(color: string): boolean {
```suggestion
  function isValidHex(color: string): boolean {
```
would be common naming convention here

2024-11-04 22:47 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  }
```suggestion
  const validationSchema = object({
    color: string()
      .required(t('Required'))
      .test('valid-hex-color', t('Invalid HEX color code'), isValidHex)
  })
```

Drop these functions and use `Formik` to handle validation, see `LinkAction.tsx`

2024-11-04 22:47 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  }, [selectedColor])
is this needed? You're already passing in default state for the component when it mounts in line 92 , useState will handle re-renders

2024-11-04 22:52 UTC, DanChae03 commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  }, [selectedColor])
It's so that if selectedColor changes via external means (Palette, etc) it will update in the textfield as well.

2024-11-05 01:53 UTC, DanChae03 commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  }, [selectedColor])
Not needed with formik

2024-11-05 02:25 UTC, Kneesal requested changes

2024-11-05 02:25 UTC, Kneesal commented on apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +          label=""
```suggestion
```
drop empty label prop

2024-11-05 02:25 UTC, Kneesal commented on libs/locales/en/apps-journeys-admin.json
> +  "Invalid HEX color code": "",
Looks like the key isn't being translated properly, can you please look into this?

2024-11-06 22:11 UTC, Kneesal approved these changes

2024-11-07 11:38 UTC, merged