refactor: selectable wrapper
JesusFilm/core pull request #403
Opened 2022-03-23 01:48 UTC by storyworks

# Description

Refactors how we select a block so the selection is done by wrapping each block in a wrapper. This `SelectableWrapper` is now in charge of selection logic and styling.

Also refactored RadioQuestion to use BlockRenderer to create RadioOptions when selected. This sets us up to easily implement RadioQuestion/Option block editing.

**Note: This excludes selection of the VideoBlock due to PR size, will tackle that in following PR**

Prerequisite to 
[Inline Editing options](https://3.basecamp.com/3105655/buckets/26787371/todos/4752720789)
[Create an option](https://3.basecamp.com/3105655/buckets/26787371/todos/4752720597)
[Inline editing header / description](https://3.basecamp.com/3105655/buckets/26787371/todos/4752720789)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] PR Checks
- [ ] Manual test selection works for all blocks except Video

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-03-23 02:18 UTC, storyworks commented on libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.tsx
> +const StyledRadioOption = styled(Button)<ButtonProps>(({ theme }) => ({
Slowly also refactoring some blocks to use `styled` over `sx`

2022-03-23 02:18 UTC, storyworks commented on libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
> +        <BlockRenderer block={option} wrappers={wrappers} key={option.id} />
Use BlockRenderer to create RadioOptions in Admin mode. No need to pass in `selected`, `disabled` states or `onClick` so this works.

2022-03-23 02:18 UTC, storyworks commented on libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
> -  '&:last-child': { marginBottom: 0 }
To test in VR..

2022-03-24 01:29 UTC, storyworks commented
Will merge in main along with other PR review fixes

2022-03-24 01:40 UTC, storyworks commented on libs/journeys/ui/src/components/Button/Button.tsx
> -  let marginTop: number
We still want the gap created with a top margin - will split out changes in PR

2022-03-24 03:18 UTC, mikeallisonJS requested changes

2022-03-24 03:18 UTC, mikeallisonJS commented on libs/journeys/ui/src/components/Video/Video.spec.tsx
> +describe.skip('Admin Video', () => {
Is this intentional?

2022-03-24 03:21 UTC, storyworks commented on libs/journeys/ui/src/components/Video/Video.spec.tsx
> +describe.skip('Admin Video', () => {
Yes, this test will be moved and when we do selection for the video block. I left it out in this PR since it was getting massive.

2022-03-24 03:23 UTC, mikeallisonJS submitted a review, later dismissed

2022-03-24 22:12 UTC, mikeallisonJS approved these changes

2022-03-24 22:48 UTC, mikeallisonJS approved these changes

2022-03-24 22:52 UTC, merged