feat: drag to reorder blocks on canvas
JesusFilm/core pull request #4047
Opened 2024-11-07 11:29 UTC by DanChae03

# Description

### Issue

_Provide a brief summary of why this task is needed_

### Solution

_Provide a detailed description of how exactly this task will be accomplished. This can be something technical. What specific steps will be taken to achieve the goal? This should include details on service integration, job logic, implementation, etc._

# External Changes

_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, etc._

# Additional information

_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, etc._

2025-01-15 22:19 UTC, csiyang requested changes

2025-01-15 22:19 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/DropArea/DropArea.tsx
> +              pl: 8,
Whats this for?

2025-01-15 22:19 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
> +import { DragOverEvent, useDndMonitor } from '@dnd-kit/core'
How come the drag logic had to be done here? It ideally should be its own component.

2025-01-15 22:38 UTC, DanChae03 commented on apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/DropArea/DropArea.tsx
> +              pl: 8,
It's so that when the grab handle is clicked, the cursor has the "grabbing"  cursor shape. Since the drop preview will follow the cursor as it drags, there's no other way for the cursor to have the "grabbing" shape unless it's actively over part of the drag preview - since the handle is on the side, the drag preview needs to invisibly extend to the cursor region as well - this is the only way that I found worked

2025-01-17 01:30 UTC, csiyang requested changes

2025-01-17 01:30 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
> +    await waitFor(() =>
revert

2025-01-17 01:30 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
> -          '&:first-child': {
Are these changes still required?

2025-01-17 01:36 UTC, DanChae03 commented on apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
> -          '&:first-child': {
No

2025-01-17 01:47 UTC, csiyang approved these changes

2025-01-17 02:28 UTC, merged