Image component
JesusFilm/core pull request #42
Opened 2021-09-20 21:15 UTC by gdub01

Takes width, height, src and alt. Width and height are currently mandatory but wasn't sure if that should always be true. I think it makes sense for the db to know the _stored_ image sizes so I'm imagining when we request the image block, we get the original image sizes back. The client can then determine how/if it wants to transform the image... either by modifying the source url or by changing some properties it adds to the next/image component. But I'm thinking we'll deal with some of those things later.

2021-09-24 05:21 UTC, storyworks approved these changes
Just need to merge in main before you merge - there's some updates to BlockRenderer

2021-09-24 20:58 UTC, tataihono commented
I think the backend is going to fail. Did you manage to test this before approval @storyworks?

2021-09-24 21:00 UTC, tataihono submitted a review, later dismissed

2021-09-24 21:00 UTC, tataihono commented on apps/journeys/src/components/blocks/Image/Image.stories.tsx
> +  // eslint-disable-next-line jsx-a11y/alt-text
I don't think we should be adding in eslint disables here.

2021-10-01 02:34 UTC, storyworks requested changes
There's also the issue of the conductor container cutting off the shadows on Cards, but I'm not sure if you want to fix that in another PR. https://github.com/JesusFilm/core/pull/36#discussion_r719867474

2021-10-01 02:34 UTC, storyworks commented on apps/journeys/src/components/blocks/Image/Image.tsx
> +      <NextImage src={src} alt={alt} height={height} width={width} />
Add `objectFit='cover'` ?

2021-10-01 02:36 UTC, storyworks commented on apps/journeys/src/components/blocks/Image/Image.tsx
> +      <NextImage src={src} alt={alt} height={height} width={width} />
Actually, with that - maybe use a picture that makes it more obvious if it's been squashed in some way? It's really easy to miss with this one..

2021-10-01 04:42 UTC, storyworks approved these changes

2021-10-01 04:52 UTC, merged