fix: background color selection and change
JesusFilm/core pull request #425
Opened 2022-03-29 02:10 UTC by storyworks

# Description

- Selected color swatch now properly reflects Card
- Fixed choosing color via custom color picker (also switched to using HEX rather than RGB picker)
- Changed palette colors from theme colors to custom range

[Basecamp - selected color](https://3.basecamp.com/3105655/buckets/26787371/todos/4752754608)
[Basecamp - debounce color picker fix](https://3.basecamp.com/3105655/buckets/26787371/todos/4752753333)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] PR checks
- [ ] Selected colors accurately reflect card color
- [ ] Can change color by typing / copy paste in text field
- [ ]  Can change color by clicking on palette color
- [ ]  Can change color by clicking in custom color picker

Error handling incorrect typed colors can be done separately. 

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-03-29 02:12 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
> +  it('shows the selected card color', () => {
Now always showing the HEX value rather than "None" or "Default". User doesn't care about where color is coming from.

2022-03-29 02:14 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +const palette = [
Combined in 1 palette so toggling between dark and light mode can also change the background color used (in future optimisation)

2022-03-29 02:15 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  blockId: string
Pass in Card id so we don't need to search for "CardBlock" object anymore.

2022-03-29 02:17 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  const debouncedColorChange = useRef(
Recommended to split out debounce so it's only created once across rerenders
https://www.carlrippon.com/using-lodash-debounce-with-react-and-ts/

2022-03-29 02:18 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  const palettePicker = (
Reuse out PaletteColorPicker and enables us to unit test once (before a seperate picker was used for each breakpoint)

2022-03-29 02:20 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +      <HexColorPicker
Switch to HexColorPicker. No need for RBG for Card - we're not having translucent Cards.

2022-03-29 02:21 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +      <Stack sx={{ p: 6, py: 4 }} spacing={3} direction="row">
Rest of this is same except the Color boxes & pickers are extracted out.

Also renamed 'Theme' heading to 'Palette' per Vlad's instructions

2022-03-29 02:25 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
> +  const cardTheme =
Calculated once and passed down just 1 level.
Passing down `selectedCardColor` also saves us from having to search within `BackgroundColor` to find the Cardblock associated with it.

2022-03-29 22:21 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  const debouncedColorChange = useRef(
how this different from useCallback?

2022-03-30 02:39 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  const debouncedColorChange = useRef(
I suspect it's the same issue as described https://kyleshevlin.com/debounce-and-throttle-callbacks-with-react-hooks

Though for choosing useRef over useMemo, I'm not sure why Carl favoured it - possibly for our case we don't expect our functions to change so don't need the updates we'd get with useMemo. Possibly also useRef allows us to fix the render issue with one hook instead of having seperate useCallback and useMemo..

Cancelling the debounce method should be done regardless.

2022-03-30 02:39 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  const debouncedColorChange = useRef(
I suspect it's the same issue as described https://kyleshevlin.com/debounce-and-throttle-callbacks-with-react-hooks

Though for choosing useRef over useMemo, I'm not sure why Carl favoured it - possibly for our case we don't expect our functions to change so don't need the updates we'd get with useMemo. Possibly also useRef allows us to fix the render issue with one hook instead of having seperate useCallback and useMemo..

Cancelling the debounce method should be done regardless.

2022-03-30 02:48 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  const debouncedColorChange = useRef(
I tweeted at Carl, let's see if he replies xD https://twitter.com/carlrippon/status/1473621086486990850

2022-04-08 00:26 UTC, tataihono requested changes
the attributes components must fetch their props from state.

2022-04-08 00:26 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  blockId: string
these components must rely on state.

2022-04-12 21:19 UTC, tataihono requested changes

2022-04-12 21:19 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
> +  ) as TreeBlock<CardFields>
this change is unnecessary. The old functionality would support the current block as a card regardless of where it is located.

2022-04-13 23:28 UTC, tataihono approved these changes

2022-04-13 23:39 UTC, merged