docs: added and refactored contributing for new api projects
JesusFilm/core pull request #435
Opened 2022-03-30 00:08 UTC by csiyang

# Description

Updated docs to include set up instructions for new API projects

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Nothing, just docs :) 

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-03-30 00:29 UTC, GeronimoJohn commented on CONTRIBUTING.md
>     - run `nx run journeys-admin:serve-all`
While we're here - what are the chances of new contributors running both of these commands at the same time? Some apps will run but ultimately in the VSCode terminal they'll get the error `ERROR [NestApplication] Error: listen EADDRINUSE: address already in use :::4001 +10ms`. This is not a major problem but we can make it a smoother setup process?

Maybe we can make it to 
1. Start the journey project
 - run `nx run journeys:serve-all`
2. in your local browser....

1. Start the journeys-admin project
  - run `nx run journeys-admin:serve-all`
2. in your local browser...

1. To run everything ...
 - run `nx run journeys:serve` 
 - run `nx run journeys-admin:serve`
 - run `nx run api-gateway:serve-all`
 
 Just a suggestion

2022-03-30 01:06 UTC, storyworks commented on CONTRIBUTING.md
> +   - Make a copy of `apps/api-languages/.env.example` with the file name `apps/journeys/.env.local`. Open the file and set up your own environment variables.
How do we set up out own environment variables? Last time we just copied Tatai's right? And we at least have a link to some 3rd party instructions if not our own?

2022-04-03 23:39 UTC, tataihono commented on CONTRIBUTING.md
> +   - Make a copy of `apps/api-languages/.env.example` with the file name `apps/journeys/.env.local`. Open the file and set up your own environment variables.
the instructions should be in the example.

2022-04-04 01:22 UTC, GeronimoJohn requested changes

2022-04-04 01:22 UTC, GeronimoJohn commented on CONTRIBUTING.md
> +     1. run `nx run journeys-admin:serve-all`
This would still give the VSCode terminal error
`ERROR [NestApplication] Error: listen EADDRINUSE: address already in use :::4001 +10ms`
as journeys and journeys-admin serve-all is re rerunning the API servers. Should just be serve

2022-04-04 01:22 UTC, GeronimoJohn commented on CONTRIBUTING.md
> +   - Make a copy of `apps/journeys-admin/.env.example` with the file name `apps/journeys/.env.local`. Open the file and set up your own environment variables.
Except for the journeys project the file path needs to be updated. E.g. For api-languages instead of `apps/journeys/env.local`  it should be `app/api-languages/.env.local`

2022-04-04 01:24 UTC, csiyang commented on CONTRIBUTING.md
> +1. Set up env files for projects
Mark down automatically converts it to the correct numbers

2022-04-04 01:25 UTC, csiyang commented on CONTRIBUTING.md
> +     1. run `nx run journeys-admin:serve-all`
oops

2022-04-04 01:35 UTC, GeronimoJohn requested changes

2022-04-04 01:35 UTC, GeronimoJohn commented on CONTRIBUTING.md
> +   - Make a copy of `apps/api-videos/.env.example` with the file name `apps/api-videos/.env.local`. Open the file and set up your own environment variables.
How do we get a copy of the arclight api key? Is this info something we would want to be shown?

2022-04-04 01:36 UTC, csiyang commented on CONTRIBUTING.md
> +   - Make a copy of `apps/api-videos/.env.example` with the file name `apps/api-videos/.env.local`. Open the file and set up your own environment variables.
@tataihono

2022-04-06 22:45 UTC, tataihono commented on CONTRIBUTING.md
> +   - Make a copy of `apps/api-videos/.env.example` with the file name `apps/api-videos/.env.local`. Open the file and set up your own environment variables.
@SwayCiaramelloCru any thoughts about this?

2022-04-13 19:29 UTC, csiyang commented on CONTRIBUTING.md
> +   - Make a copy of `apps/api-videos/.env.example` with the file name `apps/api-videos/.env.local`. Open the file and set up your own environment variables.
Will add it in once we have clear instructions for it

2022-04-13 19:36 UTC, tataihono approved these changes

2022-04-13 19:38 UTC, merged