test: add tests for video view
JesusFilm/core pull request #4453
Opened 2024-11-22 02:20 UTC by edmonday

# Description

### Issue

`VideoView.tsx` needed tests and stories

### Solution

- Added tests and stories for `VideoView.tsx`
- Added mock data for `apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts`
- Updated `Metadata.tsx` so that video data is passed down to children
- Updated tests for files affected by addition of mock data and changes to `Metadata.tsx`

2024-11-24 22:49 UTC, Kneesal requested changes

2024-11-24 22:49 UTC, Kneesal commented on apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/data.mock.ts
drop this file and use adminVideoMock file, both files contain the same data

2024-11-24 23:01 UTC, edmonday commented on apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/data.mock.ts
dropped

2024-11-25 00:06 UTC, Kneesal approved these changes

2024-11-25 00:37 UTC, merged