feat: api videos playlist
JesusFilm/core pull request #451
Opened 2022-04-04 20:31 UTC by mikeallisonJS

# Description

This adds playlist support for videos, ingests series information from arclight, and adds filters to the video queries for the video api

https://3.basecamp.com/3105655/buckets/26736589/todos/4795311585

# How should this PR be QA Tested?

- [ ] Existing video calls in journeys-admin are unaffected
- [ ] Playlists and filters are available in watch

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-04-05 14:45 UTC, gdub01 approved these changes
awesome

2022-04-06 21:32 UTC, tataihono requested changes

2022-04-06 21:32 UTC, tataihono commented on apps/api-videos/db/seed.ts
> +      duration: Math.round(mediaComponentLanguage.lengthInMilliseconds * 0.001)
add `subtitle: []`, and `downloads: []`

2022-04-06 21:32 UTC, tataihono commented on apps/api-videos/db/seed.ts
> +      duration: Math.round(mediaComponentLanguage.lengthInMilliseconds * 0.001)
further down and here you should also add `episodeIds: []`

2022-04-06 21:32 UTC, tataihono commented on apps/api-videos/db/seed.ts
> +  episodeIds?: string[]
required

2022-04-06 21:32 UTC, tataihono commented on apps/api-videos/db/seed.ts
> +  variants?: VideoVariant[]
required

2022-04-06 21:32 UTC, tataihono commented on apps/api-videos/db/seed.ts
> +  downloads?: Download[]
required

2022-04-06 21:32 UTC, tataihono commented on apps/api-videos/db/seed.ts
> +  subtitle?: Translation[]
required

2022-04-06 21:32 UTC, tataihono commented on apps/api-videos/db/seed.ts
> +          isInnerSeries: {
use `playlistIds:`

2022-04-06 21:32 UTC, tataihono commented on apps/api-videos/src/app/modules/video/video.graphql
> +  Videos containing episodes are considered playlists
```suggestion
  A Video containing episodes is considered a playlist
```

2022-04-07 03:11 UTC, tataihono requested changes
episodes and episodeIds should just return an empty array if there is nothing there. Otherwise every consumer is going to have to do null checks

2022-04-07 03:11 UTC, tataihono commented on apps/api-videos/src/app/modules/video/video.graphql
> +  episodeIds: [ID!]
```suggestion
  episodeIds: [ID!]!
```

2022-04-07 03:11 UTC, tataihono commented on apps/api-videos/src/app/modules/video/video.graphql
> +  episodes: [Video!]
```suggestion
  episodes: [Video!]!
```

2022-04-08 00:01 UTC, tataihono approved these changes

2022-04-08 00:13 UTC, merged