fix: disable link action in editor
JesusFilm/core pull request #455
Opened 2022-04-05 23:24 UTC by csiyang

# Description

LinkAction and NavigateToJourneyAction, should not be handled when in editor mode. This PR fixes this by checking if there is a selectedBlock and sending through a boolean prop to handleAction

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4810871664)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] When in editor button that has link action to URL should not redirect to link
- [ ] When in editor button that has Navigate to Journey Action should not redirect to Journey
- [ ] Button actions works as expected when not in edito

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-04-05 23:32 UTC, GeronimoJohn commented on libs/journeys/ui/src/libs/action/handleAction.spec.ts
> +    const editorMode = false
can just use the editorMode on line 22

2022-04-05 23:47 UTC, GeronimoJohn approved these changes

2022-04-06 02:30 UTC, storyworks requested changes
We talked about finding a solution which didn't use the editor state in the blocks, so they could remain isolated from that logic.

2022-04-06 02:44 UTC, csiyang commented
Closing because we need another solution to solve this bug as per [this comment](https://github.com/JesusFilm/core/pull/455#pullrequestreview-932715164).

2022-04-06 02:44 UTC, closed without merging