test: journeyquicksettings
JesusFilm/core pull request #4639
Opened 2024-12-09 21:06 UTC by jianwei1

journeyquicksettings tests

2024-12-12 01:30 UTC, csiyang requested changes

2024-12-12 01:30 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettings.spec.tsx
> +//
```suggestion
```

2024-12-12 01:30 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettings.spec.tsx
> +  it('should render journeyquicksettingsgoals on goals tab click', () => {
```suggestion
  it('should render journeyQuickSettingsGoals on goals tab click', () => {
```
Any particular reason for this not being in camelCase? We have words with no spaces in camelCase for readability.

2024-12-16 22:06 UTC, Kneesal approved these changes

2024-12-18 03:58 UTC, merged