feat: video poster blur
JesusFilm/core pull request #484
Opened 2022-04-13 05:06 UTC by storyworks

# Description

Add blur to video block, card video cover and card image cover. Includes a refactor of Cover to remove redundant styles

Checked against main and card + video blocks look fine. One issue I found was when there's too much content on a card with image blur background:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/10802634/163103756-78a17526-badc-4800-b8fc-b642cf2e0ecf.png">

The card stretches in height, instead of being a fixed height and scrolling within the card on desktop. This issue already exists in main, but I've fixed it slightly so that you can still see the progress bar. 

<img width="896" alt="image" src="https://user-images.githubusercontent.com/10802634/163103959-54de155a-436a-4c71-9f09-cb2ccde60cb7.png">
In main, we can't even see the progress bar.

- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4757610703)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] PR tests pass
Manually checked
- [ ] Check Video Block poster image - also without poster image still works
- [ ] Check Card - plain background + colour background + blur image background unchanged
- [ ] Check Card - video cover works and has poster with blur on all breakpoints
- [ ] Check Card - image cover works and has blur on all breakpoints

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-04-13 23:46 UTC, storyworks commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +          minHeight: '100%'
Fixes the progress bar not showing issue shown in the description

2022-04-13 23:47 UTC, storyworks commented on libs/journeys/ui/src/components/Card/Card.spec.tsx
> +    expect(getByTestId('CardImageCover')).toHaveAttribute(
Using NextImage, the url is like `data:image/png...` and is very long. Testing alt instead to check the image is there - correct image displayed is covered by VR.

2022-04-13 23:49 UTC, storyworks commented on libs/journeys/ui/src/components/Card/Card.tsx
> -      sx={{
All removed styling was used to position the old card background

2022-04-13 23:52 UTC, storyworks commented on libs/journeys/ui/src/components/Card/Card.tsx
> +            justifyContent: 'center'
Fixes, 
![Uploading image.png…]()

2022-04-14 01:15 UTC, storyworks commented on libs/journeys/ui/src/components/Card/Cover/Cover.tsx
> -          display: { xs: 'flex', md: 'none' },
Lines 111-237 are extracted to ContentOverlay. No changed are made except I add backgroundImage directly to the overlay for the blur.

2022-04-14 03:48 UTC, storyworks commented on .storybook/preview.js
> +    chromatic: { viewports: [360, 1200], diffThreshold: 0.1 },
Chromatic default is `0.63` ranges from 0 to 1.

2022-04-18 22:02 UTC, tataihono requested changes

2022-04-18 22:57 UTC, storyworks commented on libs/journeys/ui/src/components/Video/Video.tsx
> +        autoplay: autoplay != null,
Yip I found this too this morning :) thanks!

2022-04-19 20:03 UTC, storyworks commented on libs/shared/ui/src/components/NextImage/NextImage.tsx
> +const StyledNextImage = styled(Image)({
I split NextImage out into a common component since Vlad didn't want the inner shadow showing on placeholder images. The other ways of overriding this filter didn't work so resorted to `!important` but I didn't want this duplicated across the project.

Can leave a comment if there's anything else I also need to update.

2022-04-20 00:47 UTC, tataihono approved these changes
https://github.com/JesusFilm/core/pull/503 can you coordinate with @GeronimoJohn to ensure that his fixes can get merged in here.

2022-04-20 05:19 UTC, merged