feat: social share
JesusFilm/core pull request #494
Opened 2022-04-14 04:07 UTC by csiyang

# Description

Add og tags for social sharing, added buttons in the social drawer 

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752672406)

# How should this PR be QA Tested?
- [ ] Clicking on facebook button of a published journey should take you to a new window on facebook that has a share card with the social share title description and image
- [ ] Clicking on twitter button of a published journey should take you to a new window on twitter that has a share card with the social share title description and image

# Checklist
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-04-14 04:08 UTC, csiyang commented
Needs [this](https://github.com/JesusFilm/core/pull/485) PR to be merged in first

2022-04-16 21:38 UTC, tataihono requested changes
this shouldn't use javascript to open a link in a new window. Instead you should use a Material Link component with an anchor tag.

2022-04-18 21:17 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
> +      <Stack direction="row" spacing={3}>
@tataihono should these buttons be disabled if journey is not published?

2022-04-18 21:23 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
> +      <Stack direction="row" spacing={3}>
yes.

2022-04-18 21:27 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
> +            component="a"
Try convert this into a button compoent

2022-04-18 21:28 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.spec.tsx
>      expect(getByTestId('social-image-edit')).toBeInTheDocument()
Strip the test id's where possible

2022-04-19 23:10 UTC, tataihono requested changes

2022-04-19 23:10 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
> +          onClose={handleCloseFacebookTooltip}
not required

2022-04-19 23:10 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
> +  }
not required

2022-04-19 23:10 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
> +  const shareUrl = journey?.slug ?? `untitled-journey-${journey?.id as string}`
don't guess this.

2022-04-19 23:10 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
> +  const encodedUrl = encodeURIComponent(shareUrl)
why does this need to be encoded? slugs should already be ready to go into a url

2022-04-19 23:10 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
> +              href={`https://www.facebook.com/sharer/sharer.php?u=https://your.nextstep.is/${encodedUrl}`}
```suggestion
              href={`https://www.facebook.com/sharer/sharer.php?u=https://your.nextstep.is/${journey.slug}`}
```

2022-04-20 02:02 UTC, tataihono approved these changes

2022-04-20 02:13 UTC, merged