fix: cardBlock sets null parentOrder on coverBlocks
JesusFilm/core pull request #504
Opened 2022-04-19 21:02 UTC by storyworks

# Description

Moving blocks breaks as cover image and videos have a parentOrder and thus are considered part of the array we can reorder. 

Set parentOrder explicitly as null in the api and delete the existing coverBlocks on when cover images are replaced/removed to fix and simplify the logic on the frontend.

This is an api change prequisite to getting move working

- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4786305141)

# How should this PR be QA Tested?

- [ ] PR checks

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-04-20 00:39 UTC, tataihono requested changes
image and video resolvers should update the parent block with the new cover block id. Can't see that happening here.

2022-04-20 00:39 UTC, tataihono commented on apps/api-gateway/schema.graphql
> +  True if the coverBlockId in a parent block is set to this block id. Cover blocks should only be set at creation.
The latter is already true because it is only contained in the ImageBlockCreateInput.

```suggestion
  True if the coverBlockId in a parent block should be set to this block's id.
```

2022-04-20 01:57 UTC, storyworks commented on apps/api-gateway/schema.graphql
> +  True if the coverBlockId in a parent block is set to this block id. Cover blocks should only be set at creation.
Added that so people won't be tempted to add the `isCover` prop to update later down the line.

2022-04-20 02:05 UTC, tataihono commented on apps/api-gateway/schema.graphql
> +  True if the coverBlockId in a parent block is set to this block id. Cover blocks should only be set at creation.
this is already true though. The prop is only available on ImageBlockCreateInput.

2022-04-20 02:22 UTC, storyworks commented on apps/api-gateway/schema.graphql
> +  True if the coverBlockId in a parent block is set to this block id. Cover blocks should only be set at creation.
I know it's already true and I'm saying I added the latter to ensure it remains true. As someone unfamiliar with the design might think we can easily toggle an image as cover or not. This could prompt them to search out more an realise we have a create & delete process for setting cover images.

2022-04-20 19:55 UTC, storyworks commented on apps/api-journeys/src/app/modules/block/card/card.resolver.ts
> +    // Delete existing coverBlock when replacing or removing
@tataihono , you mentioned to remove this logic (handles replace & delete) after we make frontend changes. 

Double checking that when we click to delete (not replace) a video or image block - does that logic also move to Image/Video? Because no other block has their own custom delete mutation, and we'd need to add the `isCover` prop to the Image/Video block

2022-04-21 02:06 UTC, tataihono requested changes

2022-04-21 02:06 UTC, tataihono commented on apps/api-journeys/src/app/modules/block/image/image.resolver.ts
> +    } else {
this else is not needed as the above statement returns a value. This simplifies the amount of code visually in a flow control block.

```
if (test) {
  return value1
} else {
  return value2
}
```
is more complex than just

```
if (test) {
  return value1
}
return value2
```

2022-04-21 02:06 UTC, tataihono commented on apps/api-journeys/src/app/modules/block/image/image.resolver.ts
> +      })
this should be cached and reversed. That is, store the current coverBlockId in a variable, update the parent, then delete the block. This will ensure any clients that load the page always has a working coverBlock regardless of which version they get.

2022-04-21 02:06 UTC, tataihono commented on apps/api-journeys/src/app/modules/block/video/video.resolver.ts
> +      })
reverse as above

2022-04-21 02:06 UTC, tataihono commented on apps/api-journeys/src/app/modules/block/video/video.resolver.ts
> +    } else {
else not needed as above

2022-04-21 20:52 UTC, tataihono approved these changes

2022-04-21 21:45 UTC, merged