feat: image loading state
JesusFilm/core pull request #523
Opened 2022-04-25 21:58 UTC by csiyang

# Description
Adding loading circles when updating an image and waiting for it to load.

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752779793)

# How should this PR be QA Tested?
- [ ] Creating and updating an image should show a loading circle on the dialog that updates it.

# Checklist
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-04-25 22:07 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
> +// const onClose = jest.fn()
Remove comment

2022-04-25 22:07 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.tsx
> +            loading={loading}
Moved from everything from poster dialog into here to allow this imageBlockThumbnail to also have the loading state

2022-04-25 22:48 UTC, tataihono requested changes
remove an intermediary state and just use the original state. you are causing rerenders when its not necessary.

2022-04-25 22:48 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
> +
just use createLoading || updateLoading

2022-04-25 22:48 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
> +      loading={loading}
```suggestion
      loading={createLoading || updateLoading}
```

2022-04-25 22:48 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
> +  }, [updateLoading])
remove.

2022-04-25 22:48 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
> +  const [imageBlockUpdate, { loading: updateLoading }] =
```suggestion
  const [imageBlockUpdate, { loading }] =
```

2022-04-25 22:48 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
> +
remove

2022-04-25 22:48 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
> +          loading={loading}
```suggestion
          loading={createLoading || updateLoading}
```

2022-04-26 01:40 UTC, tataihono requested changes
you can remove a number of the loading={false} statements if you just make the loading boolean optional. Because there is no behavioral adjustments to the component when it is false all you really care about is if loading is true.

2022-04-26 01:40 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
> +  }, [createLoading, updateLoading])
delete and use `createLoading || updateLoading` below

2022-04-26 01:40 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
> +        loading={loading}
```suggestion
        loading={createLoading || updateLoading}
```

2022-04-26 01:40 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
> +          loading={false}
the underlying component should not make this boolean required negating the need to add this everywhere.

2022-04-26 01:40 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
> +  loading: boolean
```suggestion
  loading?: boolean
```

2022-04-26 01:40 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
> +  loading: boolean
```suggestion
  loading?: boolean
```

2022-04-26 01:40 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
> +      {loading ? (
```suggestion
      {loading === true ? (
```

2022-04-26 01:40 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
> -
undo

2022-04-26 01:40 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.tsx
> -
undo

2022-04-26 02:04 UTC, tataihono approved these changes

2022-04-26 02:26 UTC, merged