fix: radio question remove inbuilt question and description
JesusFilm/core pull request #527
Opened 2022-04-26 03:20 UTC by storyworks

# Description

Removes the inbuilt question and description in RadioQuestionBlock. These will be created as seperate TypographyBlocks.

[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4874313225)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] No heading / description as part of radio question
- [ ] Selecting the RadioQuestion shows the AddOption button, clicking on an option selects it, must click again to edit option.

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-04-26 20:03 UTC, tataihono requested changes
no using class names directly. also you have some dependency issues.

2022-04-26 20:03 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
> +    <Box className="MuiButtonGroup-root MuiButtonGroup-grouped MuiButtonGroup-groupedVertical">
don't do this. Just use button group. DIrectly using classes like this is very bad since these class names are not a guarantee.

2022-04-26 21:39 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
> +    <Box className="MuiButtonGroup-root MuiButtonGroup-grouped MuiButtonGroup-groupedVertical">
I'm doing this because it gets put within a button group (See RadioQuestion block), when the radio options render in the DOM however - each normal radio option gets wrapped in a div that has these classes on it that determine styling but this RadioOption doesn't. So I'm adding this manually to mimic what should happen. I'm still not sure what it doesn't get generated...

2022-04-26 21:41 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
> +    <Box className="MuiButtonGroup-root MuiButtonGroup-grouped MuiButtonGroup-groupedVertical">
Just copy in the relevant styles to sx. Don’t use underlying classes. Material ui does not guarantee these won’t change in future versions.

2022-04-26 22:48 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
> +    <Box className="MuiButtonGroup-root MuiButtonGroup-grouped MuiButtonGroup-groupedVertical">
That would require to use admin-only logic to style the journeys-ui RadioOption block too.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/10802634/165404947-42a395ab-e3fa-471f-91d3-7308f93f7f65.png">

You would think that if the classes ever changed, the custom styles you put in would no longer match the rest of the block - so the problem you're trying to avoid would remain?

2022-04-26 22:48 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
> +    <Box className="MuiButtonGroup-root MuiButtonGroup-grouped MuiButtonGroup-groupedVertical">
That would require to use admin-only logic to style the journeys-ui RadioOption block too. (Box and classes removed below)

<img width="327" alt="image" src="https://user-images.githubusercontent.com/10802634/165404947-42a395ab-e3fa-471f-91d3-7308f93f7f65.png">

You would think that if the classes ever changed, the custom styles you put in would no longer match the rest of the block - so the problem you're trying to avoid would remain?

2022-04-26 23:15 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
> +    <Box className="MuiButtonGroup-root MuiButtonGroup-grouped MuiButtonGroup-groupedVertical">
Adding the Box mimics the wrappers around each RadioOption - ButtonGroup then applies classNames to each div and styling is fixed.

2022-04-27 01:41 UTC, tataihono approved these changes

2022-04-27 01:41 UTC, merged