Themes
JesusFilm/core pull request #53
Opened 2021-09-26 23:45 UTC by storyworks

2021-09-27 00:46 UTC, tataihono requested changes
theme folder should be moved to themes
theme map should just become index.ts

2021-09-27 00:46 UTC, tataihono commented on apps/journeys/pages/[journeyId].tsx
> +          locale
don't think locale is needed for this PR.

2021-09-27 00:46 UTC, tataihono commented on apps/journeys/pages/index.tsx
> +    <ThemeProvider theme={themes.light}>
this should use JourneyThemeProvider
```suggestion
    <JourneyThemeProvider themeName={ThemeName.light}>
```

2021-09-27 00:46 UTC, tataihono commented on apps/journeys/src/components/JourneysThemeProvider/JourneysThemeProvider.spec.tsx
> +      <JourneysThemeProvider themeName={'light' as ThemeName}>
```suggestion
      <JourneysThemeProvider themeName={ThemeName.light}>
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/themeMap.ts
> +import { baseLight } from './themes'
```suggestion
import { light, dark } from './themes'
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/themes.ts
> +export const baseLight = createTheme({
```suggestion
export const light = createTheme({
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/themes.ts
> +  ...baseColorsLight
```suggestion
  ...lightColors
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/themes.ts
> +  ...baseColorsDark
```suggestion
  ...darkColors
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/tokens/colors.ts
> +export const baseColorsLight = {
```suggestion
export const lightColors: ThemeOptions = {
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/tokens/colors.ts
> +    mode: 'light' as PaletteMode,
```suggestion
    mode: 'light',
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/tokens/colors.ts
> +export const baseColorsDark = {
same as above
```suggestion
export const darkColors: ThemeOptions = {
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/tokens/spacing.ts
> +export const baseSpacing = {
```suggestion
export const baseSpacing: ThemeOptions = {
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/tokens/spacing.ts
> +    space: {
This should be optional
```suggestion
    space?: {
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/tokens/colors.ts
> +    surfaceAlt: PaletteOptions['primary']
```suggestion
    surfaceAlt?: PaletteOptions['primary']
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/tokens/colors.ts
> +    surface: PaletteOptions['primary']
```suggestion
    surface?: PaletteOptions['primary']
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/tokens/typography.ts
> +export const baseTypography = {
```suggestion
export const baseTypography: ThemeOptions = {
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/themes.ts
> +import { baseColorsLight, baseColorsDark } from './tokens/colors'
```suggestion
import { lightColors, darkColors } from './tokens/colors'
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/themeMap.ts
> +  light: baseLight
```suggestion
  light,
  dark
```

2021-09-27 00:46 UTC, tataihono commented on libs/shared/ui/src/libs/theme/themeMap.ts
> +export const themes = {
```suggestion
export default {
```

2021-09-27 01:17 UTC, storyworks commented on libs/shared/ui/src/libs/theme/themes.ts
> +import { baseColorsLight, baseColorsDark } from './tokens/colors'
I'll change everything to what you've suggested although now I'm remembering why I didn't call it "light" and "dark" to begin with - it's that they are modes of a theme rather than the name of a theme itself and we'd possibly get light and dark versions of future themes.

2021-09-27 01:21 UTC, storyworks commented on libs/shared/ui/src/libs/theme/tokens/colors.ts
> +    surface: PaletteOptions['primary']
Is this because we may use these color tokens on non-journey related theming? It is needed at the moment since Typography and Button blocks get their colors from the surface token.

2021-09-27 02:45 UTC, tataihono commented on libs/shared/ui/src/libs/theme/tokens/colors.ts
> +    surface: PaletteOptions['primary']
Palette is where that becomes required. Otherwise every time you want to write a PaletteOptions override you have to define a surface.

2021-09-27 02:46 UTC, tataihono commented on apps/journeys/pages/[journeyId].tsx
> +          locale
how come this was resolved?

2021-09-27 02:47 UTC, tataihono commented on apps/journeys/pages/index.tsx
> +    <ThemeProvider theme={themes.light}>
also how come this was resolved?

2021-09-27 21:40 UTC, tataihono submitted a review, later dismissed

2021-09-27 21:40 UTC, tataihono commented on apps/journeys/pages/index.tsx
> +import { Box, Button, Container, ThemeProvider } from '@mui/material'
You should use the ThemeProvider from the @core/shared/ui here. Don't unpack the logic of that component in here.

2021-09-27 21:40 UTC, tataihono commented on apps/journeys/pages/index.tsx
> +    <ThemeProvider theme={themes.base.light}>
```suggestion
    <ThemeProvider themeName={ThemeName.base} themeMode={ThemeMode.light}>
```

2021-09-27 21:40 UTC, tataihono commented on libs/shared/ui/src/libs/themes/ThemeProvider/ThemeProvider.spec.tsx
> +        themeName={'base' as ThemeName}
```suggestion
        themeName={ThemeName.base}
```

2021-09-27 21:40 UTC, tataihono commented on libs/shared/ui/src/libs/themes/ThemeProvider/ThemeProvider.spec.tsx
> +        themeMode={'light' as ThemeMode}
```suggestion
        themeMode={ThemeMode.light}
```

2021-09-27 21:40 UTC, tataihono commented on libs/shared/ui/src/libs/themes/index.ts
> +export default themes
remove

2021-09-27 23:49 UTC, tataihono requested changes

2021-09-27 23:49 UTC, tataihono commented on libs/shared/ui/src/libs/themes/base/tokens/typography.ts
> +          props: { variant: 'overline' as const, gutterBottom: true },
```suggestion
          props: { variant: 'overline', gutterBottom: true },
```

2021-09-27 23:49 UTC, tataihono commented on libs/shared/ui/src/libs/themes/base/tokens/typography.ts
> +      textTransform: 'uppercase' as const
```suggestion
      textTransform: 'uppercase'
```

2021-09-27 23:49 UTC, tataihono commented on libs/shared/ui/src/libs/themes/index.ts
> +type ThemeMap = Record<ThemeName, Record<ThemeMode, Theme>>
why did this get resolved. You don't need to manually type this?

2021-09-27 23:49 UTC, tataihono commented on libs/shared/ui/src/libs/themes/ThemeProvider/ThemeProvider.spec.tsx
> +import { render } from '@testing-library/react'
This file actually should be moved from src/libs to src/components since its actually a component. Libs shouldn't contain any .tsx files.

2021-09-28 00:51 UTC, storyworks commented on libs/shared/ui/src/libs/themes/index.ts
> +const themes: ThemeMap = {
Just checked again, not getting the error anymore so will remove.

2021-09-28 01:03 UTC, tataihono approved these changes

2021-09-28 01:10 UTC, merged