feat: added loading state
JesusFilm/core pull request #532
Opened 2022-04-26 19:49 UTC by csiyang

# Description
Add loading state for image on video setting drawer for the cover image

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4874319622)

# How should this PR be QA Tested?
- [ ] Both the image on the dialog and drawer should show loading circles for image loading when creating or update video cover image

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-04-26 21:34 UTC, tataihono requested changes

2022-04-26 22:10 UTC, tataihono requested changes

2022-04-26 22:10 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
> +    onLoad?.()
this is going to be called as soon as this component is instantiated.

I think this component needs an independent loading state.

2022-04-26 22:10 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
> +      await waitFor(() => expect(getByRole('progressbar')).toBeInTheDocument())
stacked waitfors are bad form. You should only need one of these and then the others should just pass right?

2022-04-27 20:31 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
> +      await waitFor(() => expect(getByRole('progressbar')).toBeInTheDocument())
No, each one is needed

2022-04-27 22:59 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
> +  useEffect(() => {
Using this useEffect instead of another state to manage loading for parent. Had to disable the eslint warning since I don't want to fire on onLoad and onLoading.

2022-04-29 01:03 UTC, tataihono approved these changes

2022-04-29 01:04 UTC, merged