feat: add stepViewEvent to step block
JesusFilm/core pull request #568
Opened 2022-05-05 21:06 UTC by csiyang

# Description

Creates a stepViewEvent every time a step block is viewed on a journey

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787374/todos/4816009972)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] stepViewEventCreate mutation should be called once when you view a step
- [ ] stepViewEventCreate mutation should not be called in admin

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-05-05 21:24 UTC, csiyang commented
This PR requires [this](https://github.com/JesusFilm/core/pull/566) to be merged first

2022-05-08 20:54 UTC, tataihono requested changes

2022-05-08 20:54 UTC, tataihono commented on libs/journeys/ui/src/components/Step/Step.tsx
> +  uuid = uuidv4,
this is just for testing. You should instead stub this in jest. @GeronimoJohn had to learn how to do this. Maybe follow up with him how to do it.

2022-05-08 20:54 UTC, tataihono commented on libs/journeys/ui/src/components/Step/Step.tsx
> +    if (wrappers == null) {
This is not a good metric for determining if this is contained on journeys.

2022-05-08 20:54 UTC, tataihono commented on libs/journeys/ui/src/components/Step/Step.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
should not just disable this check.

2022-05-13 04:16 UTC, tataihono approved these changes

2022-05-13 04:16 UTC, merged