Conductor to use Swiper JS
JesusFilm/core pull request #57
Opened 2021-09-29 01:19 UTC by tataihono

- use swiper v6 (instead of v7 as it uses ESM which breaks jest and storybook)
- remove padding from default decorator, JourneyProgress, RadioQuestion
- fix video data-testId to data-testid
- add conductor story

2021-09-29 22:53 UTC, storyworks requested changes

2021-09-29 22:53 UTC, storyworks commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +    <Container sx={{ p: 0 }}>
Currently this is adding 16px padding on Tablet + screen sizes, do we want that?

2021-09-29 22:53 UTC, storyworks commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +              `linear-gradient(90deg, ${theme.palette.background.default}FF 0%, ${theme.palette.background.default}00 100%)`
Looks like the white gradient isn't even visible on the mobile designs - did Vlad intend to include this only on desktop?

2021-09-29 23:09 UTC, tataihono commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +    if (swiper != null && activeBlock != null && treeBlocks != null) {
Yes.

2021-09-29 23:50 UTC, tataihono commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +              `linear-gradient(90deg, ${theme.palette.background.default}FF 0%, ${theme.palette.background.default}00 100%)`
Are you able to raise that in chromatic so it can be seen by Vlad?

2021-09-29 23:53 UTC, tataihono commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +    <Container sx={{ p: 0 }}>
Thanks good pickup. I've swapped this for:
```
<Container disableGutters>
```

2021-09-29 23:56 UTC, tataihono commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +              `linear-gradient(90deg, ${theme.palette.background.default}FF 0%, ${theme.palette.background.default}00 100%)`
I've removed this on mobile.

2021-09-29 23:57 UTC, tataihono commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +  const { setTreeBlocks, nextActiveBlock, treeBlocks, activeBlock } =
**Not in these changes but in blocks.ts if (args?.id != null) { should be a check for undefined instead?** 

args?.id is a nullish check. So undefined is already done here. Unless you think it should only be a check for undefined.

2021-09-30 00:00 UTC, tataihono commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +  const { setTreeBlocks, nextActiveBlock, treeBlocks, activeBlock } =
**Line 41 in blocks.ts should be block != undefined ?**

Do you mean to explicitly check for undefined? Or is a nullish check suitable?

2021-09-30 00:22 UTC, storyworks commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +  const { setTreeBlocks, nextActiveBlock, treeBlocks, activeBlock } =
oh I didn't realise != null also included undefined. That's ok then.. 
I think I'm just not used to seeing so many null checks with React/TS I guess gotta get used to it now with GraphQL in the picture.

What about the StepBlock check - no change with that and no comment on it either, any thoughts?

2021-09-30 00:44 UTC, tataihono commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +  const { setTreeBlocks, nextActiveBlock, treeBlocks, activeBlock } =
I don't want to deviate from the standard js rule set. Happy to have a conversation outside of this PR on that.

I included your stepblock check change.

2021-09-30 04:15 UTC, storyworks commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +  const { setTreeBlocks, nextActiveBlock, treeBlocks, activeBlock } =
Where is the `block.ts` StepBlock check change?

2021-09-30 04:24 UTC, tataihono commented on apps/journeys/src/components/Conductor/Conductor.tsx
> +  const { setTreeBlocks, nextActiveBlock, treeBlocks, activeBlock } =
already done :)

2021-09-30 04:27 UTC, storyworks approved these changes
The RadioOption should be white onDark Card but that's to be sorted in another PR

2021-09-30 06:04 UTC, merged