refactor signup response to event
JesusFilm/core pull request #570
Opened 2022-05-05 23:12 UTC by csiyang

# Description

Refactor signUp response to event

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787374/todos/4897009211)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Clicking sign up button with valid details in form should call signUpSubmissionEventCreate mutation

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-05-08 20:59 UTC, tataihono commented on libs/journeys/ui/src/components/SignUp/SignUp.tsx
>        // TODO: Set server error responses when available
can drop this comment since we don't care about the response.

2022-05-08 21:11 UTC, tataihono requested changes

2022-05-08 21:11 UTC, tataihono commented on libs/journeys/ui/src/components/SignUp/SignUp.tsx
> +    void signUpSubmissionEventCreate({
We need to handle the failures here since its critical that we get the user input here.

2022-05-10 02:03 UTC, csiyang commented on libs/journeys/ui/src/components/SignUp/SignUp.tsx
> +    void signUpSubmissionEventCreate({
@tataihono Im using the snackbar to show this error. Had to add the provider around journeys. Thoughts?

2022-05-10 23:26 UTC, tataihono submitted a review, later dismissed

2022-05-10 23:26 UTC, tataihono commented on libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
> +  // })
please flesh out this test.

2022-05-11 23:41 UTC, tataihono approved these changes

2022-05-13 05:23 UTC, tataihono approved these changes

2022-05-13 05:35 UTC, merged