feat: add click event on button click
JesusFilm/core pull request #573
Opened 2022-05-06 01:38 UTC by csiyang

# Description

Creates click event when a button is clicked

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787374/todos/4897008404)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Calls ButtonClickEventCreate mutation on button click

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-05-09 00:46 UTC, tataihono submitted a review, later dismissed
the api changes need to be rolled out separately.

2022-05-09 01:30 UTC, csiyang commented
Is dependant on [this PR](https://github.com/JesusFilm/core/pull/571) to be merged first

2022-05-13 04:46 UTC, tataihono requested changes

2022-05-13 04:46 UTC, tataihono commented on libs/journeys/ui/src/components/Button/Button.stories.tsx
> +import { Button } from './Button'
```suggestion
import { Button } from '.'
```

2022-05-13 04:47 UTC, tataihono commented on libs/journeys/ui/src/components/Button/Button.spec.tsx
> +import { Button, BUTTON_CLICK_EVENT_CREATE } from './Button'
import { BUTTON_CLICK_EVENT_CREATE } from './Button'
import { Button } from '.'

2022-05-13 05:16 UTC, tataihono approved these changes

2022-05-13 05:16 UTC, merged