refactor: move usejourney to journeysui
JesusFilm/core pull request #578
Opened 2022-05-09 03:42 UTC by csiyang

# Description

Move useJourney from journeys-admin to journeys-ui.

- Link to Basecamp Todo

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] None

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-05-10 23:00 UTC, tataihono requested changes

2022-05-10 23:00 UTC, tataihono commented on libs/journeys/ui/src/libs/index.ts
> +} from './context'
JOURNEY_FIELDS should also be exported.

2022-05-10 23:04 UTC, csiyang commented on apps/journeys-admin/tsconfig.json
> +    "../../libs/journeys/ui/src/libs/context/JourneyContext.spec.tsx"
It changed automatically...

2022-05-11 00:07 UTC, tataihono requested changes

2022-05-11 00:07 UTC, tataihono commented on apps/journeys-admin/pages/journeys/[journeySlug].tsx
> -import { BLOCK_FIELDS, IMAGE_FIELDS } from '@core/journeys/ui'
This file should also bring in Journey Fields.

2022-05-11 01:22 UTC, merged