fix: deleting card on next card properties
JesusFilm/core pull request #636
Opened 2022-05-20 00:04 UTC by GeronimoJohn

# Description

When deleting a card while the next card properties drawer is open. Deleting a card results in an error.

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4951056297)

# How should this PR be QA Tested?

While a card is selected, click the Properties tab and click on the next step to open the drawer

- [ ] Deleting a card while the next card properties drawer is open should be successful

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-05-30 04:12 UTC, csiyang requested changes

2022-05-30 04:12 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
```suggestion
if (currentBlock == null) return 
```

2022-05-30 04:12 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
> +        id: currentBlock?.id,
```suggestion
        id: currentBlock.id,
```

2022-05-30 04:12 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
> +          nextBlockId: currentBlock?.id
```suggestion
          nextBlockId: currentBlock.id
```

2022-05-30 04:15 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
Tried this already, but still gave an error - will look into it again

2022-05-30 04:32 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Conditions/Conditions.tsx
> +        checked={block?.locked}
What happens here if block is null? 

Can be do a block null check here, or make checked nullable and disable if null on toggleOption?

2022-06-03 03:28 UTC, tataihono requested changes

2022-06-03 03:28 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Cards/Cards.tsx
> +    ({ id }) => currentBlock != null && currentBlock.nextBlockId === id
```suggestion
    ({ id }) => currentBlock?.nextBlockId === id
```

2022-06-03 03:28 UTC, tataihono commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Conditions/Conditions.tsx
> +        checked={block != null ? block.locked : false}
```suggestion
        checked={block?.locked ?? false}
```

2022-06-26 23:23 UTC, tataihono commented
@GeronimoJohn you still working on this?

2022-06-27 00:55 UTC, GeronimoJohn commented
@tataihono oh yes, this is a pretty straightforward fix-ish. I don't think that I'll have time to work on the merge changes for this one during this cycle. Can re-open it at a cooldown somehow

2022-07-01 04:52 UTC, closed without merging