fix: flakey vr tests
JesusFilm/core pull request #637
Opened 2022-05-20 02:53 UTC by GeronimoJohn

# Description

Tidy Up flakey VR tests

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4928530180)

# How should this PR be QA Tested?

- [ ] No more flakey VR tests

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-05-24 21:06 UTC, tataihono requested changes

2022-05-24 21:06 UTC, tataihono commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.stories.tsx
> +      disableSnapshot: false
not sure this is a solution??

2022-05-24 21:21 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.stories.tsx
> +      disableSnapshot: false
Will look into another solution

2022-05-29 23:25 UTC, GeronimoJohn commented
I've noticed that the card preview's image seems really flakey. This PR #595, fixes the image issue by using a different image instead. Will wait for it to be merged and see if we still get the same flakey VR tests relating to images.

2022-06-03 03:23 UTC, tataihono approved these changes

2022-06-03 03:24 UTC, merged

2022-06-29 03:32 UTC, storyworks commented on apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
> +    }
Can we remove all these this since Chromatic recommended diffThresholds are already quite accurate (I've tested by globally changing changing it). It's better to actually change the image used in the test since we're still getting flakey image issues + this affects our sensitivity to pick up other changes on the page