feat: terms and conditions and privacy policy links
JesusFilm/core pull request #662
Opened 2022-05-25 23:33 UTC by GeronimoJohn

# Description

Add the terms and conditions and privacy policy link of Cru underneath our cards

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27717553/todos/4960684431)

# How should this PR be QA Tested?

When visiting our journey, underneath the cards there should now be a terms and conditions and privacy policy link

- [ ] Clicking on the Terms link should redirect you to Cru's Terms and Conditions webpage
- [ ] Clicking on the Privacy link should redirect you to Cru's Privacy Policy webpage

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-05-26 05:02 UTC, tataihono requested changes

2022-05-26 22:11 UTC, GeronimoJohn commented on apps/journeys/src/components/Conductor/Links/Links.tsx
> +      <Typography variant="caption">{t('NextSteps © 2022')}</Typography>
This string injection, I think, doesn't work in storybook yet but works as expected on frontend. Though I'm assuming the PR `add i18n to storybook` covers this?

2022-05-27 00:29 UTC, tataihono commented on apps/journeys/src/components/Conductor/Links/Links.tsx
> +      <Typography variant="caption">{t('NextSteps © 2022')}</Typography>
Right

2022-05-27 01:02 UTC, tataihono submitted a review, later dismissed

2022-05-27 01:02 UTC, tataihono commented on libs/locales/en/apps-journeys_old.json
> +{
delete this file

2022-05-27 01:02 UTC, tataihono commented on apps/journeys/src/components/Footer/Footer.tsx
> +          }
this style change should be handled in the theme.

2022-05-27 02:42 UTC, GeronimoJohn commented on apps/journeys/src/components/Footer/Footer.tsx
> +          }
Added this here because it might/will affect the rest of our typography components if I put this on the theme.

2022-05-27 02:43 UTC, GeronimoJohn commented on libs/shared/ui/src/libs/themes/base/tokens/colors.ts
> +          }
I found that adding the opacity achieves the same effect that we're trying to do with this

2022-06-16 19:07 UTC, tataihono approved these changes

2022-06-16 20:59 UTC, merged