fix: get step heading logic
JesusFilm/core pull request #670
Opened 2022-05-26 23:19 UTC by csiyang

# Description

getStepHeading was only getting the first typog block encountered. Extended logic so that it will return the biggest typog block based on variant.

- Link to Basecamp Todo

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] On admin the 'Next Card' property should display the correct heading for the next card
- [ ] On journeys, the correct current step name should be displayed in browser tab title
- [ ] Correct current name should be sent to GA4

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-05-26 23:27 UTC, csiyang commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.spec.ts
> +            __typename: 'ButtonBlock',
This buttonBlock is important since the reduce function returns the first block if no typography blocks are found

2022-05-26 23:27 UTC, csiyang commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +function getStepNumber(stepId: string, steps: TreeBlock[]): string {
This function is still the same, just moved it

2022-05-26 23:27 UTC, csiyang commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +const orderedTypogVariants: TypographyVariant[] = [
variant from globalTypes are ordered in alphabetical lol

2022-05-26 23:27 UTC, csiyang commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +function typogReducer(previous: TreeBlock, current: TreeBlock): TreeBlock {
previous cant have undefined assigned to it (typescript error) so this returns the first block or the biggest typog block. There is a further check for typog block below.

2022-05-26 23:29 UTC, csiyang commented
@GeronimoJohn can you QA if you have time? (Don't worry about the GA4 one)

2022-05-27 03:50 UTC, tataihono requested changes
I think this file also needs to take in a t function for translation.

2022-05-27 03:50 UTC, tataihono commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +const orderedTypogVariants: TypographyVariant[] = [
orderedVariants since this is local to this file.

2022-05-27 03:50 UTC, tataihono commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +function typogReducer(previous: TreeBlock, current: TreeBlock): TreeBlock {
```JS
if (current.__typename !== 'TypographyBlock') return previous

if (previous.__typename !== 'TypographyBlock') return current

const previousIndex = orderedTypogVariants.findIndex(
  (variant) => variant === previous.variant
)

const currentIndex = orderedTypogVariants.findIndex(
  (variant) => variant === current.variant
)

return currentIndex < previousIndex ? current : previous
```

2022-05-27 03:50 UTC, tataihono commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +  TypographyVariant.overline
this array has to be reversed. If the typography variant is not in this array then the findIndex above will return -1 for it. Since you are doing a `currentIndex < previousIndex` then you are going to get -1 < n which is going to be true.

2022-05-27 06:19 UTC, csiyang commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +function typogReducer(previous: TreeBlock, current: TreeBlock): TreeBlock {
why previous and current nullable?

2022-05-27 07:17 UTC, tataihono requested changes

2022-05-27 07:17 UTC, tataihono commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +    return `${t('Step')} ${index + 1}`
```suggestion
    return t('Step {{number}}', { n: index + 1 })
```

2022-05-27 07:17 UTC, tataihono commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +    return `${t('Step')} ${index + 1}`
this is just in case the locale prepends the number before the word step. Usually we let the translator decide this.

2022-06-02 22:06 UTC, tataihono requested changes
two small changes

2022-06-02 22:06 UTC, tataihono commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +  if (previous == null || previous.__typename !== 'TypographyBlock')
```suggestion
  if (previous == null)
```

2022-06-02 22:06 UTC, tataihono commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +  previous: TreeBlock | null,
```suggestion
  previous: TreeBlock<TypographyFields> | null,
```

2022-06-02 22:06 UTC, tataihono commented on libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
> +): TreeBlock {
```suggestion
): TreeBlock<TypographyFields> {
```

2022-06-03 03:29 UTC, tataihono approved these changes

2022-06-03 03:46 UTC, merged