fix: step order on delete
JesusFilm/core pull request #677
Opened 2022-06-01 01:36 UTC by csiyang

# Description

- Correctly updates parent order on step blocks when a block is deleted. 
- Fixed logic on getSelected block to select after a block is selected

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27717553/todos/4985508524)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] When a card is deleted before the last card. Adding a new card should create it after the last card.

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-06-01 02:20 UTC, csiyang commented on apps/api-journeys/src/app/modules/block/block.service.ts
> +            AND block.__typename == 'StepBlock'
Yeah all blocks where getting returned from this query. I could've done `AND block.parentBlockId == null` but thought this was more descriptive

2022-06-02 22:08 UTC, tataihono commented on apps/api-journeys/src/app/modules/block/block.service.ts
> +            AND block.__typename == 'StepBlock'
this is a good check I think because we might have other non-step primary blocks in the future.

2022-06-02 22:11 UTC, tataihono requested changes
no api changes with frontend changes in the same PR.

2022-06-02 23:06 UTC, tataihono approved these changes

2022-06-02 23:06 UTC, merged