feat: new journey statuses
JesusFilm/core pull request #687
Opened 2022-06-07 23:01 UTC by mikeallisonJS

# Description

This PR adds archive/delete/restore functionality to the journeys API

https://3.basecamp.com/3105655/buckets/27930172/todolists/5007994015

# How should this PR be QA Tested?

This will require UI components to fully test due to authentication. It should have full unit-test coverage and uses no new service calls.

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-06-07 23:23 UTC, csiyang commented on apps/api-journeys/src/app/modules/journey/journey.graphql
> +  journeyArchive(id: ID!): Journey
I wonder this could take an array of id's to accomodate for the "all" mutations? (archive all, delete all etc...)

2022-06-07 23:25 UTC, mikeallisonJS commented on apps/api-journeys/src/app/modules/journey/journey.graphql
> +  journeyArchive(id: ID!): Journey
Building a 2nd set of endpoints for that, based off the current user

2022-06-07 23:31 UTC, csiyang approved these changes

2022-06-13 23:38 UTC, tataihono requested changes

2022-06-13 23:38 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.graphql
> +  journeyTrashAllArchived: [Journey]
can these get some comments on how they are expected to be used?

2022-06-13 23:38 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.resolver.ts
> +    })
small nit. not worth calculating lastActiveStatus unless the if statement is false.

```suggestion
    if (
      result.status === JourneyStatus.draft ||
      result.status === JourneyStatus.published
    ) {
      throw new UserInputError('Journey is already active')
    }
    
    const lastActiveStatus =
      result.publishedAt == null ? JourneyStatus.draft : JourneyStatus.published

    return await this.journeyService.update(id, {
      status: lastActiveStatus
    })
```

2022-06-13 23:38 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.resolver.ts
> +        ...j,
small nit. Not a huge fan of shorthand.
```suggestion
      .filter((journey) => journey.status === JourneyStatus.archived)
      .map((journey) => ({
        ...journey,
```

2022-06-13 23:38 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.resolver.ts
> +    const results: Journey[] = (await this.journeyService.getAllByOwner(userId))
wonder if we could pass a filter to getAllByOwner? if the user only has hundreds of journeys these are all going to be loaded into memory just to be filtered down.

2022-06-13 23:38 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.resolver.ts
> -
what happens if the status field is not set in the db? I assume this is going to fail? Should be a default if status is undefined or null.

2022-06-13 23:38 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.service.ts
> +  async getAllByOwnerEditor(
```suggestion
  async getAllByOwnerOrEditor(
```

2022-06-13 23:38 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.service.ts
> +           && journey.status IN ${status}
can status be optional here?

2022-06-14 03:31 UTC, mikeallisonJS commented on apps/api-journeys/src/app/modules/journey/journey.resolver.ts
> -
Status is a required field, I'm not sure there is any case it could

2022-06-14 03:31 UTC, mikeallisonJS commented on apps/api-journeys/src/app/modules/journey/journey.service.ts
> +  async getAllByOwnerEditor(
This is the original name prior to this PR, do you want it changed?

2022-06-14 03:36 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.service.ts
> +  async getAllByOwnerEditor(
oh. leave it as is.

2022-06-14 03:40 UTC, tataihono commented on apps/api-journeys/src/app/modules/journey/journey.resolver.ts
> -
right. Looks like the db is already populated.

2022-06-14 04:11 UTC, tataihono approved these changes

2022-06-15 22:38 UTC, csiyang approved these changes

2022-06-15 22:46 UTC, merged