feat: block duplication api
JesusFilm/core pull request #705
Opened 2022-06-17 05:37 UTC by storyworks

# Description

Allows us to duplicate blocks (inc cards). `getDuplicateBlockAndChildren` will be reused for each StepBlock on a journey when duplicating journeys. 

- [Duplicate Block API](https://3.basecamp.com/3105655/buckets/27930137/todos/5008338102)
- [Duplicate Card API](https://3.basecamp.com/3105655/buckets/27930137/todos/5008354498)

# How should this PR be QA Tested?

Manually tested locally - I created a duplicate button and works for the following scenarios
- [ ] Duplicate a block with no children (typography / radio option / sign up / image / video) & duplicated block appears after original. Visually VideoBlock which takes up the entirety of the card so duplicate VideoBlocks are on stacked on top.
- [ ] Duplicate a block with children (radio question / button) & duplicated block appears after original
- [ ] Duplicate a step / card & duplicated block appears at end of list

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-06-17 05:42 UTC, storyworks commented on apps/api-journeys/src/app/modules/block/block.service.ts
> +  async duplicateBlock(
Calls `getDuplicateBlockAndChildren` and positions the newly created duplicate block in the correct place.

Would appreciate thoughts on the name `getDuplicateBlockAndChildren` because this just retrieves the new block objects we want to save. Line 103 takes this data and actually creates the blocks.

2022-06-17 05:44 UTC, storyworks commented on apps/api-journeys/src/app/modules/block/block.service.ts
> +      const duplicateBlockAndChildren = await this.saveAll(blockAndChildrenData)
We want the `blockAndChildrenData` to have the `_key` defined so the `_id` will be generated based off that. Otherwise the values we generated for `id` in `getDuplicateBlockAndChildren` get overwritten by arrango's autogenerated `_id`

2022-06-17 05:46 UTC, storyworks commented on apps/api-journeys/src/app/modules/block/block.service.ts
> +      const duplicatedBlock = {
`.getSiblingsInternal` returns block objects with keys, so adding key to this to keep the siblings array consistent after inserting this in.

2022-06-17 05:56 UTC, storyworks commented on apps/api-journeys/src/app/modules/block/block.service.ts
> +    duplicateId?: string
A block may generate a duplicateId for it's child - this is needed in the cases where we need to set a child's id in the parent (eg for `endIconId, posterBlockId ...`)

2022-06-21 03:48 UTC, storyworks commented on apps/api-journeys/src/app/modules/block/block.service.ts
> +      siblings.splice(insertIndex, 0, duplicatedBlock)
Today we've just found an issue where the duplicated block was being returned in the data twice (doesn't impact visuals, but the same block is repeated in the returned data. Fixing it now)

2022-06-21 04:06 UTC, tataihono requested changes

2022-06-21 04:06 UTC, tataihono commented on apps/api-journeys/src/app/modules/block/block.graphql
> +  blockDuplicate(id: ID!, journeyId: ID!, parentOrder: Int): [Block!]!
can you document the parent order arg here? something communicating that this is where the duplicated block should be placed otherwise where it goes if null?

2022-06-21 23:48 UTC, storyworks commented on apps/api-journeys/src/app/modules/block/block.service.ts
> +            parentBlockId
In a subsequent PR (journeys duplication api) I extract this out into `defaultDuplicateBlock` and spread it over the explicitly defined blocks above to simplify.

2022-06-22 00:45 UTC, tataihono requested changes

2022-06-22 00:45 UTC, tataihono commented on apps/api-journeys/src/app/modules/block/block.graphql
> +  blockDuplicate(id: ID!, journeyId: ID!, parentOrder: Int): [Block!]!
https://www.apollographql.com/docs/apollo-server/schema/schema/#descriptions-docstrings

```
blockDuplicate(
	id: ID!
	journeyId: ID!
	"Description for an argument"
	parentOrder: Int
): [Block!]!
```

2022-06-23 05:30 UTC, tataihono approved these changes

2022-06-23 05:33 UTC, storyworks commented
Will update this api to look through a list of all generated child ids, and map to an attribute if it's key ends with "Id". This removes the need to know about the internals of a particular block.

2022-06-23 05:33 UTC, merged