feat: add analytics page
JesusFilm/core pull request #717
Opened 2022-06-22 23:06 UTC by csiyang

# Description

Add analytics page for journeys full report

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27931561/todolists/5008386044)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Should show a test report when visiting localhost:4200/analytics

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-06-22 23:13 UTC, csiyang commented
Requires API changes from https://github.com/JesusFilm/core/pull/693 to be merged first

2022-06-26 23:16 UTC, csiyang commented on libs/nest/powerBi/src/index.ts
> +export { getPowerBiEmbed } from './lib/embed'
@tataihono I still have this whole folder left over, is it still needed?

2022-06-27 00:05 UTC, tataihono requested changes

2022-06-27 00:05 UTC, tataihono commented on apps/journeys-admin/pages/analytics/index.tsx
> +import { ReactElement } from 'react'
this file should just be apps/journeys-admin/pages/analytics.tsx

2022-06-27 00:05 UTC, tataihono commented on apps/journeys-admin/pages/analytics/index.tsx
> +})
we should check for analytics flag in launch darkly. redirect them if its not present.

2022-06-27 00:05 UTC, tataihono commented on apps/journeys-admin/src/components/JourneysFullReport/JourneysFullReport.tsx
> +  )
hmm. i am wondering if we should have this component be much simpler. Do you know if the design for the errors and loading will be the same across journeys full/summary and journey full/summary? If so this should be refactored otherwise there is going to be duplicate error and loading logic across these four components. Potentially this component should be the "PowerBiReport" component. under that component you could put the dynamic loader and call that PowerBiReport/Remote or something like that?

2022-06-27 00:19 UTC, csiyang commented on apps/journeys-admin/setupTests.tsx
> +Object.defineProperty(window.self, 'crypto', {
https://community.powerbi.com/t5/Developer/TypeError-cryptoObj-getRandomValues-is-not-a-function-unrelated/m-p/1963294

2022-06-27 00:20 UTC, tataihono commented on apps/journeys-admin/setupTests.tsx
> +Object.defineProperty(window.self, 'crypto', {
can you add a comment to the file.
its not immediately obvious why this is needed to prevent it from being removed in future.

2022-06-27 03:55 UTC, csiyang commented on apps/journeys-admin/src/components/PowerBiReport/PowerBiReport.spec.tsx
> +                    'https://app.powerbi.com/reportEmbed?reportId=f6bfd646-b718-44dc-a378-b73e6b528204&groupId=be8908da-da25-452e-b220-163f52476cdd&w=2&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVVT
@tataihono this needs to be a proper URL or this test fails on github actions. Do you think this URL would stay the same or would it expire too?

2022-06-27 04:12 UTC, tataihono requested changes

2022-06-27 04:12 UTC, tataihono commented on apps/journeys-admin/setupTests.tsx
> +// getRandomValues is required for powerBi unit tests, see isssue: https://community.powerbi.com/t5/Developer/TypeError-cryptoObj-getRandomValues-is-not-a-function-unrelated/m-p/1963294
```suggestion
// getRandomValues is required for powerBi unit tests, see issue: https://community.powerbi.com/t5/Developer/TypeError-cryptoObj-getRandomValues-is-not-a-function-unrelated/m-p/1963294
```

2022-06-27 04:12 UTC, tataihono commented on apps/journeys-admin/src/components/PowerBiReport/Remote/Remote.spec.tsx
> +describe('PowerBiReport', () => {
this should match the name of the file.

2022-06-27 04:12 UTC, tataihono commented on apps/journeys-admin/src/components/PowerBiReport/PowerBiReport.tsx
> +        <ReportSkeleton message={'The analytics are loading...'} />
i dont really think this needs a child component for ReportSkeleton. that component is very simple.

2022-06-27 04:15 UTC, tataihono commented on apps/journeys-admin/src/components/PowerBiReport/PowerBiReport.spec.tsx
> +                    'https://app.powerbi.com/reportEmbed?reportId=f6bfd646-b718-44dc-a378-b73e6b528204&groupId=be8908da-da25-452e-b220-163f52476cdd&w=2&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVVT
you need to stub this. we cannot have tests requiring real world resources being available.

2022-06-27 06:54 UTC, tataihono requested changes
small nit.

2022-06-27 06:54 UTC, tataihono commented on apps/journeys-admin/src/components/PowerBiReport/PowerBiReport.spec.tsx
> +                    'https://app.powerbi.com/reportEmbed?reportId=reportid&groupId=groupId&config=config',
```suggestion
                    'https://app.powerbi.com/reportEmbed?reportId=reportId&groupId=groupId&config=config',
```

2022-06-29 03:24 UTC, tataihono requested changes
nearly there!

2022-06-29 03:24 UTC, tataihono commented on apps/journeys-admin/src/components/DynamicPowerBiReport/DynamicPowerBiReport.tsx
> +}: DynamicPowerBiReportProps): ReactElement {
```suggestion
export function DynamicPowerBiReport(props: ReportProps): ReactElement {
```

2022-06-29 03:24 UTC, tataihono commented on apps/journeys-admin/src/components/DynamicPowerBiReport/DynamicPowerBiReport.tsx
> +  return <Report reportType={reportType} />
```suggestion
  return <Report {...props} />
```

2022-06-29 03:24 UTC, tataihono commented on apps/journeys-admin/src/components/DynamicPowerBiReport/DynamicPowerBiReport.tsx
> +}
```suggestion
```

2022-06-29 03:45 UTC, tataihono submitted a review, later dismissed

2022-06-29 21:19 UTC, tataihono submitted a review, later dismissed

2022-06-30 02:30 UTC, tataihono approved these changes

2022-06-30 02:31 UTC, merged