Fix Radio Question/Option Design
JesusFilm/core pull request #72
Opened 2021-10-05 00:48 UTC by GeronimoJohn

- Update Radio Question/Option to follow the design on figma

2021-10-05 01:33 UTC, storyworks commented on apps/journeys/src/components/blocks/RadioOption/RadioOption.tsx
>      color: '#54A055'
makeStyles is now deprecated https://mui.com/styles/basics/

use `sx` instead? This way you can also reference the theme and apply a typography variant directly to this:

` sx={{
        fontSize: (theme) => theme.typography.body1.fontSize
      }}`

2021-10-05 01:39 UTC, storyworks requested changes

2021-10-05 01:39 UTC, storyworks commented on libs/shared/ui/src/libs/themes/base/tokens/colors.ts
> +            borderColor: '#AAACBB'
![image](https://user-images.githubusercontent.com/10802634/135946809-561c6995-d057-4e45-8f12-fa2b5b6a6740.png)
Still no border when the option is dark.. it only appears once it is clicked - do you know why? Also instead of hardcoding colors, use a color token?

2021-10-05 01:39 UTC, storyworks commented on libs/shared/ui/src/libs/themes/base/tokens/colors.ts
> +            borderColor: '#AAACBB'
Sorry to add onto this ticket but are you also able to fix this corner? 
It looks like a div is set to have a larger `borderRadius` to it's parent div. (Both div's need same borderRadius)
![image](https://user-images.githubusercontent.com/10802634/135946965-7cb1e9a8-d050-48c2-9605-2f20ba934aa2.png)

2021-10-06 00:23 UTC, GeronimoJohn commented on libs/shared/ui/src/libs/themes/base/tokens/colors.ts
> +            borderColor: '#AAACBB'
That border thing is very odd. It's currently working for me at the moment. But will look into that more.

2021-10-06 00:48 UTC, GeronimoJohn commented on apps/journeys/src/components/blocks/RadioOption/RadioOption.tsx
>      color: '#54A055'
Used body2 instead of body1 - followed figma design

2021-10-06 21:53 UTC, storyworks submitted a review, later dismissed

2021-10-06 21:53 UTC, storyworks commented on libs/shared/ui/src/libs/themes/base/tokens/colors.ts
> +            borderColor: secondary.dark
I like that you found a color token that fit for both light / dark themes here. 

To avoid having to add `color: '#FFFFFF80'` in disabled mode you could replace these 2 borderColor and override "borderBottom: `1px solid ${secondary.main}`" secondary dark throws an error :(

2021-10-06 21:53 UTC, storyworks commented on libs/shared/ui/src/libs/themes/base/tokens/colors.ts
> -      disabled: '#26262E',
Use `disabled: secondary.dark` and remove the `&.disabled : {color: _____ }` references? It's also hard because the designs use primary but with opacity changes.. Although it looks like the opacity has just been randomly picked based on what looks nice..

Let's use the tokens for now and if we need the change secondary tokens to be an rgb value (includes opacity), then it should already work for these disabled buttons.

2021-10-06 21:53 UTC, storyworks commented on libs/shared/ui/src/libs/themes/base/tokens/colors.ts
>    components: {
After this line, add `...baseColorsLight.components,`
Then you should be able to remove `MuiButtonGroup` styling in the dark mode and inherit the same one that's used in the light theme.

2021-10-06 22:41 UTC, GeronimoJohn commented on libs/shared/ui/src/libs/themes/base/tokens/colors.ts
> -      disabled: '#26262E',
Have also applied this logic to the light modes disabled.

2021-10-07 00:12 UTC, merged