feat: archive and trash tabs
JesusFilm/core pull request #741
Opened 2022-06-29 21:55 UTC by mikeallisonJS

# Description

Adds archived and trashed tabs to front-end journey list in admin

https://3.basecamp.com/3105655/buckets/27930172/todos/5012753472

# How should this PR be QA Tested?

Archived & Trashed tab views exist

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-06-29 22:19 UTC, csiyang requested changes

2022-06-29 22:19 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
> +import { ReactElement, useEffect } from 'react'
Steven had asked that the `Add` button (on the bottom right) should only show on Active Tab

2022-06-29 22:19 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.tsx
> +                  {t('Trashed Journeys are moved here for up to 40 days.')}
This text should always show up. See [discussion](https://www.figma.com/file/Rt5hcy8zJIUwz4SmnfniSG?node-id=4981:221967#207399858) with Steven

Did we get the delete in 40 days working? If it will work we could keep the text the same

2022-06-29 22:19 UTC, csiyang commented on apps/journeys-admin/pages/index.tsx
> +      : t('Trashed Journeys')
Had asked Tatai about translations, he mentioned Ziwei was still working on something for it before we start implementing it project wide. No need to remove though.

2022-06-29 22:40 UTC, mikeallisonJS commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.tsx
> +                  {t('Trashed Journeys are moved here for up to 40 days.')}
Delete in 40 days is not yet handled in a job, but a filter is in place to hide them at 40 days

2022-06-29 23:28 UTC, csiyang approved these changes

2022-06-30 21:29 UTC, csiyang approved these changes

2022-06-30 21:51 UTC, merged