feat: batch archive delete actions
JesusFilm/core pull request #743
Opened 2022-06-30 01:13 UTC by mikeallisonJS

# Description

This PR adds the ability to batch delete/archive/restore/trash owned journeys

https://3.basecamp.com/3105655/buckets/27930172/todos/5012821094

# How should this PR be QA Tested?

- [ ] Test archive/delete/restore/trash all options in action menu
- [ ] Owned journeys should be affected

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-06-30 03:41 UTC, csiyang requested changes

2022-06-30 03:41 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.tsx
> +        divider={true}
No dividers in the design

```suggestion
```

2022-06-30 03:41 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.tsx
> +        fullscreen={!smUp}
Did they ask for this to be fullscreen in mobile? No designs for it from what I can see.

```suggestion
```

2022-06-30 03:41 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.tsx
> +        fullscreen={!smUp}
Not in the design

```suggestion
```

2022-06-30 03:41 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyListMenu/JourneyListMenu.tsx
> +export default function JourneyListMenu({
I think this component should have stories for the different tabs

2022-06-30 03:41 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
> +    update(cache, { data }) {
Just wondering if there was any particular reason for using this instead of optimistic response?

2022-06-30 03:41 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
> +        fullscreen={!smUp}
remove
```suggestion
```

2022-06-30 03:41 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
> +        fullscreen={!smUp}
remove 
```suggestion
```

2022-06-30 05:23 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.tsx
> +        fullscreen={!smUp}
```suggestion
```

2022-06-30 05:25 UTC, csiyang reviewed
The batch actions weren't working for me when I tried it on this branch

2022-06-30 05:25 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.tsx
> +        fullscreen={!smUp}
```suggestion
```

2022-06-30 20:39 UTC, mikeallisonJS commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
> +    update(cache, { data }) {
Yes, I wanted to ensure the server-side checks for ownership were run and any hiccups were caught

2022-06-30 21:50 UTC, csiyang requested changes

2022-06-30 21:50 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.tsx
> +        enqueueSnackbar(t('Journeys deleted.'), {
```suggestion
        enqueueSnackbar(t('Journeys deleted'), {
```

2022-06-30 21:50 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.tsx
> +        enqueueSnackbar(t('Journeys restored.'), {
```suggestion
        enqueueSnackbar(t('Journeys restored'), {
```

2022-06-30 23:00 UTC, mikeallisonJS commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
> +        enqueueSnackbar(t('Journeys trashed.'), {
I think the 'journeys trashed' is in line with all of the other messages, but am open

2022-06-30 23:24 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
> +        enqueueSnackbar(t('Journeys trashed.'), {
Lets do it your way

2022-07-01 00:11 UTC, csiyang approved these changes

2022-07-01 20:09 UTC, mikeallisonJS commented
merged with associated branch

2022-07-01 20:09 UTC, closed without merging