feat: replace video url with language
JesusFilm/core pull request #769
Opened 2022-07-11 21:39 UTC by mikeallisonJS

# Description

This branch replaces the video url with current video language

- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28141725/todos/5055608394)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Check that video blocks display language instead of url

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

2022-07-11 23:58 UTC, csiyang requested changes

2022-07-11 23:58 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
> +      ?.name.find(({ primary }) => !primary)?.value
Is it ok to just for !primary, how many other names do we usually expect, do we need to make sure to default it to english if it can or something?

2022-07-11 23:58 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
> +          caption={language ?? undefined}
We don't need this anymore since the language state can be undefined right?

```suggestion
          caption={language}
```

2022-07-11 23:58 UTC, csiyang commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
> +    it('shows title and language (with native)', async () => {
Add test for `it("shows title and native language", () => {...})`

2022-07-12 00:03 UTC, mikeallisonJS commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
> +      ?.name.find(({ primary }) => !primary)?.value
The api call defaults it to english for non-primary

2022-07-12 00:06 UTC, mikeallisonJS commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
> +    it('shows title and language (with native)', async () => {
That is the changed test above

2022-07-12 00:14 UTC, mikeallisonJS commented on apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
> +          caption={language ?? undefined}
removed

2022-07-12 01:57 UTC, csiyang submitted a review, later dismissed

2022-07-17 20:58 UTC, csiyang approved these changes

2022-07-18 21:10 UTC, merged