fix: scroll to top after journey duplication
JesusFilm/core pull request #776
Opened 2022-07-13 03:42 UTC by GeronimoJohn

# Description

If our users have a lot of journeys and they've decided to duplicate a journey at the very bottom of the list. Some of them might not be aware that they'll have to scroll up to see the duplicated journey. I've added the ability to scroll to the top after journey duplication.

- Link to Basecamp Todo

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] After duplicating a journey it should scroll to the top displaying the newly duplicated journey

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-07-14 04:53 UTC, csiyang requested changes

2022-07-14 04:53 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.tsx
> +
```suggestion

  const [oldJourneys, setOldJourneys] = useState<Journeys[]>()
  const [journeys, setJourneys] = useState<Journeys[]>()

  useEffect(() => {
    setOldJourneys(journeys)
    setJourneys(data?.journeys)
  }, [data, newJourneys, oldJourneys])

  const duplicatedJourneyId = getDuplicatedJourney(oldJourneys, newJourneys)

```

2022-07-14 04:53 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/utils/getDuplicatedJourney.ts
> +    return newJourneys?.find((journey, i) => journey !== oldJourneys[i])?.id
Can we verify that data.journeys always comes back in the same order?

2022-07-14 04:53 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/utils/getDuplicated.spec.ts
> +    expect(duplicatedJourneyId).not.toEqual('duplicated-journey-id')
I think you need to change the assertion to this since its what the component returns
```suggestion
    expect(duplicatedJourneyId).toBeUndefined()
```

2022-07-14 04:53 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/utils/getDuplicated.spec.ts
> +  it('should not return the duplicated journey id if journey length is the same', () => {
I think we need to change this test should check for the lower and upper conditions where it returns undefined

2022-07-14 04:54 UTC, GeronimoJohn commented on apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/utils/getDuplicatedJourney.ts
> +    return newJourneys?.find((journey, i) => journey !== oldJourneys[i])?.id
@mikeallisonJS would you happen to know if this is true?

2022-07-15 20:25 UTC, mikeallisonJS approved these changes

2022-07-17 22:12 UTC, merged