feat: add single journey report filter
JesusFilm/core pull request #790
Opened 2022-07-25 00:17 UTC by csiyang

# Description

Add filter for journey id for single reports

[- Summary](https://3.basecamp.com/3105655/buckets/28496243/todos/5138437108)
[- Full](https://3.basecamp.com/3105655/buckets/28496243/todos/5138437108)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-07-25 00:18 UTC, csiyang commented
This PR needs to be verified that it actually works once singleFull and singleSummary reports have journeys to filter.

2022-08-22 15:09 UTC, tataihono requested changes
looks good just one typescript change.

2022-08-22 15:09 UTC, tataihono commented on apps/journeys-admin/src/components/DynamicPowerBiReport/Report/Report.tsx
>  }
Typescript can do this for us!

```suggestion
interface MultipleReportProps {
  reportType:
    | JourneysReportType.multipleFull
    | JourneysReportType.multipleSummary
  journeyId: undefined
}

interface SingleReportProps {
  reportType: JourneysReportType.singleFull | JourneysReportType.singleSummary
  journeyId: string
}

export type ReportProps = SingleReportProps | MultipleReportProps
```

2022-08-23 18:48 UTC, tataihono requested changes

2022-08-23 18:48 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.spec.tsx
> +      const originalEnv = process.env
you must restore process.env to its original condition in the after function.

2022-08-23 19:22 UTC, tataihono submitted a review, later dismissed

2022-08-23 19:22 UTC, tataihono commented on apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.spec.tsx
> +      process.env = originalEnv
this needs to happen in an after function not the it.

If this test fails midway through it will not restore the process env.

https://stackoverflow.com/questions/48033841/test-process-env-with-jest

2022-08-23 19:32 UTC, tataihono approved these changes

2022-08-23 19:49 UTC, merged