fix: extend role guard
JesusFilm/core pull request #805
Opened 2022-08-02 04:11 UTC by GeronimoJohn

# Description

Added new roles to our role guard. We've added the ability to check if the user is currently a publisher and if a journey is currently a template.

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28496234/todos/5168827856)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] API only
- [ ] Run any mutation call on the front end and it should still as expected

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-08-02 23:03 UTC, storyworks requested changes

2022-08-02 23:03 UTC, storyworks commented on apps/api-journeys/src/app/lib/roleGuard/roleGuard.ts
let's add:

`const journeyIds = [journeyId].flat()`

This allows us to remove the if/else `Array.isArray(journeyId)` check and just loop through `journeyIds`
Move the `const userRole = await fur(this.userRoleService, userId)` outside the loop, as we fetching it more than once will be redundant. This will save us some db calls making the api faster.

Then for the loop:
```
journeyIds.forEach((journeyId)=>{ 
// fetch journey
// fetch userJourney
// checkAllowedAccess
})
```

2022-08-02 23:31 UTC, GeronimoJohn commented on apps/api-journeys/src/app/modules/journey/journey.resolver.ts
> +      Role.publisher,
Oh good find! I didn't realised I left this

2022-08-03 00:07 UTC, storyworks commented on apps/api-journeys/src/app/lib/roleGuard/roleGuard.ts
You can still convert `journeyId` to always be an array and remove the extra if/else check. Most of the code is unnecessarily duplicated. 

At the very least, move out `userRole` fetching

2022-08-03 21:16 UTC, storyworks commented on apps/api-journeys/src/app/lib/roleGuard/roleGuard.spec.ts
> +    it('should return true if role is publisher and template true', async () => {
`should return true for 1 role and attribute`

2022-08-03 21:17 UTC, storyworks commented on apps/api-journeys/src/app/lib/roleGuard/roleGuard.spec.ts
> +    it('should return true if role is an array and includes publisher', async () => {
`should return true for multiple roles`

2022-08-03 21:17 UTC, storyworks commented on apps/api-journeys/src/app/lib/roleGuard/roleGuard.spec.ts
> +    it('should return true if role is public and template true and status published', async () => {
`should return true for role with attributes`

2022-08-03 21:18 UTC, storyworks commented on apps/api-journeys/src/app/lib/roleGuard/roleGuard.spec.ts
> +    it('should return true if user role includes publisher', async () => {
`should return true for single user role`

2022-08-03 21:18 UTC, storyworks commented on apps/api-journeys/src/app/lib/roleGuard/roleGuard.spec.ts
> +    it('should return true if role is an array and includes publisher', async () => {
should return true for user role in array

2022-08-03 21:21 UTC, storyworks commented on apps/api-journeys/src/app/lib/roleGuard/roleGuard.ts
> +        (key: any) => attributes[key] === journey[key]
Linting

2022-08-03 22:14 UTC, storyworks approved these changes

2022-08-03 22:17 UTC, merged