feat: template list/ card
JesusFilm/core pull request #806
Opened 2022-08-03 07:27 UTC by csiyang

# Description

- Template List
- Add template to main nav
- Add back button to title bar
- Template Card
- Add admin mode for template card (when used for templatesAdmin)
- Loading skeleton

[- Template Card](https://3.basecamp.com/3105655/buckets/28496234/todos/5147215755)
[- Template List](https://3.basecamp.com/3105655/buckets/28496234/todos/5147216115)
[- Menu nav](https://3.basecamp.com/3105655/buckets/28496234/todos/5147215539)

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Clicking on templates from main nav menu should take you to "Journey Templates"
- [ ] Clicking the back button from "Journey Templates" page should take you back to the home page
- [ ] Template card should have title, date, description, language and image (from social share image)
- [ ] Clicking on card should take you to template details (empty page at the moment)

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-08-03 07:39 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
> +  template,
This is only for when the card is used in templateAdmin

2022-08-03 07:39 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateList/TemplateCard/TemplateCard.stories.tsx
> +const Template: Story = ({ ...args }) => (
There's quite a few cases for this component, hence the amount of stories. Open to suggestions to any way we may be able to reduce

2022-08-03 07:39 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateList/TemplateCard/TemplateCard.tsx
> +        <CardActionArea sx={{ width: 'calc(100% - 129px)' }}>
CardMedia adds width and CardActionArea was getting pushed out.

2022-08-03 07:39 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateList/TemplateCard/TemplateCard.tsx
> +                      <StatusChip status={template.status} />
Status chip icon alignment is kinda out of whack, will fix in a future PR

2022-08-03 07:39 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateList/TemplateCard/TemplateCard.tsx
> +                      <Box sx={{ pr: 6 }} />
Wrapping the chip in box or using spacing (from stack) was throwing the styling way off, so added padding using this for now.

2022-08-03 07:39 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateList/TemplateListData.ts
> +export const defaultTemplate: Template = {
This whole file is pretty similar to JourneyListData, but thought it was different enough to create a seperate file (mainly because type Template is different to type Journey)

2022-08-03 10:10 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateList/TemplateCard/TemplateCard.stories.tsx
> +const Template: Story = ({ ...args }) => (
Might just keep one story for admin, since the chips are visually tested in its own component

2022-08-03 23:48 UTC, storyworks requested changes

2022-08-03 23:48 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateList/TemplateCard/TemplateCard.stories.tsx
> +const Template: Story = ({ ...args }) => (
- [ ] Instead of descriptive and Admin draft, we could replace with `Complete` / `All Features` or something like that which indicates all the props are passed in?

This story should focus on demo-ing which features are available if they were to use it and can rely on stories on other pages (Template Library page or Template List page) to show how it would look in reality

- [ ] Keep default as is, and just have 1 loading variant - use Admin Loading and rename to Loading.

- [ ] Top left corner of Admin stories are also rendering incorrectly..

<img width="485" alt="image" src="https://user-images.githubusercontent.com/10802634/182729211-4811f5bf-699d-4e41-b414-9e1b02b0be8d.png">

2022-08-03 23:48 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateList/TemplateListData.ts
> +export const defaultTemplate: Template = {
Could do `defaultTemplate = {...defaultJourney, [add template specific props here]}` same for all the others `const oldTemplate = {...oldJourney, [template specific props]}` etc to simplify this file.

Also fair enough to create this seperate data file, but technically speaking a template isn't a different type to Journey - it's still a journey block. In saying Template is a new type, you're saying a specific configuration of Journey is a new type - which isn't a pattern we have and I'm not sure that we should introduce... 

If it's important enough to be a different type, it should be a completely different block type as well. This is the arguement for making a seperate YoutubeVideoBlock rather than extending VideoBlock to include props only used for Youtube and using those props to let us know if it was a Youtube video or not.

2022-08-03 23:48 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateList/TemplateList.tsx
> +        <>
Remember fragments should only be used if there are multiple JSX expressions listed. Not necessary here / don't add them by default.

2022-08-03 23:48 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateList/TemplateList.tsx
> +  templates?: Template[]
rename to journeys here too

2022-08-03 23:48 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateList/TemplateCard/TemplateCard.tsx
> +        <>
Remove Fragment

2022-08-03 23:48 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.stories.tsx
> +export const TemplateJourney = Template.bind({})
Will draft and published templates have different menus? If so `DraftTemplate` and `PublishedTemplate` else `Template`

Using JourneyCardMenu rather than making a TemplateCardMenu also makes me think eventually we're planning to make JourneyCard and TemplateCard the same component... Which I think is the intention.

2022-08-03 23:48 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
> +        <Link href={`/journeys/${journeyId}`} passHref>
Since every other part of the component is the same, `href={template != true ? /journeys/${journeyId} : /templates/${journeyId}}`

2022-08-03 23:48 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
> +    )
Also check that the edit link is correct

2022-08-03 23:48 UTC, storyworks commented on apps/journeys-admin/pages/templates/index.tsx
> +  query GetPublicTemplates {
`query GetPublishedTemplates` - we no longer have concepts of public/private

2022-08-03 23:49 UTC, storyworks commented
Thanks for commenting on your PR, made it easier to review! :)

2022-08-04 02:30 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateList/TemplateListData.ts
> +import { GetPublicTemplates_journeys as Template } from '../../../__generated__/GetPublicTemplates'
`as Journey`

2022-08-04 02:44 UTC, storyworks commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
> +    )
Do a search to see if anyone else has tested with Link, if so do that else nvm.

2022-08-04 04:19 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateList/TemplateList.tsx
> +        <>
This fragment is needed since the map can render multiple components

2022-08-04 08:07 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
> +        <Link href={`/journeys/${journeyId}`} passHref>
Actually this button doesnt even work, will fix it in another PR

2022-08-05 20:27 UTC, BethanyMcCabe commented
I tested through your QA tests, and it looks like it is doing exactly what it should do. In addition to your tests I tested navigation from a Journey Detail page to templates. I also tested from editing a journey.
I see that the language text size is bigger than the one on the Active Journey page.
Very minor, but I see a flash of empty cards when the template list is loading (see video) It seems to be happening when navigating to the Active Journey list too.
I tested it on Chrome, Edge,  my Google Pixel 6, and a 12" iPad Pro

https://user-images.githubusercontent.com/19290044/183157764-cac71352-24c5-46ce-b691-12dc0b5d1d06.mp4

2022-08-24 15:46 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
> +  const nativeLanguage = journey?.language.name[0].value ?? ''
The native Language isn't always the first language in the list. We use `primary` to determine native language. See `LanguageSelect` lines 31 and 32. 

We also can't properly do local language fyi. We're guessing local language of our user is english and guessing the first non-primary language in the list is english. But use what we have in LanguageSelect as it's the best we've got so far..

2022-08-25 18:05 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
> +      {admin === true &&
The admin check needs to be outside since CardActions only appears when its admin. Do you mean for me to shift the journey null check?

2022-08-25 18:18 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.tsx
> +      {journeys != null ? (
The linting is enforcing the current layout of this...

2022-08-25 18:38 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
> +      {admin === true &&
Ah yes, journey null check

2022-08-25 18:39 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.tsx
> +      {journeys != null ? (
My comment isn't getting at the linting but suggesting a different way to generate the placeholder template cards.

2022-08-25 19:50 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.tsx
> +      {journeys != null ? (
Ahh i see

2022-08-26 20:00 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
> +  const nativeLanguage = journey?.language.name[0].value ?? ''
![image](https://user-images.githubusercontent.com/67619008/186981710-4c0c6260-518b-4e1d-8710-0e50741235bf.png)
Could we not do something like what Mike did here? `VideoBlockEditor.tsx` lines 63-78

2022-08-31 21:48 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
> +  const nativeLanguage = journey?.language.name[0].value ?? ''
Everything I've said above applies also to VideoBlockEditor - they also use the `primary` prop to determine native language. 

And they also make the same assumption about local language - I'm explicitly explaining that while we do this, don't take this to be 100% accurate. It was possible you didn't know this key piece of info due to how you originally calculated the languages.

2022-08-31 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.spec.tsx
> +  it('renders menuitem with link', () => {
menuitem is the html role that this component renders down to. Do you mean "menu item"? Or did you mean to test that role="menuitem" as well?

2022-08-31 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.spec.tsx
> +      getByTestId('AbcRoundedIcon').parentElement?.parentElement
getByRole 'menuitem' doesn't work?

2022-08-31 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.stories.tsx
> +  color: 'black'
Switch to use one of our color tokens. 'black' might work but we want this to be a example of what people should do.

2022-08-31 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.tsx
> +    <>
You already know what I'm gonna say xD

2022-08-31 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.tsx
> +            sx={{
Can we put lines 33-37 all on 1 line? same for lines 42-44?

2022-08-31 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.tsx
> +          <Link href={link as string} passHref>
Use NextLink ?

2022-08-31 23:30 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
> +  admin?: boolean
If we use `admin` as the prop name, can you add a comment as to what that means? We have so many instances of admin in this codebase already. Or pick another name?

2022-09-01 00:03 UTC, csiyang commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.tsx
> +    <>
removed fragments

2022-09-01 00:03 UTC, csiyang commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
> +
removed

2022-09-01 00:03 UTC, csiyang commented on apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
> +    expect(queryByRole('menuitem', { name: 'Access' })).not.toBeInTheDocument()
removed

2022-09-01 00:05 UTC, csiyang commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.tsx
> +            sx={{
Done, not sure why linting made this in the first place

2022-09-01 00:12 UTC, csiyang commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.spec.tsx
> +  it('renders menuitem with link', () => {
![image](https://user-images.githubusercontent.com/67619008/187806309-94568af9-dacf-4504-99c3-358c2df3197d.png)

2022-09-01 02:11 UTC, storyworks commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.spec.tsx
> +  it('renders menuitem with link', () => {
Usually the test gives suggestions on what roles do exist - can you find something similar? I've definitely seen this kind of component be tested by role before...

2022-09-01 02:12 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateCard/TemplateCard.stories.tsx
> +  title: 'Journeys-Admin/TemplateList/TemplateCard'
Remove TemplateList subpath

2022-09-01 03:48 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
> +        <CardActionArea sx={{ width: `calc(100% - ${contentWidth})` }}>
```suggestion
        <CardActionArea sx={{ flexGrow: 1, width: '60%' }}>
```

2022-09-01 03:48 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
> +            position: 'relative',
Don't need this position relative

2022-09-01 03:52 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
> +                    variant="body2"
<img width="392" alt="image" src="https://user-images.githubusercontent.com/10802634/187827966-75a5dd55-9b1c-4ac9-82f9-cfcf82d7de11.png">
Get UX to review size of text for status and language. It's significantly larger than what we use for JourneyCard.

Also check margins between icon and text.

2022-09-05 04:45 UTC, csiyang commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.spec.tsx
> +  it('renders menuitem with link', () => {
No menuItem since the component is ListItem

2022-09-05 04:45 UTC, csiyang commented on apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationMenuItem/NavigationMenuItem.spec.tsx
> +      getByTestId('AbcRoundedIcon').parentElement?.parentElement
No menuItem since the component is ListItem

2022-09-05 21:43 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
> +  const nativeLanguage =
Next time we touch languages we should extract this logic out into a getLanguage util

2022-09-05 21:43 UTC, storyworks approved these changes

2022-09-05 21:47 UTC, merged