Columns
JesusFilm/core pull request #89
Opened 2021-10-18 14:38 UTC by gdub01

This branch probably should have been named grid in hindsight... but it supports grids like: 

```
type: Enum('container' | 'item' | 'container item')
bpMd: Enum(_6 | _12)
```

and it would be used like this:
step:
  grid(container):
    grid(item):
      radioQuestions
    grid(item):
      image

2021-10-19 03:25 UTC, storyworks requested changes

2021-10-19 03:25 UTC, storyworks commented on apps/journeys/src/components/blocks/Grid/Grid.tsx
> +      md={gridType.includes('item') ? columnSize : undefined}
`md` is Tablet (P),  so though there are no designs for it now, I'm assuming it should be 12. `sm / lg` are Mobile /tablet landscape - so should take custom column size.

Are you also able to fix the broken stories/tests?

2021-10-19 03:25 UTC, storyworks commented on apps/api-journeys/schema.graphql
> +  md: ColumnSize
Maybe we could rename md to `gridSize: GridSize` ? or something not md, since md is Tablet portrait..

2021-10-19 03:25 UTC, storyworks commented on apps/api-journeys/schema.graphql
> +enum ColumnSize {
What do you think of adding 'auto' to this list? like mui's GridSize

2021-10-19 03:25 UTC, storyworks commented on apps/api-journeys/schema.graphql
> +  type: GridType
We also need a prop that lets each column know the alignment of the content:

![image](https://user-images.githubusercontent.com/10802634/137838521-bac78184-0590-4a36-9779-cdade67e745e.png)

2021-10-20 21:49 UTC, gdub01 commented on apps/api-journeys/schema.graphql
> +  md: ColumnSize
renamed it to lg

2021-10-21 20:00 UTC, storyworks commented on apps/journeys/src/components/blocks/Grid/Grid.tsx
> +      md={gridType.includes('item') ? columnSize : undefined}
You're probably already making the change but adding here to document our convo. It seems like from the designs the landscape viewports can be both single or double column. So this check would need to be on `sm, lg, xl`

![image](https://user-images.githubusercontent.com/10802634/138348100-dd76a288-42f1-427f-8700-ca3df3ff3844.png)

I think Tatai's PR is determining if the content is offset or full screen so the check here should be enough.

2021-10-21 20:11 UTC, storyworks commented on apps/journeys/src/components/blocks/Grid/Grid.tsx
> +      lg={item?.lg.replace('_', '') as GridSize}
Could have just kept that `columnSize` check you had before and applied it to all breakpoints but make the direction `row` for landscape viewports or `column` for portrait? No need for `item.lg` prop?

2021-11-01 03:24 UTC, storyworks requested changes

2021-11-01 03:24 UTC, storyworks commented on apps/journeys/src/components/blocks/GridContainer/GridContainer.tsx
> +      direction={hyphenate(direction) as GridDirection}
Possibly don't need this now and linting needs to be fixed, but other than that - looks good :)
```suggestion
      direction={hyphenate(direction)}
```

2021-11-01 21:36 UTC, storyworks commented on apps/journeys/src/components/blocks/GridContainer/GridContainer.tsx
> +      direction={hyphenate(direction) as GridDirection}
From Slack:

![image](https://user-images.githubusercontent.com/10802634/139745366-157d23b8-6fa8-4198-8e8b-e28942e1fac3.png)

2021-11-01 21:39 UTC, storyworks approved these changes

2021-11-02 18:11 UTC, merged