docs: added common issues
JesusFilm/core pull request #892
Opened 2022-09-16 03:45 UTC by jianwei1

# Description

Updating the "Getting Started" docs to include 2 common issues with setting up a Docker container on Mac

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-09-16 03:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JesusFilm/core?pullRequest=892) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JesusFilm/core?pullRequest=892) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JesusFilm/core?pullRequest=892) it.</sub>

2022-09-29 04:22 UTC, tataihono approved these changes

2022-09-29 04:23 UTC, tataihono requested changes

2022-09-29 04:23 UTC, tataihono commented on apps/docs/docs/02-getting-started/01-development-environment.mdx
> +### Container isn't using enough resources on Mac
```suggestion
### Container is running slowly or crashing on Mac
```

2022-09-29 04:23 UTC, tataihono commented on apps/docs/docs/02-getting-started/01-development-environment.mdx
> +1. Set CPUs:7, Memory:12.00GB, Swap:4GB
```suggestion
1. Set CPUs: 7, Memory: 12.00GB, Swap: 4GB
```

2022-10-03 01:46 UTC, closed without merging

2022-10-03 01:48 UTC, storyworks commented
This was weirdly running all VR tests and chewing through our usage. Will fix linting issues in new branch