Video Player Extensions
JesusFilm/core pull request #90
Opened 2021-10-19 02:42 UTC by GeronimoJohn

- Create trigger block schema
- Implement trigger block to the front end
- Add media support for arclight
- Add VideoBlockResponses
- Add test for trigger block
- Update Video tests and storybook

Remaining TODO: 
- Implement the trigger block at the front end.
- Add tests for trigger block
- Define what capturing "SECONDSWATCHED" means

2021-11-02 00:17 UTC, tataihono requested changes
this PR needs to be split up into frontend and backend PRs.

2021-11-02 00:17 UTC, tataihono commented on apps/api-journeys/src/modules/video/video.spec.ts
> +          position: 0.3
```suggestion
          state: 'PLAYING',
          position: 30
```

2021-11-02 00:17 UTC, tataihono commented on apps/api-journeys/prisma/migrations/20211014003622_add_trigger_block_to_block_type/migration.sql
> +ALTER TYPE "BlockType" ADD VALUE 'TriggerBlock';
```suggestion
ALTER TYPE "BlockType" ADD VALUE 'VideoTriggerBlock';
```

since this block is pretty much only going to be used by video.

2021-11-02 00:17 UTC, tataihono commented on apps/api-journeys/prisma/seed.ts
> +        video: {
```suggestion
        content: {
```

maybe content would be more appropriate here. Otherwise its a video prop inside a video.

2021-11-02 00:17 UTC, tataihono commented on apps/api-journeys/src/modules/trigger/trigger.ts
> +  type TriggerBlock implements Block {
can you add a comment above for clients to understand what this block is for? Also try VideoTriggerBlock for this.

2021-11-02 00:17 UTC, tataihono commented on apps/api-journeys/src/modules/trigger/trigger.ts
> +    triggerStart: Int!
can you add a comment above this for clients to understand that this is the number of seconds since the start of the video

2021-11-03 22:48 UTC, tataihono requested changes

2021-11-03 22:48 UTC, tataihono commented on apps/api-journeys/codegen.yml
> +        TriggerBlock: .prisma/api-journeys-client#Block as BlockType
```suggestion
        VideoTriggerBlock: .prisma/api-journeys-client#Block as BlockType
```

2021-11-03 22:48 UTC, tataihono commented on apps/api-journeys/src/modules/trigger/index.ts
> +export { videoTriggerModule } from './trigger'
this should be moved from the trigger folder to the videoTrigger folder.

2021-11-03 22:48 UTC, tataihono commented on apps/api-journeys/src/modules/trigger/trigger.spec.ts
> +describe('TriggerModule', () => {
```suggestion
describe('VideoTriggerModule', () => {
```

Can you make sure to update all instances of trigger to videoTrigger?

2021-11-03 22:48 UTC, tataihono commented on apps/api-journeys/src/modules/video/video.ts
> +    position: Float
this should just be an int. we don't need to store more than seconds.

2021-11-03 22:48 UTC, tataihono commented on apps/api-journeys/src/modules/video/video.ts
> +  interface Video {
```suggestion
  interface VideoContent {
```

can we go with VIdeoContent instead of just video.

2021-11-03 22:48 UTC, tataihono commented on apps/api-journeys/src/modules/video/video.ts
> +    content: Video
this should be required.

2021-11-03 22:48 UTC, tataihono commented on apps/api-journeys/src/modules/video/video.ts
> +    startAt: Int
can you add comments to many of these props so we know what they are for. The name doesn't really show us what they are needed for.

2021-11-03 22:48 UTC, tataihono commented on apps/journeys/pages/[journeyId].tsx
> +  TRIGGER_FIELDS,
```suggestion
  VIDEO_TRIGGER_FIELDS,
```

same changes on backend should be made here (rename trigger to video trigger).

2021-11-03 22:48 UTC, tataihono commented on apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
> +      videoContent: {
I thought on the backend this field was just called content

2021-11-03 22:48 UTC, tataihono commented on apps/journeys/src/components/blocks/Trigger/Trigger.tsx
> +  const handleTrigger = (player: videojs.Player): void => {
I actually think this should just be implemented as a useEffect.

```Typescript
useEffect(() => {
	if(player != null) {
		player.on('timeupdate', () => {
      if (player.currentTime() >= triggerStart) {
        if (player.isFullscreen()) player.exitFullscreen()
        player.pause()
        handleAction(triggerAction)
      }
    })
  }
}, [player])
```

2021-11-03 22:48 UTC, tataihono commented on apps/journeys/src/components/blocks/Video/Video.spec.tsx
> +                position: 0.3
should provide whole seconds

2021-11-03 23:38 UTC, GeronimoJohn commented on apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
> +      videoContent: {
I think there's another prop from a different block that's also called content and graphql at the client-side didn't like that. Hence I had to give it a different name on the front-end (videoContent)

2021-11-03 23:41 UTC, GeronimoJohn commented on apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
> +      videoContent: {
Should we leave the backend to be named content or just change it to videoContent? But if we do videoContent will have a prop called videoContent

2021-11-04 00:32 UTC, GeronimoJohn commented on apps/api-journeys/src/modules/video/video.ts
> +    position: Float
I just tried setting the position to have the type of INT. But VideoJS gives us back the time in float. When I tested this to record time I just get a type error in the front end. Can convert the value but not sure if this is how we should go about it.

2021-11-04 01:41 UTC, tataihono commented on apps/api-journeys/src/modules/video/video.ts
> +    position: Float
yup just turn it itno a seconds int.

2021-11-04 02:14 UTC, storyworks commented on apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
> +      videoContent: {
Seems like you've changed it to `content` in the backend. 

Now you just need to update videoFields.ts to 
```
content {
      src
    }
```
Run `nx codegen journeys` and update the stories / test files

2021-11-04 02:28 UTC, storyworks commented on apps/journeys/pages/[journeySlug].tsx
> +            ... on VideoTriggerBlock {
These should be referenced in alphabetical order, move under VideoBlock :)

2021-11-04 02:30 UTC, storyworks commented on apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
> +      videoContent: {
And also rename Trigger.tsx etc VideoTrigger.tsx?

I know you've moved the folder within Video which helps us find it if we're looking through the folder tree, but naming it VideoTrigger.tsx will also help us find it when doing a `cmd+P` search.

2021-11-04 03:03 UTC, storyworks commented on apps/journeys/src/components/blocks/Video/Trigger/Trigger.tsx
> +export function Trigger({
Seems really strange to have this as a seperate component that just triggers a useEffect (seemed strange when it was just triggering a function as well)

Could VideoTriggerBlock not have just been a VideoTriggerAction? And then VideoBlock has a prop `triggers` that takes an array of VideoTriggerActions?

And then in Video.tsx, on first render we loop through the triggers and start the `player.on('timeupdate'....` listeners?

2021-11-04 03:52 UTC, storyworks commented on apps/journeys/src/components/blocks/Video/Trigger/Trigger.tsx
> +export function Trigger({
After talking to @tataihono , VideoTrigger was made a block so its children could be the overlays that appear at different timestamps. Right now we're not implementing overlays so have held off from passing children into the render function. 

If we decide not to use video overlays in the end, this should be refactored, removing the VideoTrigger.tsx component and treating the Video `children` as `triggers`, looping through them to add the listeners in `Video.tsx`

2021-11-04 03:59 UTC, storyworks approved these changes

2021-11-04 04:06 UTC, storyworks approved these changes

2021-11-04 21:31 UTC, storyworks approved these changes

2021-11-04 23:07 UTC, storyworks approved these changes

2021-11-04 23:16 UTC, merged