fix: access templates
JesusFilm/core pull request #915
Opened 2022-09-23 00:56 UTC by storyworks

# Description

If trying to access template admin or library as a new user (with no journeys), display the following error page:

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/10802634/191874949-32c77790-aa5f-4865-839b-f0e9025edd4b.png">

[Basecamp](https://3.basecamp.com/3105655/buckets/29147486/todos/5358874874)

# How should this PR be QA Tested?

- [ ] Create a new account (or go to account with no journeys - in active, archive or trashed). Get publisher role added, then click on templates library and admin page. You should see that picture display.

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-09-23 02:08 UTC, csiyang requested changes

2022-09-23 02:08 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateList/TemplateList.tsx
> +  journeys,
All the changes on this file is not needed. This parent page of this will automatically redirect if not publisher.

2022-09-23 02:08 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.tsx
> +              You need to be invited to create the first template
```suggestion
              You need to be invited to use your first template
```

2022-09-23 02:08 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.stories.tsx
> +  journeys: [{}],
why are the curlies needed?
```suggestion
  journeys: [],
```

2022-09-23 02:25 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateList/TemplateList.tsx
> +  journeys,
This is a publisher, but a publisher who doesn't have any journeys

2022-09-23 02:25 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateList/TemplateList.tsx
> +  journeys,
It's a different kind of error you're thinking about

2022-09-23 02:26 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.stories.tsx
> +  journeys: [{}],
Need to pass in something for journeys so we know they have access

2022-09-26 21:31 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateList/TemplateList.tsx
> +  journeys,
Oh was it asked to also restrict publishers to also have a personal journey first. I was thinking since all publishers share templates, they may never have their own journey, so thought it was weird we would restrict template access with personal journies?

2022-09-26 21:33 UTC, storyworks commented on apps/journeys-admin/src/components/TemplateList/TemplateList.tsx
> +  journeys,
That makes sense, put the push back in the templates thread?

2022-09-30 04:38 UTC, jianwei1 commented
> # How should this PR be QA Tested?
> New user (no journeys):
> 
> * [x]  If they go to templates library, they will see access denied message
> * [x]  Cannot go to templates admin (redirected)
> * [x]  If they go to journey list, they will see access denied message
> 

Have tested the new user checks. All pass but I did notice that on iphone/Ipad the templates admin will display for a brief second before being redirected. I've made a comment (with video) on the [to do](https://3.basecamp.com/3105655/buckets/29494894/todos/5369802313#__recording_5383394118)

2022-10-02 20:51 UTC, csiyang approved these changes

2022-10-02 20:56 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.tsx
> +  const showLibrary = journeys == null || journeys?.length > 0 || isPublisher
This is the bit thats causing the flash. Can we move this check out into its own check? 

```suggestion
  const showLibrary = journeys == null || journeys?.length > 0
```

2022-10-02 20:57 UTC, csiyang requested changes
Don't mind this, just a comment to request change

2022-10-02 21:06 UTC, csiyang commented on apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.tsx
> +  const showLibrary = journeys == null || journeys?.length > 0 || isPublisher
oops this is not the problem

2022-10-02 21:07 UTC, csiyang approved these changes

2022-10-02 21:08 UTC, merged