fix: changing video providers
JesusFilm/core pull request #927
Opened 2022-09-29 04:00 UTC by GeronimoJohn

# Description

Changing video providers is broken on admin. Specifically changing to an internal video break the admin or gives out an error

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29494894/todos/5373621635)

# How should this PR be QA Tested?

Create a video block and select a video
- [ ] Changing video providers of a video block should work
- [ ] Chagnign video providers of a background video should work

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-09-29 04:39 UTC, tataihono approved these changes

2022-09-29 05:29 UTC, tataihono approved these changes

2022-09-29 05:30 UTC, tataihono submitted a review, later dismissed
missed failing test

2022-09-29 21:21 UTC, tataihono submitted a review, later dismissed

2022-09-29 22:49 UTC, jianwei1 commented
> # How should this PR be QA Tested?
> Create a video block and select a video
> 
> * [x]  Changing video providers of a video block should work
> * [x]  Changing video providers of a background video should work
> 
@GeronimoJohn checks pass on desktop

2022-10-04 04:55 UTC, tataihono commented on apps/journeys/next.config.js
> +      'd1wl257kev7hsz.cloudfront.net',
can you put a comment next to this indicating that its for arclight content?

2022-10-04 04:56 UTC, tataihono submitted a review, later dismissed

2022-10-04 22:41 UTC, tataihono approved these changes

2022-10-05 01:42 UTC, tataihono requested changes

2022-10-05 01:42 UTC, tataihono commented on libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
> +  const videoImage = videoBlock?.image ?? videoBlock?.video?.image
Wonder if this is worth making deliberate.

```suggestion
  const videoImage = videoBlock?.source === VideoBlockSource.internal ? videoBlock?.video?.image : videoBlock?.image
```

2022-10-05 01:42 UTC, tataihono commented on libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
> +  const videoImage = videoBlock?.image ?? videoBlock?.video?.image
same also for the video component.

2022-10-05 02:06 UTC, tataihono commented
<div style="position: relative; padding-bottom: 62.5%; height: 0;"><iframe src="https://www.loom.com/embed/0f97caeaa25a477fbdc14d87995087ab" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>

I was able to QA this successfully.

2022-10-05 02:10 UTC, tataihono approved these changes

2022-10-05 02:13 UTC, merged