test: update journey-ui vr
JesusFilm/core pull request #933
Opened 2022-10-03 03:31 UTC by storyworks

# Description

Removing a bunch of todos in stories + fixing others

[Fix TextResponse story](https://3.basecamp.com/3105655/buckets/29494894/todos/5369620172)

# How should this PR be QA Tested?

- [ ] Checks are green
- [ ] New VR standards agreed on by devs (will link to docs)

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-10-03 03:32 UTC, storyworks commented on libs/journeys/ui/src/components/GridContainer/GridContainer.stories.tsx
> +    chromatic: { disable: true }
Disabled Grid stories since we aren't using this block, also renaming all templates to "Template" by default.

2022-10-03 03:33 UTC, storyworks commented on libs/journeys/ui/src/components/Image/Image.stories.tsx
> +export const Default: Story<TreeBlock<ImageFields>> = Template.bind({})
The actual default image block is the empty source one. Have updated this in image and video. 

This makes more sense as we will have different sources of image / video in the future.

2022-10-03 03:34 UTC, storyworks commented on libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
> -export const Long: Story<TreeBlock<RadioQuestionFields>> = DefaultTemplate.bind(
Don't need a `long` example anymore - RadioQuestion is just a group of options. The `Long` scenario is tested there.

2022-10-03 03:37 UTC, storyworks commented on libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
> +Default.args = { ...signUpProps }
This could be directly added to the SignUp component in line 95 - but not sure if people had a preference to put it here or there.

Putting it on line 95 is less lines of code but requires people to know how props override one another + look closer into the template to see the default build.

2022-10-03 03:39 UTC, storyworks commented on libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
> +export const Complete = Template.bind({})
The complete example for forms should now include all the customisable options featured.
Also it has a `complete` flag which toggles on blocks which show how it sits in relation to others. 

Could have put the other blocks on the default story too, but wondered if that distracts / makes it confusing which is the actual block

2022-10-03 03:40 UTC, storyworks commented on libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
> +  const fields = screen.getAllByRole('textbox')
For some strange reason, the name of the first Name field was "Name Name" and the second was "". Same for the 2 email fields. So referencing like this for now...

2022-10-03 03:41 UTC, storyworks commented on libs/journeys/ui/src/components/TextField/TextField.stories.tsx
> +            <Stack direction="row" spacing={4}>
Stacking these examples side by side as multiple people have now confused the default textfield as the textfield with placeholder (rather than an unfocused textfield with label)

2022-10-04 19:59 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.stories.tsx
> -export const Filled = Template.bind({})
Button is no different whatever is in it and screenshot captured looks the same.. (since we had to hide the cursor due to blinking) Possibly could still keep the text variant as viewing it in storybook could show something different.

2022-10-04 20:00 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attribute/Attribute.stories.tsx
> -export const Selected: Story = () => {
This test done in Button.tsx - not needed here

2022-10-04 20:01 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextField/TextField.spec.tsx
> -describe('TextField', () => {
TextField was the original block for TextResponse - it's unused, our mistake for not deleting earlier

2022-10-04 20:02 UTC, storyworks commented on apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.stories.tsx
> -import { MockedProvider } from '@apollo/client/testing'
All these "New___Button" snaps are captured in the "Add blocks" panel story. There aren't different variants of this button, and if there were - it would be captured in "Button" stories.

2022-10-04 21:57 UTC, csiyang requested changes

2022-10-04 21:57 UTC, csiyang commented on libs/journeys/ui/src/components/GridContainer/GridContainer.stories.tsx
> +)
```suggestion
export const OffsetRight: Story<TreeBlock<GridContainerFields>> = Template.bind({})
```

2022-10-04 21:57 UTC, csiyang commented on libs/journeys/ui/src/components/Image/Image.stories.tsx
> +    <Image {...imageProps} {...args} alt={alt} />
Why does the alt prop need to be seperated?

```suggestion
    <Image {...imageProps} {...args} />
```

2022-10-04 21:57 UTC, csiyang commented on libs/journeys/ui/src/components/Image/Image.stories.tsx
>  }
Can we keep it so each template passes all of its own props? I feel like this is more clear.
```suggestion
Default.args = {
  ...ImageProps,
  src: null
}
```

2022-10-04 21:57 UTC, csiyang commented on libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
> -        />
I think we should add this back so the story can match what a radio question block looks like

2022-10-04 21:57 UTC, csiyang commented on libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
> +    <JourneyProvider>
How come journeyProvider is needed now?

2022-10-04 21:57 UTC, csiyang commented on libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
> +export const Complete = Template.bind({})
Why do some blocks have surrounding typogs to show how the block fits and some others don't? 

Was kinda confused at first why they were there. Could we add a comment somewhere in the story to say why we have the typogs?

Also could we rename the complete prop to something else? Might get confusing since we're starting to call a lot of our stories Complete too. Maybe something like `inContext`?

2022-10-04 21:57 UTC, csiyang commented on libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
> +const typographyProps: TreeBlock = {
```suggestion
const typographyProps: TreeBlock<TypographyBlock> = {
```

2022-10-04 22:04 UTC, storyworks commented on libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
> +export const Complete = Template.bind({})
`Complete` is meant to show the component with all the customisable options changed.

I thought it'd be good to add context related story to these texts to test out margins. 
I added it to complete since I thought it made sense that, that story would have all the bells and whistles. I could be it's own story, but if it made sense to others - we could combine.

2022-10-04 22:11 UTC, storyworks commented on libs/journeys/ui/src/components/Image/Image.stories.tsx
> +    <Image {...imageProps} {...args} alt={alt} />
<img width="753" alt="image" src="https://user-images.githubusercontent.com/10802634/193939373-1c604e6f-e286-4cb3-888b-f3aad00766b1.png">

We get this error without it..

2022-10-04 22:15 UTC, storyworks commented on libs/journeys/ui/src/components/Image/Image.stories.tsx
>  }
Can do - I was wondering about this.

Would you want this convention even if it meant adding in an extra line in some cases?
eg doing:
```
export const Default = Template.bind({})
Default.args = { ...mockedProps }
```

Whereas if the basic mocked data was already in the template, you wouldn't need the second line?

2022-10-04 22:16 UTC, storyworks commented on libs/journeys/ui/src/components/Image/Image.stories.tsx
> +  chromatic: { delay: 300 }
Oops, will change this - no longer need the delay

2022-10-04 22:20 UTC, storyworks commented on libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
> -        />
This is another question to raise - I removed it so it's agnostic / we focus on the margins and how the block interacts with what's above and below it. When we first started building this - I thought it might be good for Storybook to also document how we use blocks and be documentation for journey-builders.

If we were still able to do that - I reckon those stories could be omitted from Chromatic screenshots? And just in for documentation "real life example" purposes?

2022-10-04 22:21 UTC, storyworks commented on libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
> +    <JourneyProvider>
Will double test and get back

2022-10-06 03:14 UTC, storyworks commented on libs/journeys/ui/src/components/Image/Image.stories.tsx
>  }
@csiyang will do, and explained https://jfp-digital.slack.com/archives/C041QM21FDL/p1665025846147379?thread_ts=1664925026.334719&cid=C041QM21FDL

2022-10-06 22:02 UTC, storyworks commented on libs/journeys/ui/src/components/GridContainer/GridContainer.stories.tsx
> +)
This is cut off from prettier... so won't change.

2022-10-06 22:07 UTC, storyworks commented on libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
> -        />
@csiyang , double checked the code - I didn't actually remove the question. It now reads "How can we help you know more about Jesus?" So still gives context to how RadioQuestion block might be used.

2022-10-07 00:02 UTC, storyworks commented on libs/journeys/ui/src/components/Button/Button.stories.tsx
> +  Parameters<typeof Button>[0] & { variants: ButtonVariant[] }
Use `Story` when we need to extend the base props `Parameters<typeof Button>[0]` with something else (in this case `variants`)

2022-10-07 00:08 UTC, storyworks commented on libs/journeys/ui/src/components/Card/Card.stories.tsx
> +export const Custom = Template.bind({})
Don't need to provide type here - typescript can infer it from Template.

Keeping it would be the same as writing
`const myName: string = "Ziwei"`
`const name: string = myName.toUpperCase()`

The second line is not needed.

2022-10-07 02:26 UTC, GeronimoJohn approved these changes

2022-10-07 02:59 UTC, GeronimoJohn approved these changes

2022-10-07 03:02 UTC, tataihono approved these changes

2022-10-07 03:25 UTC, merged