feat: create visitor report page structure
JesusFilm/core pull request #947
Opened 2022-10-10 22:34 UTC by csiyang

# Description

Please include a summary of the change and which todo is completed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Link to Basecamp Todo

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-10-10 23:04 UTC, csiyang commented on apps/journeys-admin/pages/reports/journeys.tsx
> +        title={t('Journeys Report')}
Updated title for now, but will change to match design in the future

2022-10-10 23:04 UTC, csiyang commented on apps/journeys-admin/pages/reports/index.tsx
> +  return <></>
None of the components are needed anymore since this page immediately gets redirected

2022-10-10 23:04 UTC, csiyang commented on apps/journeys-admin/pages/reports/index.tsx
> +  whenUnauthed: AuthAction.REDIRECT_TO_LOGIN
launch darkly and i18 not needed since this page only redirects

2022-10-10 23:04 UTC, csiyang commented on apps/journeys-admin/pages/reports/index.tsx
> +    redirect: {
docs: https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#redirect

2022-10-10 23:04 UTC, csiyang commented on apps/journeys-admin/pages/reports/visitors.tsx
> +        Visitors report list
Skeleton page apart from this text

2022-10-10 23:04 UTC, csiyang commented on apps/journeys-admin/pages/reports/visitors/[userId].tsx
> +        Single Visitor report
Skeleton page apart from this text

2022-10-11 03:24 UTC, tataihono commented on libs/locales/en/apps-journeys-admin_old.json
>    "Your Trashed journeys will appear here.": "Your Trashed journeys will appear here.",
can you delete this whole file. It is not needed.

2022-10-11 03:24 UTC, tataihono requested changes
will likely look to merge this into a feature branch.

2022-10-13 02:41 UTC, tataihono requested changes
just a name change.

2022-10-13 02:41 UTC, tataihono commented on apps/journeys-admin/pages/reports/journeys.tsx
> +function JourneysReportsPage(): ReactElement {
ReportsJourneysPage just to be consistent with routing.

2022-10-13 02:41 UTC, tataihono commented on apps/journeys-admin/pages/reports/visitors.tsx
> +function VisitorsReportsPage(): ReactElement {
consistency with route

```suggestion
function ReportsVisitorsPage(): ReactElement {
```

2022-10-20 22:35 UTC, tataihono requested changes

2022-10-20 22:35 UTC, tataihono commented on apps/journeys-admin/pages/reports/visitors/[userId].tsx
> +import { ReactElement } from 'react'
can the name of this file be changed to [visitorId].tsx

2022-10-26 01:44 UTC, tataihono approved these changes

2022-10-26 01:44 UTC, merged