Social media sharing
JesusFilm/core pull request #96
Opened 2021-10-27 03:48 UTC by csiyang

- updated backend with meta data
- added authentication for journey create, update and publish
- updated backend tests
- updated front end to use the meta data for social media sharing

2021-10-31 23:33 UTC, tataihono requested changes

2021-10-31 23:33 UTC, tataihono commented on apps/api-journeys/src/modules/image/image.spec.ts
> +        primaryImageBlockId: '1'
```suggestion
        primaryImageBlockId: 'primaryImageBlockId'
```

2021-10-31 23:33 UTC, tataihono commented on apps/api-journeys/src/modules/image/image.spec.ts
> +        id: '1',
```suggestion
        id: 'primaryImageBlockId',
```

2021-10-31 23:33 UTC, tataihono commented on apps/api-journeys/src/modules/image/image.spec.ts
> +        id: '1',
```suggestion
        id: 'primaryImageBlockId',
```

2021-10-31 23:33 UTC, tataihono commented on apps/api-journeys/src/modules/image/image.spec.ts
> +        primaryImageBlockId: '1'
```suggestion
        primaryImageBlockId: 'primaryImageBlockId'
```

2021-10-31 23:33 UTC, tataihono commented on apps/journeys-e2e/cypress.json
> +  "defaultCommandTimeout": 50000
I think we need to swap to production compiles for this. It compiled much quicker as a result.

2021-10-31 23:33 UTC, tataihono commented on apps/journeys-e2e/src/integration/app.spec.ts
> +  beforeEach(() => cy.visit('http://localhost:4100/'))
```suggestion
  beforeEach(() => cy.visit('/'))
```

2021-10-31 23:33 UTC, tataihono commented on apps/journeys-e2e/src/integration/firstStep.spec.ts
> +describe('journeys', () => {
can this file get a better name. Like [journeyId].spec.ts to match the nextjs page thats being tested.

```suggestion
describe('JourneyPage', () => {
```

2021-10-31 23:56 UTC, csiyang commented on apps/journeys-e2e/cypress.json
> +  "defaultCommandTimeout": 50000
Not too sure about how to swap this...

2021-11-01 03:20 UTC, tataihono approved these changes

2021-11-01 03:24 UTC, merged