fix: youtube videos not playing
JesusFilm/core pull request #981
Opened 2022-10-18 02:43 UTC by GeronimoJohn

# Description

Youtube videos are not loading on journeys, and cannot be played. This happens on both iPhone and iPad, for both regular video blocks and background videos. The card will either display an infinite spinning animation or just display the thumbnail image.

**The current fix is temporary** and will further look into it during this cycle's (Cycle 8) cooldown. The current fix is to disable autoplay for youtube videos and card background videos. It should also disable rendering video image on ios or android

Other things found: 
When videos are not set to autoplay, the video image covers the video controls

[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29689605/todos/5431672006)

# How should this PR be QA Tested?

- [ ] it should load youtube videos on journeys
- [ ] it should not autoplay youtube videos
- [ ] it should not render video image on ios
- [ ] it should not render video image on android

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged into main

2022-10-18 02:57 UTC, tataihono commented
- [ ] can play an internal video on a card without an image and autoplay disabled on iOS, android, and web
- [ ] can play an internal video on a card without an image and autoplay enabled on iOS, android, and web
- [ ] can play an internal video on a card with an image and autoplay disabled on iOS, android, and web
- [ ] can play an internal video on a card with an image and autoplay enabled on iOS, android, and web
- [ ] can play a youtube video on a card without an image and autoplay disabled on iOS, android, and web
- [ ] can play a youtube video on a card without an image and autoplay enabled on iOS, android, and web
- [ ] can play a youtube video on a card with an image and autoplay disabled on iOS, android, and web
- [ ] can play a youtube video on a card with an image and autoplay enabled on iOS, android, and web

2022-10-18 03:29 UTC, GeronimoJohn commented
There's always going to be an image with the recent changes that we've added to video.tsx. I've broken down to do to each platform to better understand what's broken and where

Web
- [ ] can play an internal video on a card with an image and autoplay disabled
- [ ] can play an internal video on a card with an image and autoplay enabled
- [ ] can play a youtube video on a background video with an image and autoplay enabled
- [ ] can play a youtube video on a background video with an image and autoplay disabled

IOS
- [ ] can play an internal video on a card with an image and autoplay disabled
- [ ] can play an internal video on a card with an image and autoplay enabled
- [ ] can play a youtube video on a background video with an image and autoplay enabled
- [ ] can play a youtube video on a background video with an image and autoplay disabled

Android
- [ ] can play an internal video on a card with an image and autoplay disabled
- [ ] can play an internal video on a card with an image and autoplay enabled
- [ ] can play a youtube video on a background video with an image and autoplay enabled
- [ ] can play a youtube video on a background video with an image and autoplay disabled

2022-10-19 03:00 UTC, tataihono requested changes

2022-10-19 03:00 UTC, tataihono commented on libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
>        playerRef.current = videojs(videoRef.current, {
```suggestion
      // autoplay when video is YouTube on iOS does not work. We should disable autoplay in that case.
      const isYouTubeAndiOS = isYouTube && /iPhone|iPad|iPod/i.test(navigator?.userAgent)
      playerRef.current = videojs(videoRef.current, {
```

2022-10-19 03:00 UTC, tataihono commented on libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
> +        ),
```suggestion
        autoplay: !isYouTubeAndiOS,
```

2022-10-19 03:00 UTC, tataihono commented on libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
> +        muted: !(isYouTube && /iPhone|iPad|iPod/i.test(navigator?.userAgent)),
```suggestion
        muted: true,
```

2022-10-19 03:00 UTC, tataihono commented on libs/journeys/ui/src/components/Video/Video.tsx
> +        // renders big play button for youtube videos on IOS devices
```suggestion
        // renders big play button for youtube videos on iOS devices
```

2022-10-19 03:00 UTC, tataihono commented on libs/journeys/ui/src/components/Video/Video.tsx
> +                src={`https://www.youtube.com/embed/watch?v=${videoId}`}
```suggestion
                src={`https://www.youtube.com/watch?v=${videoId}`}
```

2022-10-19 04:10 UTC, tataihono approved these changes

2022-10-19 04:12 UTC, merged